### PR TITLE
test(python): don't run tests that write to disk by default

### PR DESCRIPTION
**Pull request by ritchie46**

### CODE REVIEW

**Comment by stinodego** [comment]
Just wondering: are these tests causing issues somehow? Or are they just slow?

**Comment by ritchie46** [comment]
> Just wondering: are these tests causing issues somehow? Or are they just slow?

Just slower.

**Comment by stinodego** [comment]
We can just use the `@pytest.mark.slow` then, right? We already have that marker. Keep things simple.

I can send a PR to update accordingly if you want.

**Comment by ritchie46** [comment]
Ok, I thought it was more separated, but I have no strong opinion on this. Other than that I don't want to trash my disk on every tests call. :)

**Pull request merged**
