### PR TITLE
test(python): Fix test for new deltalake release

### PR DESCRIPTION
**Pull request by ion-elgreco**
We need to explicitly provide overwrite mode when setting overwrite_schema = True

@stinodego :)

### CODE REVIEW

**Review by stinodego — COMMENTED** [review]
@ion-elgreco Thanks! That fixes one of the tests, there is one more still failing - `test_write_delta`. It complains that a file already exists, probably because it's not overwriting correctly?

**Comment by ion-elgreco** [comment]
@stinodego  ah didn't see that one, one sec

**Review by stinodego — APPROVED** [review]
Thanks! Good to merge if CI is green.

**Comment by ion-elgreco** [comment]
> Thanks! Good to merge if CI is green.

Seems more tests are incompatible, will. Compile it locally and run it

**Comment by stinodego** [comment]
> Seems more tests are incompatible, will. Compile it locally and run it

There seem to be some differences between Linux / Windows :thinking:

**Comment by ion-elgreco** [comment]
> > Seems more tests are incompatible, will. Compile it locally and run it
> 
> There seem to be some differences between Linux / Windows :thinking: first Windows failed and Linux passed, now it's the other way around.

Ah yes that's because Linux wheels for 0.19 failed, due to some issue with maturin, I am waiting on my PR to be merged in delta-rs so I can re release them

**Comment by ion-elgreco** [comment]
@stinodego tests should be fine now, did a local compile with a deltalake v0.19. I'll ping you when I fixed our python wheels

**Pull request merged**
