### PR TITLE
feat(python): add offsets utility

### PR DESCRIPTION
**Pull request by ritchie46**
@stinodego this should be enough. Would this work?

It is zero copy.

### CODE REVIEW

**Comment by stinodego** [comment]
Are the offsets not `UInt64`? Otherwise looks fine, I can use this!

**Comment by ritchie46** [comment]
No, I wish they were. All arrow offsets are signed integers because Java. Because of that we need to check if they are not negative during runtime. :smiling_face_with_tear:

**Comment by ritchie46** [comment]
closes #10324

**Comment by alexander-beedie** [comment]
> because Java

The only type of coffee I _don't_ drink...  ;)

**Pull request merged**
