### PR TITLE
Remove read_excel hacks

### PR DESCRIPTION
**Pull request by cnpryer**
Removes eprint and sheet id hacks. Must use `xlsx2csv` 0.8.0 or greater.

### CODE REVIEW

**Comment by alexander-beedie** [comment]
> I don't think we have testing for `read_excel`. Might be an awkward fs test to have, but is that something we should add? Would make related contributions easier to vet.

Could construct a suitable xls/xlsx file and stash in `/tests/files/` for unit testing? (like some of the other io tests)

**Review by ghuls — APPROVED** [review]
With xls2csv fixed/updated, this should be good to go.

**Comment by cnpryer** [comment]
Yea I figured it'd be overkill.

**Comment by ritchie46** [comment]
Thanks all!

**Pull request merged**
