### PR TITLE
Time zone conversion bug (NY -> UTC works, UTC -> NY doesn't)

### PR DESCRIPTION
**Pull request by dpatton-gr**
~~Unit test that simply reproduces time zone conversion bug. Sadly my Rust skills aren't good enough to actually fix it :)~~
Turns out the fix was straightforward :)

### CODE REVIEW

**Comment by ritchie46** [comment]
Oh, your solution even simpler. Could you rebase on the changes I made?

**Comment by dpatton-gr** [comment]
> Oh, your solution even simpler. Could you rebase on the changes I made?

Ah yeah, will do :+1:

**Comment by dpatton-gr** [comment]
Done. Feel free to close this PR and raise a fresh one if you'd rather preserve the chronology / add the conventional labels in the title etc.
(Btw thanks so much for adding time zone support, it's game-changing for a lot of people I think)

**Comment by ritchie46** [comment]
Thanks!

**Pull request merged**
