### PR TITLE
extend literal fast-paths to string-replace methods

### PR DESCRIPTION
**Pull request by alexander-beedie**
As discussed, have now extended the optimisation previously made with `str.contains` to the following...

* `series.str.replace_all`
* `series.str.replace`
* `expr.str.replace_all`
* `expr.str.replace`

In **Python** there is a `literal` flag on the existing functions (to explicitly opt-in to literal replacement vs regex replacement), and in **Rust**, there is a corresponding new `*_literal` variant for each of the respective funcs.

Also, like the earlier `contains` patch, **the fast-path will be opted-into automatically** anyway _iif_ the supplied pattern is definitely not a regex (as defined by `!c.is_ascii_punctuation` on the constituent chars).

**No changes to default behaviour** on any existing calls - some will just get faster if the pattern implies a simple string-literal replace op, and any errors caused by Python-side escaping via `re.escape` can be avoided by opting-in explicitly via the `literal=True` flag (errors can occur due to no-op escapes, such as on a space char, not being handled identically between the two regex engines).

**Simple example** 

If the `literal` flag is set, can replace `*` char without having to escape it; will also run faster as the regex engine is not invoked (as it would be if treated as an escaped pattern):

```python
import polars as pl

df = pl.DataFrame(
    data    = [(1,"**text**"),(2,"*with special* chars**")],
    columns = ["idx","before"],
    orient  = "row",
).with_column(
    column  = pl.col("before").str.replace_all("*","",literal=True).alias("after")
)
# ┌─────┬────────────────────────┬────────────────────┐
# │ idx ┆ before                 ┆ after              │
# │ --- ┆ ---                    ┆ ---                │
# │ i64 ┆ str                    ┆ str                │
# ╞═════╪════════════════════════╪════════════════════╡
# │ 1   ┆ **text**               ┆ text               │
# ├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
# │ 2   ┆ *with special* chars** ┆ with special chars │
# └─────┴────────────────────────┴────────────────────┘
```

--

Also: 

* I _think_ I'm doing the right thing with `Cow::Owned`, but please correct me if not...  ;)
* I considered the literal flag for the `extract` funcs, but then couldn't think what the use-case for that actually is... maybe extracting the same substring and counting it? In which case a flag on `count_match` would be a better idea - can look at that next.

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks for the great PR. :+1: 

Your mention of `Cow` got me thinking. I don't think we should rust std's default replacement functions here. They always allocate and this is expensive. Maybe we should look at:

https://crates.io/crates/cow-utils

When it needs to allocate, it returns a `Cow::Owned` and otherwise a `Cow::Borrowed` with a slice to the original string. I think this crate is a good start. In a future optimization we can then improve upon that, and reuse the allocated `String` buffer every iteration.

**Comment by alexander-beedie** [comment]
> Your mention of `Cow` got me thinking. I don't think we should rust std's default replacement functions here. They always allocate and this is expensive. Maybe we should look at: https://crates.io/crates/cow-utils

Nice... even the least sophisticated usage here could be a big win for the -likely _very_ common- case of a literal pattern not being matched for a decent proportion of the strings under consideration. Doing no work at all is highly performant! :)

I'll take a look and see if I can do a simple first-pass. 

Also thinking of optimizing two other common cases - prefix/suffix stripping, as indicated by `^prefix` and `suffix$`. Should be trivial to spot these patterns and redirect to the equivalent literal fast-path (could have explicit `.str.startswith` and `.str.endswith` methods on the Python API too?)

Before that, will see about a literal fast-path for `count_match`, and extend the replace/contains docs with some examples that use the new option.

**Comment by ritchie46** [comment]
> Nice... even the least sophisticated usage here could be a big win for the -likely very common- case of a literal pattern not being matched for a decent proportion of the strings under consideration. Doing no work at all is highly performant! :)

Indeed. That would save a lot of system calls.

**Comment by alexander-beedie** [comment]
I'll tidy this up as a fresh PR after testing the `Cow` changes; seems to have been a noisy rebase, and I might make a few other small tweaks. (Also, the `match` syntax change to `str_contains` - what a night/day difference! Clearly should have been that way from the start - my bad  :)

**Pull request closed without merging**
