### PR TITLE
Code coverage for Rust/Python

### LINKED ISSUE #3241: Code coverage
I think adding more tests to the repo would help get ahead of issues. It is a little hard to tell at the moment what tests would have the best effect. I think adding an automated code coverage job in the CI would help focus any test improvement effort. For example, CodeCov has the ability to [merge reports from multiple languages](https://docs.codecov.com/docs/merging-reports). Happy to help set up a CI stage when I get a chance.

### PR DESCRIPTION
**Pull request by cjermain**
This resolves #3241 by introducing a new `make coverage` target that produces coverage for both the Rust and Python sections. This includes coverage of Rust code that called from Python tests (inspired by PyO3 coverage CI, and demoed in [cjermain/rust-python-coverage](https://github.com/cjermain/rust-python-coverage).

Example runs demoed in https://github.com/cjermain/polars/pull/1 have coverage of 77.21%:
https://codecov.io/gh/cjermain/polars/tree/e6e225779a974407ced2421ff8d32701423725e3

This requires CodeCov to be added to the polars repository/organization.

Follow up items:
- [ ] Add the CodeCov badge to the README.md

### CODE REVIEW

**Comment by zundertj** [comment]
This is great work!

Do you know why the individual files/lines are not being displayed? I.e. for instance https://app.codecov.io/gh/cjermain/polars/blob/e6e225779a974407ced2421ff8d32701423725e3/py-polars/polars/convert.py gives me a `There was a problem getting the source code from your provider. Unable to show line by line coverage.`

**Comment by cjermain** [comment]
Thanks @zundertj! I think the CodeCov error is because we don't have any coverage for the `master` branch, it is trying to compare the commit/branch against that.

**Comment by zundertj** [comment]
Now it does work, odd. Could be what you said as well.

**Comment by ritchie46** [comment]
This is pretty cool. How does it work? I mean how can it know even from calling python, which rust branches we hit?

**Comment by cjermain** [comment]
I wrote up a description of how the pieces fit together in the demo, which I think is easier to understand. This PR uses the same approach.
https://github.com/cjermain/rust-python-coverage#how-does-it-work

More detailed information on the `rustc` instrumentation-based coverage:
https://doc.rust-lang.org/stable/rustc/instrument-coverage.html

**Pull request merged**
