### PR TITLE
feat: use consistent float ordering, and allow float hashing

### PR DESCRIPTION
**Pull request by orlp**
Fixes https://github.com/pola-rs/polars/issues/10457.

### CODE REVIEW

**Comment by ritchie46** [comment]
Any news on this one @orlp?

**Comment by orlp** [comment]
@ritchie46 I'm finishing the asof PR today and getting back to working on this one. It's a lot more work than I initially thought and will likely have to be done in multiple PRs. We have quite a few places we compare items, and in a lot of places it's also assumed that `bit_repr` can be used to hash floats.

**Comment by ritchie46** [comment]
> 

> and in a lot of places it's also assumed that `bit_repr` can be used to hash floats.

True, I think we should get that out incrementally.

> Part of this PR is also moving the compute portion (the comparison kernels) out of polars-arrow into a new crate polars-compute.

Maybe we should think of the name of this one. As polars-ops also is compute, but requires the polars series/dataframe types first. I believe you want a polars-compute that only works on arrow memory right?

**Comment by orlp** [comment]
@ritchie46 

> Maybe we should think of the name of this one. As polars-ops also is compute, but requires the polars series/dataframe types first. I believe you want a polars-compute that only works on arrow memory right?

I'm not sure if I'd put it in such a hardline stance, but I'd see `polars-compute` as low-level basic operations. The place we'd put SIMD-specific stuff, raw operations. I'd see `polars-ops` as a place for higher-level operations using the `polars-compute` kernels, and lifting the low-level kernels to higher concepts like `Series`/`DataFrame`s.

**Pull request closed without merging**
