### PR TITLE
feat(python): Add `LazyFrame.collect_async`

### PR DESCRIPTION
**Pull request by Object905**
Hi! My first pull request here.

I've been heavily using polars in rest api with gunicorn.
Threaded workers are working ok, since polars usually does not hold GIL.
But now I've run into bottleneck where most of the time is spent waiting for LazyFrame.collect on python side and scaling threads further is becoming problematic. 

Since polars works in a threadpool I thought it would be nice to go further and be able to use gevent/asyncio, releasing control to other greenlets/tasks while waiting for collect to complete, like when querying database.

I've implemented this with queues, since gevent has [Synchronized queues](https://www.gevent.org/api/gevent.queue.html) that can be plugged in.
Also might be possible to use this for other purposes for optimizations on python side and asyncio by using `asyncio.queues.Queue`.

Added rayon dependency in py-polars, which might be bad, because they have to be kept in sync with workspace, but did not want to expose this as public api on rust side, but maybe function with callback `FnOnce(Result<DataFrame>) + Send + 'static` can also be useful in rust and just used in py-polars?

### CODE REVIEW

**Comment by stinodego** [comment]
Thanks for the PR!

If this is accepted, it should be called `collect_async`, or `async` should be a a toggle parameter for `collect`.

I'll leave it to someone else to judge whether this is worth including in the library.

**Comment by Object905** [comment]
I don't like async toggle parameter because it changes return type drastically.

I've though about collect_async, it's just when when you  type `.collect` in IDE its going to show up in suggestions. Which might not be as desirable, because it's a pretty niche api.

Anyway - renamed to collect_async for now.

**Comment by Object905** [comment]
Had other idea that might be not as intrusive.

Instead of making collect_async method on LazyFrame I could make `polars.collect_all_async` function in similar fashion .
Added benefit is that it also would make possible to send a list of LazyFrames at once.

**Comment by Object905** [comment]
Improved docs. Queue instance are passed, instead of class, because custom ones might have variations of how they are constructed. Made improvements regarding args/kwargs of queue.get and `queue` parameter required - because it's not much useful when you use default queue.Queue anyway.

Managed to avoid adding rayon dependency in py-polars, by using polars_core::POOL.

Added `polars.collect_all_async` - async variation of polars.collect_all.
Since it's a niche use, LazyFrame.collect_async may be removed to not bloat api? Because collect_all_async can be adapted for this case.

For those who would like to use this functionality for single frame this might be used for asyncio:

```
async def collect_async(ldf: polars.LazyFrame) -> Awaitable[polars.DataFrame]:
    return (await polars.collect_all_async([ldf], queue=janus.Queue().async_q).get())[0]

df = await ldf.pipe(collect_async)
```

**Comment by ritchie46** [comment]
I like this idea. On the rust side we are also looking how we can interact better with tokio runtimes. 

Can you tag the current public functions/methods as experimental? Then I think it is good to go.

**Comment by Object905** [comment]
Done. Marked as experimental, moved some notes under `Notes`.

**Comment by ritchie46** [comment]
Alright. Let's see how this goes. Thanks for the PR.

**Comment by jakob-keller** [comment]
Thanks @Object905, this feature could be very helpful in our heavily concurrent asyncio-based application.

I am wondering whether the API may be tweaked to return asyncio.Future instances or similar awaitables, eliminating the need for the queue argument?

`await ldf.collect_async()` would be sweet!

I could try to come up with a prototype, but I am unsure how to go ahead without breaking your gevent use case.

**Pull request merged**
