### PR TITLE
Workflow to generate m1 wheels

### LINKED ISSUE #1345: m1 wheels generation
#### Describe your feature request

Just realize one of my colleague can't install polars on his mac m1. Short of compiling from source on his machine,

what would be the best way of cross-compiling the project for him ?

Is there a plan to support building the m1 wheels for pip ?

### PR DESCRIPTION
**Pull request by tiphaineruy**
fixes #1345

Adds a workflow that generates universal2 wheel

### CODE REVIEW

**Comment by tiphaineruy** [comment]
This  workflow should be temporary I guess and at some point all the CI should be aggregated into one, named cleaned up etc.

I've tested It on my fork and was able to upload a universal2 wheel to pypi.test

You should probably replace -u ritchie46
by __token__ and use a dedicated token for the project at some point too.

**Comment by ritchie46** [comment]
Thanks a lot @tiphaineruy. This helps a lot. Does a universal2 wheel mean that its universal and also works x86_64? If so, is the other release pipeline for macOS not needed anymore?

> You should probably replace -u ritchie46
by token and use a dedicated token for the project at some point too.

Good one. That's probably better.

**Comment by tiphaineruy** [comment]
From what I read / saw in other project, convention seems to be to generate an x86_64 and a universal2.  I guess you could generate x86_64 and arm64 and not universal2.
When not on m1 pip will favor the x86 wheel for example which is lighter than bundling both arch.

The main issue I have with universal2 is the time as it need to build both arch, this is taking ~1h40m on ghaction.
 This is why I'll have to, when I have more time, merge that with the other ghaction to mutualize the x86 build. But I feel the .workflows folder need a cleanup.

**Comment by ritchie46** [comment]
Check. Maybe a specific `arm64` is better in that case indeed. For now, let's first release to M1 so that all the early adapter can use polars as well. :)

**Comment by tiphaineruy** [comment]
@ritchie46 Just a heads-up in case you missed it (didn't see you run it yet):
for now  the workflow is
>  on: [workflow_dispatch]
You'll have to run it manually. If you plan to make a wheel for current version.
If you just wait for next release, disregard this comment ;).

**Pull request merged**
