### PR TITLE
refactor(rust): Purge arrow-rs support

### PR DESCRIPTION
**Pull request by orlp**
This was a legacy holdover from before polars-arrow was vendored, we never used this.

### CODE REVIEW

**Comment by ritchie46** [comment]
A rebase away.

**Comment by deanm0000** [comment]
:(

**Comment by eitsupi** [comment]
Isn't this a breaking change?

**Comment by ritchie46** [comment]
For rust it is. And it will be in a major version bump. @deanm0000 did you use this? As it is arrow, you can still use ffi for this.

**Comment by deanm0000** [comment]
I was using to interop with geoarrow, or try to anyway

**Comment by sportfloh** [comment]
Hi, @ritchie46 
I used this to convert arrow-rs RecordBatches to a polars DataFrame like this:
```
pub fn record_batch_to_dataframe(batch: &RecordBatch) -> Result<DataFrame, PolarsError> {
    let schema = batch.schema();
    let mut columns = Vec::with_capacity(batch.num_columns());

    for (i, column) in batch.columns().iter().enumerate() {
        let arrow = Box::<dyn polars_arrow::array::Array>::from(&**column);
        columns.push(Series::from_arrow(
            schema.fields().get(i).unwrap().name().into(),
            arrow,
        )?);
    }

    Ok(DataFrame::from_iter(columns))
}
```
Is there an ffi example? Thanks!

**Comment by EricFecteau** [comment]
@sportfloh I found a solution using FFI: https://github.com/sfu-db/connector-x/discussions/720

**Pull request merged**
