### PR TITLE
feat(python): add expression method equivalents for existing math/logical operators

### LINKED ISSUE #4224: [Python] Expose all operators Expr implements as methods
#### Describe your feature request

Currently, Polars only exposes some operators as methods of Expr. I propose exposing all of them as methods of Expr

Advantages:
- consistent docs, all operators have corresponding functions which document the types.
   - Being able to find the `pow` function in docs but none of the other operators caused me no end of confusion.
- can be more readable when used in code, especially for longer chains

Additionally, it might make sense to use this as a way to document the operators and what arguments they can take as i was unable to find anything about that.

Currently implemented operators, and their method version if present:

|dunder operator|method|
|-|-|
`__invert__`|`self.is_not`
`__xor__`|` `
`__rxor__`|` `
`__and__`|` `
`__rand__`|` `
`__or__`|` `
`__ror__`|` `
`__add__`|` `
`__radd__`|` `
`__sub__`|` `
`__rsub__`|` `
`__mul__`|` `
`__rmul__`|` `
`__truediv__`|` `
`__rtruediv__`|` `
`__floordiv__`|` `
`__rfloordiv__`|` `
`__rmod__`|` `
`__mod__`|` `
`__pow__`|`self.pow`
`__rpow__`|` `
`__ge__`|`self.gt_eq`
`__le__`|`self.lt_eq`
`__eq__`|`self.eq`
`__ne__`|`self.neq`
`__lt__`|`self.lt`
`__gt__`|`self.gt`
`__neg__`|` `

Edit: it would probably make sense to do the same for DataFrame and Series operators, not just Expr

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #4224.

* Adds equivalent method expressions for the remaining comparison/math operators...
  ```python
  # python operators
  df_op = df.select(
      a = pl.col(c1) == pl.col(c2),
      b = pl.col(c1) // pl.col(c2),
      c = pl.col(c1) > pl.col(c2),
      d = pl.col(c1) >= pl.col(c2),
      e = pl.col(c1) < pl.col(c2),
      f = pl.col(c1) <= pl.col(c2),
      g = pl.col(c1) % pl.col(c2),
      h = pl.col(c1) != pl.col(c2),
      i = pl.col(c1) - pl.col(c2),
      j = pl.col(c1) / pl.col(c2),
      k = pl.col(c1) ^ pl.col(c2),
  )
  ```
  ```python
  # equivalent methods 
  df_expr = df.select(
      a = pl.col(c1).eq(pl.col(c2)),
      b = pl.col(c1).floordiv(pl.col(c2)),
      c = pl.col(c1).gt(pl.col(c2)),
      d = pl.col(c1).ge(pl.col(c2)),
      e = pl.col(c1).lt(pl.col(c2)),
      f = pl.col(c1).le(pl.col(c2)),
      g = pl.col(c1).mod(pl.col(c2)),
      h = pl.col(c1).ne(pl.col(c2)),
      i = pl.col(c1).sub(pl.col(c2)),
      j = pl.col(c1).truediv(pl.col(c2)),
      k = pl.col(c1).xor(pl.col(c2)),
  )
  ```
* ...and logical and/or (supporting *args, so you can splat or supply 'n' conditions):
  ```python
  # python operators
  df.select(
      all = (
          (pl.col("x") >= pl.col("z"))
          & (pl.col("y") >= pl.col("z"))
          & (pl.col("y") == pl.col("y"))
          & (pl.col("z") <= pl.col("x"))
          & (pl.col("y") != pl.col("x"))
      ),
      any = (
          (pl.col("x") == pl.col("y"))
          | (pl.col("x") == pl.col("y"))
          | (pl.col("y") == pl.col("z"))
          | (pl.col("y").cast(int) == pl.col("z"))
      )
  )
  ```
  
  ```python
  # equivalent methods 
  df.select(
      all = (pl.col("x") >= pl.col("z")).and_(
          pl.col("y") >= pl.col("z"),
          pl.col("y") == pl.col("y"),
          pl.col("z") <= pl.col("x"),
          pl.col("y") != pl.col("x"),
      ),
      any = (pl.col("x") == pl.col("y")).or_(
          pl.col("x") == pl.col("y"),
          pl.col("y") == pl.col("z"),
          pl.col("y").cast(int) == pl.col("z"),
      )
  )
  ```

### CODE REVIEW

**Comment by StevenLi-DS** [comment]
Hi @alexander-beedie, is there any reason why addition (+) and multiplication (*) are not included?

**Comment by alexander-beedie** [comment]
Multiplication is definitely included, just not listed above (will add for clarity); may have missed addition though, hmm. Will double-check.

**Comment by avimallu** [comment]
Amazing, thanks a lot! This will definitely make code less of an eyesore.

**Comment by alexander-beedie** [comment]
> Hi @alexander-beedie, is there any reason why addition (+) and multiplication (*) are not included?

@StevenLi-DS: have added the missing support for `add` in #7667 - that should be everything now? (since we don't have bitshift ops yet). Let me know if I overlooked anything else.

**Comment by alexander-beedie** [comment]
> @alexander-beedie Thanks man. I just look at it. Do we have exponentiation (x ** y)?

Yup; see [pow](https://github.com/pola-rs/polars/blob/275bd410b7775b797cee86bfdfa2f88b1264930d/py-polars/polars/expr/expr.py#L3534
). I'll do a second pass on the recent additions to give them better docstrings later, along the same lines.

**Pull request merged**
