### PR TITLE
feat: better `tree-formatting` representation 

### LINKED ISSUE #9685: Make `tree-formatting` beautiful
### Problem description

A good first issue on the rust side. If you have the patience to make ascii-art.

The names of the nodes should not change, but we could format cells, padding, alignment etc.

See #9684

Current implementation:

```python
>>> from polars import col
>>> e = (col("foo") * col("bar")).sum().over(col("ham")) / 2
>>> e.meta.tree_format()
```
```
    binary: /    

      |              |       

    lit(2)           window      

                     |               |        

                     col(ham)        sum          

                                     |        

                                     binary: *    

                                     |                |       

                                     col(bar)         col(foo)    


```

### PR DESCRIPTION
**Pull request by Cheukting**
Close #9685 

Right now this is how it looks like:

```
>>> from polars import col
>>> e = (col("foo") * col("bar")).sum().over("ham", "ham2") / 2
>>> e.meta.tree_format()

          1               2                3               4                5       
  ┌─────────────────────────────────────────────────────────────────────────────────
  |
  |  ╭───────────╮  
1 |  | binary: / |  
  |  ╰───────────╯  
  |       | ╰-------------╮        
  |       |               |        
  |       |               |        
  |  ╭────────╮       ╭────────╮     
2 |  | lit(2) |       | window |     
  |  ╰────────╯       ╰────────╯     
  |                       | ╰--------------╮---------------╮        
  |                       |                |               |        
  |                       |                |               |        
  |                   ╭───────────╮    ╭──────────╮    ╭─────╮        
3 |                   | col(ham2) |    | col(ham) |    | sum |        
  |                   ╰───────────╯    ╰──────────╯    ╰─────╯        
  |                                                        |        
  |                                                        |        
  |                                                        |        
  |                                                    ╭───────────╮  
4 |                                                    | binary: * |  
  |                                                    ╰───────────╯  
  |                                                        | ╰--------------╮       
  |                                                        |                |       
  |                                                        |                |       
  |                                                    ╭──────────╮     ╭──────────╮  
5 |                                                    | col(bar) |     | col(foo) |  
  |                                                    ╰──────────╯     ╰──────────╯  
```

To do for this PR to be ready:
- [x] Fix the test
- [x] Fix code formatting
- [x] Consider if the col/ row number go beyond 9 (handle double digit)

### CODE REVIEW

**Comment by Cheukting** [comment]
A few questions for @ritchie46:

- We are not going to handle the col/ row to be beyond 99 (which is very unlikely), is that OK?
- Do we want the index to start from 1 or 0?
- The format is slightly different from the suggestion from issue #9685 , that is due to the balance of looking nice and the complexity of the code. Are you happy with the preview above?

**Comment by orlp** [comment]
@Cheukting Could you remove that 99 limit? At the start you can check what the highest column/row index is, and calculate its width. Then you can print the numbers using `{:width$}` to all then consistently right-align to that width.

Also my preference would go out to zero-indexing, always.

**Comment by Cheukting** [comment]
@orlp Got it!

**Comment by Cheukting** [comment]
update preview:
```
>>> from polars import col
>>> e = (col("foo") * col("bar")).sum().over("ham", "ham2") / 2
>>> e.meta.tree_format()

           0               1               2                3               4        
   ┌─────────────────────────────────────────────────────────────────────────────────
   |
   | ╭───────────╮ 
 0 | | binary: / | 
   | ╰───────────╯ 
   |       | ╰─────────────╮        
   |       |               |        
   |       |               |        
   |  ╭────────╮      ╭────────╮    
 1 |  | lit(2) |      | window |    
   |  ╰────────╯      ╰────────╯    
   |                       | ╰──────────────╮───────────────╮        
   |                       |                |               |        
   |                       |                |               |        
   |                 ╭───────────╮    ╭──────────╮       ╭─────╮     
 2 |                 | col(ham2) |    | col(ham) |       | sum |     
   |                 ╰───────────╯    ╰──────────╯       ╰─────╯     
   |                                                        |        
   |                                                        |        
   |                                                        |        
   |                                                  ╭───────────╮  
 3 |                                                  | binary: * |  
   |                                                  ╰───────────╯  
   |                                                        | ╰──────────────╮       
   |                                                        |                |       
   |                                                        |                |       
   |                                                  ╭──────────╮     ╭──────────╮  
 4 |                                                  | col(bar) |     | col(foo) |  
   |                                                  ╰──────────╯     ╰──────────╯  

```

**Comment by ritchie46** [comment]
I love the looks @Cheukting! This will make debugging so much easier. :)

**Comment by Cheukting** [comment]
@orlp @ritchie46 seems Windows does not like UTF-8, any idea?

**Comment by orlp** [comment]
@Cheukting Could you be more specific? What goes wrong?

**Comment by Cheukting** [comment]
> @orlp @ritchie46 seems Windows does not like UTF-8, any idea?

So if we look at the [failed test here](https://github.com/pola-rs/polars/actions/runs/6233279240/job/16918157578?pr=11176#step:8:121) window will write out a bunch of utf-8 code like: `\u2500` instead of `─`

**Comment by orlp** [comment]
@Cheukting I think it might actually be the test-side that is broken, rather than Rust. Python does not open files in UTF-8 by default. Can you try replacing `.open("r")` with `.open("r", encoding="utf-8")`?

**Comment by Cheukting** [comment]
Thank you @orlp All green now :-)

**Review by ritchie46 — COMMENTED** [review]
Looks really nice @Cheukting. One question; how does it look if we have one column with an extremely long name?

**Comment by Cheukting** [comment]
> Looks really nice @Cheukting. One question; how does it look if we have one column with an extremely long name?

like this:

```
>>> from polars import col
>>> e = (col("foo") * col("bar")).sum().over(col("hammmmmmmmmmm which is veryyyyyyy long")) / 2
>>> e.meta.tree_format()

           0                                1                                 2               3        
   ┌───────────────────────────────────────────────────────────────────────────────────────────────────
   │
   │ ╭───────────╮ 
 0 │ │ binary: / │ 
   │ ╰───────────╯ 
   │       │ ╰──────────────────────────────╮                         
   │       │                                │                         
   │       │                                │                         
   │  ╭────────╮                       ╭────────╮                     
 1 │  │ lit(2) │                       │ window │                     
   │  ╰────────╯                       ╰────────╯                     
   │                                        │ ╰───────────────────────────────╮        
   │                                        │                                 │        
   │                                        │                                 │        
   │                 ╭─────────────────────────────────────────────╮       ╭─────╮     
 2 │                 │ col(hammmmmmmmmmm which is veryyyyyyy long) │       │ sum │     
   │                 ╰─────────────────────────────────────────────╯       ╰─────╯     
   │                                                                          │        
   │                                                                          │        
   │                                                                          │        
   │                                                                    ╭───────────╮  
 3 │                                                                    │ binary: * │  
   │                                                                    ╰───────────╯  
   │                                                                          │ ╰──────────────╮       
   │                                                                          │                │       
   │                                                                          │                │       
   │                                                                    ╭──────────╮     ╭──────────╮  
 4 │                                                                    │ col(bar) │     │ col(foo) │  
   │                                                                    ╰──────────╯     ╰──────────╯  

>>> e = col("hammmmmmmmmmm which is veryyyyyyy looooooooooooong")
>>> e.meta.tree_format()

                                  0                              
   ┌─────────────────────────────────────────────────────────────
   │
   │ ╭─────────────────────────────────────────────────────────╮ 
 0 │ │ col(hammmmmmmmmmm which is veryyyyyyy looooooooooooong) │ 
   │ ╰─────────────────────────────────────────────────────────╯ 

>>> 

```

**Comment by ritchie46** [comment]
Great stuff! IMO it looks great. :)

Thank you and welcome to the contributors. Luckily we finished well within a visa duration. ;)

**Review by ritchie46 — APPROVED** [review]

**Comment by Cheukting** [comment]
Yay! Thank you for the guidance @orlp and @ritchie46 - I am looking for the next task (maybe another issue) if there's any :-)

**Comment by alexander-beedie** [comment]
> Yay! Thank you for the guidance @orlp and @ritchie46 - I am looking for the next task (maybe another issue) if there's any :-)

Looking at our Issue tracker I'm sure you will be able to find something, heh :)
Nice contribution!

**Pull request merged**
