### PR TITLE
docs(python): make an explicit note in `read_parquet` and `scan_parquet` about hive-style partitioning (point to `scan_pyarrow_dataset` instead)

### PR DESCRIPTION
**Pull request by alexander-beedie**
Ref #10276.

### CODE REVIEW

**Comment by stinodego** [comment]
I'd rather we implement the functionality than add a note like this. Maybe add it as a warning instead, saying something like "not implement yet for read_parquet".

**Comment by alexander-beedie** [comment]
> I'd rather we implement the functionality than add a note like this. Maybe add it as a warning instead, saying something like "not implement yet for read_parquet". And this should not close the linked issue.

Would be great if we added it, but while the functionality _doesn't_ exist we do need to point people to where it is ;)
I'll change "closes" to "ref" so we leave the issue open as a reminder.

**Comment by stinodego** [comment]
Agreed! That's why I would say let's make it a warning, because users might expect that functionality to be in there.

**Comment by alexander-beedie** [comment]
> Agreed! That's why I would say let's make it a warning, because users might expect that functionality to be in there already and run into trouble.

You don't think a `Warning` is a bit strong? I'll add some `See Also` sections to these functions too - that might also help make it clearer that there are several related pieces of functionality 🤔

**Review by stinodego — APPROVED** [review]
All right then, this will be nice to have until we improve `read/scan_parquet` capabilities!

**Comment by alexander-beedie** [comment]
> All right then, this will be nice to have until we improve `read/scan_parquet` capabilities!

Good things are coming! I'm excited about the improving cloud functionality :))

**Pull request merged**
