### PR TITLE
fix(rust): Resolve the compilation error when utilizing the `lazy` feature

### PR DESCRIPTION
**Pull request by bioinformatist**
Currently, using `lazy` feature will cause the compiler to raise an error like:

image

The issue arises from conditional compiling: the match arms on enum `ALogicalPlan` must cover the `HConcat` variant, but the arm [was bypassed](https://github.com/pola-rs/polars/blob/main/crates/polars-lazy/src/physical_plan/planner/lp.rs#L175-L184) by default.

### CODE REVIEW

**Comment by ritchie46** [comment]
Activating the feature is not a way to resolve this. Can you fix the conditional compilation please?

**Comment by bioinformatist** [comment]
Yeah it seems have some side effect to architecture. Let me have a try.

**Comment by ritchie46** [comment]
I already removed the feature. So this is fixed on main. Will issue a release shortly.

**Comment by bioinformatist** [comment]
I've observed that. Or do you think the feature could be kept by the method in this PR?

**Comment by bioinformatist** [comment]
> I already removed the feature. So this is fixed on main. Will issue a release shortly.

I've observed that. Or do you think the feature could be kept by the method in this PR?

**Pull request closed without merging**
