### PR TITLE
fix(python): Allow for tolerance when comparing nested dtype columns

### LINKED ISSUE #9264: assert_frame_equal no tolerance with pl.List columns
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`polars.testing.assert_frame_equal()` seems always to do an exact check on `List` columns.
The `atol` and `rtol` arguments do not seem to make a difference. 

### Reproducible example

```python
import polars as pl
from polars.testing import assert_frame_equal


# This one does not raise an AssertionError:
assert_frame_equal(
    pl.from_dict({'A': [0.2, 0.3]}),
    pl.from_dict({'A': [0.2, 0.3000000000000001]}),
    atol=1e-5,
)

# This raises an AssertionError:
assert_frame_equal(
    pl.from_dict({'A': [[0.2, 0.3]]}),
    pl.from_dict({'A': [[0.2, 0.3000000000000001]]}),
    atol=1e-5,
)
```

### Expected behavior

The second example should not raise an `AssertionError`, as the difference is below the specified tolerance.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Linux-6.3.2-arch1-1-x86_64-with-glibc2.37
Python:      3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
----Optional dependencies----
numpy:       1.24.2
pandas:      2.0.0
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by dkrako**
Resolves #9264

I have added four test cases to test exact matching and tolerance for `assert_frame_equal` and `assert_series_equal`.

The problematic code was at the beginning of `_assert_series_inner` where `check_exact` was being overwritten.

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Nice :)  Could you add a few more tests to explicitly cover more permutations?
Integer tolerances, negative values, larger tolerances, etc?

**Comment by dkrako** [comment]
Sure! I have added some more tests and luckily identified a case where nested types were tried to be subtracted.

**Review by alexander-beedie — CHANGES_REQUESTED** [review]
One last update and I think we're good - doesn't seem like the float tolerance goes to 'n' levels of nesting yet, eg:
```python
# list[f64]
assert_frame_equal( 
    pl.DataFrame({"a": [[0.2, 3.]]}),
    pl.DataFrame({"a": [[0.2, 3.00000001]]}),
)
```
```python
# list[list[f64]]
assert_frame_equal( 
    pl.DataFrame({"a": [[[0.2, 3.]]]}),
    pl.DataFrame({"a": [[[0.2, 3.00000001]]]}),
)
# AssertionError: Values for column 'a' are different.
```

**Comment by dkrako** [comment]
Thanks for noticing! I have added even more tests and could find another bug when comparing nans.

**Comment by dkrako** [comment]
I added more tests including testing of struct datatypes

**Review by alexander-beedie — APPROVED** [review]

**Comment by alexander-beedie** [comment]
> I added more tests including testing of struct dtypes

Great job; thanks for taking the time.

**Pull request merged**
