### PR TITLE
feat(python): add multi-threaded apply

### PR DESCRIPTION
**Pull request by ritchie46**
I don't like it, but I also don't want to content with a dask or pandarallel thread/multiprocess pool.

We can do something similar for multiprocessing behind a big fat warning that you only should do this as last resort.

### CODE REVIEW

**Comment by josh** [comment]
Haha, I was surprised to see this go in so quickly. But I'll poke it at it as well. One area it _may_ also help is IO blocked UDFs. Should _someone_ do something crazy like make HTTP requests to fill a column 🫣

**Comment by alexander-beedie** [comment]
> Should _someone_ do something crazy like make HTTP requests to fill a column 🫣

_"Confess..."_🤣

**Comment by ritchie46** [comment]
Do most http libs release the GIL?

**Comment by josh** [comment]
> Do most http libs release the GIL?

Most will end using the builtin Py C socket library, so it should. This apply for common `requests`/`urllib3` usage.

**Comment by alexander-beedie** [comment]
Can confirm that `requests` does...
https://github.com/psf/requests/issues/3474

**Pull request merged**
