### PR TITLE
fix: consume duplicates in rolling_by window

### PR DESCRIPTION
**Pull request by ritchie46**
@MarcoGorelli FYI

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
nice! so, salvaging the fastpath rather than conditionally taking a slowpath

Just as a suggestion, is it possible to keep the parametric tests from #11237? They're very fast to run, and would add quite some confidence in the method's correctness (it's from them that I discovered the duplicates bug)

**Comment by ritchie46** [comment]
Sure, can you open them as a separate PR?

**Comment by MarcoGorelli** [comment]
https://github.com/pola-rs/polars/pull/11262

good news is - those tests currently fail, but when rebased onto this branch, they pass! very confident in `group_by_rolling`'s correctness then 🎉

**Comment by ritchie46** [comment]
>  so, salvaging the fastpath 

Yes, I didn't like a full data pass to check if we have duplicates. This shouldn't have any noticable performance implications on the happy  path, most of our time is in the binary search and the `Duration::add_us`.

image


I think we should take a look at both later.

**Pull request merged**
