### PR TITLE
Optional pyarrow

### PR DESCRIPTION
**Pull request by ghuls**

### CODE REVIEW

**Comment by ritchie46** [comment]
Looks good! I am not sure about this, but maybe we could replace the kwargs `pyarrow=True`, with `pyarrow=_PYARROW_AVAILABLE` to increase ergonomics?

**Comment by ghuls** [comment]
It still might be nice to opt in specificly for the pyarrow parser for read_csv, read_ipc and read_parquet. I assume it some conditions the polars parser is better suited than the pyarrow parser while still needing pyarrow for other operations.

**Comment by ghuls** [comment]
For optional dependencies a `fsspec` section in `pyproject.toml` probably should be added as well in the future, so it it more discoverable that it is supported too for reading files.

**Comment by ritchie46** [comment]
> It still might be nice to opt in specificly for the pyarrow parser for read_csv, read_ipc and read_parquet. I assume it some conditions the polars parser is better suited than the pyarrow parser while still needing pyarrow for other operations.

Yes, so we let the `use_pyarrow=False` as is. And I think we have to reconsider some defaults. The native parsers are maturing rapidly.

**Comment by ritchie46** [comment]
> For optional dependencies a fsspec section in pyproject.toml probably should be added as well in the future, so it it more discoverable that it is supported too for reading files.

Yes, and connectorx. I believe that's all

**Comment by ritchie46** [comment]
It looks great, thanks a lot. Let me know when its ready to go.

**Comment by ghuls** [comment]
I think it is fine now (fixed some "a Arrow" to "an Arrow" error strings and added extra optional dependencies. It would be good if someone else would test it too.

**Comment by ritchie46** [comment]
>  It would be good if someone else would test it too.

Yes, I will see if I can create CI tests for a native installation.

**Comment by jorgecarleitao** [comment]
I do not know the size of polars these days, but I know of people using pandas+pyarrow in lambdas hitting the 50Mb threshold for the size of a lambda, so this is quite promising. Thank you for this!

**Comment by ghuls** [comment]
> I do not know the size of polars these days, but I know of people using pandas+pyarrow in lambdas hitting the 50Mb threshold for the size of a lambda, so this is quite promising. Thank you for this!

For a release build of polars it seems like it is around 30MB.

**Pull request merged**
