### PR TITLE
fix(rust,python): return same dtype for mean/median for datetime/duration

### LINKED ISSUE #10232: Median on duration Series returns a datetime rather than a timedelta
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import timedelta
import polars as pl
s = pl.Series("s", [timedelta(0), timedelta(1)])
s.describe()
```

Output:
```
shape: (5, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ value               │
│ ---        ┆ ---                 │
│ str        ┆ str                 │
╞════════════╪═════════════════════╡
│ count      ┆ 2                   │
│ null_count ┆ 0                   │
│ min        ┆ 0:00:00             │
│ max        ┆ 1 day, 0:00:00      │
│ median     ┆ 1970-01-01 12:00:00 │
└────────────┴─────────────────────┘
```

### Issue description

The median shows up as a datetime in .describe() of a Series.  But in a dataframe, the result is correctly a timedelta/duration.

### Expected behavior

Expected:
```
shape: (5, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ value               │
│ ---        ┆ ---                 │
│ str        ┆ str                 │
╞════════════╪═════════════════════╡
│ count      ┆ 2                   │
│ null_count ┆ 0                   │
│ min        ┆ 0:00:00             │
│ max        ┆ 1 day, 0:00:00      │
│ median     ┆ 12:00:00            │
└────────────┴─────────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            Linux-3.10.0-1160.92.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.9.17 (main, Jun  8 2023, 11:31:03) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Resolves #10232

I realized after implementing this that on the python side we already had this for expressions:

```python
    def median(self) -> dt.date | dt.datetime | dt.timedelta | None:
        """
        ...docstring
        """
        s = wrap_s(self._s)
        out = s.median()
        if out is not None:
            if s.dtype == Date:
                return _to_python_date(int(out))
            else:
                return _to_python_datetime(int(out), s._s.time_unit())
```

which sort of indicates that on the rust side it was intended to keep the mean/median as the physical float64. Is this the case and should I tackle the issue on the python side instead?

### CODE REVIEW

**Comment by stinodego** [comment]
I'll have to page @ritchie46 on this one.

**Comment by ritchie46** [comment]
@mcrumiller can you make sure CI is green?

**Comment by mcrumiller** [comment]
@ritchie46 sure--can you comment on the OP up top?

**Comment by mcrumiller** [comment]
Ok, here's another question: the mean and median of an integer series is a float. Should the mean and median of a date be a datetime?

**Comment by MarcoGorelli** [comment]
looks like there's lots of test failures and a merge conflict, could you fix this up please then I'll take a look?

**Comment by mcrumiller** [comment]
Hi Marco, I got stuck trying to get median/std working for expressions that
was mentioned in another issue. I'll get this one working today.

**Comment by mcrumiller** [comment]
I'm going to close this an open another PR.

**Pull request closed without merging**
