### PR TITLE
feat(python): support setting multiple conditional formats on the same `Excel` table column/range

### PR DESCRIPTION
**Pull request by alexander-beedie**
A follow-on from #7379, which allowed one format to be applied to multiple columns...

...can now apply multiple conditional formats to the same column/range; just supply them as a list.

## Also

* Extends parameterised tests to cover additional Excel export variations.
* Further improves typing and the help/docstring.

## Example

Building on the [previous](https://github.com/pola-rs/polars/pull/7379) demo...

```python
df = pl.DataFrame(
    {
        "jan": range(0,12,1),
        "feb": range(0,24,2),
        "mar": range(0,36,3),
        "apr": range(0,48,4),
        "may": range(0,60,5),
        "jun": range(0,72,6),
        "jul": range(0,84,7),
        "aug": range(0,96,8),
        "sep": range(0,108,9),
        "oct": range(0,120,10),
        "nov": range(0,132,11),
        "dec": range(0,144,12),
    }
)
```
...apply _multiple_ formats to the same column-range:
```python
cols = tuple( df.columns )

df.write_excel(
    conditional_formats = {
        cols: [
            {"type":"3_color_scale"},
            {"type":"unique", "format":{"font_color":"#ffffff"}},
            {"type":"cell", "criteria":"between", "minimum":30, "maximum":55, "format":{"bold":True}},
        ],
    },
    column_widths = {cols: 45},
)
```
* Apply three-colour scale as a heatmap.
* Highlight values that only occur once in white.
* Bold formatting for values falling within a specific range.

xl_multiple_conditional_formats

### CODE REVIEW

**Comment by alexander-beedie** [comment]
FYI: @jmcnamara - this should complete exposing all (?) conditional formatting capabilities.

**Comment by ritchie46** [comment]
We don't have plotting functionality, but we come very close. :D

**Comment by jmcnamara** [comment]
> FYI: @jmcnamara - this should complete exposing all (?) conditional formatting capabilities.

It looks like it. At this point I don't remember all of the feature myself. :-) However, it looks like anything that could be done via xlsxwriter can be done in polars now. I may add your heat map example to the XlsxWriter docs since that is a nice visual example.

**Comment by jmcnamara** [comment]
> We don't have plotting functionality, but we come very close. :D

@ritchie46 It isn't generalise plotting but you can [add Excel charts to the polars output](https://xlsxwriter.readthedocs.io/working_with_polars.html#adding-charts-to-dataframe-output) with just a few extra steps.

**Pull request merged**
