### PR TITLE
test(python): add `-S` option to prevent site import

### LINKED ISSUE #9138: test_polars_import intermittently fails
### Issue description

One of the two intermittently failed tests mentioned in #9122.

I looked into the `test_polars_import` and I've found the issue:

```python
        if_err = f"Possible import speed regression; took {total_import_time//1_000}ms"
        assert total_import_time < 200_000, f"{if_err}\n{df_import}"
```

The total import time was taking too long. The test runs the following:

```
python -X importtime -c "import polars"
```

And looking at the output, we have this:

```
FAILED tests/unit/test_polars_import.py::test_polars_import - AssertionError: Possible import speed regression; took 205ms
  ┌───────────────────────────────────────────────────────────────┬──────────┬─────────────────┐
  │ import                                                        ┆ own_time ┆ cumulative_time │
  │ ---                                                           ┆ ---      ┆ ---             │
  │ str                                                           ┆ i32      ┆ i32             │
  ╞═══════════════════════════════════════════════════════════════╪══════════╪═════════════════╡
  │  polars                                                       ┆ 1298     ┆ 123721          │
  |                                      ...                                                   |
  │        email                                                  ┆ 469      ┆ 469             │
  │  site                                                         ┆ 64801    ┆ 205091          │
  │    sitecustomize                                              ┆ 232      ┆ 232             │
  │    _sysconfigdata_m_linux_x86_64-linux-gnu                    ┆ 734      ┆ 734             │
  │    coverage                                                   ┆ 341      ┆ 122808          │
  │      coverage.control                                         ┆ 2058     ┆ 122007          │
                   ...
```

The `site` import is separate from `polars`. Looking at the [docs for the site module](https://docs.python.org/3/library/site.html), we have this:

> **This module is automatically imported during initialization**. The automatic import can be suppressed using the interpreter’s [`-S`](https://docs.python.org/3/using/cmdline.html#cmdoption-S) option.
>
>Importing this module will append site-specific paths to the module search path and add a few builtins, unless [`-S`](https://docs.python.org/3/using/cmdline.html#cmdoption-S) was used. In that case, this module can be safely imported with no automatic modifications to the module search path or additions to the builtins. To explicitly trigger the usual site-specific additions, call the [`site.main()`](https://docs.python.org/3/library/site.html#site.main) function.

So, for our import test, I believe we should use the `-S` option, since we're only concerned with how long polars takes to load, not the `site` module, which is outside of our control.

### PR DESCRIPTION
**Pull request by mcrumiller**
Resolves #9138

### CODE REVIEW

**Comment by stinodego** [comment]
No, it's the import test that is failing here. So the fix doesn't seem to work - or at least, it doesn't fully solve the issue.

**Comment by mcrumiller** [comment]
It must be a python 3.7 issue then, the test runs fine when I run it, and although the issue is in the import test, it occurs during the `ldf.collect()`.

**Comment by mcrumiller** [comment]
Ok, it looks like `-S` may not work on 3.7.

**Comment by mcrumiller** [comment]
Ok, I have a better solution, since it looks like `-S` messes with the site-packages potentially, and we probably don't want that.

The call to `python -X importtime -c "import polars"` returns a frame that includes import times for `polars` and `site`. We should simply ignore the records containing `site` and recompute our own cumulative times.

I'm going to cancel this PR and make a new one.

**Pull request closed without merging**
