### PR TITLE
feat[python]: Optionally return an writable numpy array with Series()…

### PR DESCRIPTION
**Pull request by ghuls**
….to_numpy(writable=True) (#4563)

Optionally return an writable numpy array with Series().to_numpy(writable=True).

Closes: #4563

### CODE REVIEW

**Comment by ghuls** [comment]
@ritchie46 at first sight looks like pl.Series(view() does not work on Windows.

```python
 monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x000001D93CC4F970>

    def test_to_numpy(monkeypatch: Any) -> None:
        for writable in [False, True]:
            for flag in [False, True]:
                monkeypatch.setattr(pl.internals.series.series, "_PYARROW_AVAILABLE", flag)
    
                np_array = pl.Series("a", [1, 2, 3], pl.UInt8).to_numpy(writable=writable)
    
>               np.testing.assert_array_equal(np_array, np.array([1, 2, 3], dtype=np.uint8))
E               AssertionError: 
E               Arrays are not equal
E               
E               Mismatched elements: 3 / 3 (100%)
E               Max absolute difference: 71
E               Max relative difference: 71.
E                x: array([72, 16, 12], dtype=uint8)
E                y: array([1, 2, 3], dtype=uint8)
```

**Comment by ritchie46** [comment]
> @ritchie46 at first sight looks like pl.Series(view() does not work on Windows.
> 
> ```python
>  monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x000001D93CC4F970>
> 
>     def test_to_numpy(monkeypatch: Any) -> None:
>         for writable in [False, True]:
>             for flag in [False, True]:
>                 monkeypatch.setattr(pl.internals.series.series, "_PYARROW_AVAILABLE", flag)
>     
>                 np_array = pl.Series("a", [1, 2, 3], pl.UInt8).to_numpy(writable=writable)
>     
> >               np.testing.assert_array_equal(np_array, np.array([1, 2, 3], dtype=np.uint8))
> E               AssertionError: 
> E               Arrays are not equal
> E               
> E               Mismatched elements: 3 / 3 (100%)
> E               Max absolute difference: 71
> E               Max relative difference: 71.
> E                x: array([72, 16, 12], dtype=uint8)
> E                y: array([1, 2, 3], dtype=uint8)
> ```

Nope, I am quite positive that we should not use `view` here. It is UB, as we drop the series after that. 

The only way I see that to work is for use to assign the `Series` as an attribute to the array we return. That way we will not drop the series before the numpy array is deleted.

**Comment by ghuls** [comment]
Can this be fixed in `view` in general?

**Comment by ghuls** [comment]
Seems like you can't add an attribute to an ndarray by default. https://stackoverflow.com/questions/67509913/add-an-attribute-to-a-numpy-array-in-runtime

**Comment by ritchie46** [comment]
Can you do a rebase @ghuls? I think it should work now.

**Comment by ghuls** [comment]
Rebased.

I also build polars for Pypy and ran the tests. Now it didn't give an error. 2 weeks ago it did, related to some numpy test, so your save memory view patch seems to work fine.

**Comment by ritchie46** [comment]
> Rebased.
> 
> I also build polars for Pypy and ran the tests. Now it didn't give an error. 2 weeks ago it did, related to some numpy test, so your save memory view patch seems to work fine.

Ah, nice. Two birds with one stone. :)

**Pull request merged**
