### PR TITLE
chore(python): Update PyO3

### PR DESCRIPTION
**Pull request by ritchie46**

### CODE REVIEW

**Comment by stinodego** [comment]
> A new #[pyclass(frozen)] option has been added to opt-out of runtime borrow checking by removing the ability to access &mut self for objects owned by Python.

Maybe this helps deal with those pesky clippy warnings (borrow_deref_ref)?

**Comment by stinodego** [comment]
@ritchie46 Any reason you left this be? I'd be interested in figuring out how to do this migration.

Reference:
https://pyo3.rs/latest/migration.html#from-016-to-017

**Comment by ritchie46** [comment]
This was blocked by https://github.com/PyO3/pyo3/issues/2615. I think we can update on next py03 0.18 release.

**Comment by stinodego** [comment]
PyO3 version [0.18.0](https://github.com/PyO3/pyo3/releases/tag/v0.18.0) was recently released! So we can see if an upgrade is possible now.

**Comment by jjerphan** [comment]
Hi! I am interested by PyO3. Is there something blocking this PR? Can I help in some way, for example by pursuing it? :slightly_smiling_face:

**Comment by stinodego** [comment]
I believe the blocking issue has been resolved in the latest version of PyO3. Feel free to make a fresh PR with the PyO3 version update!

**Comment by jjerphan** [comment]
Thanks! I have opened https://github.com/pola-rs/polars/pull/6531 to follow-up.

**Comment by stinodego** [comment]
This can be closed, as #6531 was just merged.

**Pull request closed without merging**
