### PR TITLE
fix(rust, python): Fix erroneous warning in `hist`

### LINKED ISSUE #8978: "not explicitly sorted" warning in `Series.hist`
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This triggers from the doctests. 

### Reproducible example

```python
import polars as pl

s = pl.Series([1,2,3,4])
s.hist(bin_count=2)
# argument in operation 'asof_join' is not explicitly sorted
```

### Expected behavior

There should be no warning - the implementation in `polars_algo` must set the sorted flag properly.

### Installed versions

master

### PR DESCRIPTION
**Pull request by CloseChoice**
closes #8978

### CODE REVIEW

**Comment by CloseChoice** [comment]
Did not find a good way to test that no warning is thrown. If anyone could point me towards a good solution, I'll really appreciate it.

**Review by stinodego — APPROVED** [review]
I can confirm this resolves the issue.

You could probably write a test for this using pytest `capsys` - but I think it's better not to. This warning is only temporary, and we are looking to implement a better way of raising warnings from Rust anyway.

**Comment by CloseChoice** [comment]
I already tried the `capsys` fixture but did not figure out a way how to access the stdout only stderr.

**Comment by ritchie46** [comment]
Thank you @CloseChoice

**Pull request merged**
