### PR TITLE
fix(python): Fix empty list or Series selections on DF or Series

### PR DESCRIPTION
**Pull request by mgperry**
Addresses  #8659

I've refactored the 2 `_pos_idxs` methods into a single Series method (operating on self) and a function for converting numpy to indexes, since there was a lot of shared logic between methods (rather than just adding sentinels to both). I'm also unsure if the numpy method is actually more performant or correct than just casting to the related polars type (zero copy?) and calling the Series method.

### CODE REVIEW

**Comment by ghuls** [comment]
If I remember correctly the numpy branch was needed to avoid at least one additional allocation (and a noticable slower function if you have a lot of indices).

It could be that is was just this call that is more optimal than, similar code for Series:
```
        # Update negative indexes to absolute indexes.
        idxs = np.where(idxs < 0, size + idxs, idxs)
```

The pull request that introduced this whole code:
https://github.com/pola-rs/polars/pull/4160

To benchmark, create a big dataframe/series and a big index Series and numpy array for all different integer types.
You will see that UInt32 and np.uint32 will be the fastest (for normal Polars, for Polars big-idx is should be the UInt64 and np.uint64 variants). The other integer types are at least twice slower, some even 3 times if I remember correctly.

**Comment by mgperry** [comment]
So you're saying we should cast the Series to numpy then :P

In all seriousness, the Series method does go through the frame/expr api so it would not be suprising if it was slower. I will run some benchmarks if I get the chance.

**Comment by mgperry** [comment]
So I ran some benchmarks on just the conversion for 10M rows of Int32. numpy is faster on two counts:
- the conversion is around 10x faster (`np.where` vs `idxs.to_frame()` etc.)
- casting numpy is around 50x faster (np.int32 -> np.uint32)

I assume the dramatic difference in casting speed is due to checks, however in this case we've manually performed the checks, so a faster code path might be available. We could even speed up the numpy version by doing the casting with `np.astype` before building the series. 

The conversions add some overhead but not much, converting the series to numpy and back still gives a >10x speedup.

**Comment by ritchie46** [comment]
> I assume the dramatic difference in casting speed is due to checks, however in this case we've manually performed the checks, so a faster code path might be available. We could even speed up the numpy version by doing the casting with np.astype before building the series.

I think we should add the posibility to do unchecked casts as well. Currently we check if the cast can be done, which is very costly. Probably blocks autovectorization.

**Comment by mgperry** [comment]
The checks themselves (`min()`, `max()` etc.) are also quite a bit faster using numpy.

**Comment by ritchie46** [comment]
Could @stinodego or @alexander-beedie check if this is good to go?

**Comment by alexander-beedie** [comment]
> Could @stinodego or @alexander-beedie check if this is good to go?

Sure, I can give this a good look-over tonight, no problem (my brain is currently melting at work, so won't be much help until this evening ;) 👍

**Comment by ritchie46** [comment]
Thanks! Take care of your brain in the mean time. :)

**Comment by alexander-beedie** [comment]
So, needs a rebase, but otherwise I think this is almost ready to go; a few comments to address first:

In a nice bit of synergy (following the merge of #9004) I think we can now massively speed-up the `is_int_sequence` check by basically just... not doing it (but safely) ;)

We just need to check that the _first_ value `isinstance(v,int) and not isinstance(v,bool)` and then immediately init the Series - if any values are not conformant it'll throw, so we can skip checking every element in python-space first.

Also, the Series dtype used to take values should be `get_index_type()`; no need to allocate for 64bit if we don't have to. If we want to continue to disallow nulls [^1], all we have to do is check `has_validity()` on the indexing Series after init.

I think this change should cover the above points, while matching the existing behaviour:
```python
  elif (
      isinstance(item, Sequence)
      and not item
      or (isinstance(item[0], int) and not isinstance(item[0], bool))
  ):
      idx_series = Series("", item, dtype=get_index_type())._pos_idxs(self.len())
      if idx_series.has_validity():
          raise ValueError("Cannot __getitem__ with index values containing nulls" )
      return self._take_with_series(idx_series)
```

Let's also address a leftover typing gremlin while we're at it; I don't believe we should still be advertising ` | list[bool]` in the `__getitem__` signature.

I'll check again tomorrow after these tweaks and a rebase? 👍
I'd expect it to be good to go then.

[^1]: I don't really mind allowing nulls - for each index value that's null, you just get a null back; not that crazy? :)

**Review by alexander-beedie — CHANGES_REQUESTED** [review]
So, needs a rebase, but otherwise I think this is almost ready; a few comments:

In a nice bit of synergy (following the merge of #9004) I think we can now massively speed-up the `is_int_sequence` check (in Series `__getitem__`) by basically just... not doing it (but safely) ;)

We only need to check that the _first_ value `isinstance(v,int) and not isinstance(v,bool)` and then immediately init the Series - if any values are not conformant it'll throw, so we can skip checking every element in python-space first; this should be a nice speedup for large numbers of index values. (We may be able to skip checking the first value too; I haven't tested all the potential permutations yet, so being slightly conservative ;)

Also, the Series dtype used to take values should be `get_index_type()`; no need to allocate for 64bit if we don't have to. If we want to continue to disallow nulls [^1], all we have to do is check `has_validity()` on the indexing Series after init.

I think something like this should cover the above points, while matching the existing behaviour:
```python
  elif (
      isinstance(item, Sequence)
      and not item
      or (isinstance(item[0], int) and not isinstance(item[0], bool))
  ):
      idx_series = Series("", item, dtype=get_index_type())._pos_idxs(self.len())
      if idx_series.has_validity():
          raise ValueError("Cannot __getitem__ with index values containing nulls" )
      return self._take_with_series(idx_series)
```

Let's also address a leftover typing gremlin while we're at it; I don't believe we should still be advertising ` | list[bool]` in the Series `__getitem__` signature.

I'll check again tomorrow after these tweaks and a rebase?
I'd expect it to be good to go then. 👍

[^1]: I don't really mind allowing nulls - for each index value that's null, you just get a null back; not that crazy? :)

**Comment by mgperry** [comment]
Hi Alex, thanks for the review, didn't get round to this today but I have time early tomorrow.

**Comment by ritchie46** [comment]
@mgperry can you ping me once you made the changes?

**Comment by mgperry** [comment]
I've made these changes with one exception:
- We need to use Int64 rather than the index type because we are taking native python integers, which can be negative. Checking for positive integers in python space will surely be slower than doing the conversion, and if users really care about speed (and know there are no negative numbers) they can directly make a UInt32 (or 64 for big polars) Series.

Re: lists of booleans, it looks like we also can't subset a dataframe or series using a series of booleans. There aren't any tests for this, is this the desired behaviour? I can imagine cases where this could be useful, it's certainly a common pattern in R, although i guess `filter` expressions are preferred.

PS Apologies for the slight delay it took me a while to figure out that i was trying to rebase across a merge.

**Comment by alexander-beedie** [comment]
@mgperry: all makes sense - could you rebase/resolve? 
Would be nice to get this in :)

**Comment by mgperry** [comment]
rebased + resolved

**Review by alexander-beedie — APPROVED** [review]

**Comment by alexander-beedie** [comment]
> rebased + resolved

Nice one; thanks for the contribution! :)

**Pull request merged**
