### PR TITLE
depr(python, rust!): Rename `count_match` to `count_matches`

### LINKED ISSUE #10907: Rename str.count_match to str.count_matches
I find the singular [`count_match`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.count_match.html#polars.Expr.str.count_match) to be rather jarring. I think we should rename it (with a deprecated alias) to `count_matches`.

### PR DESCRIPTION
**Pull request by I8dNLo**
Closes #10907 

Renamed all occurrences of count_match to count_matches. Also rename CountMatch to CountMatches as mentioned in #10907

### CODE REVIEW

**Comment by stinodego** [comment]
@I8dNLo Thanks for the PR, but this is not the way to do it. You'll have to deprecate the old methods on the Python side.

You can see https://github.com/pola-rs/polars/pull/10813 for reference. I'll put this on draft for now, mark as ready when it's ready!

**Comment by I8dNLo** [comment]
Sure, will do

**Comment by I8dNLo** [comment]
@stinodego Can you clarify what's the problem with docs? Looks like I can not get it

**Review by stinodego — APPROVED** [review]

**Comment by stinodego** [comment]
@I8dNLo Thanks for the update - I fixed the last few inconsistencies (check my commits to see what went wrong :))

This is ready to be merged!

**Pull request merged**
