### PR TITLE
feat(python): add defaults to unnest() and to_struct()

### PR DESCRIPTION
**Pull request by sorhawell**

### CODE REVIEW

**Comment by sorhawell** [comment]
I learned I should make a PR to my own fork first to pre-trigger tests

**Comment by stinodego** [comment]
Late reaction, but: if you feel this is ready to review, please mark it as such so that we can review it. It's currently marked as a draft.

**Comment by ritchie46** [comment]
Any updates on this one @sorhawell?

**Comment by sorhawell** [comment]
thank you @stinodego and @ritchie46  for reminding me, I have marked as ready for review

**Pull request closed without merging**
