### PR TITLE
feat[python]: improve frame init from `@dataclass` and `namedtuple` rows

### LINKED ISSUE #4801: Dataframe should handle nested data sequences
### Problem Description

Creating a new dataframe from nested list (`polars.DataFrame(nested_data_list)`) doesn't split the data to fields, read as object. 

```python
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Callable, NamedTuple

import pandas as pd
import polars as pl
from pydantic import BaseModel


def make_sample_list(
    maker: Callable[[str, datetime, float], Any],
    sample_count: int = 5,
    ticker_name: str = "BLA",
):
    return [maker(ticker_name, datetime.now(), 10 + i) for i in range(sample_count)]


@dataclass
class StockPriceDataclass:
    ticker: str
    dt: datetime
    price: float | None = None


class StockPricePydantic(BaseModel):
    ticker: str
    dt: datetime
    price: float | None = None


class StockPriceNamedTuple(NamedTuple):
    ticker: str
    dt: datetime
    price: float | None = None

sample_dc = make_sample_list(StockPriceDataclass)
sample_sp= make_sample_list(lambda n,t,p: StockPricePydantic(ticker=n, dt=t,price=p))
sample_nt = make_sample_list(StockPriceNamedTuple)
```

Creating dataframe from these lists results in rather weird tables:

image

Opposed to pandas (pydantic is not welcome there too):

image

Of course, there is workaround like this:
image

But it's far from ideal.

I would happily implement it.

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #4801 

----

Python's `dataclass` and `namedtuple` are native types with good performance which have the added bonus that we can infer the column names and data orientation (from both) and the expected schema (from `dataclass`). 

This PR allows `DataFrames` to be initialised from both types (matching `pandas`, which supports the same).

**Setup** _(example)_
```python
from dataclasses import dataclass
from datetime import datetime

@dataclass
class Trade:
    timestamp: datetime
    ticker: str
    price: float
    size: int | None = None

trades = [
    Trade(datetime(2022, 9, 8, 14, 30, 45), "AAPL", 157.5, 125),
    Trade(datetime(2022, 9, 9, 10, 15, 12), "FSLY", 10.0, 1500),
    Trade(datetime(2022, 9, 7, 15, 30), "MU", 55.5, 400),
]
```
**Initialise frame** _(no need to set 'columns' or 'orient'; they are automatically inferred)_
```python
import polars as pl
df = pl.DataFrame( trades )

# shape: (3, 4)
# ┌─────────────────────┬────────┬───────┬──────┐
# │ timestamp           ┆ ticker ┆ price ┆ size │
# │ ---                 ┆ ---    ┆ ---   ┆ ---  │
# │ datetime[μs]        ┆ str    ┆ f64   ┆ i64  │
# ╞═════════════════════╪════════╪═══════╪══════╡
# │ 2022-09-08 14:30:45 ┆ AAPL   ┆ 157.5 ┆ 125  │
# ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
# │ 2022-09-09 10:15:12 ┆ FSLY   ┆ 10.0  ┆ 1500 │
# ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
# │ 2022-09-07 15:30:00 ┆ MU     ┆ 55.5  ┆ 400  │
# └─────────────────────┴────────┴───────┴──────┘
```

**Note**
The [issue](https://github.com/pola-rs/polars/issues/4801) also mentioned classes derived from `pydantic`; however, I have _not_ integrated support for this - unlike dataclasses and namedtuple the package is not part of the standard Python distribution, and I don't see sufficient value in taking the extra dependency (given the added functionality above).

**Also**
Some additional minor typing improvements.

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Looks like a py 3.7 issue to clean-up (doesn't have `types.UnionType` or `typing.get_args`, apparently); will setup a new venv in a bit and take a look.

**Comment by alexander-beedie** [comment]
**Update:** done - everything now working from 3.7 to 3.10.

**Comment by ritchie46** [comment]
Thanks @alexander-beedie :raised_hands:

**Comment by gsanchez2141** [comment]
Hi everyone 
I started using polars this week and i'm truly impressed 

QQ (hopefully this is the right place to ask if not let me know where would that place be)
What would be best way to use the approach mentioned above with pl.read_csv()? is it possible?

**Pull request merged**
