### PR TITLE
fix(rust, python): use row-encoded for struct::is_sorted

### PR DESCRIPTION
**Pull request by ritchie46**

### CODE REVIEW

**Comment by magarick** [comment]
What exactly is this doing? If that operation is expensive, I have an implementation that works fine when there are no nulls so we could avoid it when it isn't necessary. But I don't know without knowing what's going on there. Is it giving each row an integer code?

**Comment by ritchie46** [comment]
Row encoding dictates the structs ordering. The encoding is not free, but is heavily optimized.

The comparison with row encoding are very cheap and cache friendly.

**Comment by magarick** [comment]
> Row encoding dictates the structs ordering. The encoding is not free, but is heavily optimized.

I get what it does. I was hoping for a description of how or a pointer to somewhere I can read about it. The code wasn't super clear to me.

> The comparison with row encoding are very cheap and cache friendly. 

Sounds like we can just plop that down in the struct comparison functions then.

**Comment by ritchie46** [comment]
> Sounds like we can just plop that down in the struct comparison functions then.

Right, for the `gt` `gt_eq` etc.

**Pull request merged**
