### PR TITLE
test(python): Use pytest marker for slow tests

### PR DESCRIPTION
**Pull request by stinodego**
Relates to #6364 

Changes:
* Move all tests under `py-polars/tests/slow` into the regular test modules `py-polars/tests/unit`, but add a `@pytest.mark.slow()` marker.
* Deselect all slow and parametric tests by default by adding `-m "not slow not hypothesis"` to the default pytest run options.
  * This has the side effect that running slow and parametric tests becomes a little bit more cumbersome to run, as we must overwrite the default. This is mostly because the pytest configuration options are not easy to work with...
  * For example, `pytest -k slowtestname` will not work, as the test is deselected by default. You will have to specify `pytest -k slowtestname -m slow`.
* Update Makefile and CI accordingly

This setup has a few advantages:
* Tests can live in the test module where you would expect them. They are not split 'arbitrarily' between a `slow` and a `unit` folder. This is especially cumbersome when relying on test fixtures.
* Tests that turn out to be slow can simply be marked as `@pytest.mark.slow()` to exclude them from the regular `make test` run.
* This is the 'recommended' way of doing things with pytest, as they mention this approach as an example multiple times in their docs. So it should be fairly intuitive for users.

### CODE REVIEW

**Comment by ritchie46** [comment]
Does pytes have config files? So that running pytest directly runs only the defaults?

**Comment by stinodego** [comment]
Yes, we can set defaults in the `pyproject.toml`!

We can set it to skip slow tests by default; I think that's what you're getting at? I'll add a commit for that.

That does mean that running all tests is done with the slightly unintuitive `pytest -m ""` (to overwrite the default), but that doesn't seem like a big issue.

**Comment by stinodego** [comment]
Could also add `not hypothesis` to the default run. Then you can just run `pytest` instead of `pytest tests/unit`. That makes sense actually.

**Comment by ritchie46** [comment]
Great! That's what I meant indeed. I think that's perfect as long as our CI is complete.

**Pull request merged**
