### PR TITLE
allow using py-polars without parquet or feathers support

### PR DESCRIPTION
**Pull request by Dvad**
Trying to use polars in an environment without those features I found two issues:
 - the rust part of py-polars package does not compile 
 - some function in the python package are not accessible anymore even though they do not depend on the parquet feature of the pyarrow module, for instance the conversion from and to pandas
 
Those issues can be reproduced with the following command:
`cargo +nightly build --features "json,avro,is_in,json,polars/repeat_by" --no-default-features`

This PR tries to address the issues.

### CODE REVIEW

**Comment by Dvad** [comment]
I discovered the contribution guideline just after making the PR. I ran `make pre-commit`, hence why I forced push the new fixed commits.

**Comment by ritchie46** [comment]
The python polars bindings were never really meant to have opt-in/out features. The feature gates merely exists for developing. 

I don't think I want the extra complexity of feature gates in python polars.

**Comment by Dvad** [comment]
That makes total sense, not sure my use case is common... I might as well just maintain this patch on a fork until I fix my target environment. Thanks for the awesome work!

**Comment by ritchie46** [comment]
> That makes total sense, not sure my use case is common... I might as well just maintain this patch on a fork until I fix my target environment. Thanks for the awesome work!

Thanks for the understanding :) May I ask what your specific rationale is? Is the binary too large?

**Comment by Dvad** [comment]
When trying to integrate polars in a already existing project I hit two issues:
1. dependency version hell about rust zstd version. Another package had a hardcoded dependency on a zstd version. polars dependency on zstd disappears without those two features. Since those feature were exposed in the Cargo.toml, I just thought I could use that to solve my issue in the short term. 
2. `import pyarrow._parquet` fails for some reasons. I have not deeply investigated why, It could be either because my pyarrow was not compiled with parquet support or is not up-to-date (but updating it is not easy as it should for my particular use case).

Now, I don't know if dependency issues are common in big rust projects, so if the intention here is to have very little opt-in feature in py-polar, my first point is almost certainly better addressed by fixing the other packages and the whole dependency tree.

The fix for the second point does not seem as complicated as using rust features (see the part of the PR touching the .py). Considering that `pyarrow` is an external dependency which can be compiled with or without parquet support independently of polars, how do you feel about this part? (basically testing for `import pyarrow` and `import pyarrow.parquet` separatly.

Best,

**Comment by jorgecarleitao** [comment]
One common pain I see in the AWS world is the fact that pandas+pyarrow almost completely fill lambda's maximum allowed size. So, in this context, being able to pick what is needed from polars could mitigate this when using polars together with other libraries.

Having said that, I could not find a way yet to create wheels in maturin depending on the chosen feature set in `setup.py` (not even sure if pypi supports this, anyways), and it is also not clear how common this problem is.

**Comment by ritchie46** [comment]
> Now, I don't know if dependency issues are common in big rust projects, so if the intention here is to have very little opt-in feature in py-polar, my first point is almost certainly better addressed by fixing the other packages and the whole dependency tree.

**Rust polars** is meant to use with opt-in features. The **python bindings not**. You can definitely compile rust polars without parquet or feather support. 

Why do you want to compile the python polars bindings in another crate? Once we are in python land it doesn't really matter right? Or do I misunderstand your use case?

**Comment by jorgecarleitao** [comment]
Could it be that you are compiling the whole workspace instead of the rust polars alone? I.e. could you try something like `cargo build -p polars --features "json,avro,is_in,json,polars/repeat_by"`?

**Pull request closed without merging**
