### PR TITLE
fix(python): Update docstring `with_columns` to reflect a new dataframe is being returned

### PR DESCRIPTION
**Pull request by zundertj**
In line with the docstring of `with_column` (singular).

I have also converted the comments about the experimental flag into normal text, that is much nicer in the docs.

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Maybe also make a note that a new DataFrame doesn't mean a new copy of all of the underlying data? Reassure the users that this is cheap.

**Comment by zundertj** [comment]
> Maybe also make a note that a new DataFrame doesn't mean a new copy of all of the underlying data? Reassure the users that this is cheap.

As I understand it, the existing columns (unless overwritten) will not be copied indeed; that would only happen on another modification in either the existing or new dataframe, i.e. copy-on-write, but I would prefer @ritchie46  to formulate this correctly.

**Comment by ritchie46** [comment]
We copy the pointer to the columns, not the data.

**Comment by zundertj** [comment]
I just realized you can't mutate a column, so there is no write, and thus no "copy-on-write".  Copying pointers is thus the same behavior (and easier).

**Comment by ritchie46** [comment]
> I just realized you can't mutate a column, so there is no write, and thus no "copy-on-write". Copying pointers is thus the same behavior (and easier).

Well, we can. IFF we are the only owners, a `set_at_idx` mutates. Internally we also mutate on arithmetic IFF we are the only owner.

This is actually only possible thanks to rusts borrow checker. We have cow++ 😏

**Comment by zundertj** [comment]
Ok, but that is not something that can trip you up, as it is on the series, i.e. `set_at_idx` does not affect `df1` here:


```python
import polars as pl
df1 = pl.DataFrame({"a": [1,2]})
df2 = df1.with_column( (pl.col("a")*2).alias("b"))
df1["a"].set_at_idx(1, 10)
print(df2)
```


I guess my knowledge of this on Polars is so poor, because it always works as expected...

**Comment by ritchie46** [comment]
> Ok, but that is not something that can trip you up, as it is on the series, i.e. `set_at_idx` does not affect `df1` here:
> 
> ```python
> import polars as pl
> df1 = pl.DataFrame({"a": [1,2]})
> df2 = df1.with_column( (pl.col("a")*2).alias("b"))
> df1["a"].set_at_idx(1, 10)
> print(df2)
> ```
> 
> I guess my knowledge of this on Polars is so poor, because it always works as expected...

I don't want users to be bothered with such things as well. We should figure it out internally. 😊

**Comment by alexander-beedie** [comment]
At the level of a docstring (vs a design doc) it's more than sufficient to reassure the caller that, if they already have a 99-column DataFrame, the addition of another column via `with_columns` does not mean that the existing 99 are going to get copied to create the new frame.

Something short & sweet like this?
```
Notes
-----
Creating a new DataFrame using this method does not create a new copy of the underlying data.
```
On top of that, anyone coming from Pandas has probably long ago given up trying to work out where all of their memory went anyway, so this is loosely equivalent to the Hitchhiker's Guide To The Galaxy putting "[DON'T PANIC](https://en.wikipedia.org/wiki/Phrases_from_The_Hitchhiker%27s_Guide_to_the_Galaxy#Don't_Panic)" on the cover, In large, friendly letters... :)

**Comment by zundertj** [comment]
Sure, I just wanted to make sure I understand how it works before I put it into correct, more high-level, words. I have used your suggestion, with an additional "existing" qualifier.

**Comment by alexander-beedie** [comment]
> Sure, I just wanted to make sure I understand how it works before I put it into correct, more high-level, words. I have used your suggestion, with an additional "existing" qualifier.

Can just swap "underlying" for "existing" - I think you've chosen the better word there ;)

**Pull request merged**
