### PR TITLE
ci[python]: Use maturin-action for Windows/macOS release

### PR DESCRIPTION
**Pull request by stinodego**
Changes:
* Use `maturin-action` for the Windows/macOS workflow, rather than manually running commands.
  * I see no reason not to use the action, like we do in other release workflows. But maybe I am missing something?
* Some minor reformatting, also in the other macOS workflow

**This is untested**, as I don't really know how to test this without actually publishing the wheel. And I don't want to do that since I don't know enough yet about the release process / if that could potentially break something.

### CODE REVIEW

**Comment by ritchie46** [comment]
Let's do that one time when we are live in the office and try to get a release out. Then we can iterate quickly.

There is also a test.pypi. So we can set the architecture up for this so that we can test this properly.

**Comment by stinodego** [comment]
> Let's do that one time when we are live in the office and try to get a release out. Then we can iterate quickly.
> 
> There is also a test.pypi. So we can set the architecture up for this so that we can test this properly.

Yes, I think that's the way to go!

**Comment by kylebarron** [comment]
As another point of reference, I'm generally very fond of [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) for making wheels on CI. I've used it more for non-Rust projects, but in geopolars I also got it working to wrap maturin. It ended up being [pretty straightforward](https://github.com/geopolars/geopolars/blob/0dbe45e783212bb5fa5683682e9c4c34b341fc5b/.github/workflows/python-wheels.yml). The gist is:

```yml
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.0
        env:
          # Python wheel support for mac M1 started as of 3.8. So if we _only_ build universal2
          # wheels, we don't build a wheel for 3.7. Therefore, we set CIBW_ARCHS_MACOS to both, but
          # explicitly skip x86-64-only wheels for 3.8 and higher.
          CIBW_SKIP: "cp2* cp35* cp36* cp38*macosx*x86_64 cp39*macosx*x86_64 cp310*macosx*x86_64 pp* *win32 *i686 *musllinux*"
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
          CIBW_BEFORE_ALL: "curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y"
          CIBW_BEFORE_ALL_MACOS: "rustup target add aarch64-apple-darwin"
        with:
          package-dir: py-geopolars

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
```

At least in the linked setup, it's not hard to test without making a release; you just need to [comment out the automatic publishing](https://github.com/geopolars/geopolars/blob/0dbe45e783212bb5fa5683682e9c4c34b341fc5b/.github/workflows/python-wheels.yml#L83-L88).

**Comment by kylebarron** [comment]
Polars is able to distribute only a few wheels because it uses [pyo3's `abi3` support](https://pyo3.rs/latest/building_and_distribution.html#py_limited_apiabi3), but those docs also say:

> The downside of this is that PyO3 can't use optimizations which rely on being compiled against a known exact Python version.

Since polars is very performance focused, maybe it would make sense to remove the `abi3` support defined here:
https://github.com/pola-rs/polars/blob/527ae86f7996bea60b7ae1bb4be48229d515e115/py-polars/Cargo.toml#L34
and distribute Python-version-specific wheels? I'm curious if that could lead to a perf improvement for newer versions of Python.

**Comment by messense** [comment]
> cibuildwheel uses the `pyproject.toml` setup, so it uses maturin's pep 517 support.

Yes, if anything goes wrong, feel free to report to maturin.

BTW, I think cibuildwheel is not a good fit for building non-x86 on GitHub Actions, fortunately  [cibuildwheel v2.10.0](https://github.com/pypa/cibuildwheel/releases/tag/v2.10.0) added 
support for [building wheels on Cirrus CI](https://cibuildwheel.readthedocs.io/en/stable/setup/#cirrus-ci), so you can move Linux aarch64, macOS M1 builds to Cirrus CI to build on its native platforms now!

**Comment by messense** [comment]
> By "good fit" do you mean unable to build for non-x86 or just longer build times

M1 is different, it's actually cross compiling which is fast enough. The QEMU base Linux builds are 6x slower than native build, it seem to be around 150 mins for polars for each build target.

**Pull request merged**
