### PR TITLE
added example for microsecond

### PR DESCRIPTION
**Pull request by romanovacca**
@stinodego 

I have added this example, but I feel like the current setup of methods (where we have 2 lookalike functions) is a bit confusing and error prone.

```
Expr.dt.microsecond() :
Extract microseconds from underlying DateTime representation.
```

and

```
Expr.dt.microseconds() 
Extract the microseconds from a Duration type.
```

I think that this will lead to a lower satisfaction for people using these functions, since 1 of them runs on a datetime, while the other can only be used on duration type and the function name itself does not give information on which of the 2 does what. This will mean people have to look up the documentation every time.

What do you think?

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks @romanovacca :+1: 


> @stinodego
> 
> I have added this example, but I feel like the current setup of methods (where we have 2 lookalike functions) is a bit confusing and error prone.
> 
> ```
> Expr.dt.microsecond() :
> Extract microseconds from underlying DateTime representation.
> ```
> 
> and
> 
> ```
> Expr.dt.microseconds() 
> Extract the microseconds from a Duration type.
> ```
> 
> I think that this will lead to a lower satisfaction for people using these functions, since 1 of them runs on a datetime, while the other can only be used on duration type and the function name itself does not give information on which of the 2 does what. This will mean people have to look up the documentation every time.
> 
> What do you think?

I see you pointing to the same functions?

In any case, thanks for the docstring. :+1:

**Comment by romanovacca** [comment]
@ritchie46 that is exactly my point! I was pointing to two different functions, one with "s" at the end and the other without. While the behaviour is different, see how that can be misleading?

**Comment by ritchie46** [comment]
Right, they should be unified. :thinking:

**Comment by stinodego** [comment]
> Right, they should be unified. 🤔

I think that makes the most sense. I've actually bumped into this before but hadn't made an issue for it.

**Comment by romanovacca** [comment]
Shall I make an issue for this and link to this issue?

**Comment by stinodego** [comment]
Sure!

**Pull request merged**
