### PR TITLE
depr(python,rust!): Rename cumulative functions `cumsum -> cum_sum` and similar

### PR DESCRIPTION
**Pull request by stinodego**
Closes [#12013](https://github.com/pola-rs/polars/issues/12013)

Renames the following (with proper deprecation on the Python side):
* `cumfold` -> `cum_fold`
* `cumreduce` -> `cum_reduce`
* `cumsum` -> `cum_sum`
* `cumprod` -> `cum_prod`
* `cummin` -> `cum_min`
* `cummax` -> `cum_max`
* `cumcount` -> `cum_count`

### CODE REVIEW

**Comment by rancomp** [comment]
That's a big one! :)


I want to put the spotlight on `cumulative_eval` again, because I think there's a naming inconsistency in the naming conventions. More specifically, when should each of `map / apply / eval` be used?
When I suggested `cumulative_eval` be renamed `cumulative_map` I was thinking of `rolling_apply` which was deprecated in favor of `rolling_map`.

**Comment by stinodego** [comment]
We will pick that one up separately - Ritchie had some doubts.

**Comment by MarcoGorelli** [comment]
Why is this milestoned for 1.0? Looks like introduces a deprecation warning, rather than enforcing the deprecation, shouldn't it go into 0.19.14?

(btw, adding the top-level ones to https://github.com/astral-sh/ruff/pull/8686/files)

**Comment by stinodego** [comment]
> shouldn't it go into 0.19.14?

Yes, it should be merged now. The milestone is just a sort of reminder of 'stuff that must be done before releasing 1.0.0'.

**Comment by JulianCologne** [comment]
@stinodego small question:
You just added all the `horizontal` functions with a naming of
- `<func>_horizontal`

But for cumulative functions we put `cum` at the front
- `cum_<func>`

This is a very small detail. Not sure if this should be consistent?

**Comment by stinodego** [comment]
> Not sure if this should be consistent?

Maybe - you could argue either way. For now I think this is fine - at least it's more consistent with our naming standards.

**Pull request merged**
