### PR TITLE
test(rust): Clean up some warnings

### PR DESCRIPTION
**Pull request by stinodego**
My IDE was complaining about these.

There are also a bunch of broken tests in `polars/polars/lazy/polars-plan/src/logical_plan`, and an issue with the example in `examples/read_csv/src/main.rs`. Any suggestion on what to do with those?

### CODE REVIEW

**Comment by ritchie46** [comment]
> There are also a bunch of broken tests in polars/polars/lazy/polars-plan/src/logical_plan, and an issue with the example 

How do you know they are broken? Don't they run in CI?

**Comment by stinodego** [comment]
> > There are also a bunch of broken tests in polars/polars/lazy/polars-plan/src/logical_plan, and an issue with the example
> 
> How do you know they are broken? Don't they run in CI?

Well there are definitely some issues with the Rust test suite in the CI.

For example, the first part of the `make test` command is ```POLARS_MAX_THREADS=4 cargo t -p polars-core test_4_threads``` but this doesn't actually seem to run any tests:

```
warning: /home/stijn/code/polars/polars/polars-sql/Cargo.toml: unused manifest key: target.cfg(not(target_os = "linux")).features
    Finished test [unoptimized + debuginfo] target(s) in 0.12s
     Running unittests src/lib.rs (/home/stijn/code/polars/target/debug/deps/polars_core-4fe57ae2cd83e9cc)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 131 filtered out; finished in 0.00s
```

And indeed some tests are not being run, for example `test_lazy_logical_plan_join` - if I run `cargo test test_lazy_logical_plan_join` with all the relevant parameters, it's just deselected.

**Comment by ritchie46** [comment]
Can we take a look at this at a later moment live?

**Comment by stinodego** [comment]
> Can we take a look at this at a later moment live?

Sure 👍

**Comment by ritchie46** [comment]
Wait, I can make an issue and take a look later.

**Pull request merged**
