### PR TITLE
test(python): Use pytest `tmp_path`

### PR DESCRIPTION
**Pull request by stinodego**
We've had some issues with temporary directories in conjunction with parallel pytest runs. This should address any issues.

~May address #9122~

Added bonus: all tests now seem to work under Windows!
I will try to re-enable test parallization for Windows in the CI in a separate PR.

### CODE REVIEW

**Comment by ritchie46** [comment]
Why does temporary directory not work then?

**Comment by stinodego** [comment]
pytest's `tmp_path` fixture guarantees a unique path based on the test invocation. [Docs here](https://docs.pytest.org/en/7.3.x/how-to/tmp_path.html). I believe one of the reasons `TemporaryDirectory` had trouble was when parallel threads tried to create a directory of the same name. That is no longer possible.

Not sure why the Windows tests suddenly work properly now.

In general, I'd say `tmp_path` is the 'official' way to do it according to pytest, so it should be preferred. Saves us from including that vendored copy of `TemporaryDirectory` too.

**Comment by ritchie46** [comment]
Check, thanks.

**Comment by alexander-beedie** [comment]
>  Saves us from including that vendored copy of `TemporaryDirectory` too.

That makes me happy... nice one :)

**Pull request merged**
