### PR TITLE
ci(python): try to turn off build_info

### PR DESCRIPTION
**Pull request by ritchie46**
I try to make `build_info` only compiled in CI, but it doesn't work for some reason. Modifying any unrelated file leads to a recompile.

#5612 

@slonik-az, @stinodego  do you think I am missing something obvious here?

### CODE REVIEW

**Comment by stinodego** [comment]
Did you look at the `py-polars/build.rs` file? If I delete that, caching works again.

**Comment by ritchie46** [comment]
> Did you look at the `py-polars/build.rs` file? If I delete that, caching works again. Obviously, that would break the feature entirely...

Thanks for the pointer. Will investigate further. I know you can define when the `build-rs` file should trigger a recompile. Which is not set at the moment.

**Comment by ritchie46** [comment]
superseded by: #5618

**Comment by slonik-az** [comment]
`py-polars/build.rs` is indeed the root-cause. It is required by `built` crate to collect the build_info. Part of this information is the build timestamp that is changing at every cargo invocation making `build.rs` output change causing `cargo` to trigger recompilation.

A clean solution to this problem would be to decouple Makefile's `test` and `build` targets as it was done in PR #5137. Hopefully it will make CI happy by making building and testing two distinct steps.

In development, one can disable `build_info` feature  avoiding the problem altogether. If typing `make build test` is too much typing, one can introduce a shortcut target like `make bt` that does `make build test` in one go.

**Pull request closed without merging**
