### PR TITLE
feat(rust, python): Expr.cat.get_categories expression

### PR DESCRIPTION
**Pull request by ritchie46**
Get the underlying categories of a `Categorical` data type.

### CODE REVIEW

**Comment by magarick** [comment]
Can't we just call it "categories" or "levels". The whole "get" thing just feels unnecessary.

**Comment by ritchie46** [comment]
> Can't we just call it "categories" or "levels". The whole "get" thing just feels unnecessary.

No, we are explicit in our API. So we must answer the question what do you want to do with the "categories"? If we named it "categories", we close the door for a future "set_categories" or "insert_categories" etc.

**Comment by magarick** [comment]
> > Can't we just call it "categories" or "levels". The whole "get" thing just feels unnecessary.
> 
> No, we are explicit in our API. So we must answer the question what do you want to do with the "categories"? If we named it "categories", we close the door for a future "set_categories" or "insert_categories" etc.

I don't see how it closes the door to anything. It's a minor issue but i see "categories" or "levels" more as an attribute that you're accessing, not a function that's doing anything. Perfectly explicit in that case, and a function that actually does something, that has a verb in front. I guess everyone has their own internal view of what's clear and obvious and right though, :shrug:

**Comment by ritchie46** [comment]
> Perfectly explicit in that case, and a function that actually does something, that has a verb in front. I guess everyone has their own internal view of what's clear and obvious and right though, shrug

But it isn't an attribute. It is a function. You are right, people have their own preferences, that's why I hammer on this, as we have different developers working on this, but we should have a unified code and API style.

The goals for the API are listed here: https://github.com/pola-rs/polars/issues/6120#issuecomment-1374911565

**Comment by mcrumiller** [comment]
When do we get a `.dog` namespace?

**Pull request merged**
