### PR TITLE
Add flag to allow str.contains to search for string literals (#3711)

### PR DESCRIPTION
**Pull request by alexander-beedie**
Optional `literal` flag for `str.contains` that allows the Rust layer to handle regex-escaping; solves the issue where the Rust/Python layers had different ideas about escaping the space char. Also makes the intention (to match a literal value) clear from the API side, without the user having to escape it themselves.

```python
import polars as pl
import re

df = pl.DataFrame({
    'id': [1,2,3],
    'text': ['some * * text','with special * chars','etc']
})
```

*Before (python-side escaping)*
```python
df.filter( pl.col('text').str.contains(re.escape(r'* *')) )  
# >> ComputeError("regex error: ...
```
*After (pass flag allowing regex crate to handle it)*
```python
df.filter( pl.col('text').str.contains(r'* *',literal=True) )  
# ┌─────┬───────────────┐
# │ id  ┆ text          │
# │ --- ┆ ---           │
# │ i64 ┆ str           │
# ╞═════╪═══════════════╡
# │ 1   ┆ some * * text │
# └─────┴───────────────┘
```

Please cast a judicious eye over this, as I am in the very early days of getting to grips with Rust, heh...
(My coding history is primarily full of C++/Python/misc) ;)

--
**Update**: @ritchie46 - realised that the Rust tests weren't updated with the new param, hence failing - would you prefer a separate `contains_literal` func on the Rust side instead of having the `literal` param on `contains`? Probably less disruptive to existing code, but not sure what you'd consider more idiomatic/appropriate in this case - happy to adjust either way.

### CODE REVIEW

**Comment by ritchie46** [comment]
> Update: @ritchie46 - realised that the Rust tests weren't updated with the new param, hence failing - would you prefer a separate contains_literal func on the Rust side instead of having the literal param on contains? Probably less disruptive to existing code, but not sure what you'd consider more idiomatic/appropriate in this case - happy to adjust either way.

Sounds good.

I do think that the literal should have different implementation and should not use regex at all. That way we can do a very fast string search which can be super fast.

**Comment by alexander-beedie** [comment]
> I do think that the literal should have different implementation and should not use regex at all. That way we can do a very fast string search which can be super fast.

I _think_ the regex library may already optimise for this case, but will confirm/verify before assuming  ;)  Will get it done tonight or over the weekend and update the req. Cheers!

**Comment by alexander-beedie** [comment]
> I do think that the literal should have different implementation and should not use regex at all. That way we can do a very fast string search which can be super fast.

Confirmed the performance difference by benchmarking both implementations over 50,000,000 large string elements, with matches of various lengths/complexity that can be found at various points in the strings - on the test dataset the performance advantage of non-Regex literal matching ranges between ~6-25%, so that's a clear win...

Will update the patch shortly.

**Comment by alexander-beedie** [comment]
One more update - if the pattern is clearly a literal string (eg: only alphanumeric / whitespace / underscore) then `contains` will automatically redirect to `contains_literal`. Should speed-up quite a few common cases without needing to explicitly opt-in...

**Comment by ritchie46** [comment]
> One more update - if the pattern is clearly a literal string (eg: only alphanumeric / whitespace / underscore) then contains will automatically redirect to contains_literal. Should speed-up quite a few common cases without needing to explicitly opt-in...

That's a nice one!

**Comment by ritchie46** [comment]
Thanks a lot @alexander-beedie, a nice first stab on Rust. :)

**Comment by alexander-beedie** [comment]
> Thanks a lot @alexander-beedie, a nice first stab on Rust. :)

And hopefully not the last! :)

**Pull request merged**
