### PR TITLE
Upgrade series.describe()

### PR DESCRIPTION
**Pull request by r-brink**
Adding functionality to describe function for Series. 

- Nicer visualisation when returning the results
- Including utf8, float, int, bool and datetime dtypes

Any ideas on the tests? The floats are hard to assert. We could round all the floats to two decimals, but it's not very elegant.

### CODE REVIEW

**Comment by ritchie46** [comment]
@r-brink you have mypy type errors. :eyes:

**Comment by ritchie46** [comment]
Another thing. We can now use the expressions + select to make the `describe` embarrassingly parallel. 

Something like:

```python
exprs = []

# first prepare all the expressions
for name in df.columns:
    exprs.append(col(name).sum().suffix("_sum")
    exprs.append(col(name).min().suffix("_min")
    exprs.append(col(name).max().suffix("_max")
    ...
    exprs.append(col(name).unique().suffix("_unique")
    
# run them all in parallel.
df.select(exprs)
```

**Comment by r-brink** [comment]
What do you prefer @ritchie46? Use the expressions or extend based on the current approach?

**Comment by ritchie46** [comment]
> What do you prefer @ritchie46? Use the expressions or extend based on the current approach?

I think its fine for now. 

One nit: could we name the columns? I am thinking something like:

```
operation | value
```

**Comment by ghuls** [comment]
Any specific reason  for using `_` as variable? I am only familiar with `_` when the value will not be used.

**Comment by r-brink** [comment]
> 
> 
> Any specific reason for using `_` as variable? I am only familiar with `_` when the value will not be used.

TIL I have bad coding practices. Thanks for the heads up @ghuls. Fixed it in the latest commit

**Pull request merged**
