### PR TITLE
feat: support multiple sources in scan_file

### PR DESCRIPTION
**Pull request by ritchie46**
This can improve performance of reading multiple files from the cloud that cannot be globbed. Creating a single `LazyFrame` will amortize the cost of retrieving a schema and dns lookups.

It is of course also more ergonomic. :)

### CODE REVIEW

**Comment by svaningelgem** [comment]
Hi @ritchie46 ,

I saw this PR because it broke mine 😁. I just was wondering what your reasoning was for not opting to pass in a `paths: Vec<PathBuf>,` always?
As I understand it:
- the rust users need to change their calls anyhow, so they could easily make it an array
- pypolars can hide this change from their users

But now you need to duplicate a lot of times the verifying if it is 1 path or multiple? I think it'd be also more clean if you could only provide 1 path parameter.

**Comment by ritchie46** [comment]
Because we don't yet support globbing for multiple files passed. This way I know what was passed by the user.

**Comment by svaningelgem** [comment]
Can't we simply check all the paths?
In python I'd do something like:
```python
itertools.chain.from_iterable(glob(file) for file in paths)
```
I think globbing a file without a pattern would just return the file itself. So this way it's easy to abstract that behaviour away everywhere.

**Comment by orlp** [comment]
> I think globbing a file without a pattern would just return the file itself.

Filenames can contain asterisks...

**Comment by svaningelgem** [comment]
> Filenames can contain asterisks...

That's true. Didn't think of that one.
Isn't there a way to say then during globbing: "if file exists {use file} else {glob}"?

**Pull request merged**
