### PR TITLE
Some API alignment (missing funcs) between `DataFrame`, `LazyFrame`, and `Series`

### PR DESCRIPTION
**Pull request by alexander-beedie**
While implementing some larger-scale slice improvements for #3759, ended up also bringing a couple of `DataFrame`, `LazyFrame`, and `Series` methods into alignment (which helps make the common slice code "more" common ;)

These are standalone updates, so pushing them in advance of a slice-specific patch (likely later this weekend). One minor `slice` function improvement is included for all three types, which is allowing the length param to be optional).

**DataFrame**
* Added `reverse`, to match `LazyFrame` (implementation remains `self.select(pli.col("*").reverse())`).

**LazyFrame**
* Expose `clone` method, to match existing methods in `DataFrame` and `Series`.

**Series**
* Added `reverse` in Rust and exposed up to Python, to match`LazyFrame` (and now `DataFrame`).
* Added `is_empty`, matching `LazyFrame` and `DataFrame`.

### CODE REVIEW

**Comment by ritchie46** [comment]
Great! It only needs to add the new methods to the docs and it is good to go. CI is failing on that.

**Comment by alexander-beedie** [comment]
> Great! It only needs to add the new methods to the docs and it is good to go. CI is failing on that.

Aha, got them - added the missing autosummary refs to docs (and also added the missing `Series.is_empty()` while I was at it). 

Looking at the docs, any issue with sorting the method references within each section? (I didn't change anything in that respect, in case there's some ordering criteria I'm not aware of, but I think it might be helpful when looking things up).

**Comment by ritchie46** [comment]
> Looking at the docs, any issue with sorting the method references within each section? (I didn't change anything in that respect, in case there's some ordering criteria I'm not aware of, but I think it might be helpful).

None at all. Shall we do that in a subsequent PR?

**Comment by alexander-beedie** [comment]
> None at all. Shall we do that in a subsequent PR?

Sounds good to me; I'll raise a separate req after this lands.

**Pull request merged**
