### PR TITLE
feat: expressify peak_min/peak_max

### PR DESCRIPTION
**Pull request by orlp**
Moves another operation from core into ops, and makes it more generally useful by making it an expression.

### CODE REVIEW

**Comment by Bidek56** [comment]
@orlp Do you know how to include `peak_min` and `peak_max` in [this](https://github.com/pola-rs/nodejs-polars/blob/d14ff79d29f90e08dba27b6b6930402bce4c27fc/src/series.rs#L1065) code?
It worked fine in rs-0.32, with rs-0.34 I am getting: `method not found in Series`
Thx

**Comment by orlp** [comment]
@Bidek56 I don't actually know, I may have messed up and not exposed it anywhere. How would you go about doing `is_in`, which was also removed from `polars-core`?

**Comment by Bidek56** [comment]
`is_in` is not affected, it work fine like this:
```  
  #[napi(catch_unwind)]
    pub fn is_in(&self, other: &JsSeries) -> napi::Result<JsSeries> {
        let series = is_in(&self.series, &other.series)
                        .map(|ca| ca.into_series())
                        .map_err(JsPolarsErr::from)?;

        Ok(JsSeries::new(series))
    }
```

**Comment by Bidek56** [comment]
I have access to this peak_min, but I need it for `Series`
```
polars_ops::chunked_array::peaks
pub fn peak_min<T>(ca: &ChunkedArray<T>) -> BooleanChunked
where
    T: PolarsNumericType,
```

**Comment by orlp** [comment]
@Bidek56 I'll fix this tomorrow making sure to expose the functions publicly.

**Comment by orlp** [comment]
@Bidek56 Actually, looking at it, I was curious how other expression-only things worked. For example `lower_bound` you do like this: https://github.com/pola-rs/nodejs-polars/blob/d14ff79d29f90e08dba27b6b6930402bce4c27fc/src/lazy/dsl.rs#L1142

Would it not be possible to also do `peak_min`/`peak_max` like that? On the py-polars side it is currently handled through the expression interface.

**Comment by Bidek56** [comment]
@orlp I am looking to fix [`series.peak_max()`](https://github.com/pola-rs/nodejs-polars/blob/d14ff79d29f90e08dba27b6b6930402bce4c27fc/src/series.rs#L1064) not for expression. Thx

**Comment by Bidek56** [comment]
@orlp  I was able to implement `peak_min/peak_max` using expression. Thank you for suggestion!!

**Pull request merged**
