### PR TITLE
fix(python): Fix group keys in `partition_by(as_dict=True)` / `GroupBy.__iter__` in some cases

### LINKED ISSUE #13371: Partition_by should returns tuples as keys when partitioning on a list of a single column, like group_by does
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1, 1, 2, 2], "b": range(4)})

keys = [k for k, _ in df.group_by("a", maintain_order=True)]
print(keys)
keys = [k for k, _ in df.group_by(["a"], maintain_order=True)]
print(keys)
keys = [k for k, _ in df.group_by(["a", "b"], maintain_order=True)]
print(keys)
keys = list(df.partition_by("a", maintain_order=True, as_dict=True).keys())
print(keys)
keys = list(df.partition_by(["a"], maintain_order=True, as_dict=True).keys())
print(keys)
keys = list(df.partition_by(["a", "b"], maintain_order=True, as_dict=True).keys())
print(keys)
```

### Log output

```shell
[1, 2]
[(1,), (2,)]
[(1, 0), (1, 1), (2, 2), (2, 3)]
[1, 2]
[1, 2]
[(1, 0), (1, 1), (2, 2), (2, 3)]
```

### Issue description

Passing a list of a single column to partition by should return keys as one element tuple, similarly to what iterating on a groupby does.

The current behaviour is inconsistent with how partition by behaves with more than one by column passed, making hard to generalize code that uses is if this takes the partition columns from the outside.

### Expected behavior

When passed a list of columns to partition_by should always return keys as tuple, like how list(group_by) does

### Edit

This bahaviours seems to happen also when using selectors in partition by, in particular depending on the number of column matched at runtime by the selector a scalar or a select is returned. This is not great too, but may be another issue. Mentioned here: https://github.com/pola-rs/polars/issues/13371#issuecomment-1880684263

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           3.8.0
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.3
pyarrow:              14.0.1
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           3.1.9
```

</details>

### PR DESCRIPTION
**Pull request by stinodego**
Closes #13371

The group keys are sometimes a single value, and sometimes a tuple of values. Which one used to depend on the data, e.g. if `cs.string()` matched multiple columns you would get tuples, otherwise a single value. 

#### The fix

We don't want the output format to depend on the data, so it has been updated to depend on the user input:
* If a user passes a single string to `by`, group keys are a single value
* Otherwise, we don't know how many columns willl be matched (this may vary for expressions/selectors), so we use a tuple. This may lead to length-1 tuples being used as keys.

This should help users reliably parse the output of the affected functions.

#### The deprecation

In the future we will go one step further and always return tuples as group keys. This makes it completely predictable and consistent. A deprecation warning has been added to the previous behavior.

### CODE REVIEW

**Comment by mcrumiller** [comment]
Hey @stinodego, I wonder if the selectors `cs.first()` and `cs.last()`, being selectors guaranteed to return a single columns, should also return a scalar key. But it might just make more sense to always return tuples with selectors as you have done.

**Comment by stinodego** [comment]
> Hey @stinodego, I wonder if the selectors `cs.first()` and `cs.last()`, being selectors guaranteed to return a single column, should also return a scalar key. But it might just make more sense to always return tuples with selectors as you have done.

Honestly the more I think about it, the more I think it should just be tuples always.

**Comment by alexander-beedie** [comment]
> Honestly the more I think about it, the more I think it should just be tuples always.

I'd vote for that ;)

**Comment by CaselIT** [comment]
That would be fine for me too (just my 2cents}

**Comment by stinodego** [comment]
> > Honestly the more I think about it, the more I think it should just be tuples always.
> 
> I'd vote for that ;)

Deprecation warning added - we can change this in the future. We can merge the other changes as a fix.

**Comment by ritchie46** [comment]
Yeap, so always tuples in 1.0. :+1:

**Pull request merged**
