### PR TITLE
fix(python): selectors by_name and by_dtype should allow empty list as input

### PR DESCRIPTION
**Pull request by 29antonioac**
Closes https://github.com/pola-rs/polars/issues/10855

Currently the selectors are being created with an unpacked list `F.col(*all_names)`, but since `F.col` can manage iterables, by not unpacking we allow selecting nothing by inputing an empty list.

```python
import polars as pl
import polars.selectors as cs

cols_to_process = [] # This could come from an input file

# This works now
df = pl.DataFrame({"a": [1,2,3]}) 
df_processed = df.with_columns(cs.by_name(cols_to_process) * 2)
```

Fixing this in my opinion gives more consistency on how some functions work: `with_columns` also works with empty lists for example.

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Hmm... not sure about this; may need some other/different tweaks. I'll be able to review it properly tomorrow night though 👍

**Comment by 29antonioac** [comment]
Thanks! Happy to try to improve this if you think this could be useful!

**Comment by 29antonioac** [comment]
Hi, I just had another look at the code of the selectors and `F.col` and I can't see a reason why this could be a problem. Probably since I'm not used to this codebase I'm missing a lot of stuff so feel free to correct me 😄 

Looks like the empty list is fully covered in [F.col](https://github.com/pola-rs/polars/blob/3492c1a2e4c47a859bcb33ba4e61eb8927dbdac5/py-polars/polars/functions/col.py#L206) so I think it shouldn't be an issue. It looks every case is controlled in that function.

This could increase the consistency across other selectors too like [datetime()](https://github.com/pola-rs/polars/blob/3492c1a2e4c47a859bcb33ba4e61eb8927dbdac5/py-polars/polars/selectors.py#L956) (it uses a list to create the selector instead of an unpacked iterable), and consistency with the use of different ones as `numeric()` (if there's no numeric columns in the dataframe, it returns nothing). Any thoughts?

Thanks a lot!

**Comment by alexander-beedie** [comment]
Apologies, got swamped by a few things; will get this sorted out today 👌

**Review by stinodego — APPROVED** [review]
I looked into this, and it's a good change 👍 there's no need to unpack the lists here. Thanks!

**Pull request merged**
