### PR TITLE
chore: refactor community files

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
This PR aims to moves the `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` file inside the `.github/` dir. Github looks for a contribution guideline file in the following order: `.github dir > project root > docs dir` ([source](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)). Moving the file to the `.github/` dir leads to a minimal project structure without any functional change.

### CODE REVIEW

**Comment by ritchie46** [comment]
I don't think people start looking for it in a .github directory.

**Comment by SauravMaheshkar** [comment]
Yes makes sense. But I think it's alright if the Code of Conduct is placed within the `.github/` dir right ? It's anyways visible in the sidebar repository description.

Screenshot 2023-03-05 at 4 00 29 PM

**Comment by alexander-beedie** [comment]
> But I think it's alright if the Code of Conduct is placed within the `.github/` dir right ? It's anyways visible in the sidebar repository description.

That one would make sense to me, given that GitHub actively surfaces it in a standard location; would be both consistent and discoverble. But that's not the case (I believe) for "contributing"?

**Comment by SauravMaheshkar** [comment]
> source

If you're wonderinig if

> > But I think it's alright if the Code of Conduct is placed within the `.github/` dir right ? It's anyways visible in the sidebar repository description.
> 
> That one (code of conduct) would make sense to me, given that GitHub actively surfaces it in a standard location; would be both consistent and discoverable. But that's not the case (I believe?) for "contributing".

If you're wondering if the `CONTRIBUTING.md` file placed within the `.github/` dir would be surfaced by Github or not, it would be surfaced. Refer to [Step 3 in the Github Docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file)

**Comment by stinodego** [comment]
I'd like to have the code of conduct in the `.github` folder, but have `CONTRIBUTING.md` in the root for extra visibility.

Polars isn't the easiest project to start contributing to, so we should really keep the bar as low as possible.

**Review by stinodego — APPROVED** [review]

**Pull request merged**
