### PR TITLE
chore(python): Disable clippy lint "too many arguments" for `py-polars`

### LINKED ISSUE #11614: refactor(py-polars): remove `#pyo3(signature...`'s
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

in py-polars, I noticed quite a lot of `#[pyo3(signature = ...`s. [reference guide](https://pyo3.rs/main/function/signature).

Example: `PyDataFrame.read_parquet`) has this signature.
But sometimes even methods without this are exposed to python after all (example: `pl.scan_csv`).

I'm just wondering if it wouldn't be better to annotate it with `#[pyfunction]` and `#[pyclass]` and let pyo3 handle the rest? Because in nearly all situations, it's just a reiteration of the functions attributes. Only in some minor circumstances there are defaults added. These should be kept of course.

What my proposal would be under this ticket is to clean up the default signatures that are generated by pyo3 anyhow.
This would greatly reduce the code duplication between the annotation and the function definition.

### Installed versions

<details>

```
main branch
```

</details>

### PR DESCRIPTION
**Pull request by svaningelgem**
Removing all the arguments that are across the code by lifting the threshold to 99.

### CODE REVIEW

**Comment by stinodego** [comment]
I think it makes sense to disable this for `py-polars`, as we don't really choose the number of arguments - it's dictated by the Python side, and having many arguments isn't that much of a problem due to default values.

I wouldn't support turning this off for the Rust code base. We should probably take a look at these functions and refactor them, instead of turning off the lints globally.

**Review by stinodego — CHANGES_REQUESTED** [review]
I think it makes sense to disable this for `py-polars`, as we don't really choose the number of arguments - it's dictated by the Python side, and having many arguments isn't that much of a problem due to default values.

I wouldn't support turning this off for the Rust code base. We should probably take a look at these functions and refactor them, instead of turning off the lints globally.

**Comment by svaningelgem** [comment]
Well, when I encounter some daunting task like this, especially if it's sprinkled just about everywhere in the code, I tend to disable the warnings.
Because this will never get refactored (never say never, but from a practical point of view: highly unlikely).

**Review by stinodego — APPROVED** [review]
I disabled the lint properly in `lib.rs`. This is good to go!

**Pull request merged**
