### PR TITLE
docs(python): Don't break lines in nav but let it scroll

### PR DESCRIPTION
**Pull request by vvilhonen**
Change

Screenshot 2022-10-26 at 19 09 22

into

Screenshot 2022-10-26 at 19 12 24

### CODE REVIEW

**Comment by ghuls** [comment]
This was added on purpose, see:
https://github.com/pola-rs/polars/pull/4604

**Comment by vvilhonen** [comment]
Scrolling seems less bad better trade off to me than seeing half of the function name like ’ff’, ’val’, ’rst’.

**Comment by alexander-beedie** [comment]
FYI: I finally solved this issue for good - PR coming shortly... 🎉

**Comment by vvilhonen** [comment]
Thanks, that's way better!

**Pull request closed without merging**
