### PR TITLE
Type aliases for string literals

### PR DESCRIPTION
**Pull request by stinodego**
Relates to #4288

My goal is to set up a clear connection between the string literals passed by the user and the Rust enum backing it.

Changes:
* Created type aliases for all user-facing string literals
* Renamed `polars.internals.datatypes` to `polars.internals.type_aliases`. The term datatypes was confusing as we already have a `polars.datatypes` with the actual datatypes.

### CODE REVIEW

**Comment by matteosantama** [comment]
Good idea! Do these Rust enums get turned into Python enums already (or can they be)?

We could then do a couple of things

1. Have a CI check that verifies the coupling between the Python type aliases and the Rust enums. 
2. Require the Python enums as inputs instead of accepting string parameters

**Comment by stinodego** [comment]
> Good idea! Do these Rust enums get turned into Python enums already (or can they be)?

Right now they don't. I guess it might be possible to turn them into Python objects the same way we're doing it with `PyDataFrame` etc. If I read [this py3o issue](https://github.com/PyO3/pyo3/issues/417) correctly, I think it's possible.

I don't really see the followup, though. Requiring users to specify their arguments as Python enums feels a bit convoluted. I don't want to type `pl.FillNullStrategy.max` if I could just type `"max"`. Especially if that string is type checked and we get a useful error message on invalid inputs.

It would be nice though if it could somehow help us define all these type aliases automatically. I could see that happen at some point with some work.

For now my first steps were just to define these aliases and then make sure they all get handled consistently/identically on the Rust side.

**Comment by matteosantama** [comment]
>  I don't want to type pl.FillNullStrategy.max if I could just type "max"

That's what I had in mind, but you're right -- that's pretty ugly. 

 > For now my first steps were just to define these aliases and then make sure they all get handled consistently/identically on the Rust side.

Yes, definitely a step in the right direction!

**Comment by ritchie46** [comment]
Are we free to rename the aliases without that being a breaking change? That's my only concern here. Other than that I think this cleans up.

**Comment by stinodego** [comment]
Yes, the naming won't affect the user side at all!

It will affect what they see in the docs, however. That is why I am careful to include all the options in the docstring for these types.

**Comment by ritchie46** [comment]
> Yes, the naming won't affect the user side at all! mypy just reads the underlying literal.

Alright! :)

**Pull request merged**
