### PR TITLE
feat(rust, python): building blocks for expression expansion sets

### PR DESCRIPTION
**Pull request by ritchie46**
This is not intended for external usage, but this provides the building blocks that allow us to implement selection unions.

With this @alexander-beedie's new selector API can implement:

```python
# SET A + SET B
# select all "bar" named column AND all list columns
(s.matches("^bar.*$") + s.by_dtype(pl.Utf8)).other_expression(..)

# SET A - SET B
# select all datetime columns except the ones with "foo" in the name
(s.datetime(..) - s.contains("foo")).other_expression(..)
```

This exposes a `meta._as_selector()` expression, which creates a state:

```
Expr::Selector{
   add: [Expr],
   subtract: [Expr]
}
```

where the `add` and `subtract` can hold expanding expressions.

The `Expr::Selector` can do UNION ADD with `_selector_add` and UNION SUBTRACT with `_selector_sub`.

example:

```python
    df = pl.DataFrame({name: [] for name in "abcde"})

    s1 = pl.all().meta._as_selector()
    s2 = pl.col(["a", "b"])
    s = s1.meta._selector_sub(s2)
    assert df.select(s).columns == ["c", "d", "e"]

    s1 = pl.col("^a|b$").meta._as_selector()
    s = s1.meta._selector_add(pl.col(["d", "e"]))
    assert df.select(s).columns == ["a", "b", "d", "e"]

    s = s.meta._selector_sub(pl.col("d"))
    assert df.select(s).columns == ["a", "b", "e"]
```

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Awesome; will integrate into the "&" and "|" operators on the selector proxy :)

**Comment by alexander-beedie** [comment]
This covers `and` and `not`; can we get `or` next? :)
```python
df.select( (s.ends_with("_usd") | s.string()) )
```
Also... maybe rename `_selector_union` and `_selector_exclude`? (as add/sub ops can still be broadcast to the selector fields, eg: `s.numeric() - 100`).

**Comment by ritchie46** [comment]
Will take a look. That's a bit more complicated as we don't have the schema yet.

**Comment by ritchie46** [comment]
>  (as "add" and "sub" ops can still be broadcast to the selected fields, eg: s.numeric() - 100).

What do you mean?

**Comment by alexander-beedie** [comment]
> EDIT: The proxy should dispatch the proper python overload to this one.

Yup, and it will - I just mean that purely from a _naming_ perspective add/sub refer to the operators "+" and "-" on the python side (under methods), whereas the appropriate operators for logical unions of the selectors are "&", "|", and "~" (so not a functional issue, just a naming-alignment issue) ;)

**Comment by alexander-beedie** [comment]
> I see that `|` == `+`, but how is `~` equal `-`? It misses an operand.

By itself it isn't, but by construction `~` should be equal to `<everything> - <something>`

**Comment by ritchie46** [comment]
Right, but that assumes that `<everything>` holds "everything". It can also hold as subset e.g. "something". 

It gets philosophical ^^

**Comment by alexander-beedie** [comment]
Well, I can experiment accordingly ;)
But "|" will definitely be good to go, heh...

**Comment by ritchie46** [comment]
Yes, the `and` is more complicated. Could do it a single time. But it is not easy to do `A & B | C & D`. We should nest the selectors in a tree, but not really happy with that complexity.

**Review by alexander-beedie — APPROVED** [review]

**Comment by ritchie46** [comment]
Will try to follow up with an `&` operator.

**Pull request merged**
