### PR TITLE
Duration datatype

### PR DESCRIPTION
**Pull request by mhconradt**
This allows subtracting dates / datetimes to get a duration, and adding durations to dates / datetimes to get a date / datetime.

Initially named the data type `Duration` after the Arrow data type, but am considering renaming the data type to `TimeDelta` because there's already the `Duration` object for specifying intervals for `every`, `period`, etc. It's probably best to either rename `DataType::Duration` to `DataType::Timedelta` and/or rename `Duration` to `Interval`.

I basically copied the implementation of adding `Datetime + Duration` between `DatetimeChunked` and `DurationChunked`, is there a better way of doing this?

`Datetime + Duration = Datetime` and `Datetime - Datetime = Duration` introduce some new typing mechanics, specifically because you can't cast `T` and `U` to `V` in this case of `T op U = V` as you could when adding numeric types. I added a shim between the old type system and the new one while also ensuring operands have the same time units. If there's a better way of doing this, let me know.

I would like to figure out adding `timedelta` to a `Date / Datetime / Duration` Series but am not sure which is the best way to do this yet.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Awesome!

For reference, the difference between duration and interval in Arrow is that duration is a physical quantity (i.e. it measures time differences from a physical time) while interval is a calendar quantity (it measures time differences in number of days, months, etc).

For example, 
* a duration of 1 day is exactly 24h = 24*60*60 seconds
* an interval of 1 day may be larger or smaller than 24*60*60 seconds depending on whether e.g. there was a summer time shift or not.

Thus, adding a duration to a datetime (with or without tz) is just adding the numbers; adding an interval requirements taking calendar time shifts into account. [Here](https://github.com/jorgecarleitao/arrow2/blob/main/src/temporal_conversions.rs#L372) is the compute we use in arrow2 for `timestamp w/ tz + interval`

**Comment by ritchie46** [comment]
Nice! This was once included in polars, but was removed because of the strain on compilation times and complexity.

Now that we have logical types in place I think it makes sense to add it again. For the naming I don't think the name collision between `Duration struct` and `DataType::Duration` is that bad as they semantically are the same. We also have a python datetime and a `DataType::Datetime`. But if you want to rename it let's then rename the `Duration struct` to `TimeDelta` so that we remain more true to arrows naming conventions.

> I basically copied the implementation of adding Datetime + Duration between DatetimeChunked and DurationChunked, is there a better way of doing this?

We can make a function that accepts a `Datatime` and a `Duration`, that's more DRY.


> I would like to figure out adding timedelta to a Date / Datetime / Duration Series but am not sure which is the best way to do this yet.

I don't really understand what you mean here?

**Comment by mhconradt** [comment]
@ritchie46 By adding a `timedelta` to a Series I mean being able to do this in Python:
```python
pl.date_range(datetime(2021,1,1), datetime(2022, 1,1), interval="1d") - timedelta(hours=1)
```
Right now you can only do this via the SQL API:
```python
dates = pl.date_range(datetime(2021,1,1), datetime(2022, 1,1), interval="1d", name="date")
dates.to_frame().select(pl.col("date") - pl.lit(timedelta(hours=1))
shape: (366, 1)
┌─────────────────────┐
│ date                │
│ ---                 │
│ datetime[ns]        │
╞═════════════════════╡
│ 2020-12-31 23:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-01-01 23:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-01-02 23:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-01-03 23:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-12-28 23:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-12-29 23:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-12-30 23:00:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2021-12-31 23:00:00 │
└─────────────────────┘
```

**Comment by ritchie46** [comment]
> @ritchie46 By adding a timedelta to a Series I mean being able to do this in Python:

Ah right. You could check the rhs of `__sub__()` in `Series` for the `timedelta` python type.

If it is the `timedelta` type, we could do arithmetic via the expression API. This is easiest with the empty `select` context:

```python
pl.select(pl.col(series_variable) - pl.lit(timedelta(hours=1)).to_series()
```

**Comment by ritchie46** [comment]
I've gone through the code. It looks really good and really complete. I think that when CI is green its good to go. :+1:

**Comment by ritchie46** [comment]
Thank you @mhconradt.

**Pull request merged**
