### PR TITLE
support Decimal comparison & sortby & groupby

### LINKED ISSUE #11078: Support group by with decimal(precision, scale) columns
### Description

Polars does not accept columns with `Decimal(precision, scale)` type in the `group_by` method. It would be nice to have this feature!

# Sample code:

```
use polars::prelude::*;

fn to_decimal_series(precision: usize, scale: usize, data: &[i128]) -> Series {
    Int128Chunked::from_vec("", data.into())
        .into_decimal_unchecked(Some(precision), scale)
        .into_series()
}

fn main() {
    let a = to_decimal_series(35, 0, &[-2_i128, 2, -6, 10, 2, -9]);
    let b = to_decimal_series(35, 0, &[-2_i128, 2, -6, 10, 2, -9]);

    let lazy_data = df!("a" => a, "b" => b).unwrap().lazy();

    let data = lazy_data.groupby(&[col("a")]).agg(
        &[col("b").sum()]
    ).collect().unwrap();
    
    println!("Data: {:?}", data);
}
```

```
[dependencies]
polars = { version = "0.32.1", features = ["lazy", "bigidx", "dtype-decimal"]}
```

# Output error:

```
thread 'main' panicked at '`group_tuples` operation not supported for dtype `decimal[35,0]`', /home/joe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.32.1/src/series/series_trait.rs:174:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

While I'm still getting familiar with the Polars core code, I'm willing to implement this feature if no one more familiar with Polars can. I plan to start exploring the code soon and would appreciate a brief outline of the specific areas to focus on. I believe this will be valuable.

### LINKED ISSUE #11079: Support order by with decimal(precision, scale) columns
### Description

Polars does not accept columns with `Decimal(precision, scale)` type in the `sort` method. It would be nice to have this feature!

# Sample code:

```
use polars::prelude::*;

fn to_decimal_series(precision: usize, scale: usize, data: &[i128]) -> Series {
    Int128Chunked::from_vec("", data.into())
        .into_decimal_unchecked(Some(precision), scale)
        .into_series()
}

fn main() {
    let a = to_decimal_series(35, 0, &[-2_i128, 2, -6, 10, 2, -9]);
    let b = to_decimal_series(35, 0, &[-2_i128, 2, -6, 10, 2, -9]);

    let lazy_data = df!("a" => a, "b" => b).unwrap().lazy();

    let data = lazy_data.sort("a", Default::default()).collect().unwrap();
    
    println!("Data: {:?}", data);
}
```

```
[dependencies]
polars = { version = "0.32.1", features = ["lazy", "bigidx", "dtype-decimal"]}
```

# Output error:

```
thread 'main' panicked at '`arg_sort` operation not supported for dtype `decimal[35,0]`', /home/joe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-core-0.32.1/src/series/series_trait.rs:369:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### LINKED ISSUE #12118: Implement equality operation for `Decimal` types
### Reproducible example

```python
import polars as pl
from decimal import Decimal as D

s1 = pl.Series([D("1.00000"), D("2.00000")], dtype=pl.Decimal)
s2 = pl.Series([D("1.00000"), D("2.00001")], dtype=pl.Decimal)

result = s1 == s2
# pyo3_runtime.PanicException: not implemented
```

### Issue description

Decimal equality is not implemented.

### Expected behavior

Result should be `[True, False]`

```python
from polars.testing import assert_series_equal

expected = pl.Series([True, False])
assert_series_equal(result, expected)
```

### PR DESCRIPTION
**Pull request by flisky**
* support comparison, fix #12118 
* support sort by, fix #11079
* support group by, fix #11078

### CODE REVIEW

**Comment by cgevans** [comment]
It's great that this is getting done, but in my attempts to implement this, it has been rather tricky to make sure that it's right.  Here, for example:

```python
import polars as pl
pl.Config(activate_decimals=True)
from decimal import Decimal as D
a = pl.Series([D("1.5"), D("22.25"), D("10.0")]) 
b = a.cast(pl.Float64)
c = pl.Series([1,2,10])
d = pl.Series([6, 89, 40])

a == D("1.5")  # => False
b == 1.5 # => Series([True, False, False])
a == 1.5 # => False
a == 10 # => False

a == pl.Series([1.5]) # => Series([True, False, False])
a == pl.Series([D("1.5")]) # => Series([False,False,False])  # because of inference and comparison required equal scale
a == pl.Series([D("1.5")], dtype=pl.Decimal(scale=2)) # => same, related to #13572 
a == pl.Series([D("1.5")]).cast(pl.Decimal(scale=2)) # => Series([True, False, False])
```

I think there's also potentially a question of whether comparison should actually handle different-scale (and different-precision) lhs and rhs, eg, by increasing using max(scale) for comparison and ensuring that the lower-scale side fits within the precision.

**Comment by flisky** [comment]
@cgevans your cases are valuable, and I think I've covered them. I'm glad to go deeper if you have more questions.

Or maybe I should split out this PR for easier review (and merge)? (I struggled hours with feature flags to pass CI)

**Comment by cgevans** [comment]
I should note I'm just a random person who really needs decimal support in polars, and who is happy to see you doing this PR that makes it less likely I'll need to find time to work on trying to add support myself.  So whether or not to split it up would be a question for the actually knowledgeable developers to answer.

I will try to build this and see how the changes work, however.

**Comment by flisky** [comment]
I'll split this PR into small ones, closing.

**Pull request closed without merging**
