### PR TITLE
fix: leading whitespaces are trimmed at start of the line (#12832 )

### PR DESCRIPTION
**Pull request by xyxel**

### CODE REVIEW

**Comment by xyxel** [comment]
PR is created in respect to comments from https://github.com/pola-rs/polars/issues/12763. I assume the next step will be adding new parameter for whitespaces trimming.

**Comment by ritchie46** [comment]
Which bug should this fix? I miss context here.

**Comment by xyxel** [comment]
Originally I fixed the bug: https://github.com/pola-rs/polars/issues/12832
But it's related to conversation in https://github.com/pola-rs/polars/issues/12763
The main idea that leading whitespaces at start of the line should not be trimmed because they are part of value. Looks like they should be trimmed if user set appropriate parameter only.

**Comment by ritchie46** [comment]
I believe this PR was superseded by #14042

Not entirely sure.

**Comment by xyxel** [comment]
Yes, you are right. Thank you.
One more note. If there is empty line then currently polars adds additional rows with None values, so test below is correct (As I understand, previous version trimmed empty line):
```
    df = pl.read_csv(
        b"a,b\n\nc,d\n",
        new_columns=["A", "B"],
        has_header=False,
        comment_prefix="#",
        use_pyarrow=False,
    )
    expected = pl.DataFrame({"A": ["a", None, "c"], "B": ["b", None, "d"]})
    assert_frame_equal(df, expected)

```
But I'm not sure if it's expected behavior or not.

**Pull request closed without merging**
