### PR TITLE
Polars vs Pivot: Round 3 🥊 `~2-25x` improvement

### LINKED ISSUE #2968: Low Speed and High Memory Usage with Pivot
#### What language are you using?

Python

#### What version of polars are you using?

polars-0.13.14

#### What operating system are you using polars on?

Linux

#### What language version are you using
Python 3.7.12

#### Describe your bug.

I noticed a very high memory usage while running the `pivot` method on a moderate size dataframe (10m rows).
I constructed this example to try to illustrate the issue. I ran the same code snipped with both polars and pandas. Pandas' run was faster and consumed 8x less memory. 

**Polars**
image
image

**Pandas**
image
image

#### What are the steps to reproduce the behavior?
Here is the code to reproduce the examplesI

```python
from itertools import product
import random
import polars as pl

row_id = range(3_000_000)
types =  product(['t1', 't2', 't3'], row_id)
types = list(zip(*types))
pl_df = pl.DataFrame({'row_id': range(len(types[0])), 'types': types[0], 'values':[random.randint(0, 1_000_000) for _ in range(len(types[0]))]})
pl_df_long = pl_df.pivot(values='values', index='row_id', columns='types')
```

```python
from itertools import product
import random
import pandas as pd

row_id = range(3_000_000)
types =  product(['t1', 't2', 't3'], row_id)
types = list(zip(*types))
pd_df = pd.DataFrame({'row_id': range(len(types[0])), 'types': types[0], 'values':[random.randint(0, 1_000_000) for _ in range(len(types[0]))]})
pd_df_long = pd_df.pivot(values='values', index='row_id', columns='types')
```

Thank you for building and maintaining this great library!
Best regards,
LG

### PR DESCRIPTION
**Pull request by ritchie46**
Starting to hate this operation with a vengeance. Hard to get a performant solution. Third attempt.

This PR fixes #2968 and improves performance of that query by **~25x** on my machine.

Another upside of this implementation is that it allows us to change the pivot API in such a way that we can accept expressions as aggregations. :sunglasses:

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
With a -100 loc. LOL. Amazing work, @ritchie46 !

**Comment by ritchie46** [comment]
> With a -100 loc.

Oof.. That is proof that the previous round was won by "pivot". :stuck_out_tongue_winking_eye:

**Comment by cbilot** [comment]
Quite the improvement indeed!  I hauled out this dataset:
```
shape: (1265459773, 6)
┌───────────┬─────────┬────────────┬─────────┬────────┬──────┐
│ vtr_id    ┆ cnty_cd ┆ party_affl ┆ vtr_sts ┆ gender ┆ race │
│ ---       ┆ ---     ┆ ---        ┆ ---     ┆ ---    ┆ ---  │
│ i64       ┆ str     ┆ str        ┆ str     ┆ str    ┆ str  │
╞═══════════╪═════════╪════════════╪═════════╪════════╪══════╡
```
and benchmarked a pivot using:
* 'cnty_cd' as index,
* the other four string fields as columns
* aggregation function of 'count'

The resulting dataset is shape: (67, 84).

I ran the pivot five times (with garbage collecting before each run).  The times for each run of the pivot operation in seconds:
#### Polars 0.13.22:
120, 124 118, 117, 126

#### compiled polars: origin/pivot (through 5f579998):   
61, 60, 60, 60, 60

Well done!

**Comment by ritchie46** [comment]
> 

Thanks for lending your beast of a machine for the case. :)

**Pull request merged**
