### PR TITLE
Add DataFrame constructor to docs

### LINKED ISSUE #2314: Broken doc link: DataFrame constructor page isn't linked
The constructor here doesn't have a link: https://pola-rs.github.io/polars/py-polars/html/reference/dataframe.html#constructor

I presume that's just a dropped link? [Series](https://pola-rs.github.io/polars/py-polars/html/reference/series.html) has a constructor doc

### PR DESCRIPTION
**Pull request by zundertj**
Closes #2314.

### CODE REVIEW

**Comment by ritchie46** [comment]
This fail because with autodoc we need to document every method, which is a good thing. I think it is clear that we must make `DataFrame.read_csv` private.

**Comment by zundertj** [comment]
Ok, didnt saw your comment, now I added the four `DataFrame.read_xxx` methods. Shall I make those private instead, by prepending an underscore? I.e. `DataFrame._read_csv`, etc?

**Comment by ritchie46** [comment]
Yes, please. :)

**Comment by zundertj** [comment]
Done.

**Pull request merged**
