### PR TITLE
feat(python): Update `write_delta` to write large arrow types without casting

### PR DESCRIPTION
**Pull request by ion-elgreco**
We were able to add support for pyarrow 13+ with deltalake release v0.13.0: https://github.com/delta-io/delta-rs/releases/tag/python-v0.13.0

### CODE REVIEW

**Comment by stinodego** [comment]
Great stuff! Makes me wonder though: is there any reason I would want to write as small rather than large types? And should this be considered a breaking change?

**Comment by ion-elgreco** [comment]
@stinodego if you're a Polars user then writing in small types wouldn't make sense, since there is a chance with the casting to normal types it doesn't fit into the array.

I wouldn't consider it breaking. For a user nothing changes. Writing delta still works the same as before, just better support now:)

**Comment by stinodego** [comment]
> Writing delta still works the same as before

What happens though if I have an existing pipeline where I append to an existing table? Updating Polars would then trigger a schema change, right? That can definitely be considered breaking.

**Comment by stinodego** [comment]
> I can write to the same table in normal types and then a large arrow, and visa versa.

Interesting! Does this mean that `deltalake` does the casting for us, then? As I assume the primitive types of the table are the small types, correct?

**Comment by stinodego** [comment]
I see. All right then, this can go in! Thanks a lot.

**Review by stinodego — APPROVED** [review]

**Comment by ldacey** [comment]
Is there any downside with using the large types? I have been explicitly casting the large types down historically.

image

**Comment by ion-elgreco** [comment]
>  Is there any downside with using the large types? I have been explicitly casting the large types down historically.
> 
> image
> 
> 

The only downside is that it may not fit into the memory array because of the 2GB limit.

**Pull request merged**
