### PR TITLE
feat(python): add dedicated `selectors` module, consolidating/expanding existing selector capabilities

### PR DESCRIPTION
**Pull request by alexander-beedie**
A productive Saturday! 

@ritchie46: as per Discord, I've taken our existing `col`, `exclude`,`all`, `first` and `last` selector capabilities and unified/expanded them into a more explicit `s` selector expression, which comes with a generous amount of new documentation and examples.

To take it to the next level (_combining_ selectors arbitrarily with `&` and `|`) we'll need to add lower-level support, and the new expression reserves these operators for future use. I was able to implement `~` for everything but `first` and `last`, so that is already up & running.

The selectors remain valid `Expr`, so all the usual broadcasting and expression chaining works as expected.

# The new selectors

```python
import polars.selectors as s

# select by position
s.all()
s.first()
s.last()

# select by dtype
s.by_dtype(...)
s.float()
s.integer()
s.numeric()
s.temporal()
s.string(...)

# select by name
s.by_name(...)
s.contains(...)
s.ends_with(...)
s.matches(...)
s.starts_with(...)
```

# Examples

Create empty example frame with various columns/dtypes:

```python
import polars.selectors as s
import polars as pl

df = pl.DataFrame(
    schema = {
        "abc": pl.UInt16,
        "bbb": pl.UInt32,
        "cde": pl.Float64,
        "def": pl.Float32,
        "eee": pl.Boolean,
        "fgg": pl.Boolean,
        "ghi": pl.Time,
        "JJK": pl.Date,
        "Lmn": pl.Duration,
        "opp": pl.Datetime("ms"),
        "qqR": pl.Utf8,
    },
)
```
All numeric cols:
```python
df.select( s.numeric() ) 
# ┌─────┬─────┬─────┬─────┐
# │ abc ┆ bbb ┆ cde ┆ def │
# │ --- ┆ --- ┆ --- ┆ --- │
# │ u16 ┆ u32 ┆ f64 ┆ f32 │
# ╞═════╪═════╪═════╪═════╡
# └─────┴─────┴─────┴─────┘
```
All cols containing an 'e':
```python
df.select( s.contains("e") )
# ┌─────┬─────┬──────┐
# │ cde ┆ def ┆ eee  │
# │ --- ┆ --- ┆ ---  │
# │ f64 ┆ f32 ┆ bool │
# ╞═════╪═════╪══════╡
# └─────┴─────┴──────┘
```
All cols ending with 'e' or 'g':
```python
df.select( s.ends_with("e","g") ) 
# ┌─────┬──────┬──────┐
# │ cde ┆ eee  ┆ fgg  │
# │ --- ┆ ---  ┆ ---  │
# │ f64 ┆ bool ┆ bool │
# ╞═════╪══════╪══════╡
# └─────┴──────┴──────┘
```
All cols that are *not* integer or temporal:
```python
df.select( ~s.by_dtype(pl.INTEGER_DTYPES, pl.TEMPORAL_DTYPES) )
# ┌─────┬─────┬──────┬──────┬─────┐
# │ cde ┆ def ┆ eee  ┆ fgg  ┆ qqR │
# │ --- ┆ --- ┆ ---  ┆ ---  ┆ --- │
# │ f64 ┆ f32 ┆ bool ┆ bool ┆ str │
# ╞═════╪═════╪══════╪══════╪═════╡
# └─────┴─────┴──────┴──────┴─────┘
```
Select columns that do *not* match (case-insensitively) the given regex.
Note: any required start/end anchors `^` and `$` are added automatically if not found:
```python
df.select( ~s.matches(r"(?i)[F-Z]$") )
# ┌─────┬─────┬─────┬──────┐
# │ abc ┆ bbb ┆ cde ┆ eee  │
# │ --- ┆ --- ┆ --- ┆ ---  │
# │ u16 ┆ u32 ┆ f64 ┆ bool │
# ╞═════╪═════╪═════╪══════╡
# └─────┴─────┴─────┴──────┘
```
...etc ;)

# API docs

Also added a new section to the API docs, with a brief overview, import guidance, and all the new selectors...

<picture>
  <source media="(prefers-color-scheme: light)" srcset="https://github.com/pola-rs/polars/assets/2613171/ed7d23f3-5491-4efb-8b55-4ae777219e7d">
  
</picture>

### CODE REVIEW

**Comment by stinodego** [comment]
This looks great! The naming of the class seems odd to me though. The way the structure is set up suggests we might have other selectors in the future. What will those be named? `p`, `q`, ...? `s2`, `s3`, ...?

It makes more sense to me to call this class `ColumnSelector` and then offer doc examples of importing it as some short name, e.g. `from polars.selectors import ColumnSelector as s`.

**Comment by avimallu** [comment]
+1 on the request to call the class `ColumnSelector` - it definitely makes the origin clearer and keeps future expansions cleaner.

I have one request @alexander-beedie - is it possible to have an "everything else" selector that allows for selecting "all other columns" that are not explicitly or implicitly specified? A typical usecase is when I have multiple columns (`c_1`, c_2`, `c_3`), an ID column (`id`), and a set of new columns (`n_1`, `n_2`) that I've created and need to arrange the columns as `id`, `c_2`, `n_1`, n_2` with the remaining columns. This becomes particularly annoying when I have to do it multiple times, or for more complex use cases (like have all the numeric columns first, then have all others).

**Comment by alexander-beedie** [comment]
> This looks great! The naming of the class seems odd to me though. The way the structure is set up suggests we might have other selectors in the future. What will those be named? `p`, `q`, ...? `s2`, `s3`, ...?
> 
> It makes more sense to me to call this class `ColumnSelector` and then offer doc examples of importing it as some short name, e.g. `from polars.selectors import ColumnSelector as s`.

Yup, I agree with the diagnosis, but think I've got a slightly different solution (which, reading over the Discord notes again was actually @ritchie's original suggestion, haha). 

I don't envisage any other _classes_ of selector (though we could certainly have more actual selectors!), so I want to keep the correspondence between `df.select` and `selectors` (we don't call it `df.column_select`, for example, and any purported row-based selectors would actually be filters). 

I think this will be smoother - no longer implies the existence of other classes, keeps things simple:
```python
import polars.selectors as s
```
Will re-jig it accordingly ;)

**Comment by alexander-beedie** [comment]
> I have one request @alexander-beedie - is it possible to have an "everything else" selector that allows for selecting "all other columns that are not explicitly or implicitly specified"?
 
@avimallu: Sounds like a good addition - could you raise it as a separate Issue? This new unification of selectors relies on existing functionality, and I don't think a `pl.remaining()` is currently possible 😅

**Comment by ritchie46** [comment]
Really love this (still have to review). I will follow up on the rust side so we can properly do unions (A + B) and  (A - B).

**Review by ritchie46 — APPROVED** [review]
Looks great! Really shows that we already had very powerful building blocks in place.

Nicely done with the inversion trick btw. :)


*Note to us; we really need an expression expansion page in the user guide.

**Comment by alexander-beedie** [comment]
> Looks great! Really shows that we already had very powerful building blocks in place.

Very much so! And now we have one place to show it off... :)

> Nicely done with the inversion trick btw. :)

You know I like my tricks, haha... lateral thinking FTW!

> *Note to us; we really need an expression expansion page in the user guide.

Yup, we should definitely spread the word about broadcasting - it's so powerful :)

Anyway, will merge this and follow-up with a few additional selectors 👍

**Comment by cmdlineluser** [comment]
This is great. <3

Would it be possible (or make sense?) to allow the result to be used with `reversed()`

The specific use-case was to use `.coalesce` to find the last non-null in a subset of columns matching a pattern. #9088
```python
df = pl.DataFrame(dict(A1=[1, 2, 3], A2=[4, 5, None], A3=[7, None, None], B=[None] * 3))

# df.select(pl.coalesce(s.matches("A\d+")))
# shape: (3, 1)
# ┌─────┐
# │ A1  │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# │ 2   │
# │ 3   │
# └─────┘

# TypeError: '_selector_proxy_' object is not reversible
df.select(pl.coalesce(reversed(s.matches("A\d+"))))
```

**Comment by cmdlineluser** [comment]
This is great. <3

Would it be possible (or make sense?) to allow the result to be used with `reversed()`

The specific use-case was to use `.coalesce` to find the last non-null in a subset of columns matching a pattern. #9088
```python
df = pl.DataFrame(dict(A1=[1, 2, 3], A2=[4, 5, None], A3=[7, None, None], B=[None] * 3))

# df.select(pl.coalesce(s.matches("A\d+")))
# shape: (3, 1)
# ┌─────┐
# │ A1  │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# │ 2   │
# │ 3   │
# └─────┘

# TypeError: '_selector_proxy_' object is not reversible
df.select(pl.coalesce(reversed(s.matches("A\d+"))))
```
(Should I open a new issue to ask this?)

**Comment by lucazanna** [comment]
@alexander-beedie nicely done! this is a very cool new addition for Polars

As a curiosity, will this also work as s('column_name') or s.column_name ? 
I remember seeing a discussion about it, but I cannot find it anymore

**Comment by alexander-beedie** [comment]
> As a curiosity, will this also work as s('column_name') or s.column_name ?

No; this is in the same general space, but property/predicate-based selectors aren't quite the same thing as specific column selection (the presence of `s.by_name` notwithstanding ;)

**Comment by alexander-beedie** [comment]
> Would it be possible (or make sense?) to allow the result to be used with reversed()

Not in its current form, no; the columns that get selected are not known ahead of time - only at the point of evaluation down inside the engine, and there is currently no mechanism that would allow you to ask for the columns that get selected to be reversed.

However... this is a first-cut that arranges all of the _existing_ machinery into a more discoverable/coherent whole, and we are thinking about adding lower-level functionality to make more things possible with a "real" first-class selector object that can have additional behaviours (the current version is a private `_selector_proxy_` object for this reason - it'll allow us to move something more sophisticated into place later on).

I should probably consolidate some of the thoughts for the next stage into an Issue...🤔

**Comment by mcrumiller** [comment]
Can I recommend using `cs` instead of `s` for the standard short name for the module? `s` is often reserved for a simple series in the way that `df` is used for dataframes.

**Comment by alexander-beedie** [comment]
> Can I recommend using `cs` instead of `s` for the standard short name for the module? `s` is often reserved for a simple series in the way that `df` is used for dataframes.

Sounds reasonable - and would pair well with a future `c` (the proposed "col" helper).

**Pull request merged**
