### PR TITLE
feat(python): Extend quantile label precision in `describe`

### PR DESCRIPTION
**Pull request by chrstfer**
Having 99.99% rounded to 100% was bothering me. Haven't tested, but I don't see why this would break anything.

### CODE REVIEW

**Review by stinodego — CHANGES_REQUESTED** [review]
Can you please give a before and after example of what you're trying to do here? It's not completely clear to me.

I'd suggest just adding a test that shows the new behavior.

**Comment by JulianCologne** [comment]
I think the problem is if you have a column with "much" data (>>100_000) you often want to see values like "99.99%" to ignore outliers but the value "99.99" will get roundet in the output:
```python
pl.DataFrame(
    {
        "val": pl.int_range(0, 1_000_001, eager=True),
    }
).describe(percentiles=[0.99, 0.999, 0.9999])
shape: (9, 2)
┌────────────┬───────────────┐
│ describe   ┆ val           │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 1.000001e6    │
│ null_count ┆ 0.0           │
│ mean       ┆ 500000.0      │
│ std        ┆ 288675.567607 │
│ min        ┆ 0.0           │
│ 99%        ┆ 990000.0      │
│ 100%       ┆ 999000.0      │ <<<<<<<<<< 99.9%
│ 100%       ┆ 999900.0      │ <<<<<<<<<< 99.99%
│ max        ┆ 1e6           │
└────────────┴───────────────┘

```

**Comment by stinodego** [comment]
That makes sense. I'll accept the PR if it includes a test.

**Comment by chrstfer** [comment]
> @chrstfer any news?

Funny you should ask, I was just working on this. Sorry for the delay, just got back on my github today after while off.

First off I'm quite rusty at writing tests, and I've only ever done very simple ones for python. In theory I think this should just involve changing all of the hard-coded percentages in test_describe() to have 3 places after the decimal, but I'm getting bogged down actually running the test suite in test_df.py before I make a commit and push it. 

Sorry if I missed it, but is there a document describing how to setup the test environment? I created a venv and installed what it errored at me about, thinking that's not right.

Also, as I go through this I realize I'm not sure this should be default behavior. Should the loop actually construct each format string for necessary number of places rather than just defaulting to 3? That would make the test even more complicated, however.

This is my first non-documentation-focused PR on a big project, realizing how much of a noob i really am I suppose.

**Comment by chrstfer** [comment]
Well, if we do choose to default to some larger number of places then I suppose it would be changing all of the hard-coded percents, as well as adding more places at the end of the test_describe() function, something like this :

```   
    described = df.describe(percentiles=(0.001, 0.10, 0.25, 0.5, 0.75, 0.9, 0.999)) # <-- adding more places here
    assert described.schema == {
        "describe": pl.Utf8,
        "numerical": pl.Float64,
        "struct": pl.Utf8,
        "list": pl.Utf8,
    }
    assert described.rows() == [
        ("count", 4.0, "4", "4"),
        ("null_count", 1.0, "1", "1"),
        ("mean", 1.3333333333333333, None, None),
        ("std", 0.5773502691896257, None, None),
        ("min", 1.0, None, None),
        ("1.000%", 1.0, None, None),    # <-- changing hard-coded here
        ("10.000%", 1.0, None, None),
        ("25.000%", 1.0, None, None),
        ("50.000%", 1.0, None, None),
        ("75.000%", 1.0, None, None),
        ("90.000%", 2.0, None, None),
        ("99.900%", 2.0, None, None),
        ("max", 2.0, None, None),
    ]
```

**Comment by stinodego** [comment]
Closing in favor of #13593

**Pull request closed without merging**
