### PR TITLE
chore(python): Display full argument names in __repr__ for Datetime a…

### PR DESCRIPTION
**Pull request by ghuls**
…nd Duration datatypes.

### CODE REVIEW

**Comment by ghuls** [comment]
If I remember correctly, a while back `tu` and `tz` were renamed to `time_unit` and `time_zone` but the `__repr__` was not updated.

Normally if you would enter the `__repr__`, you should be able to reconstuct the original object.

There are still other usages of the `tu` and `tz` arguments in the code base, which should be changed the same, to be consistent (or Datetime and Duration arguments can be changed back to `tu` and `tz, if that would make more sense):

```
❯ rg tu= 
tests/unit/utils/test_utils.py
63:    out = _timedelta_to_pl_timedelta(timedelta(days=1), tu=None)

tests/unit/namespaces/test_datetime.py
91:    assert_series_equal(s.dt.epoch(tu=temporal_unit), expected)

polars/expr/datetime.py
1068:        ...         pl.col("date").dt.epoch(tu="s").alias("epoch_s"),
1113:        ...         pl.col("date").dt.timestamp(tu="ms").alias("timestamp_ms"),
1155:        ...         pl.col("date").dt.with_time_unit(tu="us").alias("tu_us"),
1194:        ...         pl.col("date").dt.cast_time_unit(tu="ms").alias("tu_ms"),
1195:        ...         pl.col("date").dt.cast_time_unit(tu="ns").alias("tu_ns"),

polars/series/datetime.py
827:        >>> date.dt.timestamp(tu="ns").alias("timestamp_ns")
869:        >>> date.dt.epoch(tu="s").alias("epoch_s")
906:        >>> date.dt.with_time_unit(tu="us").alias("tu_us")
940:        >>> date.dt.cast_time_unit(tu="ms").alias("tu_ms")
948:        >>> date.dt.cast_time_unit(tu="ns").alias("tu_ns")
1027:        >>> date.dt.epoch(tu="s")
1045:        >>> date.dt.epoch(tu="s")
1063:        >>> date.dt.epoch(tu="s")

❯ rg tz= 
tests/unit/test_queries.py
407:                pd.Timestamp(datetime.utcnow(), tz="UTC"),
408:                pd.Timestamp(datetime.utcnow(), tz="UTC"),
411:                pd.Timestamp(datetime.utcnow(), tz="UTC"),
412:                pd.Timestamp(datetime.utcnow(), tz="UTC"),

tests/unit/datatypes/test_temporal.py
376:    tz_ts = pa.timestamp("s", tz="America/New_York")
2002:    a = pa.array([when]).cast(pa.timestamp("s", tz="Asia/Shanghai"))

polars/utils/convert.py
190:                dt = datetime.fromtimestamp(0, tz=utc) + timedelta(
194:                dt = datetime.fromtimestamp(0, tz=utc) + timedelta(microseconds=value)
197:                dt = datetime.fromtimestamp(value / 1000, tz=utc)

polars/series/datetime.py
959:    @deprecated_alias(tz="time_zone")
983:        >>> date = date.dt.convert_time_zone(tz="Europe/London").alias("London")
1000:    @deprecated_alias(tz="time_zone")
1035:        >>> date = date.dt.convert_time_zone(tz="Europe/London").alias("London")
1053:        >>> date = date.dt.replace_time_zone(tz="America/New_York").alias("NYC")

polars/expr/datetime.py
1212:    @deprecated_alias(tz="time_zone")
1239:        ...         .dt.convert_time_zone(tz="Europe/London")
1256:    @deprecated_alias(tz="time_zone")
1279:        ...         ).dt.convert_time_zone(tz="Europe/London"),
1286:        ...         .dt.replace_time_zone(tz="Europe/Amsterdam")
```

**Comment by ghuls** [comment]
@MarcoGorelli As the time/date expert what do you think would make the most sense?

**Comment by MarcoGorelli** [comment]
> @MarcoGorelli As the time/date expert what do you think would make the most sense?

hey - I'm just going out, will check tomorrow, but from a first look this seems nice!

**Comment by ghuls** [comment]
> > @MarcoGorelli As the time/date expert what do you think would make the most sense?
> 
> hey - I'm just going out, will check tomorrow, but from a first look this seems nice!

You mean changing all `tu` and `tz` to `time_unit` and `time_zone` for all Date/Time APIs or the other way around?

**Review by stinodego — APPROVED** [review]
Yep, this change makes sense. I also want to rename the properties to `time_unit` (or possibly, simply `unit`) and `time_zone`, but I couldn't manage to do that in a non-breaking way.

This is sort-of non-breaking so fine to merge, in my opinion!

**Comment by MarcoGorelli** [comment]
> You mean changing all tu and tz to time_unit and time_zone for all Date/Time APIs or the other way around?

changing to `time_unit` / `time_zone` (I remember scratching my head at `tu` some time ago)

**Comment by ghuls** [comment]
> > You mean changing all tu and tz to time_unit and time_zone for all Date/Time APIs or the other way around?
> 
> changing to `time_unit` / `time_zone` (I remember scratching my head at `tu` some time ago)

I think on the rust side they can be replaced now as the next rust release is already breaking afaik.

**Comment by stinodego** [comment]
The Rust draft release does not list any breaking changes yet, but I believe Rust releases are usuallly breaking.

I think we can go ahead and get this done on the Rust side.

Personally I'd vote for `unit` rather than `time_unit`. I think it's clear enough, short, and matches arrow language.

**Pull request merged**
