### PR TITLE
Flate2 zlib ng

### PR DESCRIPTION
**Pull request by ghuls**

### CODE REVIEW

**Comment by ghuls** [comment]
Is this the best way to fix the formatting or can the `mut reader_bytes: ReaderBytes<'a>,` be put on a new line?

```diff
  pub fn build_csv_reader<'a>(
-    #[cfg(any(feature = "decompress", feature = "decompress-fast"))] mut reader_bytes: ReaderBytes<'a>,
-    #[cfg(not(any(feature = "decompress", feature = "decompress-fast")))] reader_bytes: ReaderBytes<'a>,
+    #[cfg(any(feature = "decompress", feature = "decompress-fast"))] mut reader_bytes: ReaderBytes<
+        'a,
+    >,
+    #[cfg(not(any(feature = "decompress", feature = "decompress-fast")))] reader_bytes: ReaderBytes<
+        'a,
+    >,
```

**Comment by ritchie46** [comment]
> Is this the best way to fix the formatting or can the `mut reader_bytes: ReaderBytes<'a>,` be put on a new line?
> 
> ```diff
>   pub fn build_csv_reader<'a>(
> -    #[cfg(any(feature = "decompress", feature = "decompress-fast"))] mut reader_bytes: ReaderBytes<'a>,
> -    #[cfg(not(any(feature = "decompress", feature = "decompress-fast")))] reader_bytes: ReaderBytes<'a>,
> +    #[cfg(any(feature = "decompress", feature = "decompress-fast"))] mut reader_bytes: ReaderBytes<
> +        'a,
> +    >,
> +    #[cfg(not(any(feature = "decompress", feature = "decompress-fast")))] reader_bytes: ReaderBytes<
> +        'a,
> +    >,
> ```

If you run `cargo fmt` this should be fixed automatically. 

You can also rune `make pre-commit`. That will fix formatting and do linting checks.

**Comment by ritchie46** [comment]
Thanks @ghuls. That's an obvious fix. Can't believe I didn't see that.

**Comment by ghuls** [comment]
> Thanks @ghuls. That's an obvious fix. Can't believe I didn't see that.
It took me a while too. Didn't expect this kind of problem.

Formatting issue should be fixed now.

**Comment by ritchie46** [comment]
> It took me a while too. Didn't expect this kind of problem.

Yeah, sorry about that. By hinting about the compiler, we all we're put on a wrong track. :/

**Pull request merged**
