### PR TITLE
feat(rust): add sort maintaining order row encoding

### PR DESCRIPTION
**Pull request by ritchie46**

### CODE REVIEW

**Comment by ghuls** [comment]
For people who wonder what this pull request is about: https://arrow.apache.org/blog/2022/11/07/multi-column-sorts-in-arrow-rust-part-2/

**Comment by ritchie46** [comment]
Yeap, most importantly this is the requisit for multicolumn joins in streaming.

**Comment by ritchie46** [comment]
@ghuls you were interested in performance benefits of this. I've got it working for numeric data. It can be faster if the cardinality of the first sort column is very low.  E.g. 1000 unique values on 10M rows. But if the cardinality is higher our current sort always seems faster. That's because we only pay an indirection when there are duplicates, where the row format always starts the compare with an indirection.

Still this is great stuff to have. When the first column is a `Utf8` for instance you definitely want the row format as we have the indirection up front. And of course the whole streaming use case. It is just good to know that our sort isn't as bad as we thought ;)

**Comment by ghuls** [comment]
@ritchie46 I have a few cases where I have to sort 3 or 4 columns, with the first and fourth of low cardinality (stored as categoricals for now), columns 2 and 3 are integers.

Does this only allow a global sort order (all column descending/ascending) or can this be set per column?

**Comment by ritchie46** [comment]
> a global sort order (all column descending/ascending) or can this be set per column?

Can be set per column. Categoricals need to be cast to physical first at the moment. Please give it some benchmarks.

**Pull request merged**
