### PR TITLE
[chore]: Remove trailing whitespace.

### PR DESCRIPTION
**Pull request by ghuls**
Remove trailing whitespace from various files.

### CODE REVIEW

**Comment by ghuls** [comment]
@universalmind303 @ritchie46 Should JS still be tested inside this repo now that it is moved to https://github.com/pola-rs/nodejs-polars/? The nodejs-polars dir probably should be removed too.

**Comment by ritchie46** [comment]
> @universalmind303 @ritchie46 Should JS still be tested inside this repo now that it is moved to https://github.com/pola-rs/nodejs-polars/? The nodejs-polars dir probably should be removed too.

Yes, if everything is clear on @universalmind303's side we can remove it.

Maybe we should rewrite the git history to save space? This will break open PR's, I believe.

**Comment by ghuls** [comment]
> > @universalmind303 @ritchie46 Should JS still be tested inside this repo now that it is moved to https://github.com/pola-rs/nodejs-polars/? The nodejs-polars dir probably should be removed too.
> 
> Yes, if everything is clear on @universalmind303's side we can remove it.
> 
> Maybe we should rewrite the git history to save space? This will break open PR's, I believe.

There are not that many commits for nodejs-polars, so it wouldn't save much space.

**Comment by ritchie46** [comment]
> > > @universalmind303 @ritchie46 Should JS still be tested inside this repo now that it is moved to https://github.com/pola-rs/nodejs-polars/? The nodejs-polars dir probably should be removed too.
> > 
> > 
> > Yes, if everything is clear on @universalmind303's side we can remove it.
> > Maybe we should rewrite the git history to save space? This will break open PR's, I believe.
> 
> There are not that many commits for nodejs-polars, so it wouldn't save much space.

Right.. let's simply remove then.

**Pull request merged**
