### PR TITLE
Use Polars ThreadPool

### PR DESCRIPTION
**Pull request by ibENPC**
As mentioned here: https://github.com/pola-rs/polars/pull/1925#issuecomment-981608768

### CODE REVIEW

**Comment by ritchie46** [comment]
:raised_hands:

**Comment by alippai** [comment]
Is there a flag / option to prevent implicit (accidental) pool creation in Rayon?

**Comment by ritchie46** [comment]
Don't know.. It would be beneficial indeed.

**Comment by alippai** [comment]
Maybe calling https://docs.rs/rayon/1.0.0/rayon/struct.ThreadPoolBuilder.html#method.build_global at the tests teardown would help this (it fails if global threadpool exists)

**Comment by ibENPC** [comment]
> Maybe calling https://docs.rs/rayon/1.0.0/rayon/struct.ThreadPoolBuilder.html#method.build_global at the tests teardown would help this (it fails if global threadpool exists)

It's a smart idea. 

However it requires to run tests that shouldn't be run (in PR for example) for the moment because `cargo miri` would complain about the [Rayon](https://github.com/rayon-rs/rayon) remaining thread.
We could use comments in order to make the tests available if needed but not triggered in general, I don't know.

That's a little bit tricky 🤪

**Comment by alippai** [comment]
This might be even better. Drop the polars threadpool in teardown and if miri complains after the test, the global threadpool was initialized. I'm not sure what issues miri has right now, but if it's about lingering threads after test run, then this might work.

**Comment by ibENPC** [comment]
How to drop the [Polars](https://github.com/pola-rs/polars) [ThreadPool](https://docs.rs/rayon/1.5.1/rayon/struct.ThreadPool.html) ?

**Comment by alippai** [comment]
I didn't use it before, but maybe https://docs.rs/rayon/1.5.1/rayon/struct.ThreadPool.html#impl-Drop?

**Comment by ibENPC** [comment]
From what I understand, the [ThreadPool](https://docs.rs/rayon/1.5.1/rayon/struct.ThreadPool.html) is declared [static](https://doc.rust-lang.org/std/keyword.static.html) as it can be seen here:
https://github.com/pola-rs/polars/blob/fafde8d8a7f052ed3f7b01be36cf64ec89218d58/polars/polars-core/src/lib.rs#L28

Therefore it can't be dropped.

I don't know if it is possible to change that in [Polars](https://github.com/pola-rs/polars) and be able to manipulate the [ThreadPool](https://docs.rs/rayon/1.5.1/rayon/struct.ThreadPool.html) for the tests with those tricks while keeping an optimized behavior for the usual crate usage.

**Comment by alippai** [comment]
Would it help if instead of the using the `.build()` we'd create the registry separately like:
```
lazy_static! {
    pub static ref REG: Arc<Registry> = Arc::new(Registry::new(ThreadPoolBuilder::new()
        .num_threads(
            std::env::var("POLARS_MAX_THREADS")
                .map(|s| s.parse::<usize>().expect("integer"))
                .unwrap_or_else(|_| num_cpus::get())
        ))?);
}``` and then we'd be able to create the POOL as `ThreadPool = ThreadPool { REG }`? That way `REG.terminate()` would be accessible. I'm just guessing here as I'm not a Rust programmer. What do you think?

**Comment by ibENPC** [comment]
It is difficult for me to understand how or why it would work. I don't think so but I might be wrong.

Do not hesitate to test the code yourself to achieve a complete implementation of your idea, the Rust compiler will help you.

**Comment by alippai** [comment]
@ibENPC you are right, `Registry` is private, we can't access it. I've added https://github.com/rayon-rs/rayon/pull/903, if they find it useful, we may use it in the future. Running `POOL.terminate()` at the end of the test makes miri happy.
I didn't dig deeper, maybe the tests using `POOL` might need to run sequentially (similar to this issue https://github.com/rust-lang/rust/issues/47506)

**Comment by ibENPC** [comment]
@alippai thank you for the work, the problem is clearer.

If we run the tests sequentially we might find a solution by using an [unsafe modification of POOL](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html#accessing-or-modifying-a-mutable-static-variable) or another unsafe method. Otherwise it seems to imply a random game with data races 🤪

@ritchie46 Is it a problem to use `-Zmiri-disable-leaks` as an option to `cargo miri` for the checks ? Because there are many functions where we can use [Rayon](https://github.com/rayon-rs/rayon), and the `miri` test as is forces only 2 distinct choices:
- Avoiding to parallelize --> best potential performance not achieved.
- Avoiding to run tests --> best potential robustness not achieved.

I can open an issue if you think that the discussion is worth it.

**Pull request merged**
