### PR TITLE
refactor(python)!: Remove deprecated behaviour

### PR DESCRIPTION
**Pull request by stinodego**
Removing some deprecated behaviour, mostly:
* Removed deprecated variable names
* Made some arguments keyword-only
* Removed the redirects on DataFrame/LazyFrame.

### CODE REVIEW

**Comment by stinodego** [comment]
@ritchie46 Can we merge this? Then I can do a last pass through our API to check for naming conventions etc.

**Comment by ritchie46** [comment]
I think so. Do we remove all deprecated or shall we leave a grace period of 1 breaking release? (Since it doesn't hurt us that much I think we should consider this in the future).

**Comment by stinodego** [comment]
> I think so. Do we remove all deprecated or shall we leave a grace period of 1 breaking release? (Since it doesn't hurt us that much I think we should consider this in the future).

The keyword-only args stuff I really want to get done now, as it's blocking some improvements.

Simple argument renames / method redirects we could have a grace period for, they don't really both us, but right now we're not tracking when these were introduced. I could leave those in for now and we'll drop all those in `1.0.0`? (I'll have to re-do this PR, that's fine).

The deprecation decorators do interfere with the `@expr_dispatch` decorator, which is annoying. If we fix that, and add functionality for tracking when the deprecation happened, we can be better at offering a grace period for deprecations.

**Comment by stinodego** [comment]
In that case, I'll go ahead with this PR. Since this is the intended to be the last breaking release before `1.0.0`, I think it's worth breaking stuff now to make the `1.0.0` release as smooth as possible.

I opened an issue for improving the deprecation utils: #8004

**Pull request merged**
