### PR TITLE
feat(python): expose cat.ordered

### PR DESCRIPTION
**Pull request by ritchie46**
#5671

### CODE REVIEW

**Comment by ritchie46** [comment]
Somehow the docs fail because the `self._s` is not initialized in the `CatNameSpace`. This is probably because of our complicated dispatch.

Any idea here @alexander-beedie?

**Comment by alexander-beedie** [comment]
> Any idea here @alexander-beedie? 

Am currently in the middle of the Jordanian desert! 😂 Will be back in range of a computer on Monday evening if you can wait a bit - I'm sure it'll be something simple to resolve (quick sanity check: the CatNameSpace has the same decorator as the others?)

**Comment by ritchie46** [comment]
> ning if you can wait a bit - I'm sure it'll be something simple to resolve (quick sanity check: the CatNameSpace has the same decorator as the others?)

No hurry at all! Have fun there in the dessert. ;)

**Comment by alexander-beedie** [comment]
> Any idea here @alexander-beedie?

Refreshed; back home from... Mars? (Feel like I should watch Dune again - part of it was shot out there ;)

Wadi Rum Desert

Ok, so you should be able to fix like so:
```python
return self._s.cat_is_ordered() if self._s is not None else None
```
The reason is that the `*NameSpace` classes are accessed _uninitialised_ from Sphinx (via the `@accessor` decorator in `series.py` which makes them available under the correct namespace when docs are built). When the property is introspected `_s` is not available, hence the error.

Could equally check the docs-build env var and return None if set, though the above is probably simpler.
```python
if os.getenv("BUILDING_SPHINX_DOCS"):
    return None
return self._s.cat_is_ordered()
```

**Comment by ritchie46** [comment]
Wow, that's some sight indeed. How did my @alexander-beedie tag even reach you there? :see_no_evil:

**Comment by alexander-beedie** [comment]
> Wow, that's some sight indeed. How did my @alexander-beedie tag even reach you there? 🙈

Heh... there was one spot in the camp with limited WiFi, so could check-up on the outside world at dinner/breakfast, lol.

I see the proposed fix didn't _quite_ work; not sure why it's claiming to want a method signature out of a `None` value, but can dig further tonight.

**Comment by alexander-beedie** [comment]
Ok... I setup a debug profile for `sphinx-build` so I could step through and see what's happening; have tried several increasingly-exotic attempts to keep it happy, but the least-intrusive solution so far is simply to omit the `@property` decorator and leave it as a method - at which point everything appears to flow through smoothly.

**Comment by alexander-beedie** [comment]
The final idea "almost" worked - was playing with a `@namespace_property` decorator (a slight variation on `@accessor`) and that allowed the docs to compile fine without any other special handling, but with one irritating issue - the generated docs reported the `ordered` attribute as a method. It seems the universe _really_ wants this to be a method...😅

**Comment by alexander-beedie** [comment]
I take it back - have made a patch on top of this one that allows us to better-handle namespaced attributes, if you want to grab it; can take a look here: https://github.com/pola-rs/polars/compare/cat_ordered...alexander-beedie:polars:cat_ordered - lets us use `@property` as normal, with no special handling.

The docs formatting as a method came down to the `.rst` accessor template, so that was an easy fix after all. The one thing that's still a bit annoying is that the docstring and expected type isn't being pulled into the generated docs; instead it's reporting the default value (False). I can revisit this later to see if the template needs updating, or if there is something else at play.

**Comment by alexander-beedie** [comment]
@ritchie46: let's just make `ordered` a method - path of least resistance, and everything will "just work". (I can potentially revisit after upgrading to sphinx v6).

**Comment by stinodego** [comment]
Closing in favor of #10325 as I didn't feel like rebasing 😄

**Pull request closed without merging**
