### PR TITLE
feat: Make formatting more consistent in DOT graphs

### PR DESCRIPTION
**Pull request by jdanford**
Additionally, should there be a space here? (i.e. "CACHE: {} times")
https://github.com/jdanford/polars/blob/86e82d7a376b3a83d0eb36de725f8f0cb304c320/crates/polars-plan/src/dot.rs#L169

### CODE REVIEW

**Comment by stinodego** [comment]
> Additionally, should there be a space here? (i.e. "CACHE: {} times")

I would think so.

**Review by stinodego — COMMENTED** [review]
Thanks for the PR! Is there a way I can see the impact of this change? Apparently, no tests fail on this change so that is a bit scary.

**Comment by jdanford** [comment]
For sure, I'm working on before/after images right now

**Comment by jdanford** [comment]
Examples are from Polars blog and docs so they're not perfect, but they reflect the changes to the TABLE and JOIN nodes

Before | After
--- | ---
before-1 | after-1
before-2 | after-2

**Comment by stinodego** [comment]
I think the tree images are identical, right?

**Review by stinodego — APPROVED** [review]
I think the changes look good, will let someone else have the final say.

**Review by ritchie46 — APPROVED** [review]

**Pull request merged**
