### PR TITLE
chore(rust): fix docs build and add to CI

### PR DESCRIPTION
**Pull request by ritchie46**

### CODE REVIEW

**Comment by stinodego** [comment]
There's already a workflow for this - `docs-rust.yml`. But it only builds for the `polars` package.

**Comment by ritchie46** [comment]
> There's already a workflow for this - docs-rust.yml

Doesn't that one build and publishes the docs?

This one tests them and fails CI if they fail. The release today failed building docs.

**Comment by stinodego** [comment]
> Doesn't that one build and publishes the docs?

It's a combination. The workflow builds the docs and fails if they cannot be build. Then if it's on the main branch, it publishes the result.

I guess we should add the full `make doctest` command there, instead of just the polars package.

**Comment by ritchie46** [comment]
The point is, it should not fail on main, but on the PR.

**Comment by stinodego** [comment]
> The point is, it should not fail on main, but on the PR.

That's what it does. Just change this:

https://github.com/pola-rs/polars/blob/672922491bac1f144747d39b864106d90010fd1e/.github/workflows/docs-rust.yml#L32-L35

To:

```yaml
      - name: Build Rust documentation
        env:
          RUSTDOCFLAGS: --cfg docsrs -D warnings
        working-directory: polars
        run: make doctest
```

**Comment by ritchie46** [comment]
Ok, will do!

**Comment by stinodego** [comment]
You'll probably have to fix a few warnings though - mostly links that need to be proper hyperlinks, and a few feature gates. I was just looking at that locally 😄

**Pull request merged**
