### PR TITLE
build(rust,python): bump rust toolchain channel

### PR DESCRIPTION
**Pull request by borchero**
# Motivation

Using `cargo` with the current toolchain results in the following error on Apple Silicon:

```
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the 'nightly-2023-03-10-aarch64-apple-darwin' toolchain
```

### CODE REVIEW

**Comment by stinodego** [comment]
If you want to bump the toolchain, you have to change it in the CI as well (release workflow).

**Comment by stinodego** [comment]
Also, I've seen that error before, and managed to fix it by re-installing my toolchains using rustup.

**Comment by borchero** [comment]
I updated the release workflow accordingly but feel free to close this PR if you don't think it's worth updating. Working on another laptop, the old toolchain also works so I suspect re-installing toolchains would solve the issue as well.

**Comment by stinodego** [comment]
I think it's fine to merge this, but I'll leave it up to Ritchie whether he wants to merge this or bump the version at a later point - he's the one usually doing this.

**Review by stinodego — APPROVED** [review]

**Comment by ritchie46** [comment]
Upgraded.

**Pull request closed without merging**
