### PR TITLE
feat(python): Support passing instantiated adbc/alchemy connection objects to `write_database`

### LINKED ISSUE #15538: Polars write_database Connection Issue with Redshift: Unrecognized Configuration Parameter
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# Attempt to write DataFrame to Redshift
df = pl.DataFrame({
    "a": [1, 2, 3],
    "b": ["x", "y", "z"]
})

redshift_uri = "your_connection_uri_here"

df.write_database(
    table_name='test.test',
    connection=redshift_uri,
    if_table_exists='replace'
)

```

### Log output

```shell
---------------------------------------------------------------------------
UndefinedObject                           Traceback (most recent call last)
File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\base.py:1971, in Connection._exec_single_context(self, dialect, context, statement, parameters)
   1970     if not evt_handled:
-> 1971         self.dialect.do_execute(
   1972             cursor, str_statement, effective_parameters, context
   1973         )
   1975 if self._has_events or self.engine._has_events:

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\default.py:919, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    918 def do_execute(self, cursor, statement, parameters, context=None):
--> 919     cursor.execute(statement, parameters)

UndefinedObject: unrecognized configuration parameter "standard_conforming_strings"


The above exception was the direct cause of the following exception:

ProgrammingError                          Traceback (most recent call last)
Cell In[33], line 1
----> 1 a.write_database(table_name='wormhole',
      2 connection=redshift_uri,
      3 if_table_exists = 'replace')

File ~\AppData\Roaming\Python\Python311\site-packages\polars\_utils\deprecation.py:134, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    129 @wraps(function)
    130 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    131     _rename_keyword_argument(
    132         old_name, new_name, kwargs, function.__name__, version
    133     )
--> 134     return function(*args, **kwargs)

File ~\AppData\Roaming\Python\Python311\site-packages\polars\dataframe\frame.py:3578, in DataFrame.write_database(self, table_name, connection, if_table_exists, engine)
   3572         raise ValueError(msg)
   3574     # ensure conversion to pandas uses the pyarrow extension array option
   3575     # so that we can make use of the sql/db export *without* copying data
   3576     res: int | None = self.to_pandas(
   3577         use_pyarrow_extension_array=True,
-> 3578     ).to_sql(
   3579         name=unpacked_table_name,
   3580         schema=db_schema,
   3581         con=engine_sa,
   3582         if_exists=if_table_exists,
   3583         index=False,
   3584     )
   3585     return -1 if res is None else res
   3586 else:

File ~\AppData\Roaming\Python\Python311\site-packages\pandas\util\_decorators.py:333, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    327 if len(args) > num_allow_args:
    328     warnings.warn(
    329         msg.format(arguments=_format_argument_list(allow_args)),
    330         FutureWarning,
    331         stacklevel=find_stack_level(),
    332     )
--> 333 return func(*args, **kwargs)

File ~\AppData\Roaming\Python\Python311\site-packages\pandas\core\generic.py:3084, in NDFrame.to_sql(self, name, con, schema, if_exists, index, index_label, chunksize, dtype, method)
   2886 """
   2887 Write records stored in a DataFrame to a SQL database.
   2888 
   (...)
   3080 [(1,), (None,), (2,)]
   3081 """  # noqa: E501
   3082 from pandas.io import sql
-> 3084 return sql.to_sql(
   3085     self,
   3086     name,
   3087     con,
   3088     schema=schema,
   3089     if_exists=if_exists,
   3090     index=index,
   3091     index_label=index_label,
   3092     chunksize=chunksize,
   3093     dtype=dtype,
   3094     method=method,
   3095 )

File ~\AppData\Roaming\Python\Python311\site-packages\pandas\io\sql.py:841, in to_sql(frame, name, con, schema, if_exists, index, index_label, chunksize, dtype, method, engine, **engine_kwargs)
    836 elif not isinstance(frame, DataFrame):
    837     raise NotImplementedError(
    838         "'frame' argument should be either a Series or a DataFrame"
    839     )
--> 841 with pandasSQL_builder(con, schema=schema, need_transaction=True) as pandas_sql:
    842     return pandas_sql.to_sql(
    843         frame,
    844         name,
   (...)
    853         **engine_kwargs,
    854     )

File ~\AppData\Roaming\Python\Python311\site-packages\pandas\io\sql.py:906, in pandasSQL_builder(con, schema, need_transaction)
    903     raise ImportError("Using URI string without sqlalchemy installed.")
    905 if sqlalchemy is not None and isinstance(con, (str, sqlalchemy.engine.Connectable)):
--> 906     return SQLDatabase(con, schema, need_transaction)
    908 adbc = import_optional_dependency("adbc_driver_manager.dbapi", errors="ignore")
    909 if adbc and isinstance(con, adbc.Connection):

File ~\AppData\Roaming\Python\Python311\site-packages\pandas\io\sql.py:1636, in SQLDatabase.__init__(self, con, schema, need_transaction)
   1634     self.exit_stack.callback(con.dispose)
   1635 if isinstance(con, Engine):
-> 1636     con = self.exit_stack.enter_context(con.connect())
   1637 if need_transaction and not con.in_transaction():
   1638     self.exit_stack.enter_context(con.begin())

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\base.py:3280, in Engine.connect(self)
   3257 def connect(self) -> Connection:
   3258     """Return a new :class:`_engine.Connection` object.
   3259 
   3260     The :class:`_engine.Connection` acts as a Python context manager, so
   (...)
   3277 
   3278     """
-> 3280     return self._connection_cls(self)

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\base.py:146, in Connection.__init__(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)
    144 if connection is None:
    145     try:
--> 146         self._dbapi_connection = engine.raw_connection()
    147     except dialect.loaded_dbapi.Error as err:
    148         Connection._handle_dbapi_exception_noconnection(
    149             err, dialect, engine
    150         )

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\base.py:3304, in Engine.raw_connection(self)
   3282 def raw_connection(self) -> PoolProxiedConnection:
   3283     """Return a "raw" DBAPI connection from the connection pool.
   3284 
   3285     The returned object is a proxied version of the DBAPI
   (...)
   3302 
   3303     """
-> 3304     return self.pool.connect()

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\pool\base.py:449, in Pool.connect(self)
    441 def connect(self) -> PoolProxiedConnection:
    442     """Return a DBAPI connection from the pool.
    443 
    444     The connection is instrumented such that when its
   (...)
    447 
    448     """
--> 449     return _ConnectionFairy._checkout(self)

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\pool\base.py:1263, in _ConnectionFairy._checkout(cls, pool, threadconns, fairy)
   1255 @classmethod
   1256 def _checkout(
   1257     cls,
   (...)
   1260     fairy: Optional[_ConnectionFairy] = None,
   1261 ) -> _ConnectionFairy:
   1262     if not fairy:
-> 1263         fairy = _ConnectionRecord.checkout(pool)
   1265         if threadconns is not None:
   1266             threadconns.current = weakref.ref(fairy)

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\pool\base.py:712, in _ConnectionRecord.checkout(cls, pool)
    710     rec = cast(_ConnectionRecord, pool._do_get())
    711 else:
--> 712     rec = pool._do_get()
    714 try:
    715     dbapi_connection = rec.get_connection()

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\pool\impl.py:179, in QueuePool._do_get(self)
    177     return self._create_connection()
    178 except:
--> 179     with util.safe_reraise():
    180         self._dec_overflow()
    181     raise

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\util\langhelpers.py:146, in safe_reraise.__exit__(self, type_, value, traceback)
    144     assert exc_value is not None
    145     self._exc_info = None  # remove potential circular references
--> 146     raise exc_value.with_traceback(exc_tb)
    147 else:
    148     self._exc_info = None  # remove potential circular references

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\pool\impl.py:177, in QueuePool._do_get(self)
    175 if self._inc_overflow():
    176     try:
--> 177         return self._create_connection()
    178     except:
    179         with util.safe_reraise():

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\pool\base.py:390, in Pool._create_connection(self)
    387 def _create_connection(self) -> ConnectionPoolEntry:
    388     """Called by subclasses to create a new ConnectionRecord."""
--> 390     return _ConnectionRecord(self)

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\pool\base.py:674, in _ConnectionRecord.__init__(self, pool, connect)
    672 self.__pool = pool
    673 if connect:
--> 674     self.__connect()
    675 self.finalize_callback = deque()

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\pool\base.py:914, in _ConnectionRecord.__connect(self)
    906     pool.dispatch.first_connect.for_modify(
    907         pool.dispatch
    908     ).exec_once_unless_exception(self.dbapi_connection, self)
    910 # init of the dialect now takes place within the connect
    911 # event, so ensure a mutex is used on the first run
    912 pool.dispatch.connect.for_modify(
    913     pool.dispatch
--> 914 )._exec_w_sync_on_first_run(self.dbapi_connection, self)

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\event\attr.py:483, in _CompoundListener._exec_w_sync_on_first_run(self, *args, **kw)
    481 with self._exec_once_mutex:
    482     try:
--> 483         self(*args, **kw)
    484     except:
    485         raise

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\event\attr.py:497, in _CompoundListener.__call__(self, *args, **kw)
    495     fn(*args, **kw)
    496 for fn in self.listeners:
--> 497     fn(*args, **kw)

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\util\langhelpers.py:1910, in only_once.<locals>.go(*arg, **kw)
   1908 once_fn = once.pop()
   1909 try:
-> 1910     return once_fn(*arg, **kw)
   1911 except:
   1912     if retry_on_exception:

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\create.py:749, in create_engine.<locals>.first_connect(dbapi_connection, connection_record)
    746 c._execution_options = util.EMPTY_DICT
    748 try:
--> 749     dialect.initialize(c)
    750 finally:
    751     # note that "invalidated" and "closed" are mutually
    752     # exclusive in 1.4 Connection.
    753     if not c.invalidated and not c.closed:
    754         # transaction is rolled back otherwise, tested by
    755         # test/dialect/postgresql/test_dialect.py
    756         # ::MiscBackendTest::test_initial_transaction_state

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py:677, in PGDialect_psycopg2.initialize(self, connection)
    676 def initialize(self, connection):
--> 677     super().initialize(connection)
    678     self._has_native_hstore = (
    679         self.use_native_hstore
    680         and self._hstore_oids(connection.connection.dbapi_connection)
    681         is not None
    682     )
    684     self.supports_sane_multi_rowcount = (
    685         self.executemany_mode is not EXECUTEMANY_VALUES_PLUS_BATCH
    686     )

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\dialects\postgresql\base.py:3120, in PGDialect.initialize(self, connection)
   3117 # https://www.postgresql.org/docs/9.3/static/release-9-2.html#AEN116689
   3118 self.supports_smallserial = self.server_version_info >= (9, 2)
-> 3120 self._set_backslash_escapes(connection)
   3122 self._supports_drop_index_concurrently = self.server_version_info >= (
   3123     9,
   3124     2,
   3125 )
   3126 self.supports_identity_columns = self.server_version_info >= (10,)

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\dialects\postgresql\base.py:5004, in PGDialect._set_backslash_escapes(self, connection)
   5001 def _set_backslash_escapes(self, connection):
   5002     # this method is provided as an override hook for descendant
   5003     # dialects (e.g. Redshift), so removing it may break them
-> 5004     std_string = connection.exec_driver_sql(
   5005         "show standard_conforming_strings"
   5006     ).scalar()
   5007     self._backslash_escapes = std_string == "off"

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\base.py:1783, in Connection.exec_driver_sql(self, statement, parameters, execution_options)
   1778 execution_options = self._execution_options.merge_with(
   1779     execution_options
   1780 )
   1782 dialect = self.dialect
-> 1783 ret = self._execute_context(
   1784     dialect,
   1785     dialect.execution_ctx_cls._init_statement,
   1786     statement,
   1787     None,
   1788     execution_options,
   1789     statement,
   1790     distilled_parameters,
   1791 )
   1793 return ret

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\base.py:1850, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1848     return self._exec_insertmany_context(dialect, context)
   1849 else:
-> 1850     return self._exec_single_context(
   1851         dialect, context, statement, parameters
   1852     )

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\base.py:1990, in Connection._exec_single_context(self, dialect, context, statement, parameters)
   1987     result = context._setup_result_proxy()
   1989 except BaseException as e:
-> 1990     self._handle_dbapi_exception(
   1991         e, str_statement, effective_parameters, cursor, context
   1992     )
   1994 return result

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\base.py:2357, in Connection._handle_dbapi_exception(self, e, statement, parameters, cursor, context, is_sub_exec)
   2355 elif should_wrap:
   2356     assert sqlalchemy_exception is not None
-> 2357     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
   2358 else:
   2359     assert exc_info[1] is not None

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\base.py:1971, in Connection._exec_single_context(self, dialect, context, statement, parameters)
   1969                 break
   1970     if not evt_handled:
-> 1971         self.dialect.do_execute(
   1972             cursor, str_statement, effective_parameters, context
   1973         )
   1975 if self._has_events or self.engine._has_events:
   1976     self.dispatch.after_cursor_execute(
   1977         self,
   1978         cursor,
   (...)
   1982         context.executemany,
   1983     )

File ~\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\engine\default.py:919, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    918 def do_execute(self, cursor, statement, parameters, context=None):
--> 919     cursor.execute(statement, parameters)

ProgrammingError: (psycopg2.errors.UndefinedObject) unrecognized configuration parameter "standard_conforming_strings"

[SQL: show standard_conforming_strings]
(Background on this error at: https://sqlalche.me/e/20/f405)

```
```


### Issue description

Attempting to use write_database to connect to a Redshift database results in an UndefinedObject error related to an unrecognized configuration parameter "standard_conforming_strings". This occurs during the initialization of the PostgreSQL dialect within SQLAlchemy, which Polars seems to utilize indirectly through Pandas' to_sql method.

### Expected behavior

The write_database command should successfully establish a connection to the Redshift database and either create or replace the specified table without errors related to database configuration parameters.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.18
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  0.11.0
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            0.16.4
fastexcel:            0.10.2
fsspec:               2023.12.2
gevent:               24.2.1
hvplot:               0.9.2
matplotlib:           3.7.2
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.0.10
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             2.6.4
pyiceberg:            0.6.0
pyxlsb:               <not installed>
sqlalchemy:           2.0.29
xlsx2csv:             0.8.2
xlsxwriter:           3.2.0```

</details>

### LINKED ISSUE #16053: write_database() - Insert many rows with sql server using fast_executemany
### Description

I would like to be able to insert many rows quickly in an sql server database table with df.write_database()

I can currently achieve this with the **fast_executemany** option in pandas but I can’t find a way to do this with polars.write_database() which only accepts a connection string and not an sql alchemy engine. The pandas code is much faster than the polars equivalent without fast_executemany.

**Example code with pandas:**
engine = create_engine(
        "mssql+pyodbc://{user}:{password}@{server}/{db_name}?driver=ODBC+Driver+17+for+SQL+Server",
        **fast_executemany=True**,
    )
ret = curve.to_pandas().to_sql(
        name="curve",
        con=engine,
        if_exists="append",
        index=False,
    )

**Example code with polars:**
curve.write_database(
    table_name="curve",
    connection="mssql+pyodbc://{user}:{password}@{server}/{db_name}?driver=ODBC+Driver+17+for+SQL+Server",
    if_table_exists="append",
    engine="sqlalchemy",
)

### LINKED ISSUE #16095: Bug report when using hive2 write_database
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```
from sqlalchemy import *
from sqlalchemy.engine import create_engine
from sqlalchemy.schema import *
import polars as pl
from pyhive import hive

### polars code
conn_url = 'hive://username:password@localhost:port/database'
engine = create_engine(conn_url)

sample_df = pd.DataFrame({"colA":[90,23,42], "colB":["kill","oks","hello"]})
### Pandas to_sql code works because of the index=False, method='multi'
sample_df.to_sql("sample_table", con=engine, index=False, method='multi')
### However polars fails when doing write_database
sample_df_pl.write_database(table_name="sample_table", connection=conn_url)

### Log output

```shell
File ~\AppData\Local\anaconda3\envs\awsenv\lib\site-packages\pyhive\hive.py:496, in Cursor._fetch_more(self)
    494 assert(self._operationHandle is not None), "Should have an op handle in _fetch_more"
    495 if not self._operationHandle.hasResultSet:
--> 496     raise ProgrammingError("No result set")
    497 req = ttypes.TFetchResultsReq(
    498     operationHandle=self._operationHandle,
    499     orientation=ttypes.TFetchOrientation.FETCH_NEXT,
    500     maxRows=self.arraysize,
    501 )
    502 response = self._connection.client.FetchResults(req)

ProgrammingError: (pyhive.exc.ProgrammingError) No result set
[SQL: INSERT INTO TABLE `sample_table` VALUES (%(colA)s, %(colB)s)]
[parameters: [{'colA': 90, 'colB': 'kill'}, {'colA': 23, 'colB': 'oks'}, {'colA': 42, 'colB': 'hello'}]]
```

### Issue description

Pandas to_sql works, but polars write_database doesn't

### Expected behavior

should be working since pandas to_sql works too

### Installed versions

--------Version info---------
Polars:               0.20.23
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.10.14 | packaged by Anaconda, Inc. | (main, Mar 21 2024, 16:20:14) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.5.6
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.29
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #16095.
Closes #16053.
Closes #15538.

Also: ref #7852.

---

So, The Great Database Write Rewrite™ is still pending, but this PR closes a number of outstanding Issues and enables various opt-in speedups to ensure that we can take better advantage of the underlying engines that we currently call into.

ℹ️ This is a non-breaking change; all existing usage is unaffected.

## Updates

* Can now supply an instantiated SQLAlchemy or ADBC connection directly; no longer limited to passing just the URI.
* This allows such connections to be established with specific optimisations, such as `fast_executemany` for pyodbc mssql connections, and other per-connection configuration parameters.
* Adds a new `engine_options` parameter that gets passed down to the chosen engine's underlying insert method (eg: pandas' `to_sql` if using SQLAlchemy, or `adbc_ingest` if using ADBC).

## Examples

Establish a pyodbc connection using "fast_executemany=True" and insert using that:
```python
from sqlalchemy import create_engine
import polars as pl

pyodbc_uri = (
    "mssql+pyodbc://user:pass@server:1433/test?"
    "driver=ODBC+Driver+18+for+SQL+Server"
)
conn = create_engine(pyodbc_uri, fast_executemany=True)

df.write_database(
    table_name="target_table",
    connection=conn,
)
```
Use a regular URI connection and pass "method='multi'" down to the `to_sql` insert method:
```python
df.write_database(
    connection="hive://user:pass@server:port/database",
    table_name="target_table",
    engine="sqlalchemy",
    engine_options={"method": "multi"},
)
```

### CODE REVIEW

**Review by ritchie46 — APPROVED** [review]

**Comment by ritchie46** [comment]
> So, The Great Database Write Rewrite™ is still pending

I want your magic on this one so bad! ^^

> Closes https://github.com/pola-rs/polars/issues/16095.
> Closes https://github.com/pola-rs/polars/issues/16053.
> Closes https://github.com/pola-rs/polars/issues/15538.
> Also: ref https://github.com/pola-rs/polars/issues/7852.

Quite some birds in one stone. :clap:

**Comment by ma-dentalcorp** [comment]
Thank you for the updates. To confirm, these updates are not yet available, right?
I upgraded my polars to latest version 0.20.25 but can't seem to use these features yet.

**Comment by alexander-beedie** [comment]
> @alexander-beedie Thank you for the updates. To confirm, these updates are not yet available, right?

Correct - coming in `0.20.26` (soon) ;)

**Comment by MrAlexBailey** [comment]
Do you need a documentation update for this? Happy to make a PR if so.

**Comment by alexander-beedie** [comment]
> Do you need a documentation update for this? Happy to make a PR if so.

@MrAlexBailey An update to the User Guide docs would be very welcome! (The function docstring itself has some examples/explanation, but a guide entry with more detail would be great 😎)

**Pull request merged**
