### PR TITLE
feat(rust, python): thousand separators in shape of repr `DataFrame`

### LINKED ISSUE #7706: Thousand separators in shape from print(DataFrame)
### Problem description

Hi,
All is in the title. 
That would be nice in order to quickly differentiate between 100M and 10M rows datasets for example. 
Comma between height and width would need to be changed to something else (like "x" maybe?). 
Thanks a lot,
Cam

### PR DESCRIPTION
**Pull request by advoet**
Resolves #7706.

Hello, I'm new to rust and contributions to open source. Thank you for the review!

I implemented this feature using the number formatting crate: https://docs.rs/num-format/latest/num_format/#
 - Appears for example as `shape: (100,000 x 200)`
 - Added formatting to series shape display, but left the comma `shape: (100,000,)`
 - Updated documentation via regex search - `shape: \((\d), (\d)\)` -> `shape: ($1 x $2)`

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Thanks for the PR :)
Looking at the updated reprs, I'm not quite sure about the new format - let's have a quick think...

* `shape(1234567, 1500)` (current)
* `shape(1,234,567 x 1,500)` (this PR)
* `shape(1_234_567, 1_500)` (better; still?)

I'm leaning towards the third, as it is still a tuple that would be valid Rust/Python if written out (admittedly this is just a repr, but the correspondence is nice...) @ritchie46, @stinodego, what do you think?

**Comment by cbzittoun** [comment]
I actually agree with your suggestion Alexander, then you can quickly copy/paste it and have a valid tuple of ints in pyhton.

**Comment by advoet** [comment]
Sorry for the commit spam, I had neglected to run `make pre-commit`.

@alexander-beedie - I removed the extra dependency, following https://stackoverflow.com/a/67834588.
Added these two methods in `fmt.rs`
 - `fn fmt_uint(num: &usize) -> String`
 - `fn fmt_df_shape((shape0, shape1): &(usize, usize)) -> String`
 
 Bonus that the "_" formatting is compatible with your `from_repr` branch :)

**Comment by alexander-beedie** [comment]
> Sorry for the commit spam, I had neglected to run make pre-commit.

Not to worry, we have a "squash " button ;)

> I removed the extra dependency

That's looking _significantly_ cleaner, thanks - also a much smaller overall diff 👍 

@ritchie46, @stinodego: seems good to me now... any final thoughts?

**Review by stinodego — APPROVED** [review]
Good addition, in my opinion!

**Comment by ritchie46** [comment]
Thanks!

**Pull request merged**
