### PR TITLE
Fix feature name

### PR DESCRIPTION
**Pull request by chatblanc-ciel**
# Problems(#11178)

- a difference in feature name on [UserGuide](https://pola-rs.github.io/polars/user-guide/expressions/strings/#extract-a-pattern)
- a difference in feature name on [Docs(Rust)](https://pola-rs.github.io/polars/docs/rust/dev/polars_lazy/dsl/string/struct.StringNameSpace.html#method.replace_all)

# Change

- API_REFERENCE_LINK
- [polars-plan] Add feature name wrapper for `regex`

### CODE REVIEW

**Comment by chatblanc-ciel** [comment]
# previous
スクリーンショット (26)

# purpose
スクリーンショット (25)

**Comment by ritchie46** [comment]
I don't understand why we need those changes? What was wrong with regex feature name in the docs?

**Comment by chatblanc-ciel** [comment]
> I don't understand why we need those changes? What was wrong with regex feature name in the docs?

The user will look at the docs and user guide to add the feature, and since the feature name is being changed in the polars package, the docs and other notations must also match or there will be confusion because the `regex` feature will not be found.
Now, polars has `lazy_regex` not `regex`.

**Comment by stinodego** [comment]
Thanks for the PR, but I think we should go the other way (rename to `lazy_regex` to `regex`). I opened a PR for that and will close this one.

Thank you for signalling this issue and taking the initiative!

**Pull request closed without merging**
