### PR TITLE
feat(rust, python): Add `literal` for str count_match

### PR DESCRIPTION
**Pull request by reswqa**
This PR is committed to solve #10930. But not supports `extract_xxx` as I'm not very clear how to define a `match group` well in this `literal` mode, especially for `str.extract_groups()`.

### CODE REVIEW

**Comment by orlp** [comment]
@reswqa Good point, it doesn't make sense to have a `literal` argument for the extract functions. So that's fine to leave them out.

**Comment by ritchie46** [comment]
Can you do a rebase?

**Comment by reswqa** [comment]
Ok, rebased. But seems that our pipeline encountered some issues related to `pyarrow` or `pandas`.

**Comment by ritchie46** [comment]
Yes, that seems unrelated to this PR. Thanks for the fix. :)

**Pull request merged**
