### PR TITLE
improve drop_duplicates/distinct

### PR DESCRIPTION
**Pull request by ritchie46**
Change the name from `drop_duplicates` to `distinct`
and add a `keep` argument that indicates which value
must be kept. For now the options are `first` and `last`

### CODE REVIEW

**Comment by iisri-vu** [comment]
Why change, this break transition from pandas.

**Comment by ritchie46** [comment]
Sure, but we never aimed to be compatible with pandas. We aim to make an API that is best for polars.

**Comment by iisri-vu** [comment]
Then I think it is not a single change in the import as advertised.

**Comment by ritchie46** [comment]
> Then I think it is not a single change in the import as advertised.

Where is this advertised?

**Pull request merged**
