### PR TITLE
fix(rust, python): fix rename + projection pushdown

### LINKED ISSUE #10595: Bug: ColumnNotFound error when renaming LazyFrame
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

lf = pl.LazyFrame(
    schema={
        "a": pl.Int32,
        "b": pl.Int32,
    },
    data=[
        [121, None],
        [122, 123],
        [123, None],
    ],
    orient="row",
)

mapping = (
    lf
    .select("a", "b")
    .rename({"b": "a", "a": "b"})
)

lf = (
    lf
    .drop("b")
    .join(mapping, on="a", how="left")
)
display(lf.collect()) # <- works
display(lf.select("a").collect()) # <- fails!
```

Error message:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ColumnNotFound(ErrString("a"))'
```

### Issue description

Should return dataframe without error.

It does work when you collect-lazify the mapping like below:

```python
mapping = (
    lf
    .select("a", "b")
    .rename({"b": "a", "a": "b"})
    .collect().lazy() # <- Collect-lazify here
)

lf = (
    lf
    .drop("b")
    .join(mapping, on="a", how="left")
)
display(lf.collect()) # <- works
display(lf.select("a").collect()) # <- works
```

### Expected behavior

Should return dataframe without error.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           0.10.0
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.25.1
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            2.1.1
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #10595

### CODE REVIEW

**Comment by reswqa** [comment]
Nice fix! 

BTW, I have a little concern about the case without optimization.

https://github.com/pola-rs/polars/blob/a75495ac1a4c6844ee82ba12f00ba9d6849b14a6/crates/polars-plan/src/logical_plan/functions/rename.rs#L31-L39

Looks like `rename_schema` seems to generate incorrect order when swapping fields. 🤔

**Comment by ritchie46** [comment]
Hmm... Is that panic dur to changes in this PR? Otherwise we have to fix that in a separate one. 

Swapping renames bite me more often. :/

**Comment by reswqa** [comment]
> Hmm... Is that panic dur to changes in this PR?

No, that panic is not introduced by this change. I am bringing it up here because the test case that can reproduce it is almost the same as in this PR, with the only difference being that optimization is turned off. 

> Otherwise we have to fix that in a separate one.

That's make sense! I will open a separate issue to cover it.

**Comment by ritchie46** [comment]
> That's make sense! I will open a separate issue to cover it.

Thanks!

**Pull request merged**
