### PR TITLE
feat(python): add `to_repr` methods to DataFrame and Series

### PR DESCRIPTION
**Pull request by ghuls**

### CODE REVIEW

**Comment by ghuls** [comment]
Closes: https://github.com/pola-rs/polars/issues/7732

@alexander-beedie I also added missing`pl.from_repr` documentation link.

**Comment by alexander-beedie** [comment]
I'm trying to come up with a different name for "to_repr", as it's not the actual repr. 

Something like "df.to_init_repr()" or "pl.to_init_repr(df)"? Distinguishes it a little better.

**Comment by ritchie46** [comment]
> I'm trying to come up with a different name for "to_repr", as it's not the actual repr.

Yes, I agree. I think `to_init_repr` is better. :+1:

**Comment by ghuls** [comment]
> I'm trying to come up with a different name for `to_repr`, as it's not the actual repr.
> 
> Something like `df.to_init_repr()` or `pl.to_init_repr(df)` instead?

I am fine with changing the name, but can you explain me why it is not the actual repr?

As far as I know `__repr__` functions should construct a string that can reinstate the object.
```python
import numpy as np

In [9]: a = np.array([[48984, 4894], [4568, 48968], [468135, 49849]])

In [10]: a.__repr__()
Out[10]: 'array([[ 48984,   4894],\n       [  4568,  48968],\n       [468135,  49849]])'

In [11]: print(a.__repr__())
array([[ 48984,   4894],
       [  4568,  48968],
       [468135,  49849]])

In [13]: from numpy import array

In [14]: eval(a.__repr__())
Out[14]: 
array([[ 48984,   4894],
       [  4568,  48968],
       [468135,  49849]])
```

Do you plan to find another name for `pl.from_repr` too?

**Comment by alexander-beedie** [comment]
> I am fine with changing the name, but can you explain me why it is not the actual repr?
> As far as I know `__repr__` functions should construct a string that can reinstate the object.

The result from an object's `repr` is defined specifically as _"a string containing a **printable representation** of an object."_ So, something useful/informative that can reasonably be returned in the console, logs, etc that _represents_ the object. 

Now, for many types it is _also_ a good idea to make the repr usable as if you could eval/init it (and on any smaller-scale custom types I develop at work I make the effort to do so too); also from the python docs: _"for **many** types, this function makes an attempt to return a string that would yield an object with the same value when passed to eval()"_ (but note the use of "many", not "all").

Objects like DataFrames (or anything else that fronts large data) don't usually return eval-style reprs because anything other than the most trivial of frames would return and absurdly large string, rendering it unprintable and/or not useful. Polars doesn't, Pandas doesn't, PyArrow doesn't, DB interfaces don't, etc. The general trend in these cases is to have a partial table representation that provides some useful sense of the object (size, col, some data, and so on).

> Do you plan to find another name for `pl.from_repr` too?

No - because `from_repr` _does_ parse the repr, exactly as advertised ;)

**Comment by ghuls** [comment]
> The result from an object's `repr` is defined specifically as _"a string containing a **printable representation** of an object[1](#user-content-fn-1-84c12975897ea446d8aca11efcefe266)."_ So, something useful/informative that can reasonably be returned in an interactive console, notebook, logs, etc.

I thought that `__str__` was meant for that. (although for a lot of objects `__str__` and `__repr__` is the same.

**Pull request merged**
