### PR TITLE
python polars 0.16.17

### PR DESCRIPTION
**Pull request by ritchie46**

### CODE REVIEW

**Comment by ritchie46** [comment]
failing test is fixed in #7907

**Comment by stinodego** [comment]
Does this mean we can start merging breaking stuff? 😄

**Comment by ritchie46** [comment]
> Does this mean we can start merging breaking stuff? 😄

Let's wait the weekend, so we can patch regressions. Monday your can go break stuff 😉

**Comment by stinodego** [comment]
Deal 🤝

**Comment by alexander-beedie** [comment]
I'm up in Dubai for the weekend; family in town! Don't break too much stuff without me 🤣

**Pull request merged**
