### PR TITLE
fix(python,rust): Compute Spearman rank correlations using average ra…

### PR DESCRIPTION
**Pull request by zundertj**
…nk for ties

Fixes https://github.com/pola-rs/polars/issues/9407.

### CODE REVIEW

**Comment by stinodego** [comment]
@zundertj It seems weird to me that Spearman rank correlation should be `Float32`, while Pearson is `Float64`. This should probably be fixed?

**Comment by zundertj** [comment]
The reason this is now different vs before is because if we pass in all integers, the correlation calculation is a different code path vs floats. Now that we change from Rank + Min to Rank + Average the values after ranking are no longer integers but Float32. I didn't change that, because I thought it was done like that on purpose. I.e., if you pass in Float32's from Python, you get a Float32 out:

```python
>>> df
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ f32 ┆ f32 │
╞═════╪═════╡
│ 1.5 ┆ 4.3 │
│ 2.3 ┆ 2.1 │
└─────┴─────┘
>>> df.select(pl.corr("a","b"))
shape: (1, 1)
┌──────┐
│ a    │
│ ---  │
│ f32  │
╞══════╡
│ -1.0 │
└──────┘
```


Do you mean that we should always return `Float64`, i.e. cast after the rank + average to Float64?

**Comment by qqlearn123** [comment]
What was the behavior previously?

**Comment by zundertj** [comment]
Spearman returned Float64 before, as it did a rank, which leads to integers, not floats, as we took the min, not the average, and then the code path returns Float64. This is in line with directly computing Pearson on Python int (32) currently, and imo it makes sense to keep the consistency here as Spearman = ranking + Pearson.

**Comment by qqlearn123** [comment]
Do you think making current behavior the same as before reasonable?

**Pull request merged**
