### PR TITLE
docs(python): show `datetime.date` import in code block

### LINKED ISSUE #13418: Possible deprecated use of .year  in "aggregations"
### Description

Looking at the Expressions/Aggregations/Filtering section, the "compute_age" function doesn't work in `0.19.19`.
```Python
def compute_age() -> pl.Expr:
    return date(2021, 1, 1).year - pl.col("birthday").dt.year()
```
 There are a few things here - there is no `date` object found (use `pl.date` instead), and the `pl.date` object has no `.year` method. I found this function worked but get quite different results from the current docs (which are probably outdated calls from that url). 

```Python
def compute_age() -> pl.Expr:
    return pl.date(2021, 1, 1)..year() - pl.col("birthday").dt.year()
```

### Link

https://docs.pola.rs/user-guide/expressions/aggregation/#filtering

### PR DESCRIPTION
**Pull request by mcrumiller**
Resolves #13418.

The "proper" age calculation looks pretty messy with the standard black formatter but the old formula, while simple, was incorrect.

Also, this points out that the imports used in the setup blocks of our code snippets aren't rendered in the documentation (note the word "import" isn't found anywhere in the [doc page](https://docs.pola.rs/user-guide/expressions/aggregation)). This caused me confusion when I first came to polars, as our code snippets used modules without any mention of importing them.

### CODE REVIEW

**Review by stinodego — CHANGES_REQUESTED** [review]
Showing the import is good. But implementing an exact age calculation is just not what this example is for. You're taking away from what the example is trying to convey. Implementing an exact formula is best left as an exercise for the reader.

**Comment by mcrumiller** [comment]
@stinodego fair enough. I'll revert the code block and update the title.

**Comment by mcrumiller** [comment]
@stinodego I kept the `date.today()` to at least keep the example current (showing 2021 makes it look like we haven't touched the docs in 3 years!).

**Review by stinodego — APPROVED** [review]
Thanks!

**Pull request merged**
