### PR TITLE
Modern style type hints

### LINKED ISSUE #3862: Utilize new type hinting functionality through `__future__` import
Now that we no longer support Python 3.6, we can use the new type hinting functionality introduced in Python 3.9/3.10/3.11 by using `from __future__ import annotations`.

Some of the nice new things:
* Type hints are automatically stringified "behind the scenes". Especially handy in this code base with lots of circular stuff.
* `List`, `Tuple`, `Dict`, etc. are now available using the built-in types `list`, `tuple`, `dict`. No imports needed and we no longer get the ambiguity with polars' `List` type.
* You can use the pipe operator for Optionals/Unions, e.g.: `columns: ColumnsType | None = None`

With your permission I'd like to update the existing type hints to the new style.

### PR DESCRIPTION
**Pull request by stinodego**
Fixes #3862 

Changes:
* Ran [pyupgrade](https://github.com/asottile/pyupgrade) to automatically update all type hints as described in the linked issue. _(Good candidate for inclusion in the CI pipeline, by the way.)_
* Removed unused typing imports
* Fixed imports of polars' `List` type (no workaround necessary anymore)
* The new style type hint causes an issue in the `Expr` class: this class implements a `list` method, at which point `mypy` becomes confused with the `list` built-in generic type. This is [expected behaviour](https://github.com/python/mypy/issues/13050). I reverted to using `List` from the `typing` module for this file.

**Welcome to the `__future__` 😎**

### CODE REVIEW

**Comment by ghuls** [comment]
I think some type hints need to stay quoted as they are not always imported (e.g. pandas, pyarrrow and  soon numpy).

@zundertj changed some of them in the past for this reason, if I am not mistaken.

At least it doesn't look like it autostringifies them in python 3.10:

```python
In [91]: import typing

In [92]: def test_df(df: pd.DataFrame) -> None:
    ...:     pass
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [92], in <module>
----> 1 def test_df(df: pd.DataFrame) -> None:
      2     pass

NameError: name 'pd' is not defined

In [93]: def test_df(df: "pd.DataFrame") -> None:
    ...:     pass
```

**Comment by stinodego** [comment]
> At least it doesn't look like it autostringifies them in python 3.10:

This 'autostringify' feature was supposed to come in Python 3.10, but ended up being postponed. It is still available by using `from __future__ import annotations`, however. You can get the full story in [this StackOverflow reply](https://stackoverflow.com/a/33533514/2344703).

**Comment by ghuls** [comment]
Thanks. That worked. I assumed it wouldn't be needed on python 3.10.

**Comment by ritchie46** [comment]
> Welcome to the __future__ 😎

😁

Thanks a lot! Really nice that we can use more modern syntax on this.

There is a conflicting file. Could you rebase? Then I merge it in.

**Comment by stinodego** [comment]
Rebased, should be good to go!

**Comment by zundertj** [comment]
Great work @stinodego ! When I worked on the type annotations in the past, it was not exactly clear how the behavior of `from __future__ import annotations` would end up in Python 3.11, hence this was not pushed through at the time. Glad that with 3.11 betas being rolled out, we can now make this change, big improvement for the code base.

**Comment by cnpryer** [comment]
Unfortunately status quo isn't changing in 3.11.

https://mail.python.org/archives/list/python-dev@python.org/message/VIZEBX5EYMSYIJNDBF6DMUMZOCWHARSO/

**Comment by stinodego** [comment]
The status is indeed still not quite decided, as far as I know. But I feel the current functionality available in the `__future__` module makes most sense for polars at this point.

Whatever decision will be made in the future - we can always revert to quoting stuff. I trust `pyupgrade` to change behaviour if the course changes. And otherwise I trust my search & replace skills :)

**Comment by zundertj** [comment]
I meant that the status-quo is not changing; that seemed more likely 8 months ago. Completely agree on no longer waiting and making the change.

**Pull request merged**
