### PR TITLE
feat(rust): Add configuration option for where Polars spills to disk 

### LINKED ISSUE #9832: Add configuration option for where Polars spills to disk
### Problem description

Some streaming operations may spill to disk. We should be able to control where this happens.

For example, we may have an environment variable called `POLARS_SPILL_DIR` that controls this setting.

Spark has something similar called `SPARK_LOCAL_DIRS` (see [StackOverflow](https://stackoverflow.com/questions/64343372/how-to-configure-where-spark-spills-to-disk)).

### PR DESCRIPTION
**Pull request by dmitrybugakov**
Closes #9832 

Implemented the ability to configure the disk spill path in Polars through the POLARS_SPILL_DIR environment variable. This change allows users to specify a custom directory for Polars to spill data to disk during heavy streaming operations (#9832)

### CODE REVIEW

**Review by stinodego — CHANGES_REQUESTED** [review]
Thanks for the PR!

Could you please add some dedicated tests on the Python side (e.g. set the env variable, check that the data actually ends up there)?

**Comment by alexander-beedie** [comment]
@stinodego: Anywhere else we  currently (or might in the future) use a temp dir? If so, should consider naming `POLARS_TEMP_DIR` instead 🤔

**Comment by stinodego** [comment]
> @stinodego: Anywhere else we currently (or might in the future) use a temp dir? If so, might want to consider naming `POLARS_TEMP_DIR` instead, to account for additional uses 🤔

I _think_ the only time we write to disk unannounced is when spilling. I'd prefer to have the environment variable be specific to this use case if at all possible. If needed we can make a more generic variable later.

**Comment by ritchie46** [comment]
I can foresee this to be done later to cache or store indexes. I'd prefer `POLARS_TEMP_DIR` for this reason.

**Comment by alexander-beedie** [comment]
> I can foresee this to be done later to cache or store indexes. I'd prefer `POLARS_TEMP_DIR` for this reason.

Nice; and we can always introduce special-purpose subdirs _within_ the main temp dir to differentiate usage (eg: "spill", "index", etc) if we want.

**Comment by ritchie46** [comment]
thank you @dmitrybugakov

**Comment by Galedon1** [comment]
Hi, I have found this thread and it is exactly what I need, but I failed to find any docs about how to actually use it (I am still beginner in programming). How to change the disk spill path in python polars?

**Comment by stinodego** [comment]
Set the environment variable `POLARS_TEMP_DIR` to the desired path.

**Pull request merged**
