### PR TITLE
feat(python): Add `writable` flag to `DataFrame.to_numpy`

### PR DESCRIPTION
**Pull request by dannyfriar**
Closes https://github.com/pola-rs/polars/issues/14519
Ref https://github.com/pola-rs/polars/issues/14334

### CODE REVIEW

**Review by stinodego — CHANGES_REQUESTED** [review]
Adding a `writable` (note: `writable`, not `writeable`) flag is a good idea. Please see `Series.to_numpy` on how to implement it.

**Comment by ritchie46** [comment]
This isn't ok. We cannot set viewed memory as writeable. That means numpy will write to polars immutable data?!

**Comment by stinodego** [comment]
> This isn't ok. We cannot set viewed memory as writeable. That means numpy will write to polars immutable data?!

It should be implemented like in `Series.to_numpy`: after creating the numpy array, if it isn't writable, make a copy.

**Comment by ritchie46** [comment]
Yeap, that would be fine.

**Comment by dannyfriar** [comment]
Ok makes sense, I will  make the change

**Review by stinodego — APPROVED** [review]
Thanks!

**Pull request merged**
