### PR TITLE
chore(python): Rename read_parquet arg `source` to `file`

### PR DESCRIPTION
**Pull request by stinodego**
To be consistent with the other I/O methods.

### CODE REVIEW

**Comment by zundertj** [comment]
I get the consistency argument, but isn't it odd to call it `file`, whilst it can also be a path to a directory?

**Comment by stinodego** [comment]
Not really; you generally call something a Parquet file, even if it's partitioned into many parts on disk.

But I agree that `source` isn't really that bad of a name. But then for read_csv I think file is better. Naming stuff is hard.

**Comment by ritchie46** [comment]
IMO source is best as it leaves room for new features like reading from bytes or the web.

**Comment by alexander-beedie** [comment]
> IMO source is best as it leaves room for new features like reading from bytes or the web.

In theory this equally applies to CSV/etc; we could be reading the CSV out of an s3 bucket, ftp link, bytes... Maybe we should actually standardise on `source` for _all_ of the I/O methods?

**Comment by stinodego** [comment]
I think that's indeed the way to go.

**Comment by stinodego** [comment]
Closing this for now, will make a new PR when I get to it.

**Pull request closed without merging**
