### PR TITLE
feat: Add IEJoin algorithm for non-equi joins and support Full non-ecqui joins

### PR DESCRIPTION
**Pull request by adamreeve**
Relevant issues:
* #10068
* #4206
* #4207

This adds a new `IEJoin` join type to the Rust library, based on the paper by [Khayyat et al.](https://vldb.org/pvldb/vol8/p2074-khayyat.pdf) and the DuckDB article on [range joins](https://duckdb.org/2022/05/27/iejoin.html). It handles joins that use two inequality expressions.

How to represent this in the user-facing Python API is still an open question, so I'm opening this as a draft PR to hopefully start some discussion on that.

I've initially exposed the IEJoin type fairly directly with a new `inequality_join` method that expects two inequality expressions in the form of `lhs_expression op rhs_expression`, where op is one of <, <=, > or >=. This might be a bit too complicated and error-prone though, so I've also added a `join_between` method as an example higher level method that matches a value in one table with a range/interval from another table. We'd probably also want to add at least a couple of other methods to cover the subtypes listed in #10068: one method for matching on overlapping ranges and another method to match on values with some tolerance, maybe named `join_range` and `band_join` for example.

I'm not sure whether the current `inequality_join` method should be exposed as-is. It can express more generic join conditions, but it might be best to keep this private and aim to eventually add a more flexible API that can handle arbitrary join expressions, eg. something like what's suggested in #4207 or https://github.com/pola-rs/polars/issues/10068#issuecomment-1649948380.

There are also some additional features and improvements that could be added but I think should be separate PRs:
* Implementing multi-threading by breaking up each side of the join into blocks (section 5 from Khayyat et al.)
* Allow additional equality join conditions like the `by` parameters of [join_asof](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.join_asof.html)
* Support streaming mode

### CODE REVIEW

**Comment by deanm0000** [comment]
@adamreeve you need to change the title of this so that "add" is capitalized and then "pull request labeler" will pass. They do that because the version change summary scrapes the PR titles so it looks bad to have some bullet points that are lower case and some that are capitalized.

**Comment by ritchie46** [comment]
Thanks a lot @adamreeve. I will pick this up. What I really want to add first is the parallel groups and then I need to think about the interface for a bit. As Ideally I'd like this to work with expressions in the default join.

**Comment by ritchie46** [comment]
Thanks a lot @adamreeve. This turned out great with full non-equi join support.

**Comment by orlp** [comment]
@adamreeve Why did you add `--no-build` to `make requirements` in this PR?

**Comment by adamreeve** [comment]
Hi @orlp, that was actually changed by @ritchie46 in 2a1e78cd059a2d62d3ecc3e1bd9ea027352689d9, I'm not sure why that was needed and if it was intentional.

**Pull request merged**
