### PR TITLE
test(python): Fix failing test

### PR DESCRIPTION
**Pull request by stinodego**
Closes https://github.com/pola-rs/polars/issues/11754

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
sorry just comment to say - please wait a second on this one, I'd like to check it if possible, I think there might an actual issue

**Comment by stinodego** [comment]
> sorry just comment to say - please wait a second on this one, I'd like to check it if possible, I think there might an actual issue

@MarcoGorelli I looked into it. The issue is this (it happens in the `is_between` call):

```python
s = pl.Series([datetime(2001, 1, 1)], dtype=pl.Datetime("ms"))
r = s.dt.offset_by("-1us")
print(r)
```
```
shape: (1,)
Series: '' [datetime[ms]]
[
        2001-01-01 00:00:00
]
```

Subsecond precision is disregarded. I thought about it, and there is really no other way to do it. The output type of an expression cannot depend on the data.

**Comment by MarcoGorelli** [comment]
yup, thanks - indeed, the issue is with the test itself

**Review by MarcoGorelli — APPROVED** [review]
thanks for fixing this, happy to get this in to avoid false positives in CI

**Pull request merged**
