### PR TITLE
feat(python): add is_integer

### PR DESCRIPTION
**Pull request by JoonHong-Kim**
it is in RUST polars but not in py-polars

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Makes sense; thanks :)

**Comment by stinodego** [comment]
Should it not technically be `is_integral`?

**Comment by ritchie46** [comment]
Doc entry? :)

**Comment by alexander-beedie** [comment]
> Doc entry? :)

I'm extending and adding one right now ;)

**Comment by alexander-beedie** [comment]
> Should it not technically be `is_integral`?

The Rust implementation has `is_integer`, so... we could either change both or (currently) have this one match that.

**Pull request merged**
