### PR TITLE
feat(python): Allow `sink_parquet` to write to cloud storage

### PR DESCRIPTION
**Pull request by svaningelgem**
The title says it all. The `sink_parquet_cloud` method wasn't available from within python yet.
Implemented it in this PR.

### CODE REVIEW

**Comment by svaningelgem** [comment]
@ritchie46 , you asked me to remind you in "a few days" about the writing of files if no movement, and as you were "@"-ing me, I assume you meant this PR?

**Comment by wtcross** [comment]
FWIW this feature has worked great for me.

**Comment by svaningelgem** [comment]
Hi @ritchie46 , @stinodego,

Is it possible to get this PR merged so Python users could enjoy the benefits of the streaming to a cloud target? It's available for rust users since forever and I'd very much like to use it from the python side as well.

Thanks

**Comment by stinodego** [comment]
This is something we want to support, but we do not want to go ahead with it right now. This type of functionality comes with a lot of potential bugs to iron out, and we have other priorities right now. We will keep this PR open and revisit it at a later point.

**Comment by svaningelgem** [comment]
Ok, let me know if I need to update it at that time.

**Comment by stinodego** [comment]
I'm closing this as we are not planning to merge this in the near future. This PR doesn't need to clutter up our PR list indefinitely. We can revisit this work when we do decide to add it. Thanks for your work.

Ref https://github.com/pola-rs/polars/issues/7675

**Pull request closed without merging**
