### PR TITLE
perf(python): Improve `Series.to_numpy` performance for chunked Series that would otherwise be zero-copy

### PR DESCRIPTION
**Pull request by stinodego**
Ref #16267

Instead of iterating over the values, we rechunk and create a writable view.

This regressed in https://github.com/pola-rs/polars/pull/16178 - now we get the best of both worlds with a writable array _and_ only a single, fast copy.

Performance of converting a chunked Series of 50 million float32s:
* Before: ~60ms
* After: ~25ms

I added some benchmark tests so that we may catch regressions here in the future.

### CODE REVIEW

**Comment by ritchie46** [comment]
Nice. I like this approach. :)

> I added some benchmark tests so that we may catch regressions here in the future.

Not entirely sure how the codspeed works, but are these tests ran by codspeed?

**Comment by stinodego** [comment]
> Not entirely sure how the codspeed works, but are these tests ran by codspeed?

Yes! You can see it here, 3 new benchmarks:
https://codspeed.io/pola-rs/polars/branches/to-np-copy-chunk

Also, I spotted a problem with this implementation for nested data, going to have another look before putting it in review again.

**Comment by ritchie46** [comment]
How does one register them then? A specific folder?

**Comment by stinodego** [comment]
> How does one register them then? A specific folder?

You just have to do `@pytest.mark.benchmark`. That's all. I made a dedicated benchmark folder because our tests require some data generation utilities and it's nice to have those in one place, but it doesn't have to be in there necessarily.

**Comment by stinodego** [comment]
I had to add an up-front check whether the Series has the right dtype / nested nulls, otherwise we could rechunk unnecessarily.

Should be good to go now, waiting for CI to turn green 🤞

**Review by ritchie46 — APPROVED** [review]

**Comment by rhshadrach-8451** [comment]
I'm seeing this raise in 0.20.27; it did not raise for me in 0.20.26. Is this expected?

```python
pl.concat(
    [
        pl.DataFrame({"a": [1, 1, 2], "b": [2, 3, 4]}),
        pl.DataFrame({"a": [1, 1, 2], "b": [2, 3, 4]}),
    ]
).to_numpy()
# PanicException: source slice length (3) does not match destination slice length (6)
```

I haven't confirmed it to be from this PR, but looked likely.

**Comment by rhshadrach-8451** [comment]
Apologies - jumped the gun here. #16288 looks more likely.

**Pull request merged**
