### PR TITLE
refactor(rust): Fixed a bunch of clippy warnings

### PR DESCRIPTION
**Pull request by rben01**
No meaningful gain except reducing noise in the problems pane of $EDITOR.

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks! Still one remaining. :)

**Comment by rben01** [comment]
The unused `SQRT_2`? I think that's a compiler bug — it's clearly used in the file and if you remove the import then it stops compiling. Probably related to using an item in a macro.

**Comment by rben01** [comment]
> > The unused `SQRT_2`? I think that's a compiler bug — it's clearly used in the file and if you remove the import then it stops compiling. Probably related to using an item in a macro.
> 
> You must put it behind a feature flag.

Of course, silly me, it's never the compiler.

**Comment by rben01** [comment]
Should be all set for merge now.

**Comment by ritchie46** [comment]
Great! Thanks!

**Pull request merged**
