### PR TITLE
feat(python): new hypothesis strategy that can generate data for `List` dtypes

### LINKED ISSUE #8138: Implement hypothesis strategies for nested types like pl.List(pl.Utf8)
### Problem description

Hypothesis is really useful for writing unit tests, but it seems like currently nested dtypes are not supported. 

```python
@given(df=dataframes(include_cols=columns(cols=2, dtype=[pl.List(pl.Int64), pl.List(pl.Utf8)]))) 
def test_my_code():
    ...
```

```python
E   hypothesis.errors.InvalidArgument: No strategy (currently) available for List(Int64) type
```

I'm writing some general code which should handle any kind of DataFrame, so these strategies would really help.

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #8138.

* Can now provide arbitrary `List` dtypes to the existing `dataframes` and `series` strategies in addition to the existing scalar dtypes; can be nested to "n" levels.

* New `create_list_strategy` parametric/hypothesis strategy allows for more explicit control over `List` generation, using the existing dtype strategies to populate the inner lists. Supports selecting list data from a fixed set of values, and can trivially be integrated into hypothesis `@composite` strategies to fine-tune the test data.

* Determine hypothesis profile via new `POLARS_HYPOTHESIS_PROFILE` environment variable.
  * If unset, uses "default" which runs our current standard of 100 iterations (fast: ~7 secs). 
  * If set to "max", will run 1,000 iterations (~35 secs)
  * If set to "ultra", will run 10,000 iterations (~4 mins 45 secs).
  * Can also set to a custom integer value to run "n" iterations. 

## Examples

**Pass `List` dtypes to existing `dataframes` strategy:**

_Easiest; treat lists just like any other dtype._

```python
from polars.testing.parametric import dataframes
import polars as pl

dataframes( 
    cols = 3, 
    min_size = 3, 
    allowed_dtypes = [
        pl.List(pl.Boolean),
        pl.List(pl.List(pl.UInt8)),
        pl.List(pl.List(pl.List(pl.Int8))),
    ],
).example()

# shape: (4, 3)
# ┌───────────────────────────────────┬───────────────────────────────────┬────────────────────────┐
# │ col0                              ┆ col1                              ┆ col2                   │
# │ ---                               ┆ ---                               ┆ ---                    │
# │ list[list[u8]]                    ┆ list[list[list[i8]]]              ┆ list[bool]             │
# ╞═══════════════════════════════════╪═══════════════════════════════════╪════════════════════════╡
# │ [[73, 218, … 242], [53, 0, … 46]… ┆ [[[20, 68], [95, -118, 8], … [-9… ┆ [true]                 │
# │ [[23, 99, … 193]]                 ┆ [[[-25, -29]]]                    ┆ [false]                │
# │ [[119, 171, 138], [218], … [183,… ┆ [[[-65, -37], [24, 19, 72]]]      ┆ [true, false, … false] │
# │ [[99], [107, 12]]                 ┆ [[[88, -104, … -24], [-127, 7], … ┆ [false]                │
# └───────────────────────────────────┴───────────────────────────────────┴────────────────────────┘
```

**Use `create_list_strategy`directly:**

_Custom - create unique lists of lists of known leap years with minimum size of 2._

```python
from polars.testing.parametric import create_list_strategy, dataframes, column

leap_year_lists = create_list_strategy(
    inner_dtype = pl.List(pl.Int16),
    select_from = [1992,1996,2004,2008,2012,2016,2020,2024],
    unique = True,
    min_size = 2,
)

dataframes(
    cols=[
        column("n", dtype=pl.UInt8),
        column("leap_year_lists", strategy=leap_year_lists),
    ],
).example()

# shape: (4, 2)
# ┌─────┬───────────────────────────────────┐
# │ n   ┆ leap_year_lists                   │
# │ --- ┆ ---                               │
# │ u8  ┆ list[list[i16]]                   │
# ╞═════╪═══════════════════════════════════╡
# │ 164 ┆ [[1996, 1996], [2020, 1996, … 20… │
# │ 205 ┆ [[2024, 2004], [2012, 2008], … [… │
# │ 198 ┆ [[1996, 2012, … 2012], [2016, 20… │
# │ 158 ┆ [[2016, 2016], [2012, 1996], … [… │
# └─────┴───────────────────────────────────┘
```

**Use `create_list_strategy` as part of a `@composite`:**

_Advanced - create a UInt8 dtype strategy as a hypothesis composite that generates pairs of small integer values in which the first is always less than or equal to the second._

```python
from polars.testing.parametric import create_list_strategy, dataframes, column
from hypothesis.strategies import composite

@composite
def uint8_pairs(draw, uints=create_list_strategy(pl.UInt8, size=2)):
    pairs = list(zip(draw(uints), draw(uints)))
    return [sorted(ints) for ints in pairs]

dataframes(
    cols = [ 
        column("colx", strategy=uint8_pairs()),
        column("coly", strategy=uint8_pairs()),
        column("colz", strategy=uint8_pairs()),
    ],
    size=3,
).example()

# shape: (3, 3)
# ┌─────────────────────────┬─────────────────────────┬──────────────────────────┐
# │ colx                    ┆ coly                    ┆ colz                     │
# │ ---                     ┆ ---                     ┆ ---                      │
# │ list[list[i64]]         ┆ list[list[i64]]         ┆ list[list[i64]]          │
# ╞═════════════════════════╪═════════════════════════╪══════════════════════════╡
# │ [[143, 235], [75, 101]] ┆ [[143, 235], [75, 101]] ┆ [[31, 41], [57, 250]]    │
# │ [[87, 186], [174, 179]] ┆ [[87, 186], [174, 179]] ┆ [[112, 213], [149, 221]] │
# │ [[23, 85], [7, 86]]     ┆ [[23, 85], [7, 86]]     ┆ [[22, 255], [27, 28]]    │
# └─────────────────────────┴─────────────────────────┴──────────────────────────┘
```

### CODE REVIEW

**Comment by alexander-beedie** [comment]
@stinodego: Now to start thinking about Struct dtypes?? 😅

**Comment by stinodego** [comment]
Good stuff @alexander-beedie ! Do we have decimals yet? 😄

**Comment by alexander-beedie** [comment]
> Good stuff @alexander-beedie ! Do we have decimals yet? 😄

Lol, not yet... but we will soon ;)

**Comment by alexander-beedie** [comment]
> Good stuff @alexander-beedie ! Do we have decimals yet? 😄

@stinodego: Initial version just committed: https://github.com/pola-rs/polars/pull/8430 😄

**Pull request merged**
