### PR TITLE
feat: support decimal in csv/json

### PR DESCRIPTION
**Pull request by flisky**

### CODE REVIEW

**Review by ritchie46 — CHANGES_REQUESTED** [review]

**Comment by JulianCologne** [comment]
Any update on this one? Would love to see more decimal support 😊

**Review by ritchie46 — COMMENTED** [review]
Sorry for the delay. Thank you for the PR. Looks good. Can you add some tests on the python side?

BTW, this will only support json, not csv.

**Comment by d-reynol** [comment]
@ritchie46 do you mind taking a look at this? Being able to write decimal to CSV would be quite useful

**Comment by JulianCologne** [comment]
Any progress here? 🤓

**Comment by flisky** [comment]
Rebased!

**Review by ritchie46 — APPROVED** [review]
Looks good. Thank you @flisky. Sorry for the delay here.

**Comment by d-reynol** [comment]
Thank you @ritchie46 !

**Pull request merged**
