### PR TITLE
Rust `cut()` refinement

### PR DESCRIPTION
**Pull request by hpux735**
Sorry for the churn, but after putting some time on the `cut` function, there is some refinement that was needed.  This just makes it accessible from the `prelude`, and also makes it work with both `Float32` and `Float64`.  Let me know if I should make it work with the Integer types, too.

### CODE REVIEW

**Comment by ritchie46** [comment]
>  Let me know if I should make it work with the Integer types, too.

I think we could accept a `Series` and cast that to float64. This way it works with all numeric types without the compilation costs. The cast is not expensive as I expect this to be called on a relatively small bins array right?

**Comment by hpux735** [comment]
Yes, I considered that, too.  I'll change that.

**Comment by ritchie46** [comment]
Any status on this one @hpux735?

**Comment by hpux735** [comment]
This got folded-into the histogram one.

**Pull request closed without merging**
