### PR TITLE
fix(python): Exclude functools wrapper frames in `find_stacklevel`

### LINKED ISSUE #11260: Wrong stacklevel from warning when constructing DataFrame with list
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import polars.selectors as cs 

from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

arr = [datetime(2020, 1, 1, tzinfo=ZoneInfo('Europe/London'))]*3
print(pl.Series(arr))
print(pl.DataFrame({'ts': arr}))
print(pl.DataFrame(arr))
```

### Log output

_No response_

### Issue description

Running the above, I get
```console
$ python t.py
/home/marcogorelli/tmp/t.py:8: TimeZoneAwareConstructorWarning: Constructing a Series with time-zone-aware datetimes results in a Series with UTC time zone. To silence this warning, you can filter warnings of class TimeZoneAwareConstructorWarning, or set 'UTC' as the time zone of your datatype.
  pl.Series(arr)
/home/marcogorelli/tmp/t.py:9: TimeZoneAwareConstructorWarning: Constructing a Series with time-zone-aware datetimes results in a Series with UTC time zone. To silence this warning, you can filter warnings of class TimeZoneAwareConstructorWarning, or set 'UTC' as the time zone of your datatype.
  pl.DataFrame({'ts': arr})
/usr/lib/python3.10/functools.py:889: TimeZoneAwareConstructorWarning: Constructing a Series with time-zone-aware datetimes results in a Series with UTC time zone. To silence this warning, you can filter warnings of class TimeZoneAwareConstructorWarning, or set 'UTC' as the time zone of your datatype.
  return dispatch(args[0].__class__)(*args, **kw)
```

### Expected behavior

That the last one also shows the warning from `t.py`

@alexander-beedie do you know what this might be due to?

### Installed versions

<details>

```

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.10.6.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.10.102.1-microsoft-standard-WSL2
Version             : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : en_GB.UTF-8
LOCALE              : en_GB.UTF-8

pandas              : 2.1.1
numpy               : 1.25.1
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 67.6.1
pip                 : 23.1.2
Cython              : None
pytest              : 7.3.1
hypothesis          : 6.82.4
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.13.2
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : 2023.7.0
fsspec              : 2023.6.0
gcsfs               : None
matplotlib          : 3.7.1
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 12.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.0
sqlalchemy          : 2.0.20
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
None

```

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Possibly resolves #11260.

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Diagnosis looks good (it's the `@singledispatch` wrappers that are interrupting the stack-level find, but maybe change it to the following check, which we can extend is/asnecessary:
```python
if fname.startswith(str(pkg_dir)) or re.match(
    # note: ignore @singledispatch wrappers
    r"singledispatch\..+wrapper", frame.f_code.co_qualname
):
```

**Review by alexander-beedie — CHANGES_REQUESTED** [review]
Diagnosis looks good (it's the `@singledispatch` wrappers that are interrupting the stack-level find), but maybe change it to use the following check, which we can easily extend (if/as necessary) by matching on a tuple of possibilities in the second `startswith`:
```python
if fname.startswith(str(pkg_dir)) or (
    (qualname := getattr(frame.f_code, "co_qualname", None))
    # note: ignore @singledispatch wrappers
    and qualname.startswith("singledispatch.")
):
```
(Side-note: while we're at it, can also pull out the `str` call against `pkg_dir` that currently sits inside the loop and have it outside, as `pkg_dir = str(Path(pl.__file__).parent)`).

**Comment by mcrumiller** [comment]
> can also pull out the str call against pkg_dir that currently sits inside the loop and have it outside

I had noticed this and forgot to do that :)

**Comment by mcrumiller** [comment]
@alexander-beedie this one should be good to go.

**Comment by MarcoGorelli** [comment]
cool, thanks for fixing this!

**Review by alexander-beedie — APPROVED** [review]

**Pull request merged**
