### PR TITLE
feat(python,rust): raise default frame/series repr height from 8 to 10

### PR DESCRIPTION
**Pull request by alexander-beedie**
Very minor change, but I received a few comments about this recently and I tend to agree with the idea. It is simply a small adjustment to favour the common case of being intrinsically more interested in a top 10 than a top 8.

Let's see what everyone thinks ;)

## The change

* Make the default number of visible rows in a frame/series repr 10 instead of 8.
* That's it. I wasn't kidding when I said it was minor.

## Why? 

Wanting to look at a top/bottom 5 or a top 10 feels _**much**_ more common than wanting to look at a top 4 or a top 8. Maybe this is down to humans having 5 fingers per hand, the decimal system, or something else, but there aren't a whole lot of "top 8" lists out there compared to "top 10" lists. The world seems used to thinking about result sets of this size, and I think there is no harm in going with the flow.

I present the following _incredibly rigorous scientific evidence_  in the form of "number of search results returned from Google" for the quoted search terms "top 8" vs "top 10" 😉 
```
"top 10": 1,660,000,000
"top 8":     82,200,000
```

Note that "top 5" also significantly outpaces both "top 8" and "top 4" (so when we _do_ truncate, presenting the top/bottom 5 (which is what truncation will leave us with) is likely preferable over top/bottom 4, particularly during interactive exploration:

```
"top 5": 633,000,000 
"top 4":  81,100,000
```

<picture>
  <source width="667" media="(prefers-color-scheme: light)" srcset="https://github.com/pola-rs/polars/assets/2613171/baba8a96-cbf3-4dfd-908a-af7c3fc901a7">
  
</picture>

_(Chart showing number of Google search results for "top n" search terms; note the huge spikes at 5 and 10)._

## How this manifests

Something like `df.head(10)` won't show you all of the results, for example:

* Top 10 Netflix (English) films this week

  Current _(can't actually see the whole top 10)_
  ```
  shape: (10, 4)
  ┌───────────────────────────────────┬──────────────┬────────────┬─────────┐
  │ film                              ┆ hours_viewed ┆ views      ┆ runtime │
  │ ---                               ┆ ---          ┆ ---        ┆ ---     │
  │ str                               ┆ str          ┆ str        ┆ str     │
  ╞═══════════════════════════════════╪══════════════╪════════════╪═════════╡
  │ The Equalizer 3                   ┆ 26,800,000   ┆ 14,800,000 ┆ 01:49   │
  │ Rebel Moon — Part One: A Child o… ┆ 25,100,000   ┆ 11,100,000 ┆ 02:16   │
  │ Leave the World Behind            ┆ 18,700,000   ┆ 7,900,000  ┆ 02:22   │
  │ Exodus: Gods and Kings            ┆ 18,600,000   ┆ 7,400,000  ┆ 02:30   │
  │ …                                 ┆ …            ┆ …          ┆ …       │
  │ Leo                               ┆ 9,800,000    ┆ 5,500,000  ┆ 01:47   │
  │ Those Who Wish Me Dead            ┆ 8,600,000    ┆ 5,200,000  ┆ 01:40   │
  │ Bitconned                         ┆ 7,700,000    ┆ 4,900,000  ┆ 01:34   │
  │ Chicken Run: Dawn of the Nugget   ┆ 8,000,000    ┆ 4,700,000  ┆ 01:42   │
  └───────────────────────────────────┴──────────────┴────────────┴─────────┘
  ```
  Proposed _(top 10 visible without truncation)_
  ```
  shape: (10, 4)
  ┌───────────────────────────────────┬──────────────┬────────────┬─────────┐
  │ film                              ┆ hours_viewed ┆ views      ┆ runtime │
  │ ---                               ┆ ---          ┆ ---        ┆ ---     │
  │ str                               ┆ str          ┆ str        ┆ str     │
  ╞═══════════════════════════════════╪══════════════╪════════════╪═════════╡
  │ The Equalizer 3                   ┆ 26,800,000   ┆ 14,800,000 ┆ 01:49   │
  │ Rebel Moon — Part One: A Child o… ┆ 25,100,000   ┆ 11,100,000 ┆ 02:16   │
  │ Leave the World Behind            ┆ 18,700,000   ┆ 7,900,000  ┆ 02:22   │
  │ Exodus: Gods and Kings            ┆ 18,600,000   ┆ 7,400,000  ┆ 02:30   │
  │ Aquaman                           ┆ 16,800,000   ┆ 7,000,000  ┆ 02:23   │
  │ The Super Mario Bros. Movie       ┆ 8,700,000    ┆ 5,700,000  ┆ 01:32   │
  │ Leo                               ┆ 9,800,000    ┆ 5,500,000  ┆ 01:47   │
  │ Those Who Wish Me Dead            ┆ 8,600,000    ┆ 5,200,000  ┆ 01:40   │
  │ Bitconned                         ┆ 7,700,000    ┆ 4,900,000  ┆ 01:34   │
  │ Chicken Run: Dawn of the Nugget   ┆ 8,000,000    ┆ 4,700,000  ┆ 01:42   │
  └───────────────────────────────────┴──────────────┴────────────┴─────────┘
  ```

I think this is somewhat trivial, but _also_ actually worthwhile; any additional thoughts, disagreements? 😄

### CODE REVIEW

**Comment by stinodego** [comment]
I think this is a good change. I'm not sure what the rationale was for the existing behavior - something with display in notebooks? I don't know. But the proposed change sounds fine to me 👍

**Comment by mcrumiller** [comment]
Related #13445.

**Review by stinodego — APPROVED** [review]

**Comment by stinodego** [comment]
Probably should have @ritchie46 sign off on this one, but looks good to me!

**Comment by ritchie46** [comment]
Can you mention this PR as a comment. Then from now on, we know the rationale behind our choice. :)

The rationale behind 8 was just me choosing something reasonable, I think.

In any case. Fine by me. 👍

**Comment by alexander-beedie** [comment]
> Can you mention this PR as a comment. Then from now on, we know the rationale behind our choice. :)

Good plan; done ;)

**Comment by Wainberg** [comment]
@alexander-beedie the default for Series is still 26 rows, should this also be changed to 10?

```python
>>> pl.Series(range(1, 26 + 1))
shape: (26,)
Series: '' [i64]
[
        1
        2
        3
        4
        5
        6
        7
        8
        9
        10
        11
        12
        13
        14
        15
        16
        17
        18
        19
        20
        21
        22
        23
        24
        25
        26
]
>>> pl.Series(range(1, 27 + 1))
shape: (27,)
Series: '' [i64]
[
        1
        2
        3
        4
        5
        6
        7
        8
        9
        10
        11
        12
        …
        15
        16
        17
        18
        19
        20
        21
        22
        23
        24
        25
        26
        27
]
```

**Pull request merged**
