### PR TITLE
Fix read_parquet with list having nested struct

### PR DESCRIPTION
**Pull request by cjermain**
I mentioned issues with reading Parquet files with nested structs in https://github.com/pola-rs/polars/issues/2448#issuecomment-1073394024. This PR is a work-in-progress to improve support for reading parquet files with nested structs. The current changes allow for the following to succeed.

```python
import pandas as pd
import polars as pl

# Write out a nested example
data = [                                                                                                       
    {'a': [{'b': 0}]},                                                                                         
    {'a': [{'b': 1}, {'b': 2}]},                                                                               
]
pd.DataFrame(data).to_parquet("~/test.parquet")

# Read it in polars
df = pl.read_parquet("~/test.parquet", use_pyarrow=True)
```

### CODE REVIEW

**Comment by cjermain** [comment]
I've noticed that double-nested structs are currently failing in the `StructChunked::new_unchecked` section of code. This can be reproduced with the above code example, replacing `data` with:
```python
data = [
    {'a': {'b': {'c': 0}}},
    {'a', {'b': {'c': 1}}},
]
```

**Comment by cjermain** [comment]
It looks like the `SeriesTrait` does not have a supporting method for converting to a `StructChunked`.
https://github.com/pola-rs/polars/blob/master/polars/polars-core/src/series/series_trait.rs#L443-L456

**Comment by cjermain** [comment]
The polars-book section on datatypes is missing an entry for `Struct`:
https://pola-rs.github.io/polars-book/user-guide/datatypes.html

**Comment by ritchie46** [comment]
> It looks like the `SeriesTrait` does not have a supporting method for converting to a `StructChunked`. https://github.com/pola-rs/polars/blob/master/polars/polars-core/src/series/series_trait.rs#L443-L456

It is on the Series struct impl.

**Comment by ritchie46** [comment]
> I've noticed that double-nested structs are currently failing in the `StructChunked::new_unchecked` section of code. This can be reproduced with the above code example, replacing `data` with:
> 
> ```python
> data = [
>     {'a': {'b': {'c': 0}}},
>     {'a', {'b': {'c': 1}}},
> ]
> ```

Can you make an issue for that? Thanks!

**Comment by cjermain** [comment]
Thanks. I'm still getting my bearings with Rust. I'll create a separate issue for the double-nested struct example. Otherwise, I think this PR is ready to merge with the test provided. It enables reading from lists with a nested struct. I don't think the test failures are related to this PR, so I rebased on the latest master branch.

**Pull request merged**
