### PR TITLE
fix(python): raise for `pl.concat(how="align")` when no columns are shared between frames

### LINKED ISSUE #13939: pl.concat using how=align panics when schemas don't share keys
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

data1 =  pl.DataFrame({
    'field1': [1, 2],
    'field2': ['A', 'B']
})

data2 =  pl.DataFrame({
    'field3': [3, 4],
    'field4': ['C', 'D']
})

pl.concat([data1, data2], how="align")  # panic   pyo3_runtime.PanicException: at least one key

pl.concat([data1, data2], how="horizontal")  # works
pl.concat([data1, data2], how="diagonal")  # works
pl.concat([data1, data2], how="diagonal_relaxed")  # works

# pl.concat([data1, data2], how="vertical")  # polars.exceptions.ShapeError: unable to vstack, column names don't match: "field1" and "field3"
# pl.concat([data1, data2], how="vertical_relaxed")  # polars.exceptions.ComputeError: schema names differ: got field1, expected field3
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/hashing/vector_hasher.rs:434:29:
at least one key
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d6d7a93866f2ffcfb51828b8859bdad760b54ce0/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/d6d7a93866f2ffcfb51828b8859bdad760b54ce0/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/d6d7a93866f2ffcfb51828b8859bdad760b54ce0/library/core/src/panicking.rs:196:5
   3: core::panicking::panic_str
             at /rustc/d6d7a93866f2ffcfb51828b8859bdad760b54ce0/library/core/src/panicking.rs:171:5
   4: core::option::expect_failed
             at /rustc/d6d7a93866f2ffcfb51828b8859bdad760b54ce0/library/core/src/option.rs:1980:5
   5: polars_core::hashing::vector_hasher::series_to_hashes
   6: rayon::iter::plumbing::bridge_producer_consumer::helper
   7: rayon_core::thread_pool::ThreadPool::install::{{closure}}
   8: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   9: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/home/origon/testing/test3.py", line 16, in <module>
    pl.concat([data1, data2], how="align")  # panic   pyo3_runtime.PanicException: at least one key
  File "/home/origon/.local/lib/python3.10/site-packages/polars/functions/eager.py", line 171, in concat
    return lf.collect() if eager else lf  # type: ignore[return-value]
  File "/home/origon/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1730, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: at least one key
```

### Issue description

When the dataframes do not share any keys, pl.concat(how="align") panics instead of throwing an exception, like vstack / vstack relaxed do. Enhancement to throw exception instead of panicking, providing the user w/ a clearer message.

### Expected behavior

Throw exception instead of panic

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.5
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               0.9.1
matplotlib:           3.8.2
numpy:                1.25.0
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Resolves #13939.

### CODE REVIEW

**Comment by deanm0000** [comment]
Shouldn't it be maybe invalid operation error https://github.com/pola-rs/polars/blob/main/py-polars/polars/exceptions.py or maybe schema error

**Comment by mcrumiller** [comment]
> Shouldn't it be maybe invalid operation error https://github.com/pola-rs/polars/blob/main/py-polars/polars/exceptions.py or maybe schema error

I think a `SchemaError` fits best. I'll set that for now and if someone else has a better reason for something else we can always switch. Thanks @deanm0000.

**Comment by alexander-beedie** [comment]
Hmm, we might need to tweak our exception docstrings a bit; I'd classify this as an `InvalidOperation` rather than `SchemaError` as there nothing wrong with the schemas of the input objects; rather, it's the operation itself (trying to combine objects that don't share common columns) that's invalid 🤔 @stinodego, interested on your take here!

**Comment by ritchie46** [comment]
Must be `InvalidOperation` indeed. The inputs of the operations are not correct.

**Comment by mcrumiller** [comment]
@ritchie46 is the error related to the new String type?

```
FAILED tests/unit/streaming/test_streaming_unique.py::test_streaming_out_of_core_unique - pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("invalid series dtype: expected `BinaryOffset`, got `binary`"))
```

**Comment by mcrumiller** [comment]
@stinodego this failed due to the now-fixed pytest markers, can you rerun the tests for this to make the red X go away?

**Comment by stinodego** [comment]
> @stinodego this failed due to the now-fixed pytest markers, can you rerun the tests for this to make the red X go away?

If you rebase the PR it should be fixed.

**Pull request merged**
