### PR TITLE
feat(rust): Get polars to compile to wasm target

### PR DESCRIPTION
**Pull request by gitkwr**
Updates that will allow polars to be compiled to webassembly target. Well tested and working.

### CODE REVIEW

**Comment by universalmind303** [comment]
just wanted to add a note: this is the fork that is currently being used for https://github.com/pola-rs/js-polars, so we can switch that to the main repo afterwards.

**Comment by ritchie46** [comment]
Thanks a lot @gitkwr. Could you resolve the conflicts?

Maybe if you have time, you could also add a wasm check in our CI. This would ensure we don't break this functionality in the future.

**Comment by gitkwr** [comment]
@ritchie46 conflict resolved. Will look into wasm tests.

**Comment by ritchie46** [comment]
I will merge this in before we get new conflicts. The wasm CI test can go in a new PR. Thanks for your work @gitkwr

**Pull request merged**
