### PR TITLE
feat(rust): move all boolean expressions into `BooleanFunction` enum

### PR DESCRIPTION
**Pull request by borchero**
# Motivation

This PR makes all [boolean expressions](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/boolean.html) adopt `FunctionExpr` by establishing a new `FunctionExpr::Boolean(BooleanFunction)` case.

`BooleanFunction` subsumes...

- the existing cases `IsNull`, `IsNotNull`, `IsIn`, `Not` (renamed as `IsNot`)
- the nan cases `IsNan`, `IsNotNan` (thus, dropping the `NanFunction` enum and moving `DropNulls` to `FunctionExpr`)
- new cases `All`, `Any`, `IsFinite`, `IsInfinite`, `IsFirst`

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks! Can you do a rebase?

**Comment by borchero** [comment]
🧹

**Comment by ritchie46** [comment]
And this one also. :/

**Comment by ritchie46** [comment]
Alright, you can rebase. ;)

**Pull request merged**
