### PR TITLE
fix(python): improve handling of database drivers that can return arrow data

### LINKED ISSUE #11131: 'generator' object has no attribute 'fetcharrowbatches'
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```py
conn = my_create_turbodbc_connection()
pl.read_database("select 1", conn, batch_size=42)
```

### Log output

_No response_

### Issue description

Sorry for the screenshots, I don't have copy & paste on the machine.

Screenshot 2023-09-15 at 13 29 28

Screenshot 2023-09-15 at 13 29 44

### Expected behavior

Should work (?)

### Installed versions

Polars 0.19.2 from conda-forge

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #11131.

Reworked the batched Arrow-return path and improved the related mocked tests. 

**Updates:** 
* Was finally able to install `turbodbc` _with_ the arrow extensions and validate the fix.
* Standardised `duckdb` interactions, adding an entry into the driver registry.

### CODE REVIEW

**Comment by alexander-beedie** [comment]
@jonashaag: you'll have to be the ultimate judge of this one, as you have somehow managed to install/compile the Arrow-enabled version of this driver :)

**Comment by jonashaag** [comment]
Sure!

You can just install it from conda-forge, it just works.

**Comment by alexander-beedie** [comment]
> You can just install it from conda-forge, it just works.

I tried that - and it just... didn't 😅 
Will try on a different architecture/env tomorrow.

**Comment by alexander-beedie** [comment]
@jonashaag, @ritchie46: was finally able to get `turbodbc` compiled/installed both without (at home) _and_ with (at work) the extension that gets it arrow support and use both versions to craft this fix and confirm that it works... 👍

**Pull request merged**
