### PR TITLE
feat(python): Make groupby rolling/dynamic iterable

### LINKED ISSUE #5786: Iterable `groupby_rolling` and `groupby_dynamic`
### Problem description

`groupby` has an `__iter__` method defined, making it quite easy to iteratively work through the groups for debugging. Although for production of course you'd just use `.agg`, it would be nice if `groupby_rolling` and `groupby_dynamic` also had an `__iter__` method.

### PR DESCRIPTION
**Pull request by stinodego**
Resolves #5786

Question: while working on this, I noticed that `groupby_rolling` defaults to `closed=left`, while `groupby_dynamic` defaults to `closed=right`. Why is this? It would make sense to me to have both default to `closed=left`.

### CODE REVIEW

**Comment by zundertj** [comment]
In finance applications, you would want `closed="right"` to be the default imo. See for example Pandas doing the same with [rolling_mean](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html).

**Comment by ritchie46** [comment]
For groupby rolling I believe it was most intuitive as then each row is the first element of its respective group. In groupby dynamic we don't have this direct row 1:1 mapping.

**Comment by ritchie46** [comment]
Nice one. I can imagine this being useful for ergonomics on smallish data.

**Comment by drivenow** [comment]
@zundertj  @ritchie46 Do you think it's suitable to use rs-polars in high frequency market data indicators calculation? which features streaming Calculation and extreme low latency.

**Pull request merged**
