### PR TITLE
feat(python): add missing `width` property to `LazyFrame`

### PR DESCRIPTION
**Pull request by alexander-beedie**
Brings in-line with `DataFrame` (spotted while starting another pass through the docs).
```python
import polars as pl
df = pl.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})

df.width
2

df.lazy().width
2
```

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks! Can you add a docs entry? ;)

**Comment by alexander-beedie** [comment]
> Thanks! Can you add a docs entry? ;)

Lol... already have in the larger PR (incoming!). It's the follow-up to the previous Series/Expr structural/nav improvements, this time for DataFrame and LazyFrame [https://github.com/pola-rs/polars/pull/5376]

**Comment by alexander-beedie** [comment]
@ritchie46: `width` added to the docs here now - going to try and do some more with the Sphinx update, so that'll come tomorrow now - never enough hours in the day... :)

**Comment by ritchie46** [comment]
> @ritchie46: `width` added to the docs here now - going to try and do some more with the Sphinx update, so that'll come tomorrow now - never enough hours in the day... :)

I know! :)

**Pull request merged**
