### PR TITLE
ci(python,rust): Use `release-drafter` to draft releases with changelogs

### LINKED ISSUE #1423: automate changelog creation

### LINKED ISSUE #4391: RFC: conventional commits
I believe @universalmind303 already suggested this once. The polars repo is very fast paced and keeping a changelog has proven to be a maintenance burden that is too high. 

To make it possible to automate creating a changelog from commit messages we need to have a standard format. Therefore I want to propose using [conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/).

Ideally they can even be enforced in CI. 

# Proposal

## types:

* feat
* fix
* chore
* ci
* docs
* perf
* test
* refactor
* revert

## Scopes:
May be comma delimited

### Required:
* python
* rust

### Optional
...

## Breaking changes
Add `!` Just before the colon `:` that prefixes the description.

Add a `BREAKING CHANGE` footer, followed by an optional description.

```
<type>[optional scope(s)]: <description>

[optional body]

[optional footer(s)]
```

### PR DESCRIPTION
**Pull request by stinodego**
Resolves #1423
Resolves #4391

Use [release-drafter](https://github.com/release-drafter/release-drafter) for drafting multiple releases.

See my [sandbox](https://github.com/stinodego/test-release-drafter) repo where I have tested this functionality extensively.

Here's how it works:
* Everything works based on PR labels.
* An auto-labeler assigns labels based on the conventional commit tag of the PR title.
  *  `rust`/`python` labels based on scope (i.e. `feat(python)`). These determine which release the PR ends up in. A PR can be in both the Rust and Python release, or in neither. If you don't specify a scope, it will not be in the changelog!
  * Labels for each of the conventional commit types `build`, `ci`, etc. Note that `feat` is mapped to the `enhancement` label.
  * `breaking` label for breaking changes (e.g. `feat(rust)!`).
  * _For example, if your title starts with `perf(python)`, it will be labeled `performance` and `python`._
* Pull requests are categorized into the following sections based on their tags:
    * Highlights (tagged manually)
    * Breaking changes (`breaking`)
    * Performance improvements (`performance`)
    * Enhancements (`enhancement`)
    * Bug fixes (`fix`)
    * Other improvements (other tags)
* The auto-labeler is nice, but you can always manually adjust labels. I see the following use cases for manual tag adjustments:
  * Add a `highlight` label to designate something as a highlight
  * Remove incorrect labels if the initial conventional commit tag was incorrect.
* Release/tag versions are automatically incremented based on the previous release of the same type. A `breaking` tag will trigger a minor version bump (as we are in pre-1.0.0 still).
* Changelog entries contain the PR name, so this name should be descriptive. The conventional commit tag will be stripped.
* After doing a release as normal, go to Releases -> Edit release -> Publish release. This creates the release. Make sure it points to the correct tag.

**Important notes**
* **This introduces a new tag format**: `py-0.14.14` (instead of `py-polars-v0.14.14`) and equivalent for Rust. These tags have been added to the latest tags for both Python and Rust.
* This assumes conventional commits according to the [official specs](https://www.conventionalcommits.org/en/v1.0.0/). This requires parentheses instead of brackets for scope definition. We'll have to get used to this new approach.
* I won't be around the next 2 weeks to address any issues that come up. Still, I think it's worth to merge this so that we can start benefitting from the autolabeler.

### CODE REVIEW

**Comment by ritchie46** [comment]
I am so excited! This would be a huge gain! <3

**Comment by stinodego** [comment]
@ritchie46 This one is ready to be merged! Unfortunately I'm not around for the next 2 weeks, and I'm sure there are some quirks to be worked out. Up to you if you want to wait until I'm back or want to go ahead and press the green button 😄

**Comment by ritchie46** [comment]
Have a nice holiday! :shipit:

**Comment by stinodego** [comment]
> Have a nice holiday! :shipit:

Thanks! I'm gonna see if I can make sure this first draft gets created properly.

**Pull request merged**
