### PR TITLE
python polars 0.18.8

### PR DESCRIPTION
**Pull request by ritchie46**

### CODE REVIEW

**Comment by avimallu** [comment]
Any reason this doesn't show up in the `Releases` section on Github?

**Comment by stinodego** [comment]
I figured it hadn't been released yet, but apparently it has. I'll make the release.

**Comment by avimallu** [comment]
I didn't know that was a manual process, thought it went along with the commit. Thanks! :D

**Comment by stinodego** [comment]
> I didn't know that was a manual process, thought it went along with the commit. Thanks! :D

The commit doesn't do anything. When we make the GitHub release, a new tag is made which triggers the release to PyPI.

Ritchie must've made the tag manually.

**Pull request merged**
