### PR TITLE
fix(rust, python): fix is_sorted for structs

### PR DESCRIPTION
**Pull request by magarick**
Struct series will now compare correctly.
We'll handle the general case later, along with some possible improvements and enhancements to is_sorted itself.

### CODE REVIEW

**Review by ritchie46 — APPROVED** [review]
Yeap, looks good. :+1:

**Comment by s-banach** [comment]
Excuse me, but can you run the following test?
```python
import polars as pl

df = (
    pl.DataFrame({"x": [0, 1, 0, 1], "y": [0, 0, 1, 1]})
    .select(pl.struct("x", "y").alias("xy"))
    .sort("xy")
)
assert df["xy"].is_sorted()
```

I can't really read/write rust, but it looks like you're attempting to test the struct inequality `s1 <= s2` by testing `s1.field <= s2.field` for each `field`. In the previous discussion, I left a comment pointing out that this is not how dictionary order works. I thought this was understood.

**Comment by magarick** [comment]
@s-banach Ack, you're right! I was trying to be clever and avoid storing information for every row but that's not possible. Only inequality means we get to stop and only for that row.

This is a good question actually, @ritchie46 are structs intended to be sorted in dictionary order or by every entry. And what do you mean by row encoding. I tried looking at the code in sort and I couldn't figure out what it was supposed to do.

**Comment by magarick** [comment]
In going through this I realized we need special handling for the case when not every field of a struct is None. It also turns out that `null_count` will return the total number of nulls in the struct but the validity will only be 0 if every element of a struct is null. Since null location is determined on a per field basis, the problem becomes much harder. This should still be doable without sorting or using RLE but it'll take just a bit longer. Thanks for your patience.

**Pull request merged**
