### PR TITLE
Rust documentation: new examples for DataFrame methods

### PR DESCRIPTION
**Pull request by ibENPC**
Adding new examples to the DataFrame methods `max`, `std`, `var`, `min`, `sum`, `mean` and `median` using the rustdoc features.

### `max`
```rust
use polars_core::df;
use polars_core::prelude::*;

fn example() -> Result<()> {
    let df1: DataFrame = df!("Die n°1" => &[1, 3, 1, 5, 6],
                             "Die n°2" => &[3, 2, 3, 5, 3])?;
    assert_eq!(df1.shape(), (5, 2));

    let df2: DataFrame = df1.max();
    assert_eq!(df2.shape(), (1, 2));
    println!("{}", df2);

    Ok(())
}
```
Output:
```text
shape: (1, 2)
+---------+---------+
| Die n°1 | Die n°2 |
| ---     | ---     |
| i32     | i32     |
+=========+=========+
| 6       | 5       |
+---------+---------+
```

### `std`
```rust
use polars_core::df;
use polars_core::prelude::*;

fn example() -> Result<()> {
    let df1: DataFrame = df!("Die n°1" => &[1, 3, 1, 5, 6],
                             "Die n°2" => &[3, 2, 3, 5, 3])?;
    assert_eq!(df1.shape(), (5, 2));

    let df2: DataFrame = df1.std();
    assert_eq!(df2.shape(), (1, 2));
    println!("{}", df2);

    Ok(())
}
```
Output:
```text
shape: (1, 2)
+-------------------+--------------------+
| Die n°1           | Die n°2            |
| ---               | ---                |
| f64               | f64                |
+===================+====================+
| 2.280350850198276 | 1.0954451150103321 |
+-------------------+--------------------+
```

### `var`
```rust
use polars_core::df;
use polars_core::prelude::*;

fn example() -> Result<()> {
    let df1: DataFrame = df!("Die n°1" => &[1, 3, 1, 5, 6],
                             "Die n°2" => &[3, 2, 3, 5, 3])?;
    assert_eq!(df1.shape(), (5, 2));

    let df2: DataFrame = df1.var();
    assert_eq!(df2.shape(), (1, 2));
    println!("{}", df2);

    Ok(())
}
```
Output:
```text
shape: (1, 2)
+---------+---------+
| Die n°1 | Die n°2 |
| ---     | ---     |
| f64     | f64     |
+=========+=========+
| 5.2     | 1.2     |
+---------+---------+
```

### `min`
```rust
use polars_core::df;
use polars_core::prelude::*;

fn example() -> Result<()> {
    let df1: DataFrame = df!("Die n°1" => &[1, 3, 1, 5, 6],
                             "Die n°2" => &[3, 2, 3, 5, 3])?;
    assert_eq!(df1.shape(), (5, 2));

    let df2: DataFrame = df1.min();
    assert_eq!(df2.shape(), (1, 2));
    println!("{}", df2);

    Ok(())
}
```
Output:
```text
shape: (1, 2)
+---------+---------+
| Die n°1 | Die n°2 |
| ---     | ---     |
| i32     | i32     |
+=========+=========+
| 1       | 2       |
+---------+---------+
```

### `sum`
```rust
use polars_core::df;
use polars_core::prelude::*;

fn example() -> Result<()> {
    let df1: DataFrame = df!("Die n°1" => &[1, 3, 1, 5, 6],
                             "Die n°2" => &[3, 2, 3, 5, 3])?;
    assert_eq!(df1.shape(), (5, 2));

    let df2: DataFrame = df1.sum();
    assert_eq!(df2.shape(), (1, 2));
    println!("{}", df2);

    Ok(())
}
```
Output:
```text
shape: (1, 2)
+---------+---------+
| Die n°1 | Die n°2 |
| ---     | ---     |
| i32     | i32     |
+=========+=========+
| 16      | 16      |
+---------+---------+
```

### `mean`
```rust
use polars_core::df;
use polars_core::prelude::*;

fn example() -> Result<()> {
    let df1: DataFrame = df!("Die n°1" => &[1, 3, 1, 5, 6],
                             "Die n°2" => &[3, 2, 3, 5, 3])?;
    assert_eq!(df1.shape(), (5, 2));

    let df2: DataFrame = df1.mean();
    assert_eq!(df2.shape(), (1, 2));
    println!("{}", df2);

    Ok(())
}
```
Output:
```text
shape: (1, 2)
+---------+---------+
| Die n°1 | Die n°2 |
| ---     | ---     |
| f64     | f64     |
+=========+=========+
| 3.2     | 3.2     |
+---------+---------+
```

### `median`
```rust
use polars_core::df;
use polars_core::prelude::*;

fn example() -> Result<()> {
    let df1: DataFrame = df!("Die n°1" => &[1, 3, 1, 5, 6],
                             "Die n°2" => &[3, 2, 3, 5, 3])?;
    assert_eq!(df1.shape(), (5, 2));

    let df2: DataFrame = df1.median();
    assert_eq!(df2.shape(), (1, 2));
    println!("{}", df2);

    Ok(())
}
```
Output:
```text
shape: (1, 2)
+---------+---------+
| Die n°1 | Die n°2 |
| ---     | ---     |
| i32     | i32     |
+=========+=========+
| 3       | 3       |
+---------+---------+
```

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks @ibENPC. For consistency with other examples, can we use column names `"a", "b", "c", ..., "z"`?

Is `"Die"` German?

**Comment by ibENPC** [comment]
"Die" is the singular of dice: 🎲

The simple story of those examples is rolling 2 dice five times.

As a beginner it is easier for me to understand when the examples have a little story (even poor) rather than raw meaningless data. Using simple use cases is generally more beginner friendly.
However if you think it is better to use `"a", "b", "c", ..., "z"` as a consistency rule we can go with it.

**Comment by ritchie46** [comment]
> "Die" is the singular of dice: 🎲
> 
> The simple story of those examples is rolling 2 dice five times.
> 
> As a beginner it is easier for me to understand when the examples have a little story (even poor) rather than raw meaningless data. Using simple use cases is generally more beginner friendly. However if you think it is better to use `"a", "b", "c", ..., "z"` as a consistency rule we can go with it.

Ah.. now I see it😁

**Comment by ibENPC** [comment]
I was inspired by the standard std::fs library : https://doc.rust-lang.org/std/fs/fn.read_to_string.html
But it seems that I shouldn't use "fn main()" for the examples, but rather something like "fn example()", my bad.

**Pull request merged**
