### PR TITLE
perf[rust]: build categoricals in csv reader

### PR DESCRIPTION
**Pull request by ritchie46**
@ghuls can you take it for a spin :) ?

### CODE REVIEW

**Comment by ritchie46** [comment]
@alexander-beedie could you look at the benchmark fail? I think it is related to #4928

**Comment by ghuls** [comment]
@ritchie46 Reading CSV with 2 categorical columns is now even faster than reading them as plain strings:

```python
In [18]: %timeit df = pl.read_csv(fragments_bed_filename, sep ="\t", skip_rows=0, new_columns=["chrom", "start", "end", "CB", "depth"], dtypes={"chrom": pl.Categorical, "CB": pl.Categorical}, has_header=False)
4.96 s ± 70.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [19]: %timeit df = pl.read_csv(fragments_bed_filename, sep ="\t", skip_rows=0, new_columns=["chrom", "start", "end", "CB", "depth"], has_header=False)
5.42 s ± 247 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```

**Comment by ghuls** [comment]
Reading as plain strings is still quite a bit faster when not rechunking.
```python
In [24]: %timeit df = pl.read_csv(fragments_bed_filename, sep ="\t", skip_rows=0, new_columns=["chrom", "start", "end", "CB", "depth"], dtypes={"chrom": pl.Categorical, "CB": pl.Categorical}, has_header=False, rechunk=False)
4.24 s ± 110 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [23]: %timeit df = pl.read_csv(fragments_bed_filename, sep ="\t", skip_rows=0, new_columns=["chrom", "start", "end", "CB", "depth"], has_header=False, rechunk=False)
3.16 s ± 42.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

I notices that the system time was quite high when reading as plain strings (probably memory allocation for big string column) compared with reading as categorical, while categorical uses more CPU time in total.
```python
In [13]: %time df = pl.read_csv(fragments_bed_filename, sep ="\t", skip_rows=0, new_columns=["chrom", "start", "end", "CB", "depth"], has_header=False)
CPU times: user 30.6 s, sys: 7.4 s, total: 38 s
Wall time: 5.68 s

In [16]: %time df = pl.read_csv(fragments_bed_filename, sep ="\t", skip_rows=0, new_columns=["chrom", "start", "end", "CB", "depth"], dtypes={"chrom": pl.Categorical, "CB": pl.Categorical}, has_header=False)
CPU times: user 41.2 s, sys: 3.59 s, total: 44.7 s
Wall time: 4.89 s

# Without rechunk:
In [25]: %time df = pl.read_csv(fragments_bed_filename, sep ="\t", skip_rows=0, new_columns=["chrom", "start", "end", "CB", "depth"], has_header=False, rechunk=False)
CPU times: user 28.6 s, sys: 4.3 s, total: 32.9 s
Wall time: 2.94 s

In [26]: %time df = pl.read_csv(fragments_bed_filename, sep ="\t", skip_rows=0, new_columns=["chrom", "start", "end", "CB", "depth"], dtypes={"chrom": pl.Categorical, "CB": pl.Categorical}, has_header=False, rechunk=False)
CPU times: user 39.4 s, sys: 2.38 s, total: 41.8 s
Wall time: 4.5 s
```

**Comment by s-banach** [comment]
Should I assume this only impacts `read_csv as categorical`, but not `scan_csv -> cast to categorical`?
(Can't test it on my work computer yet, there's a delay in getting new package versions.)

**Pull request merged**
