### PR TITLE
test(python): control for implicit naive/UTC datetime conversion in `test_init_with_timezone`

### PR DESCRIPTION
**Pull request by alexander-beedie**
@ritchie46: think this should fix it...😅

### CODE REVIEW

**Comment by ritchie46** [comment]
Al right, I will check after dinner. This always confuses me a bit. Is it correct for pyarrow to modify the values? And under what rules?

**Comment by alexander-beedie** [comment]
FYI: tried (briefly) to replicate the conversion/offset issue last night, but even after switching the test environment's locale to `nl_NL` it remained consistent. Will investigate further at the weekend.

**Comment by ritchie46** [comment]
Still got the error :/

**Comment by alexander-beedie** [comment]
> Still got the error :/

Argh... all of computing should just move to [Swatch time](https://en.wikipedia.org/wiki/Swatch_Internet_Time), lol. Ok, let's start narrowing-down; what's your platform/IDE combo, and the output of:
```python
import os
for k,v in os.environ.items():
    if k.startswith("LC_"):
        print( k,v )
```

**Comment by ritchie46** [comment]
The output:
```
LC_ADDRESS nl_NL.UTF-8
LC_NAME nl_NL.UTF-8
LC_MONETARY nl_NL.UTF-8
LC_PAPER nl_NL.UTF-8
LC_IDENTIFICATION nl_NL.UTF-8
LC_TELEPHONE nl_NL.UTF-8
LC_MEASUREMENT nl_NL.UTF-8
LC_TIME nl_NL.UTF-8
LC_NUMERIC nl_NL.UTF-8

```

Further I am on `20.04.1-Ubuntu`

**Comment by alexander-beedie** [comment]
Well, looks like I'll be running a Dutch Mac this evening... :)

**Comment by ritchie46** [comment]
> Well, looks like I'll be running a Dutch Mac this evening... :) Should be able to get a Ubuntu VM up too (there's an arm64 build).

Alright let me know if you are lost because all text is in Dutch. ;)

**Comment by alexander-beedie** [comment]
@ritchie46: after an excitingly international journey through the Syteemvoorkeuren, I declare victory; was able to replicate what you were seeing, and apply a simple fix - explicitly setting the initial test value to UTC via tzinfo/zoneinfo is all that was needed, and that appears to stabilise it across all regions/locales (and makes sense) ;)



`LC_CTYPE nl_NL.UTF-8`

Give it a go and confirm that it's now clean for you too?
(Just in case there are any other platform/environment issues at play - in which case it'll be Linux VM time ;)

**Comment by ritchie46** [comment]
I really appreciate you going the full distance! :raised_hands:

But.... I still have the same error. :( Could you point to the relevant code? Maybe I could fiddle about a bit and hope to find the culprit.

**Comment by alexander-beedie** [comment]
> I really appreciate you going the full distance! 🙌
> 
> But.... I still have the same error. :( Could you point to the relevant code? Maybe I could fiddle about a bit and hope to find the culprit.

Huh... ok, just committed a small patch to split the timezone test into two parts to help narrow down as rapidly as possible; my guess is that I have fixed one of the two paths (most likely init from `datetime`), but that the other has some slightly different behaviour (possibly the physical/integer init).

If you update from [the latest](https://github.com/pola-rs/polars/pull/5177/commits/88c0f419ea350c00a0ce06c4a8550a271372aaa4) you'll now see:
* `test_init_datetimes_with_timezone`
  init takes place in _py-polars/polars/internals/construction.py_, lines 278:279

* `test_init_physical_with_timezone`

If you can confirm which of the two fails (hopefully not both!) then I still have one more idea...

**Comment by ritchie46** [comment]
Both are failing. :(


Here is the full verbose output:

```

================================================= FAILURES =================================================
____________________________________ test_init_datetimes_with_timezone _____________________________________

    def test_init_datetimes_with_timezone() -> None:
        # some non-UTC timezones
        tz_us = "America/New_York"
        tz_europe = "Europe/Amsterdam"
    
        dtm = datetime(2022, 10, 12, 12, 30, tzinfo=ZoneInfo("UTC"))
    
        for tu in DTYPE_TEMPORAL_UNITS | frozenset([None]):
            df = pl.DataFrame(
                data={"d1": [dtm], "d2": [dtm]},
                columns=[
                    ("d1", pl.Datetime(tu, tz_us)),
                    ("d2", pl.Datetime(tu, tz_europe)),
                ],
            )
            assert (df["d1"].to_physical() == df["d2"].to_physical()).all()
>           assert df.rows() == [
                (
                    datetime(2022, 10, 12, 8, 30, tzinfo=ZoneInfo(tz_us)),
                    datetime(2022, 10, 12, 14, 30, tzinfo=ZoneInfo(tz_europe)),
                )
            ]
E           AssertionError: assert [(datetime.datetime(2022, 10, 12, 7, 30, tzinfo=zoneinfo.ZoneInfo(key='America/New_York')),\n  datetime.datetime(2022, 10, 12, 13, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/Amsterdam')))] == [(datetime.datetime(2022, 10, 12, 8, 30, tzinfo=zoneinfo.ZoneInfo(key='America/New_York')),\n  datetime.datetime(2022, 10, 12, 14, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/Amsterdam')))]
E             At index 0 diff: (datetime.datetime(2022, 10, 12, 7, 30, tzinfo=zoneinfo.ZoneInfo(key='America/New_York')), datetime.datetime(2022, 10, 12, 13, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/Amsterdam'))) != (datetime.datetime(2022, 10, 12, 8, 30, tzinfo=zoneinfo.ZoneInfo(key='America/New_York')), datetime.datetime(2022, 10, 12, 14, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/Amsterdam')))
E             Full diff:
E               [
E             -  (datetime.datetime(2022, 10, 12, 8, 30, tzinfo=zoneinfo.ZoneInfo(key='America/New_York')),
E             ?                                   ^
E             +  (datetime.datetime(2022, 10, 12, 7, 30, tzinfo=zoneinfo.ZoneInfo(key='America/New_York')),
E             ?                                   ^
E             -   datetime.datetime(2022, 10, 12, 14, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/Amsterdam'))),
E             ?                                    ^
E             +   datetime.datetime(2022, 10, 12, 13, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/Amsterdam'))),
E             ?                                    ^
E               ]

tests/unit/test_df.py:2414: AssertionError
_____________________________________ test_init_physical_with_timezone _____________________________________

    def test_init_physical_with_timezone() -> None:
        # some non-UTC timezones
        tz_uae = "Asia/Dubai"
        tz_asia = "Asia/Tokyo"
    
        dtm_us = 1665577800000000
    
        for tu in DTYPE_TEMPORAL_UNITS | frozenset([None]):
            dtm = {"ms": dtm_us // 1_000, "ns": dtm_us * 1_000}.get(str(tu), dtm_us)
    
            df = pl.DataFrame(
                data={"d1": [dtm], "d2": [dtm]},
                columns=[
                    ("d1", pl.Datetime(tu, tz_uae)),
                    ("d2", pl.Datetime(tu, tz_asia)),
                ],
            )
            assert (df["d1"].to_physical() == df["d2"].to_physical()).all()
>           assert df.rows() == [
                (
                    datetime(2022, 10, 12, 16, 30, tzinfo=ZoneInfo(tz_uae)),
                    datetime(2022, 10, 12, 21, 30, tzinfo=ZoneInfo(tz_asia)),
                )
            ]
E           AssertionError: assert [(datetime.datetime(2022, 10, 12, 15, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Dubai')),\n  datetime.datetime(2022, 10, 12, 20, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Tokyo')))] == [(datetime.datetime(2022, 10, 12, 16, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Dubai')),\n  datetime.datetime(2022, 10, 12, 21, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Tokyo')))]
E             At index 0 diff: (datetime.datetime(2022, 10, 12, 15, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Dubai')), datetime.datetime(2022, 10, 12, 20, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Tokyo'))) != (datetime.datetime(2022, 10, 12, 16, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Dubai')), datetime.datetime(2022, 10, 12, 21, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Tokyo')))
E             Full diff:
E               [
E             -  (datetime.datetime(2022, 10, 12, 16, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Dubai')),
E             ?                                    ^
E             +  (datetime.datetime(2022, 10, 12, 15, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Dubai')),
E             ?                                    ^
E             -   datetime.datetime(2022, 10, 12, 21, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Tokyo'))),
E             ?                                    ^
E             +   datetime.datetime(2022, 10, 12, 20, 30, tzinfo=zoneinfo.ZoneInfo(key='Asia/Tokyo'))),
E             ?                                    ^
E               ]

tests/unit/test_df.py:2440: AssertionError
```

As you'd expect. Of by 1.

**Comment by alexander-beedie** [comment]
Ouch. After reproducing/fixing locally, I was feeling quite hopeful too... :) 

Back to the drawing board! What is the test environment you're running under - inside an IDE, or from the command line? I'm pulling down an arm64 image of Ubuntu now, to take it one stage further, hah.

**Comment by ritchie46** [comment]
Just from the command line.

> 'm pulling down an arm64 image of Ubuntu now, to take it one stage further, hah.

:see_no_evil:

**Comment by alexander-beedie** [comment]
Almost up & running; found one for @stinodego and the ongoing `Makefile` enhancements, perhaps...? :)

From a (very!) fresh install, got the following while trying to establish a `venv`:

_"The virtual environment was not created successfully because ensurepip is not available.  On Debian/Ubuntu systems, you need to install the python3-venv package using the following command..."_

Initially thought it was missing a `python3 => python` alias, but further poking showed that wasn't quite it; I'm past it now (installed the missing package), but seems worth handling in the Makefile? Terminal output below, for context:

<pre><b>parallels@virtual</b>:<b>~/code/polars/py-polars</b>$ make venv
python -m venv  venv
/bin/bash: line 1: python: command not found
make: *** [Makefile:39: venv] Error 127

<b>parallels@virtual</b>:<b>~/code/polars/py-polars</b>$ python
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
&gt;&gt;&gt; exit()

<b>parallels@virtual</b>:<b>~/code/polars/py-polars</b>$ python -m venv
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear] [--upgrade] [--without-pip] [--prompt PROMPT] [--upgrade-deps]
            ENV_DIR [ENV_DIR ...]
venv: error: the following arguments are required: ENV_DIR

<b>parallels@virtual</b>:<b>~/code/polars/py-polars</b>$ python -m venv venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: [&apos;/home/parallels/code/polars/py-polars/venv/bin/python3&apos;, &apos;-Im&apos;, &apos;ensurepip&apos;, &apos;--upgrade&apos;, &apos;--default-pip&apos;]
</pre>

**Comment by alexander-beedie** [comment]
Never did manage to reproduce, even in the Dutch Ubuntu VM :(
Hope you can get to the bottom of it...

Screenshot 2022-10-16 at 21 15 24

_(Where is the windmill emoji :p)_

**Comment by alexander-beedie** [comment]
Closing in favour of simplified PR, now that timezone issue seems to be good!

**Pull request closed without merging**
