### PR TITLE
feat(python): allow use of `StringCache` object as a function decorator

### PR DESCRIPTION
**Pull request by alexander-beedie**
Ref: #9307. 

The same trick (upgrading our context manager to do double-duty as a decorator) works nicely here too...

```python
import polars as pl

@pl.StringCache()
def lets_get_schwifty() -> pl.DataFrame:
    df1 = pl.LazyFrame([
        pl.Series("key", ["bar"], dtype=pl.Categorical),
        pl.Series("val", [1]),
    ])
    df2 = pl.LazyFrame([
        pl.Series("key", ["bar"], dtype=pl.Categorical),
        pl.Series("val", [2]),
    ])
    return df1.join(df2, on=["key"], how="outer").collect()

print( lets_get_schwifty() )
# shape: (1, 3)
# ┌─────┬─────┬───────────┐
# │ key ┆ val ┆ val_right │
# │ --- ┆ --- ┆ ---       │
# │ cat ┆ i64 ┆ i64       │
# ╞═════╪═════╪═══════════╡
# │ bar ┆ 1   ┆ 2         │
# └─────┴─────┴───────────┘
```

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Hmm, the `typos` linter has suddenly become very slightly stricter, and I'm not sure why yet...🤔 
(Ref: the failing lint test).

**Comment by stinodego** [comment]
> @stinodego, any idea why CI is out of sync with requirements?

The CI doesn't use the Python package, it uses the `typos` Action. So it can be out of sync with the requirements.txt.

**Comment by ritchie46** [comment]
Related to some of these fixes. Can we prevent the `typos` check to check parameters and data in dataframes? That's a bit too constraining IMO.

**Comment by alexander-beedie** [comment]
> The CI doesn't use the Python package, it uses the typos Action.

Ahh, gotcha; not a big problem, it only complained about up a small handful of extra stuff.

**Comment by stinodego** [comment]
> Related to some of these fixes. Can we prevent the `typos` check to check parameters and data in dataframes? That's a bit too constraining IMO.

I think @ghuls set it up, maybe he knows some of the settings. I could look into it sometime.

**Pull request merged**
