### PR TITLE
run integration tests in coverage

### PR DESCRIPTION
**Pull request by ritchie46**
Also include the integration tests in coverage summary.

### CODE REVIEW

**Comment by ritchie46** [comment]
@cjermain any idea why this is failing? This should work right?

**Comment by cjermain** [comment]
I think that should work. Does it work locally with `make coverage`? I can take a deeper look later.

**Comment by cjermain** [comment]
@ritchie46, `make coverage` works for me locally. What about replicating the package and test threads (`--test-threads=2`) arguments from `make test` in `polars/Makefile:integration-tests`?

**Comment by ritchie46** [comment]
Maybe its a fluke in CI, I will try if merging it gives any problems. If so, we can revert.

**Pull request merged**
