### PR TITLE
feat(python, rust): improve err msg strict cast

### PR DESCRIPTION
**Pull request by JulianCologne**
improve error message when strict casting fails:

```python
pl.DataFrame(pl.int_range(0, 1000, eager=True)).with_columns(
    pl.col('int').cast(pl.Int8, strict=True),
)
```

OLD
```bash
ComputeError: strict conversion from `i64` to `i8` failed for column: int, value(s) [128, 129, … 999]; if you were trying to cast Utf8 to temporal dtypes, consider using `strptime`
```
NEW
```bash
ComputeError: strict conversion from `i64` to `i8` in column `int` failed for 872 value(s) (872 unique): [128, 129, … 999]

If you were trying to cast Utf8 to temporal dtypes, consider using `strptime`
```

Advantages:
- knowing how many total values failed to parse in a column is very useful
- knowing how many unique values failed to parse in a column is very useful
- consistency: date parsing uses the same message (e.g. `strict date parsing failed for 7 value(s) (5 unique): ["a", "b", … "e"]`)
- consistency: separate error from hint message
- no compute overhead (calling `.len()` on the failures is essentially free)

Disadvantages:
- none

### CODE REVIEW

**Comment by ritchie46** [comment]
I am not entirely sure about this. We are adding more and more compute in the error layer. Which makes handling the error gracefully more and more compute intensive.

**Comment by JulianCologne** [comment]
> I am not entirely sure about this. We are adding more and more compute in the error layer. Which makes handling the error gracefully more and more compute intensive.

thanks for you thoughts. I would somewhat disagree.
I think giving precise and valueable errors is extremely important because the world/data is often messy and cleaning up takes a lot of time and having good error messages can save lots of time.
I would argue that if somewhat is willing to use compute for some calculation he/she would gladly invest a tiny bit more compute to get better error messages instead of having to guess and maybe running the whole code 5 more times to find all the errors.

That aside my additions should be almost zero overhead (2x `.len()` calls).
All I do is adding `failed for XX value(s) (YY unique)` where
- XX = all_failures.len();
- YY = unique_failures.len();

**Comment by stinodego** [comment]
> 5 value(s) (2 unique): ["a", "b"]

We should never print data that can grow 'infinitely' in error messages. What happens if you have 1 billion rows and this fails for 500 million of them? You can fork over a bunch of money to pay your cloud provider for logging costs.

**Comment by JulianCologne** [comment]
> > 5 value(s) (2 unique): ["a", "b"]
> 
> We should never print data that can grow 'infinitely' in error messages. What happens if you have 1 billion rows and this fails for 500 million of them? You can fork over a bunch of money to pay your cloud provider for logging costs.
> 
> 5 values 2 unique, OK. Maybe printing an example value, sure. But printing all values, big no go.
> 
> I see that was already in there though - it should really be changed.

I see what you mean but this is not how this works:
```python
pl.DataFrame(pl.int_range(0, 1000, eager=True)).with_columns(
    pl.col('int').cast(pl.Int8, strict=True),
)
# ... failed for 872 value(s) (872 unique): [128, 129, … 999]
```

I was initially thinking the same and inserted a `.slice(0, 10)` but this is not required since `unique_failures.fmt_list()` already takes care of formatting the list in a condensed way.

**Comment by ritchie46** [comment]
I agree on the value of good error messages. But for polars I want to limit that to the first occurrence. E.g. show the value of the first failure, not per se the complete set.

People use try except clauses to handle errors and we are paying much, much more compute in our error messaging than in the original operation.

**Comment by JulianCologne** [comment]
I hear/understand what you say but this makes no sense here I would argue
- This PR only adds 2 numbers to the error message (**DOES NOT ADD COMPUTE**).
- The current behaviour already shows a **subset** on error examples, I did not specifically add them.
- Clarification: This will not show the complete error set!

### Reasons:
- more **usefull** error information (adding count total and count unique)
- NO additional compute (only calling `.len()` which is free)! Unique errors were there already
- consistency! See date conversion: 
    - `pl.Series(values=['2019-01-01', 'a', 'b', '2019-01-02', '2019-01-03', 'c', 'd', 'e', 'a', 'a'],).str.to_date(exact=False)`
    - `# ComputeError: strict date parsing failed for 7 value(s) (5 unique): ["a", "b", … "e"]`


### Concrete use case:
- I manage several ETL pipelines that are using CSV files and people often upload invalid/bad data
- If parsing fails I send a message to a teams channel with the error and often people just correct the first 1, 2 or 3 errors because they have no idea how many errors occurred 
- so they sometimes upload their files XX times and every time get a few new problems in the same column instead of correcting all


I feel honestly a bit frustrated atm because I think many polars users would benefit from this improved error message and this would be consistent with temporal casting error message and this does not require additions compute but I seem to be fighting a losing battle here...?! :(

**Comment by JulianCologne** [comment]
hi @ritchie46 
could you please check this PR again. I think there was a slight misunderstanding to what this PR does. It only improves a single error message (updated my first post at the top).
I can see this being useful for many polars users! ;)

**Comment by stinodego** [comment]
Hey @JulianCologne,

I don't think this PR is the way to go. You're introducing some code duplication which is not so nice. But mostly, before we introduce more changes to error messages like these, we need to have a broader discussion on what exactly we want to include in our error messages.

You can use https://github.com/pola-rs/polars/issues/10421 to give your input.

I'm closing this PR for now.

**Comment by MarcoGorelli** [comment]
Just had a look at this

You're replacing
```rust
pub fn get_casting_failures(input: &Series, output: &Series) -> PolarsResult<Series> {
    let failure_mask = !input.is_null() & output.is_null();
    input.filter_threaded(&failure_mask, false)?.unique()
}
```
with
```rust
            let failure_mask = !self.is_null() & s.is_null();
            let all_failures = self.filter_threaded(&failure_mask, false)?;
            let unique_failures = all_failures.unique()?.sort(false);
            let n_failures = all_failures.len();
            let n_failures_unique = unique_failures.len();
```
It looks to me like you're adding:
- `sort(false)`
- a couple of `len` statements
- some code complexity

I think part of the pushback here comes from the first and third one. Why is sorting necessary here? And could this complexity be added to get_casting_failures, rather than being repeated outside it?

If you remove the sorting, and just add a couple of `.len` calls to `get_casting_failures` itself, then I think something like this could be reconsidered

**Pull request closed without merging**
