### PR TITLE
refactor(python): Move core objects to top level

### PR DESCRIPTION
**Pull request by stinodego**
Partially addresses #7506 

This PR moves the core Polars classes out of the `internals` module. The `internals` module causes a false divide between internal/external that doesn't really exist. We keep using that module for solving the circular import problem, but it does not need to contain any code.

See the linked issue for more details.

Changes:
* Move `dataframe`, `lazyframe`, `series`, `expr`, and `sql` modules from `internals` to the top level. _(still re-exported through `internals`)_
* Update references and imports

Strategy for dealing with circular imports will be not really any different from what it is now:

* Try to import an object directly, e.g.
    * `from polars.series.series import Series`
    * `s = Series(...)`
* If that fails, re-export the object in `internals` and use that
    * `import polars.internals as pl`
    * `s = pl.Series(...)`

Next steps:
* Move other functionality out of the internals module

_(This will gather conflicts like crazy, but is super easy to rebase)_

### CODE REVIEW

**Review by zundertj — APPROVED** [review]
This is all good,, works well. I think we should also start removing references to `internals` as much as possible, seems it is being overused in general, probably as a result of the split this introduces in the first place.

**Comment by alexander-beedie** [comment]
I was a bit late to #7506, but this PR looks very promising; feels a bit less indirected 👍

**Comment by stinodego** [comment]
> I think we should also start removing references to `internals` as much as possible, seems it is being overused in general, probably as a result of the split this introduces in the first place.

I'll definitely get on that once I've moved all the stuff out of `internals` and have it in a 'logical' place. Then I'll see if I can get rid of that indirection altogether.

> I wasn't really feeling a further level of indirection through a "reexport"

May be a lack of proper explanation on my part - I never intended to introduce more indirection. Just keep the current form of indirection but perhaps rename it for clarity. But as I said, I hope I can set things up to avoid the need for this entirely.

**Comment by alexander-beedie** [comment]
Gets my vote.

**Comment by ghuls** [comment]
If the circular imports can be removed in the future, that would be great. This might then allow the use of `mypyc` to make heavy python functions (e.g. some of the constructors) a bit faster.

**Comment by ritchie46** [comment]
I leave this to you guys. :)

**Comment by stinodego** [comment]
All right, then I'll go ahead with this and the follow-up work 👍

**Pull request merged**
