### PR TITLE
python polars 0.17.5

### PR DESCRIPTION
**Pull request by ritchie46**
There were some issues with 0.17.4, so I try again. :crossed_fingers:

### CODE REVIEW

**Comment by ritchie46** [comment]
@messense have you got an idea what the failure of this run could be? https://github.com/pola-rs/polars/actions/runs/4722003204/jobs/8375999068

It get's killed everytime. :/

**Comment by messense** [comment]
Out of memory?

**Comment by messense** [comment]
Maybe you can try add swap: https://github.com/marketplace/actions/set-swap-space

**Comment by ritchie46** [comment]
> e

Thanks, I will give that a try. :+1:

**Pull request merged**
