### PR TITLE
Supporting Avro Reader

### PR DESCRIPTION
**Pull request by illumination-k**
## PR

Supporting avro reader in rust. (related to #1063)

I implement avro reader, but avro writer is a bit difficult because arrow2 doesn't support serializing `LargeUtf8Array`.
This is maybe because Avro has only a String schema, and maybe we cannot distinguish `LargeUtf8` and `Utf8` from schema.

If you think there is a value in avro reader alone, I will expose this to python and convert draft to PR.

## Question

If we implement avro writer, maybe we should cast `LargeUtf8` to `Utf8`, but I think this way is not a good idea because users assume that they are using `LargeUtf8`. Can you give me advice for this?

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Thanks, @illumination-k !

I have PRed a small change to arrow2 to allow writing large utf8/binary, https://github.com/jorgecarleitao/arrow2/pull/825

**Comment by ritchie46** [comment]
Awesome! I think this is valuable. I think this format also lends itself well for the lazy version `scan_*`.

**Comment by ritchie46** [comment]
It looks good to me @illumination-k. Thanks. Can I already merge this one? That would prevent some conflicts cause by this beast: #2573

**Comment by illumination-k** [comment]
@ritchie46 Sure. I will create a new PR to export Python.

**Pull request merged**
