### PR TITLE
feat[rust, python]: start supporting sql

### PR DESCRIPTION
**Pull request by ritchie46**
#2871

This is kickstarted by @potter420. Now it is time to finally include it in the python bindings.

Users can start using it and request functionality we miss.

image

### CODE REVIEW

**Comment by chitralverma** [comment]
@ritchie46  do you think there is any easy way to convert the optimized plan back to SQL query string ?

**Comment by ritchie46** [comment]
Not an easy way. We'd need to make a reverse mapping for that.

**Comment by hengaini2055** [comment]
Why support SQL? Using SQL is a bad idea. I think polars is lightening fast and expressive. Using SQL in polars will lose all.

**Comment by chitralverma** [comment]
> Why support SQL? 

it's a standard and it gives a lot of cross tools inter operability

> Using SQL is a bad idea. I think polars is lightening fast and expressive. Using SQL in polars will lose all.

polars already supports SQL, do you feel it's slow ?

**Pull request merged**
