### PR TITLE
Python: activate extension

### PR DESCRIPTION
**Pull request by ritchie46**
This allows to put any python object
in DataFrames and use them in the expression
API.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
brutal

**Comment by jorgecarleitao** [comment]
fyi @wes @pitrou: this uses Arrow's extension type to carry Python objects in arrow (via `FixedBinaryArray`). I find it to be an unexpected and cool use of the extension type.

**Comment by pitrou** [comment]
Interesting. I suppose you shouldn't send them over IPC? :-)

**Comment by ritchie46** [comment]
> Interesting. I suppose you shouldn't send them over IPC? :-)

Definitely not. :see_no_evil:  If you serialize and load in another process it will panic. Currently it checks a `pid`, but I wonder if I can add more safe rails.

**Comment by jorgecarleitao** [comment]
Cc @wesm (now with the correct handle)

**Comment by wesm** [comment]
I recall there is a C++ Jira issue from 2-3 years back about embedding PyObject* effectively like this

**Pull request merged**
