### PR TITLE
fix: Fix `from_arrow` for struct type

### PR DESCRIPTION
**Pull request by delsner**
# Motivation

Using an arrow `struct` column type in an arrow table causes `from_arrow` to fail with the following error message:

```
tests/unit/dataframe/test_df.py:210: in test_from_arrow
    df = cast(pl.DataFrame, pl.from_arrow(b))
polars/convert/general.py:433: in from_arrow
    arrow_to_pydf(
polars/_utils/construction/dataframe.py:1171: in arrow_to_pydf
    elif isinstance(column.type, pa.StructType) and column.num_chunks > 1:
E   AttributeError: 'pyarrow.lib.StructArray' object has no attribute 'num_chunks'
```

# Changes

* Fix `arrow_to_pydf` function to first check for the `num_chunks` attribute 
* Update unit test
* Ruff updates

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks, can you add a test?

**Comment by delsner** [comment]
anything else that I should include in the PR @ritchie46?

**Review by ritchie46 — APPROVED** [review]
Thank you @delsner

**Comment by AlexH-BoxFish** [comment]
I ran into this same issue and while this fix does work, I was wondering if the [pa.StructType](https://arrow.apache.org/docs/python/generated/pyarrow.StructType.html) can ever have a `num_chunks` method? From the docs it doesn't look like it. 

The only type I can see with a `num_chunks` method is [pa.ChunkedArray](https://arrow.apache.org/docs/python/generated/pyarrow.ChunkedArray.html), so perhaps there's another bug in this block?

**Pull request merged**
