### PR TITLE
fix: Return correct value for `when().then().else()` on structs when using `first()`\`last()`

### PR DESCRIPTION
**Pull request by barak1412**
Fixes https://github.com/pola-rs/polars/issues/18961.

### CODE REVIEW

**Comment by ritchie46** [comment]
Nice, can you add a test?

**Comment by barak1412** [comment]
@ritchie46 

When this PR will be merged, https://github.com/pola-rs/polars/pull/18930 will fix `assert_frame_equal`, and the existing test will verify it.
Do you want me to add a separate test?

**Comment by ritchie46** [comment]
>  Do you want me to add a separate test?

Yes, that won't hurt. :)

**Comment by barak1412** [comment]
@ritchie46 

Sure! I will try get to it afternoon, if not - on sunday.
Thanks.

**Comment by barak1412** [comment]
@ritchie46 Added test.

**Comment by ritchie46** [comment]
Thank you @barak1412

**Pull request merged**
