### PR TITLE
chore(python): Partially avoid hard-coded list of deps in show_versions

### PR DESCRIPTION
**Pull request by zundertj**
If all dependencies would be lazy imported, we could get rid of the hard coded list altogether.

### CODE REVIEW

**Comment by zundertj** [comment]
To follow up on this, I would be willing to make the other third-party dependencies lazy loaded as well if that is desired. It would be one pattern across the code base, although I'm not sure there are downsides versus importing at runtime?

**Review by ritchie46 — APPROVED** [review]
LGTM, though I'd like to leave this to @alexander-beedie  or @stinodego.

**Review by stinodego — COMMENTED** [review]
My initial feeling is that this adds some complexity but doesn't really solve the problem. Maybe it does, but only partially. So now we still have the problem, and also more complexity. That doesn't feel like progress to me.

But this part of the code is not really my wheelhouse - I'll defer to @alexander-beedie

**Comment by zundertj** [comment]
> My initial feeling is that this adds some complexity but doesn't really solve the problem. Maybe it does, but only partially. 

Hence my PR description:

> If all dependencies would be lazy imported, we could get rid of the hard coded list altogether.

In terms of complexity, I disagree that what is effectively* one line of code (and should really be in dependencies, not in `show_versions` in the first place) is adding complexity. I.e. this is the line:

```python
    third_party_lazy = [
        s
        for s in polars.dependencies.__all__
        if not s.startswith("_") and s not in sys.system_modules
    ]
```
Imo it outweighs maintaining multiple lists of dependencies across the code base, which has resulted in incorrect output multiple times already.


*: it needs a bit more code to deal with Python < 3.10, that will drop out over time

**Comment by stinodego** [comment]
I am closing this PR as stale.

Revisiting this module is probably still a good idea though.

**Pull request closed without merging**
