### PR TITLE
feat(rust,python): Serializable UDFs (User-Defined Functions) Expressions

### PR DESCRIPTION
**Pull request by cchudant**
Hello :wave: 

We use Polars at Mithril Security, and, we want to serialize LazyFrames & Logical Plans containing UserDefinedFunctions (UDFs). There is also an issue for this: #4569, for pickling of python UDFs.

This is fairly hard :sweat_smile:, but this PR is our attempt at laying out how it would work.

Basically, there are a few new pieces:

## Serialization
- UDF traits (just `polars_lazy::dsl::SeriesUdf` in this example but it could be every UDF traits) would have a new method
```rs
    #[cfg(feature = "serde")]
    fn as_serialize(&self) -> Option<(&str, &dyn erased_serde::Serialize)> {
        None // default implementation (not serializable)
    }
```
&
```rs
#[cfg(feature = "serde")]
impl serde::Serialize for dyn SeriesUdf {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let (ty, obj) = self.as_serialize().ok_or_else(|| {
            serde::ser::Error::custom("Cannot this SeriesUdf user defined function type.")
        })?;

        crate::udf_registry::serialize_udf(ty, obj, serializer)
    }
}
```
- The idea is that downstream crates (like pypolars) would implement UDF traits (RenameAliasFn) for Py<PyFunction> or equivalent, and have them implement serde Serialize too
- `udf_registry::serialize_udf` just feeds the Serializer the equivalent of `{ "type": <string repr of type>, "data": <data> }` in JSON
- Downstream crates that dont need serialization can just keep using the API as they do now.
- We use dtolnay's erased_serde crate, not really any other choice here ; but I think this is justified and ok
- Serialization is fairly straightforward!

## Deserialization
Now, the hard part: Deserialization
- We want to deserialize types like `Arc<dyn SeriesUdf>`
- Approach here is to use a runtime Type Registry: basically, for every UDF trait, a map between type repr (string) -> deserialize function
- Having a non-global type registry is probably better – this is in contrast to dtolnay's [typetag](https://docs.rs/typetag/latest/typetag/) crate, which makes a global registry. This is up for debate.
- However, the big issue here is that serde's Deserialize trait & derive macros dont have any way to get a type registry passed into the deserialize function
  - This can be solved using creating a deserialize-specific type that implements DeserializeSeed, but you cannot just derive it
  - Serde's derive macros generate a ton of code and accessors, this makes it very painful to implement by hand... and we have to sync up with whatever derive Serialize is doing
  - i tried to think of a way of solving this by wrapping the Deserializer instance, but i think this is still impossible
- The approach here is to have a RegistryDeserializable, where you can pass a type registry along when deserializing a struct
  - this is a copy of serde's Deserialize, and we can just reuse Deserialize for parts that don't need type registries
  - this is still a huge pain

## Questions
Having said that, I'd like your feedback on a few things:
- is it all worth it? does polars want to pay the cost of serializable UDFs?
  - if that is not the case, that's ok, but this is still something we need at Mithril so we will have to do this on a downstream community crate anyway
- does this approach make sense / is it satisfactory?
  other approaches may include:
  - typetag (global type registry & not portable because of weird linker magic)
  - i don't know any other approach, except maybe `bevy_reflect`, but it doesn't actually support deserializing nested trait objects iiuc
- improving on this approach
  - adding macros? remove per-udf trait boilerplate
  - a derive macro? for RegistryDeserializable, which would work like serde derive
  - putting all of this into its own crate (serde_type_registry?)
  - implement serialization for Python functions
- final question: maybe serde just isnt our friend
  - i think we can make it all work using serde, but maybe it's not worth it, and we should implement our own thing
  - i don't know

--- 

@ritchie46

### CODE REVIEW

**Comment by ritchie46** [comment]
> This is fairly hard sweat_smile,

Oof! I agree. I am curious if you can make it work! :crossed_fingers:

**Comment by cchudant** [comment]
@ritchie46 
> > This is fairly hard sweat_smile,
> 
> Oof! I agree. I am curious if you can make it work! crossed_fingers

So, I decided to try doing it using a global registry, this is way way easier than passing a registry and creating a new trait...
I added a static OnceCell that contains the registry.

Next, I think we will implement the UDF traits on a struct in pypolars that wraps a python function. This way, we will be able to serialize/deserialize python UDFs :)
We have a custom ser/deser format for UDFs in our python code, so I want to be able to provide serializer/deserializer functions from the python api too.

Also: There are many UDFs in polars. Most of them are just internal functions that can be refactored into enums
One example: https://github.com/pola-rs/polars/blob/b04c8b56b994a0830276c90cba7828b0af4f848a/polars/polars-lazy/polars-plan/src/dsl/expr.rs#L286-L293
Do you mind if we refactor those into enums?

**Comment by ritchie46** [comment]
Those udfs should not matter as they are already defined from enums. See https://github.com/pola-rs/polars/tree/master/polars/polars-lazy/polars-plan/src/dsl/function_expr

They would not be serialized. Only `AnonymousFunction`s have to be translated to `Function`.

**Comment by cchudant** [comment]
@ritchie46 
> Those udfs should not matter as they are already defined from enums. See https://github.com/pola-rs/polars/tree/master/polars/polars-lazy/polars-plan/src/dsl/function_expr
> 
> They would not be serialized. Only `AnonymousFunction`s have to be translated to `Function`.
Sorry i meant 
https://github.com/mithril-security/polars/blob/b04c8b56b994a0830276c90cba7828b0af4f848a/polars/polars-lazy/polars-plan/src/dsl/mod.rs#L623-L643
This one, for example

I didnt know about it, but i'm realizing now that it's a bigger issue than i thought, as pypolars is using them extensively
https://github.com/mithril-security/polars/blob/857ffa18af60b4945bf9b97afd2605d95a35f75b/py-polars/src/lazy/apply.rs#L123-L139

My approach works when all of the serializable UDFs types implement their traits by hand, and implement Serialize and Deserialize using the registry
Wrapping a closure in another one won't work :(

**Comment by cchudant** [comment]
@ritchie46 Hi there!

I think I'm pretty much done here

I'm sorry this PR got a bit big :sweat_smile: 

Here is the summary of the changes:

### Python PyPolars

The API has been changed, you can now do:
```py
df = pl.DataFrame({ "a": range(0, 100) })

def my_map_fn(el: int) -> int:
    return el + 1

ldf = df.lazy().select(pl.col("foo").map(my_map_fn))

# new pickle_udf argument, to use the pickle serializer
json = ldf.write_json(None, pickle_udf=True) 

# same for deserialization
ldf2 = pl.LazyFrame.from_json(json, pickle_udf=True)
```
Using custom Serializer/Deserializer functions:
```py
class MyCustomSerializer(pl.UdfSerializer):
    def serialize_udf(self, udf: Callable) -> Union[str, bytes]:
        pass

    def deserialize_udf(self, data: Union[str, bytes]) -> Callable:
        pass

custom_ser = MyCustomSerializer()

json = ldf.write_json(None, udf_serializer=custom_ser) 
ldf2 = pl.LazyFrame.from_json(json, udf_serializer=custom_ser)
```

### Low level details

Serialization in polars_lazy
- serde feature now depends on the erased_serde crate
- most important file is definitely `polars/polars-lazy/polars-plan/src/dsl/udf.rs`
  - RenameAlias, GetOutput, SeriesUdf traits have been merged: trait SerializableUdf
  - this trait supports being Serialized using an `as_serialize` upcast method
  - for deserialization however, downstream crates (like pypolars) need to register their Deserialize function inside a static OnceCell called UDF_DESERIALIZER.

----

There is currently some kind of fragmentation on how expressions are handled right now in polars_lazy
-> Some Expressions have their own enum variant, making them serializable
-> Some expressions, like is_finite(), round(), every list methods etc use `Expr::AnonymousFunction`, with a rust closure for their evaluation. There is absolutely no way to serialize/deserialize this, since this uses a rust closure instance.
I have started to refactor a lot of operators from the second case into Expr enum variants:
- new file `polars/polars-lazy/polars-plan/src/dsl/function_expr/numeric.rs` defines variants for
  - is_finite, is_infinite, round, floor, ceil, abs, upper_bound, lower_bound, log, exp
  - cumsum, cumprod, cummin, cummax, cumcount
  - row wise folds: sum, any, all, min, max
- string ops variants:
  - split, split_inc, split_exact, split_exact_inc, splitn
- struct rename_fields variant
- datetime to datetime and to duration

-> I'd like to continue this refactor later, in another PR

----

GetOutput in polars_lazy
- this trait does not exist anymore
- instead, i refactored the way we get the output fields from expressions into a util module called get_output
  - surface API has been changed, although in most cases it's just s/GetOutput::/get_output::/
  - this does not use closures wrapped in a thousand Arcs anymore like GetOutput::map_fields/map_dtype etc did, it only uses static typing
  - i'm ok with bringing back the GetOutput type as a type alias on an Arc Fn if you think this is a bad idea
  - Expr::get_field also uses this get_output:: util module now

----
 
polars_lazy Physical Plan
- evaluation in the physical plan does not use the SeriesUdf anymore, instead it uses a new trait SeriesEval

**Comment by cchudant** [comment]
@ritchie46 Hi :wave: 

I'd like to have a first review on the PR before rebasing it on master :)

**Comment by ritchie46** [comment]
Thanks @cchudant. I hope to do this upcoming weekend.

**Comment by cchudant** [comment]
@ritchie46 
> Thanks @cchudant. I hope to do this upcoming weekend.

Hello! What is the status of your review?
Maybe it's too big..? Do you want me to split this PR into 2/3 smaller PRs and keep the changes very minimal and incremental?

**Comment by graceyangfan** [comment]
@ritchie46 @cchudant I am trying to imply some Serializable UDFs for my factor computing,does it means If I want this original power of polars,I must imply  SeriesUdf for my fucntions in rust?No possible to imply from python?

**Comment by stinodego** [comment]
I am closing this as stale.

I respect the significant work that has gone into this, but this would need a rebase before it can be reviewed. If you're up for that, please ping Ritchie first to ask if this work is PR would still be welcome.

**Comment by ritchie46** [comment]
Oh, I am terrivle sorry about this one @cchudant. I totally forgot about this one. Was it succesful at the time?

**Pull request closed without merging**
