### PR TITLE
update installation instructions nodejs-polars

### PR DESCRIPTION
**Pull request by ritchie46**
@universalmind303 this is correct right?

### CODE REVIEW

**Review by universalmind303 — APPROVED** [review]
sounds good. I had it as `polars` thinking we might use that namespace, but good catch!

**Comment by chyzwar** [comment]
https://www.npmjs.com/package/polars is also owned by you? why publishing under node-polars ?

**Comment by ritchie46** [comment]
> https://www.npmjs.com/package/polars is also owned by you? why publishing under node-polars ?

Because it is not usable in default javascript, only node-js. It uses a compiled polars library. 

The plan is to use `polars` for a `webassembly` build.

**Comment by chyzwar** [comment]
ok, I see.

It seems that username polars on npm is still free
https://www.npmjs.com/~polars

If you own this username, you can publish packages as @polars/node and @polars/webassembly etc
Even if you are not planning to do this now. It is worth to register that user.

You could use package.json export to use single name for published module both node and browser https://nodejs.org/api/packages.html#package-entry-points

```
{
  "exports": {
    "node": "./node/index.js"
    "browser": "./webassembly/index.js"
  }
}
```

Unfortunately, this might be not fully supported by JS ecosystem, notably Typescript.

**Pull request merged**
