### PR TITLE
feat: support 'hive partitioning' aware readers

### LINKED ISSUE #10980: Use with_columns addition to a lazy frame with filter to prevent physically reading files
### Problem description

Say I have a big parquet file

If I do:

```
(
    pl.scan_parquet("https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet")
    .with_columns(someflag=5)
    .filter(pl.col('someflag')==6)
    .collect()
)
```

I would think that it could "see" that someflag is always 5 without actually looking at the file and then, given that the filter only keeps instances where someflag==6, that it wouldn't download the file. However it does download the file.

Of course it begs the question why would I ever do that?

I'm trying to think of a way to make scanning a cloud dataset (in particular a hive partition) faster. It seems that using scan_pyarrow_dataset ends up opening every file even when a hive partition and filter should tell it to only open one file. Maybe this is just something that happens with Azure but that's my frame of reference.

I wanted to try to essentially walk my hive partitions and then concat all the parquet files to a list of scan_parquets. However on each of the scan_parquets I "attach" a with_columns that would add the columns for the hive so I'd have something like

```
df=pl.concat([
    pl.scan_parquet("my/path/year=2020/month=5/part-0.parquet").with_columns(year=pl.lit(2020), month=pl.lit(5)),
    pl.scan_parquet("my/path/year=2020/month=6/part-0.parquet").with_columns(year=pl.lit(2020, month=pl.lit(6)),
    pl.scan_parquet("my/path/year=2020/month=7/part-0.parquet").with_columns(year=pl.lit(2020, month=pl.lit(7)),
    pl.scan_parquet("my/path/year=2020/month=8/part-0.parquet").with_columns(year=pl.lit(2020, month=pl.lit(8))
])
```

From that I was hoping I could do

```
df.filter((pl.col("year")==2020) & (pl.col("month")==5)).collect()
```

Here's a snippet of an explain:

```
UNION
  PLAN 0:
    FILTER [([(col("year")) == (2022)]) & ([(col("month")) == (11)])] FROM

     WITH_COLUMNS:
     [2023.alias("year"), 4.alias("month")]

        PYTHON SCAN 
        PROJECT */11 COLUMNS
  PLAN 1:
    FILTER [([(col("year")) == (2022)]) & ([(col("month")) == (11)])] FROM

     WITH_COLUMNS:
     [2019.alias("year"), 5.alias("month")]

        PYTHON SCAN 
        PROJECT */11 COLUMNS
```

In looking at this, I'm guessing it performs tasks from the bottom up. Could it parse that the combination of with_columns and filter can exclude the python scan and skip it like partition pruning in postgres?

### PR DESCRIPTION
**Pull request by ritchie46**
closes #10980, https://github.com/pola-rs/polars/issues/10276

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Nice! Hive partitioning support is super-useful 👍

**Comment by ritchie46** [comment]
> Nice! Hive partitioning support is super-useful 👍

Yes, especially the savings are potentially huge!

**Comment by ion-elgreco** [comment]
Closes also this: https://github.com/pola-rs/polars/issues/10276

**Comment by uditrana** [comment]
I am noticing an interesting pattern/bug with this feature.
I wrote a large dataset out using
```
df.write_parquet(
            file=DIR,
            use_pyarrow=True,
            pyarrow_options={
                "partition_cols": ["part_id_1", "part_id_2"],
                "basename_template": "test_{i}.parquet",
                "existing_data_behavior": "overwrite_or_ignore",
            },
        )
```
When I read these files back in using `pl.read_parquet()`, I observe 2 different results:
```
df1 = pl.read_parquet(DIR / "part_id_1=1" / "part_id_2="A" / "test_0.parquet")
df2 = pl.read_parquet(DIR / "part_id_1=1" / "part_id_2="A" / "*test_0.parquet")
```
In `df1`, `part_id_1` and `part_id_2` are missing from the columns, while they are present in `df2`. Basically, seems that `read_parquet` will not look for hive-partitioning structure if it is passed a single file, and even though in the second case it is reading only one file... the fact that the pattern could include multiple causes it to pick up the structure correctly.

**Comment by uditrana** [comment]
Also, slightly tangentially, could it make sense to expose an option to include an option to turn off schema extension for `hive partition columns`? I have a use case where I am running into this error while trying to read a dataset:
```
ComputeError: invalid hive partitions

Extending the schema with the hive partitioned columns creates duplicate fields.
```
This dataset was written in a way to keep the partition columns in the partitioned dataframes so that other libraries (like Pandas) can read the dataframes individually and concatenate serially (since they don't support Hive natively yet).

**Pull request merged**
