### PR TITLE
Establish more coding styles and formatting by introducing pre-commit

### PR DESCRIPTION
**Pull request by FlorianWilhelm**
Pre-commit allows to automatically apply code formatters like `black` at each commit. Additional checks include:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
  - id: isort
  - id: black
  - id: flake8

### CODE REVIEW

**Comment by FlorianWilhelm** [comment]
Okay, seems like `isort` revealed several circular import problems which were concealed with the help of absolute imports like `import polars ...` within the polars package. The reorg would be somewhat larger... don't know if you would want that @ritchie46 .

**Comment by FlorianWilhelm** [comment]
@ritchie46, I deactivated `isort` so this PR basically only cleans for mixed line endings, new-lines, black (as before), trailing whitespaces, and orders the requirements.txt.
I still feel that the circular imports and absolute imports like `import polars` in `frame.py` should be fixed but this could be done in another PR.

**Comment by ritchie46** [comment]
I see usefulness in things like checking `trailing-whitespace` etc. However I just don't like pre-commit in my workflow. I'd be willing to add those checks in a `Makefile` under `fmt`. 

There also seems some duplication in checks. For instance, I think that `flake8` already does the `ast` check, making `check-ast` redundant.

**Comment by FlorianWilhelm** [comment]
@ritchie46, fair enough. Thanks for pointing out the redundancy. So
```
id: trailing-whitespace
id: check-added-large-files
id: check-ast
id: check-json
id: check-merge-conflict
id: check-xml
id: check-yaml
id: debug-statements
id: end-of-file-fixer
id: requirements-txt-fixer
id: mixed-line-ending
```
are checks that directly come with `pre-commit`. Any additions like `flake8` are wrappers to the corresponding tools, thus there can be redundancies that can easily be resolved by deactivating e.g. `check-ast`. Also `pre-commit` allows you to install it as hook using `pre-commit install` or you can decide to not do that and just ran it manually whenever you want with `pre-commit run --all-files` just like a `Makefile`. To replicate what `pre-commit` does at least for the internal checks like `end-of-file-fixer` in a Makefile, one would need to clone the repo [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks/) manually and maybe reprogram quite a lot to run it in the same way as pre-commit does. To be honest, I would not want to provide a PR for that, sorry. Please feel free to reject this PR then.

Just of curiosity, what's your take on circular dependencies like the ones I showed above, i.e. when I activated `isort` they were revealed and only didn't happen before due to how imports were sorted and applied. This also means that sometimes switching from `import module` to from module import something` will fail as explained [here](https://stackoverflow.com/questions/22187279/python-circular-importing). Is this something you want to fix or is it just fine?

Analogously, the question arises for having absolute imports for your own package like `import polars`. Within a package, I choose to use always relative imports as I think that the code of a package should not know its own package name just like methods refer to other methods with `self.` instead of the actual object reference's name. It also makes it more explicit that the functionality comes from within the package. But I might be a bit too rigorous in this aspect. 

Happy to hear your thoughts about my two points.

**Comment by ritchie46** [comment]
>   To be honest, I would not want to provide a PR that replicates the functionality of pre-commit just to not have it in the workflow, sorry. 

No worries, I dont ask you to. :)

I will take a look if I can find some union that will please pre-commit users and myself. 

> Just of curiosity, what's your take on circular dependencies like the ones I showed above, i.e. when I activated isort they were revealed and only didn't happen before due to how imports were sorted and applied. This also means that sometimes switching from import module to from module import something will fail as explained here. Is this something you want to fix or is it just fine?

No, this bites me longer than this. I wanted `isort` earlier, but the circular imports already blew off some earlier restructuring with a growing dislike of python. There is cirular reference from `DataFrame` to `Series` and vice versa. It has not been a large priority, but I need to draw out a graph of the dependency and see how I can create a DAG from them.

**Comment by carnarez** [comment]
@FlorianWilhelm, since style and formatting is also something itching on my end (thanks for submitting this PR) I just looked a bit further in the list of the included `pre-commit` hooks that you suggested, assuming those should only be applied to the `Python` codebase (*e.g.*, `^*.py$`; a `git` pre-commit for `Rust` seems overkill knowing the peculiarity of the compiler, and successful compilation could be tested via `GitHub Actions`).

Below some food for thought:

* ~~`check-json`~~ should not need to run.
* ~~`check-xml`~~ should not need to run.
* ~~`check-yaml`~~ should not need to run.
* ~~`trailing-whitespace`~~ already checked by `flake8` (see [this](https://www.flake8rules.com/rules/W291.html)).
* ~~`check-merge-conflict`~~ is ruled out by `black` and `flake8` (non-functional `Python`).
* ~~`debug-statements`~~ could be done by using `flake8` [plugin](https://github.com/jbkahn/flake8-debugger) (for instance).
* ~~`end-of-file-fixer`~~ is mostly taken care of by IDE these days, but also by `flake8` (see [this](https://www.flake8rules.com/rules/W292.html) [that](https://www.flake8rules.com/rules/W391.html); two rules?!).
* ~~`mixed-line-ending`~~ could be fixed with a `sed` (old-school!) or `git add --renormalize .` call, or in the `.gitattributes` (see [this](https://git-scm.com/docs/gitattributes#_end_of_line_conversion)).
* ~~`check-ast`~~ isn't in my opinion that helpful; a simple functional test of the branch by the reviewer should rule this out. And `black` and/or `flake8` should also immediately pick it up.

The ones I could not really find any replacement:

* `requirements-txt-fixer` seems to be anecdotic. Do you have any experience with it?
* `check-added-large-files` is an interesting suggestion. Can be checked by the reviewer, and could already be accounted by a tuned up `.gitignore`, but might be needed on the long run.

Some of those are purely aesthetic, and although nice to have remain nice to have. I also believe most are already taken care of, or could simply be transformed into actual calls in the `fmt:` recipe of the `Makefile` (`black`, `flake8` and `isort` for instance, and I would include `mypy` to this list).

@ritchie46 I think the circular imports and other `from . import *` caught by `isort`, together with the output of `mypy`, are a lot more concerning however. This DAG would be a good start... 😉

**Comment by ritchie46** [comment]
I am closing this for now. I may serve as inspiration for a more slimmed down version of pre-commit or make jobs. Thanks @FlorianWilhelm.

**Pull request closed without merging**
