### PR TITLE
Support creating Series from mixed python objects if all else fails.

### PR DESCRIPTION
**Pull request by ghuls**

### CODE REVIEW

**Comment by ghuls** [comment]
It still prints the backtrace if pyarrow is not installed.
```python
In [8]: vals = [[12], "foo", 9]

In [9]: a = pl.Series("a", vals)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'TypeError'>, value: TypeError("'str' object cannot be interpreted as an integer"), traceback: Some(None) }', src/list_construction.rs:26:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

In [10]: a
Out[10]: 
shape: (3,)
Series: 'a' [o][object]
[
	[12]
	foo
	9
]
```

**Comment by ghuls** [comment]
It also can not figure out how to catch `PanicException` (catches `BaseExeception` for now).

**Comment by ritchie46** [comment]
Thanks @ghuls. I think we must look if we can throw an error instead of panic during list creation.

**Comment by ghuls** [comment]
> Thanks @ghuls. I think we must look if we can throw an error instead of panic during list creation.

Yes, trowing an error instead of panicking would be way better.

**Pull request merged**
