### PR TITLE
feat(python, rust): add "raise_if_empty" flag to `read_excel`, `read_csv`, `scan_csv`, and `read_csv_batched`

### LINKED ISSUE #10379: read_excel Returns NoDataError when loading an empty sheet
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl

df_temp = pl.read_excel(
    source='Empty_Workbook.xlsx',
    sheet_name='Sheet1'
)

```
[Empty_Workbook.xlsx](https://github.com/pola-rs/polars/files/12296676/Empty_Workbook.xlsx)

### Issue description

If Polars is asked to read an empty Excel sheet, it returns the below error:

```
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\project\scratch.py", line 17, in <module>
    df_temp = pl.read_excel(
  File "C:\Users\user\PycharmProjects\project\venv\lib\site-packages\polars\io\excel\functions.py", line 187, in read_excel
    return _read_excel_sheet(parser, None, sheet_name, read_csv_options)
  File "C:\Users\user\PycharmProjects\project\venv\lib\site-packages\polars\io\excel\functions.py", line 207, in _read_excel_sheet
    return read_csv(csv_buffer, **read_csv_options)
  File "C:\Users\user\PycharmProjects\project\venv\lib\site-packages\polars\io\csv\functions.py", line 351, in read_csv
    with _prepare_file_arg(
  File "C:\Users\user\PycharmProjects\project\venv\lib\site-packages\polars\io\_utils.py", line 110, in _prepare_file_arg
    return _check_empty(
  File "C:\Users\user\PycharmProjects\project\venv\lib\site-packages\polars\io\_utils.py", line 184, in _check_empty
    raise NoDataError(f"empty CSV data from {context}{hint}")
exceptions.NoDataError: empty CSV data from StringIO
```

### Expected behavior

The empty sheet was read successfully, so I think Polars should return an empty dataframe rather than an error.

This would match the way Pandas handles the same issue.

The following code returns an empty dataframe rather than an error:

```python
import pandas as pd

df_1 = pd.read_excel('Empty_Workbook.xlsx', sheet_name='Sheet1')
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.3
pandas:              2.0.2
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
None
```

</details>

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #10379.

**Feature**:

* Allows the caller to set `raise_if_empty=False`; if set, an empty (zero-column) frame is returned where we would usually raise a `NoDataError` (eg: when given zero-byte CSV files or an Excel file that contains no sheet data of any kind).
* If the flag is not explicitly set then the existing behaviour (raising an error) is maintained; zero-byte/empty files are usually indicative of a real error somewhere and we shouldn't mask this by default.

**Miscellaneous**:

* Normalises string-case of the _"empty CSV"_ error string in `NoDataError`; was lower-case if raised from `scan_csv` and upper-case when raised from `read_csv`.
* Additional docstring detail for methods with a file-like `source` param.
* De-spaghettifies the `read_excel` function :)
* Adds test coverage for all of the updated methods. 

Note: this parameter is not necessary for Parquet/IPC read methods, as those cannot be valid and zero byte, or valid but empty and without a schema that we can read.

### CODE REVIEW

**Comment by ritchie46** [comment]
I can understand the change of choosing an empty `DataFrame` as default. Though, I'd like to see this parameter implemented on the rust side to keep feature parity.

**Comment by alexander-beedie** [comment]
> I can understand the change of choosing an empty `DataFrame` as default. Though, I'd like to see this parameter implemented on the rust side to keep feature parity.

Good point; will rework accordingly (though the default remains raising an error; no change there).

**Comment by ritchie46** [comment]
Eh.. yes, you are right. The opt-int default. ^^

**Comment by alexander-beedie** [comment]
Almost done; `scan_csv` now working with the flag pushed down to Rust; will finish-up `read_csv` after some lunch.

**Review by ritchie46 — APPROVED** [review]

**Pull request merged**
