### PR TITLE
[Rust] Fix `DataFrame::max` remaining thread

### PR DESCRIPTION
**Pull request by ibENPC**
### Problem
The problem was already encountered here #1838
[Rayon](https://docs.rs/rayon/latest/rayon/) and [Miri](https://github.com/rust-lang/miri) are incompatible unless we manage a [ThreadPoolBuilder](https://docs.rs/rayon/1.5.1/rayon/struct.ThreadPoolBuilder.html) manually in order to limit the scope thanks to the `build_scoped` method (or we pass `-Zmiri-ignore-leaks` to `cargo miri`).

The following error is triggered when using `cargo miri`:
```text
error: the main thread terminated without waiting for all remaining threads
```

### New `DataFrame::max` function
The problem is spread across the crate. I have chosen this single case for the moment.
```rust
pub fn max(&self) -> Self {
    DataFrame::new_no_checks(
        rayon::ThreadPoolBuilder::new()
            .build_scoped(
                |thread| thread.run(),
                |pool| {
                    pool.install(|| {
                        self.columns.par_iter().map(|s| s.max_as_series()).collect()
                    })
                },
            )
            .expect("Scoped Rayon ThreadPool failed for DataFrame::max"),
    )
}
```
The code is ugly but we may use a macro to fix the different cases.

### Performance

This slows down a lot the runtime only for small `DataFrame`s. Otherwise we only loose few percents of runtime.

If we want to privilege the safety provided by [Miri](https://github.com/rust-lang/miri) it seems worth it.

### CODE REVIEW

**Comment by ritchie46** [comment]
Hmm... This should use the default threadpool `POOL` instead of building a new threadpool. 

Creating a new threadpool has a startup cost I don't want to pay, and can also lead to high contention when we build threadpools in another parallel operation, or multiple.

The example should be changed to the default threadpool and we should accept that `miri` cannot handle rayon for now.

**Comment by ibENPC** [comment]
Tell me if I understand well:
- This PR can be closed.
- We should continue to use [Rayon](https://docs.rs/rayon/latest/rayon/) for straightforward data-parallelism in the crate.
- All the tests that imply the use of [Rayon](https://docs.rs/rayon/latest/rayon/) should be stated `no_run` as long as [Miri](https://github.com/rust-lang/miri) cannot handle this particular [Rayon](https://docs.rs/rayon/latest/rayon/) issue.

**Comment by ritchie46** [comment]
> This PR can be closed.

Yes. But for another PR, we should use the global threadpool instead of naively calling `columns.par_iter`. Here is an example where we use the correct threadpool. https://github.com/pola-rs/polars/blob/fafde8d8a7f052ed3f7b01be36cf64ec89218d58/polars/polars-lazy/src/physical_plan/expressions/filter.rs#L43

> We should continue to use Rayon for straightforward data-parallelism in the crate.

Definitely!

> All the tests that imply the use of Rayon should be stated no_run as long as Miri cannot handle this particular Rayon issue.

Jup.

**Comment by ibENPC** [comment]
Oh indeed [Polars](https://pola-rs.github.io/polars/polars/index.html) has its own [ThreadPool](https://docs.rs/rayon/1.5.1/rayon/struct.ThreadPool.html).

https://github.com/pola-rs/polars/blob/fafde8d8a7f052ed3f7b01be36cf64ec89218d58/polars/polars-core/src/lib.rs#L28

I can try to fix this issue.

**Pull request closed without merging**
