### PR TITLE
feat(rust, python): Add support for UTF-8 BOM option in `write_csv` and `sink_csv`

### LINKED ISSUE #12241: Add support for UTF-8 BOM option in CSV Output
### Description

While polars can only output CSV in UTF-8 encoding, the default encoding in Windows is ANSI.
This causes problems as an application may not correctly interpret non-ASCII characters, when they cannot detect the correct UTF-8 encoding.
In particular, some applications does not allow users to specify the default encoding (e.g. Excel).

A easy way to solve this issue is to use the UTF-8 Byte Order Mark (BOM).
Simply add the 3-byte magic sequence at the beginning of the file, the application can recognize the encoding as UTF-8 with BOM.
And there is no need to convert the data.

Currently, I am achieving this by explicitly writing the BOM in the code, like this:

```python
# Current
with open('a_file_path.csv', 'wb') as f:
    utf8bom = ''.encode('utf_8_sig')
    f.write(utf8bom)
    df.write_csv(f)
```

I believe it would be convenient if this functionality could be provided through the polars API.
Specifically, I am proposing the following addition:

```python
# New option for write_csv & sink_csv
"""
has_bom: bool = False
    Whether to include BOM in the CSV output.
"""
df.write_csv('a_file_path.csv', has_bom=True)
```

I would like to discuss the following points and seek input:

1. Minimalism:
While this feature is relatively simple, it does add an extra option to write_csv and sink_csv.
Given the minimalism of these API, would it be acceptable?

2. Naming:
I used "has_bom" as the parameter name in the example.
Are there alternative names or suggestions, such as "has_utf8bom," that would be more suitable?

3. Parameter position:
I will place "has_bom" after "has_header", considering the nature and meaning of the parameter.
Is there a more suitable position?

If these are resolved, I am willing to start the implementation and create a pull request.

### PR DESCRIPTION
**Pull request by hirohira9119**
Closes #12241 

I have created this as draft for a discussion on some points: acceptance, naming, parameter position, etc.
Feedbacks would be greatly appreciated.

1. Acceptance:
While this feature is relatively simple, it does add an extra option to write_csv and sink_csv.
Given the minimalism of these API, would it be acceptable?

2. Naming:
I used "has_bom" as the parameter name.
Are there alternative names or suggestions, such as "has_utf8bom," that would be more suitable?

3. Parameter position:
I placed "has_bom" after "has_header", considering the nature and meaning of the parameter.
Is there a more suitable position?

### CODE REVIEW

**Comment by ritchie46** [comment]
I think it is good to have BOM writing possibilities, but we can skip the `has_bom` as polars already check for the utf8 bom and skips it. Can you remove that logic?

**Comment by hirohira9119** [comment]
Thank you for the review. I did identify the feature to check for the BOM, which is used when reading (`skip_bom` function). But I couldn't locate a corresponding logic for writing. Would it be possible for you to provide more information on the features related to the BOM in writing?

**Comment by ritchie46** [comment]
Right, for writing this needs to be added. My bad, I thought this also added reader options.

**Comment by hirohira9119** [comment]
Thanks for the clarification. I understand.

I originally chose the name "has_bom" to align with "has_header", but now recognize that it could be misleading as if it represents the input source already has a BOM.
Therefore, I plan to change the name to "with_bom", referring to the encoding name in several text editors.

And I will rearrange the order of the arguments, placing 'with_bom' before 'has_header.'  This is because the BOM appears at the first in CSV files. (initially I positioned it behind as the second 'has_xx' variable, but due to the name change, I believe it would be better to align it with the order of appearance).

I will make another commit for these.
After the commit is complete, I will move the status to "Ready for Review".

**Comment by alexander-beedie** [comment]
> I plan to change the name to "with_bom"

I would suggest `include_bom`, which probably sounds more like a directive 🤔

**Comment by hirohira9119** [comment]
Wow, 日本語でのコメントありがとうございます:smile:

And thank you for the suggestion. Now that you have mentioned it, I also think `include_bom` is more appropriate.
So I have committed the change.

**Comment by ritchie46** [comment]
@hirohira9119 are you willing to make a follow up PR on the writing side to replace `has_header` with `include_header`?

**Comment by hirohira9119** [comment]
> 2年前まで東京に住んでいました :)
> 残念ながら日本語を忘れています!

いえいえ、自然な日本語ですよ:) 
東京だったのですね！私はその隣の神奈川県に居ました。日本の生活を楽しんでいただけていたら幸いです :wink:

> FYI: you can use the following decorator to make it a non-breaking change; this will temporarily allow both parameters, but issue a DeprecationWarning when the old parameter name is used 👍

Thank you for the advice! I've created a new PR using this feature. 
And now I noticed that it has been already approved.
Probably this PR become conflicts, so I'll rebase and resolve it.

**Comment by stinodego** [comment]
@hirohira9119 I merged your other PR, seems to have caused some conflicts here. Would you mind doing a rebase here?

**Comment by hirohira9119** [comment]
@stinodego 
Thank you for the approval on the other PR. I've resolved the conflict on this end, but I apologize as I mistakenly create a merge commit instead of a rebase while resolving it on GitHub. Would it be better to redo it with a rebase? (I'll rebase locally and force push again.)

**Comment by stinodego** [comment]
> Would it be better to redo it with a rebase?

Doesn't matter much - it's fine this way!

**Comment by hirohira9119** [comment]
Is there anything else that I need to do? The tasks originally intended for this PR were completed a few days ago.
In case there are ongoing reviews, I am happy to wait.

**Comment by alexander-beedie** [comment]
@stinodego, any last updates/requests on this one? 
(looking good to me 👍)

**Review by alexander-beedie — APPROVED** [review]

**Pull request merged**
