### PR TITLE
Remove newlines from dependencies to fix Python `sdist`

### LINKED ISSUE #10366: `sdist` broken for 0.18.12 and 0.18.13
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pip install polars-0.18.13.tar.gz
```

### Issue description

Building from the sdist doesn't work as there is a line break in the `local_dependencies/polars-arrow/Cargo.toml` file for the `dependencies.arrow` section. This line break was introduced with the 0.18.12 sdist and didn't exist with 0.18.13. I can reproduce it locally. Changing the maturin version didn't have an effect for me, so this is probably not the culprit.
```
Processing $SRC_DIR
  Added file://$SRC_DIR to build tracker '/tmp/pip-build-tracker-lbgzb9xw'
  Created temporary directory: /tmp/pip-modern-metadata-vn7qaqi2
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  Checking for Rust toolchain....
  Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-vn7qaqi2 --interpreter /home/conda/feedstock_root/build_artifacts/polars_1691175902057/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python`
  error: failed to load manifest for dependency `polars`

  Caused by:
    failed to load manifest for dependency `polars-algo`

  Caused by:
    failed to load manifest for dependency `polars-core`

  Caused by:
    failed to load manifest for dependency `polars-arrow`

  Caused by:
    failed to parse manifest at `/home/conda/feedstock_root/build_artifacts/polars_1691175902057/work/local_dependencies/polars-arrow/Cargo.toml`

  Caused by:
    could not parse input as TOML
```

### Expected behavior

`pip install polars-0.18.13.tar.gz` installs `polars`.

### Installed versions

Output of `conda build` in this case:

```
    _libgcc_mutex:    0.1-conda_forge            conda-forge
    _openmp_mutex:    4.5-2_gnu                  conda-forge
    bzip2:            1.0.8-h7f98852_4           conda-forge
    ca-certificates:  2023.7.22-hbcca054_0       conda-forge
    ld_impl_linux-64: 2.40-h41732ed_0            conda-forge
    libffi:           3.4.2-h7f98852_5           conda-forge
    libgcc-ng:        13.1.0-he5830b7_0          conda-forge
    libgomp:          13.1.0-he5830b7_0          conda-forge
    libnsl:           2.0.0-h7f98852_0           conda-forge
    libsqlite:        3.42.0-h2797004_0          conda-forge
    libuuid:          2.38.1-h0b41bf4_0          conda-forge
    libzlib:          1.2.13-hd590300_5          conda-forge
    maturin:          0.14.17-py310h4426083_0    conda-forge
    ncurses:          6.4-hcb278e6_0             conda-forge
    openssl:          3.1.2-hd590300_0           conda-forge
    pip:              23.2.1-pyhd8ed1ab_0        conda-forge
    python:           3.10.12-hd12c33a_0_cpython conda-forge
    python_abi:       3.10-3_cp310               conda-forge
    readline:         8.2-h8228510_1             conda-forge
    setuptools:       68.0.0-pyhd8ed1ab_0        conda-forge
    tk:               8.6.12-h27826a3_0          conda-forge
    tomli:            2.0.1-pyhd8ed1ab_0         conda-forge
    tzdata:           2023c-h71feb2d_0           conda-forge
    wheel:            0.41.0-pyhd8ed1ab_0        conda-forge
```

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #10366

### CODE REVIEW

**Comment by xhochy** [comment]
Yes, sadly this fixes it. I have verified this using `maturin sdist -m py-polars/Cargo.toml` and then `pip install`ing the resulting sdist.

**Comment by xhochy** [comment]
I can make an issue with maturin in the coming days.

**Comment by ritchie46** [comment]
See: https://github.com/PyO3/maturin/issues/1732

**Comment by stinodego** [comment]
I think @messense just released a patch version of maturin that should solve the issue - I'll set our minimum version to `1.2.1`. So this PR can be closed.

**Pull request closed without merging**
