### PR TITLE
Fix parquet example

### PR DESCRIPTION
**Pull request by horahh**
* Current example data is in csv format
* Create a convertion to parquet first to be able to run the example

### CODE REVIEW

**Comment by horahh** [comment]
first time commiting here, shoud I create an issue? I observed few of the examples are not running due to files not availabe in the expected format.

**Comment by universalmind303** [comment]
try running `make generate_test_files` before the tests. It should generate the necessary files for the tests & examples.

**Comment by ritchie46** [comment]
As @universalmind303, the repo must be prepared. Maybe we can add a section on this in the contribution guide. Or in the readme of the examples folder.

**Comment by stinodego** [comment]
To be honest, I think it's better to just include the generated datasets in the repo. They are small enough, and it will solve issues like this and some issues in our Rust test suite where tests are order-dependent.

What do you think?

This adjustment to the example is definitely undesirable, so I will close this PR.

**Pull request closed without merging**
