### PR TITLE
refactor(rust): Remove top-level metadata from `ArrowSchema`

### PR DESCRIPTION
**Pull request by nameexhaustion**
Preparation for unifying schemas to `struct Schema<D>`

### CODE REVIEW

**Review by ritchie46 — APPROVED** [review]

**Comment by lukapeschke** [comment]
Hi, I have a question about this change: we're currently using polars v0.41.3, and use `polars_arrow::ipc::write::stream_async::StreamSink` to serialize our dataframes to arrow IPC data. We were using `ArrowSchema::with_metadata` to add custom applicative metadata at the schema level. 

Is it still possible to add schema-level metadata with polars v0.43 ? If yes, could you please point me to the right resources ? Thanks!

**Comment by nameexhaustion** [comment]
> Is it still possible to add schema-level metadata with polars v0.43 ? If yes, could you please point me to the right resources ? Thanks!

We don't intend on adding schema-level metadata to the `ArrowSchema`, however we plan to add functions to the reader / writers to load / save custom metadata.

**Comment by lukapeschke** [comment]
@nameexhaustion great thanks! Do you have a specific polars release for which this is planned ? If not, could I help on that in any way ?

**Comment by nameexhaustion** [comment]
> @nameexhaustion great thanks! Do you have a specific polars release for which this is planned ? If not, could I help on that in any way ?

There's an open issue for this at https://github.com/pola-rs/polars/issues/17560

**Pull request merged**
