### PR TITLE
feat(python): Improve `read_excel` to also use `openpyxl` for better type inferring

### PR DESCRIPTION
**Pull request by bvanelli**
Closes https://github.com/pola-rs/polars/issues/5568

Improvements on Excel support for polars, including a new exporter and an importer that does better type inferring, i.e. handling null entries, correctly parsing datetimes, etc.

There are some things to still do:

- [x] Fix pipelines, lint and format it properly, make sure mypy is passing.
- [x] Improve test coverage
- [x] Add openpyxl as optional installable
- [x] Improve the api a little bit 
- [ ] ~~(OPTIONAL) Include basic optional styling~~

### CODE REVIEW

**Comment by alexander-beedie** [comment]
@bvanelli: Thanks for taking a look! However, I suspect that an `xlsxwriter` / `xlsxwriter_rs` approach is likely to be the best way forward, given the native Rust integration (and previous experience with that library).

**Comment by ritchie46** [comment]
> @bvanelli: Thanks for taking a look! However, I suspect that an `xlsxwriter` / `xlsxwriter_rs` approach is going to be the best way forward, given the native Rust integration (and previous experience with that library).

Well.. I really don't think we should ship an excel reader / writer in our binary. It is a format I really don't want to push either. 

Having this as an optional python dependency could be added as a utility function if it doesn't adds much maintenance and complexity.

**Comment by alexander-beedie** [comment]
> Having this as an optional python dependency could be added as a utility function if it doesn't adds much maintenance and complexity.

Ahh, gotcha; in that case I'll take care of it on the Python side, and if it gets traction or there are further pushes for it on the Rust side later we'll be in a good position to translate.

**Comment by bvanelli** [comment]
Currently, the read_excel API uses a non-pythonic array, as the index of sheets start at 1: https://github.com/dilshod/xlsx2csv/blob/3180d9490f64baa25495a8098903acd28f1aa131/xlsx2csv.py#L438

Ideally, the first sheet id should be 0, but I don't want to make changes that could potentially break people's codes, so should I 

- keep the behavior for the new parser the same, starting at 1 or
- make the new behavior for only openpyxl driver, keeping the same for xlsx2csv or
- make both behaviors the same, possibly breaking current implementations

Also thanks @alexander-beedie for fixing the `format_path` issue, it was driving me insane because it always ran fine in my local machine but not on CI 😄

**Comment by ghuls** [comment]
> Currently, the read_excel API uses a non-pythonic array, as the index of sheets start at 1: https://github.com/dilshod/xlsx2csv/blob/3180d9490f64baa25495a8098903acd28f1aa131/xlsx2csv.py#L438

Maybe make an issue there that they should use `None` for all sheets instead of `0`.

**Comment by bvanelli** [comment]
I marked the PR as ready, as I have wrote some tests and improved test coverage for the old reader also.

If possible please someone take a look at how I used the methods on tests, for example the following:

```python
    df_by_sheet_id = pl.read_excel(  # type: ignore[call-overload]
        example_file, sheet_id=1
    )
```

I had to introduce the `ignore[call-overload]` because mypy was complaining. I'm not exactly sure why because I have little experience with mypy. This was also used on the tests from before (see line below, taken from master) so I used it also for my tests, but there must be a reason why it's triggering.

https://github.com/pola-rs/polars/blob/32c97cf924445b73001df5ff5a6a602dc3acf977/py-polars/tests/unit/io/test_excel.py#L18

**Comment by alexander-beedie** [comment]
Ahh, I feel a little bad as I may not have been [clear enough](https://github.com/pola-rs/polars/pull/6183#issuecomment-1379946509) that I was planning to add `write_excel` functionality myself, as I previously wrote some powerful  excel/dataframe export functionality in a previous job and was planning something similar here. I'll check over the PR tomorrow/shortly to see if we can preserve some of it... 😅

**Comment by bvanelli** [comment]
> Ahh, I feel a little bad as I may not have been [clear enough](https://github.com/pola-rs/polars/pull/6183#issuecomment-1379946509) that I was planning to add `write_excel` functionality myself, as I previously wrote some powerful excel/dataframe export functionality in a previous job and was planning something similar here. I'll check over the PR tomorrow/shortly to see if we can preserve some of it... 😅

Ah, sorry, I misunderstood then. I implemented it through engines just like with pandas, so multiple engines can be used, so you can have multiple libraries as optional dependencies. Maybe it can be adapted together?

**Comment by cnpryer** [comment]
Any update on this? I have some use cases for writing to excel where this would be great to have.

Is there a blocker?

**Comment by bvanelli** [comment]
> Any update on this? I have some use cases for writing to excel where this would be great to have.
> 
> Is there a blocker?

I'd like to know also. I can resolve merge conflicts/adapt changes if someone is willing to review it. 😃

**Comment by bvanelli** [comment]
I took a look at the MR, and it looks pretty good from the exporting perspective, however, I still feel like there is stuff missing on the importing perspective, which I think xlsxwriter does not touch. The importer library is ok for simple scenarios but it does not handle data types well, that openpyxl can do natively. See for example my [datatypes test](https://github.com/bvanelli/polars/blob/5568-excel-writer/py-polars/tests/unit/io/test_excel.py#L51).

Also, I feel like the you should include `engine` in your exporter just like pandas does for their read/write excel methods, as in the future one parser/writer written in rust could be added to the available drivers for, let's say, very fast exports. [One example here](https://github.com/bvanelli/polars/blob/5568-excel-writer/py-polars/polars/io.py#L1126).

**Comment by alexander-beedie** [comment]
>  I still feel like there is stuff missing on the importing perspective

Definitely; if you can update your PR to focus on just the import, I'll review - improvements in that area are very welcome 😄 

> Also, I feel like the you should include `engine` in your exporter just like pandas does

I don't see much purpose in doing so. If we _were_ to move to a Rust-based exporter, it would most likely be the Rust version of `xlsxwriter`, in which case we could transition the internals/API pretty transparently.

The main reason pandas offers different engines is that it doesn't actually _do_ anything with them itself; it's more like a trivial bootstrap, eg: _"here's the data, now you're on your own"_. The way I've implemented it here, we actually handle all of the table/sheet relative positioning and format integration so that you can declare what you want on a per-column/dtype basis, while still allowing direct integration with the underlying library - it's a different (and, imho, a more productive/intuitive) approach...

**Comment by bvanelli** [comment]
@alexander-beedie Finally had some time to fix the MR. There are maybe two open points I needed some input:

1) I had to import the DataFrame inside the function to avoid circular imports. I wonder if there is a better way to do it

https://github.com/pola-rs/polars/blob/83cf521d657d03f3a9cb0465444582dc471f1630/py-polars/polars/io/excel/functions.py#L228-L236

2) The readers are fundamentally different, I tried to wrap them on the same API. Unfortunately, the lazy loading of the `read_only=True` does not allow this behavior, as the `wb.close()` *must* be called ([reference](https://openpyxl.readthedocs.io/en/latest/optimized.html#read-only-mode)). If the method raises an exception, then it will not be called. This is better suited for a context handle. If I remove the `read_only`, then the behavior will match, at the cost of reading speed.

https://github.com/pola-rs/polars/blob/83cf521d657d03f3a9cb0465444582dc471f1630/py-polars/polars/io/excel/functions.py#L190

In any case, could someone review the changes? The biggest improvement of the MR is having native data types like boolean and datetime without  manual conversion, which are currently not inferred:

https://github.com/pola-rs/polars/blob/83cf521d657d03f3a9cb0465444582dc471f1630/py-polars/tests/unit/io/test_excel.py#L48-L68

**Comment by stinodego** [comment]
@bvanelli This is good work and I would like to have `openpyxl` support - it's a more modern/feature rich option when compared to `xlsx2csv`, in my opinion.

@alexander-beedie Would you mind taking a look if this PR is ready / can be adopted into our current Excel capabilities?

**Comment by alexander-beedie** [comment]
> @alexander-beedie Would you mind taking a look 

Will do - I'm definitely in favour of improving the read functionality, and having an `openpyxl` option is almost certainly the way to go 👍

**Comment by bvanelli** [comment]
> @bvanelli: would you mind updating/rebasing the PR? Let's see if we can get it in :)

Hello, thanks for the update. I do not mind mind updating/doing changes but I'm currently in vacation away from any computer for a week, so I won't be able able to do it until the 4th of September.

**Comment by bvanelli** [comment]
@alexander-beedie I merged current main into my branch and solved the conflicts. I also slightly updated the documentation to reflect the added features. As a sidenote, here is a benchmark test comparing both libraries:

```python
from __future__ import annotations
import polars as pl
from pathlib import Path


def test_openpyxl() -> None:
    excel_file_path = Path(__file__).parent / "example_benchmark_file.xlsx"
    df = pl.read_excel(excel_file_path, sheet_id=0, engine="openpyxl")


def test_xlsx2csv() -> None:
    excel_file_path = Path(__file__).parent / "example_benchmark_file.xlsx"
    df = pl.read_excel(excel_file_path, sheet_id=0)
```

- xlsx2csv: 1.168 seconds
- openpyxl: 3.303 seconds

I used an excel file with 50k rows and 3 columns.

**Review by alexander-beedie — APPROVED** [review]

**Comment by s-banach** [comment]
Haha, I saw this months ago and kept wondering if it was ever going to be added. 🚀

**Pull request merged**
