### PR TITLE
feat[rust]: Use zlib-ng again for decompressing gzipped CSV files (#3…

### PR DESCRIPTION
**Pull request by ghuls**
…895)-

Use zlib-ng again for decompressing gzipped CSV files:
  - zlib-ng does not decompress the gzipped input when the buffer is not Vector:new() or a buffer of the exact size of the decompressed output.
  - Use zlib-ng library does not need to be compiled in zlib compatibility mode for polars, so use zlib-ng native API.

### CODE REVIEW

**Comment by ghuls** [comment]
Just found an issue where they had the same problem:
https://github.com/rust-lang/flate2-rs/issues/308

**Comment by ritchie46** [comment]
Thank @ghuls. Coukd you elaborate a bit more on those two bullet points? I have forgotten what the original issue was and what now has been resolved.

**Comment by ghuls** [comment]
When flate2 uses `miniz_oxide` or `zlib`, the old code works.
When flate2 uses `zlib-ng` or `zlib-ng-compat`, only the new code works. With the old code, out would contain the compressed data, which will result later in Utf8 validation problems. Before zlib-sys 1.15, it worked with `zlib-ng-compat`, (older polars versions): https://github.com/rust-lang/libz-sys/issues/104

Here is a test file that didn't work before: https://temp.aertslab.org/.tsv/atac_fragments.head40000000.tsv.gz
```diff
-            // decompression will likely be an order of magnitude larger
-            let mut out = Vec::with_capacity(bytes.len() * 10);
+            // decompression in a preallocated buffer does not work with zlib-ng
+            // and will put the original compressed data in the buffer.
+            let mut out = Vec::new();
```

As we are not linking in other libraries that need zlib, we can use the zlib-ng API in non compatibility mode.

**Comment by MichaelMcDonnell** [comment]
FYI, the issue https://github.com/rust-lang/flate2-rs/issues/308 was not a bug in `flate2` but the in code that was using it. I suspect your code might have had the same issue.

**Pull request merged**
