### PR TITLE
DRAFT: feat(python): Add keys and align_on options for pl.concat

### LINKED ISSUE #8753: Add `keys` and `names` arguments and accept dict inputs to `pl.concat`
### Problem description

A common pattern is concatenating a sequence of dataframes with keys and adding the keys as columns (undoing `partition_by` essentially). For example, if keyed by `id` and `date`, I would currently do

```python
pl.concat(
    [
        df1.with_columns(id=pl.lit("a"), date=pl.lit(date(2023, 1, 1))),
        df2.with_columns(id=pl.lit("b"), date=pl.lit(date(2023, 1, 2))),
    ]
)
```

In pandas `pd.concat` has `keys`/`names` arguments for this, which would be nice to have in polars as well. Then I could just write something like
```python
pl.concat([df1, df2], names=["id", "date"], keys=[("a", date(2023, 1, 1)), ("b", date(2023, 1, 2))])
```

Another ergonomic improvement would be to support keyed dicts like in pandas:

```python
pl.concat({("a", date(2023, 1, 1)): df1, ("b", date(2023, 1, 2)): df2}, names=["id", "date"])
```

### LINKED ISSUE #8807: Add align_on parameter to pl.concat when horizontal is used
### Problem description

Possibly an addition to #8753. A relatively common operation is to align multiple dataframes and combine them. We already have an [`align_frames`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.align_frames.html) function, but has this note:

> Note that this does not result in a joined frame - you receive the same number of frames back that you passed in, but each is now aligned by key and has the same number of rows.

After aligning, you have to go through frames 2-N and drop the key columns. A nice feature would be either to have `pl.concat(dfs, how="horizontal", align_on=keys)`, or a separate `pl.align_and_join`. Something like this:

```python
import polars as pl

df1 = pl.DataFrame({
    "key": [1, 2, 3],
    'a': [4, 5, 6],
})

df2 = pl.DataFrame({
    "key": [1, 3, 4],
    'b': [7, 8, 9],
})

df3 = pl.concat([df1, df2], how="horizontal", align_on="key")

     df1                   df2                       df3
┌─────┬──────┐        ┌─────┬──────┐        ┌─────┬──────┬──────┐
│ key ┆ a    │        │ key ┆ b    │        │ key ┆ a    ┆ b    │
╞═════╪══════╡        ╞═════╪══════╡        ╞═════╪══════╪══════╡
│ 1   ┆ 4    │        │ 1   ┆ 7    │        │ 1   ┆ 4    ┆ 7    │
│ 2   ┆ 5    │        │ 3   ┆ 8    │  --->  │ 2   ┆ 5    ┆ null │
│ 3   ┆ 6    │        │ 4   ┆ 9    │        │ 3   ┆ 6    ┆ 8    │
└─────┴──────┘        └─────┴──────┘        │ 4   ┆ null ┆ 9    │
                                            └─────┴──────┴──────┘
```

### PR DESCRIPTION
**Pull request by mcrumiller**
resolves #8753 - Not sure if this is wanted by other people, but it seems like a nice feature to have.

resolves #8807 

These are separate features but makes sense to go into the same PR once a consensus is reached.

### CODE REVIEW

**Comment by mcrumiller** [comment]
FYI all tests pass on my local version, the failing test here is in `tests\unit\test_fmt.py`.

**Comment by mcrumiller** [comment]
I think I'm on the correct path via [Type Narrowing](https://mypy.readthedocs.io/en/stable/type_narrowing.html#type-narrowing).

**Comment by mcrumiller** [comment]
Woot! Got it working. Had to create new `TypeGuard` sequence tests in `various.py`.

It would be simpler if someone could get `_is_iterable_of` working with a Type Guard, but I couldn't figure it out.

**Comment by erinov1** [comment]
@mcrumiller thanks for picking this up! I think the discussion from https://github.com/pola-rs/polars/issues/8753 should be continued though before committing to this approach. In particular I think being able to pass a keyed dictionary like
```python
pl.concat({("a", date(2023, 1, 1)): df1, ("b", date(2023, 1, 2)): df2}, names=["id", "date"])
```
 is actually the most ergonomic functionality. For example, consider retrieving a binary blob from an OLAP database:

```python
# `results` is an iterable of tuples, where indices [0, 1] are primary keys and index 2 is a blob
results = query_db()

pl.concat(
    {(res[0], res[1]): convert_blob_to_polars(res[2]) for res in results}, names=["key_1", "key_2"]
)
```

Or loading files from a hive-style partitioned store:

```python
pl.concat(
    {
        (key_1, key_2): pl.scan_parquet(f"{key_1}/{key_2}/file.parquet")
        for key_1, key_2 in keys_to_load
    },
    names=["key_1", "key_2"],
)
```

I'm also curious about the choice in this PR to specify the keys as a dictionary. In the natural use cases above, having to specify

```python
{
    "key1": [value1, value2, value3, ...],
    "key2": [value1, value2, value3, ...]
}
```
instead of tuples of `names` and `keys` (like in pandas) requires transposing/unzipping the keys in an awkward way.

**Comment by mcrumiller** [comment]
@erinov1 I'm not married to any one approach and was planning on having others chime in with alterations. I've never used OLTP or a hive-partioned store, so that syntax looks pretty darn foreign to me, but that may just be due to my lack of experience in this matter. I went with the dictionary approach since it seemed the most straightforward to me, but I'm definitely open for discussion.

**Pull request closed without merging**
