### PR TITLE
feat(python): clarify "inefficient map_elements warning" message

### PR DESCRIPTION
**Pull request by MarcoGorelli**
This came up on Discord:

> because when you read it, it's quite strange. Replace map_elements by more map_elements

To be fair, the current message:
```diff
In this case, you can replace your `map_elements` with the following:
- pl.col("a").map_elements(lambda x: ...)
+ ((pl.col("a") * 9) / 5) + 32
```
might be confusing if you don't immediately recognise it as a git diff

I'm suggesting to make it much simpler:
```diff
Don't do this:
- pl.col("a").map_elements(lambda x: ...)
Do this instead:
+ ((pl.col("a") * 9) / 5) + 32
```

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Yup, streamlining it sounds like a good idea :)
How about changing the "Don't do this" / "Do this instead" pair to...

```diff
Replace this expression...
- pl.col("a").map_elements(lambda x: ...)
with this instead:
+ ((pl.col("a") * 9) / 5) + 32
```
?

**Comment by stinodego** [comment]
I also prefer a more 'official' tone.

**Review by stinodego — APPROVED** [review]
Thanks Marco!

**Comment by MarcoGorelli** [comment]
thanks for your reviews, and agree on the better wording

**Review by ritchie46 — APPROVED** [review]

**Pull request merged**
