### PR TITLE
test(rust, python): don't set aggregated flag on null propagated aggregation.

### LINKED ISSUE #6185: Errors when aggregating on empty filtered column and its mean, redux
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I commented on https://github.com/pola-rs/polars/issues/6074, but I figure it's easier to open to a new issue for posterity. https://github.com/pola-rs/polars/pull/6076 fixed part of the problem, but the following two examples still raise errors:

```python
import polars as pl

df_1 = pl.DataFrame(
    {"A": [0, 0], "B": [1, 2]}
)

df_2 = pl.DataFrame(
    {"A": [0, 0] * 2, "B": [1, 2] * 2}
)

expr = pl.col("A").filter(pl.col("A") > 0)
```

The following aggregation with `df_1` raises an error:

```python
df_1.groupby("B").agg((expr - expr.mean()).mean())

ComputeError: Cannot aggregate as mean. The column is already aggregated.
```

The same aggregation with `df_2` transiently raises

```python
# May need to run several times
df_2.groupby("B").agg((expr - expr.mean()).mean())

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `2`', /Users/runner/work/polars/polars/polars/polars-lazy/src/physical_plan/expressions/mod.rs:209:17
```

### Reproducible example

```python
import polars as pl

df_1 = pl.DataFrame(
    {"A": [0, 0], "B": [1, 2]}
)

df_2 = pl.DataFrame(
    {"A": [0, 0] * 2, "B": [1, 2] * 2}
)

expr = pl.col("A").filter(pl.col("A") > 0)

df_1.groupby("B").agg((expr - expr.mean()).mean())

df_2.groupby("B").agg((expr - expr.mean()).mean())
```

### Expected behavior

In both cases the result should be

```python
shape: (2, 2)
┌─────┬──────┐
│ B   ┆ A    │
│ --- ┆ ---  │
│ i64 ┆ f64  │
╞═════╪══════╡
│ 1   ┆ null │
│ 2   ┆ null │
└─────┴──────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: macOS-10.15.7-x86_64-i386-64bit
Python: 3.8.12 (default, Oct 18 2021, 20:31:01) 
[Clang 10.0.1 (clang-1001.0.46.4)]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.4.4
numpy: 1.21.5
fsspec: 2022.01.0
connectorx: 0.3.0
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
partially fix for #6185

### CODE REVIEW

**Comment by ritchie46** [comment]
This is strange. This runs perfectly fine if I run it locally.

**Comment by thomasfrederikhoeck** [comment]
I see the error locally on Windows an py-polars 0.15.14 with pl.build_info() in details.

<details>
```
{'build': {'rustc': 'rustc',
  'rustc-version': 'rustc 1.68.0-nightly (935dc0721 2022-12-19)',
  'opt-level': '3',
  'debug': False,
  'jobs': 2},
 'info-time': datetime.datetime(2023, 1, 8, 12, 46, 52, tzinfo=datetime.timezone.utc),
 'dependencies': {'adler': '1.0.2',
  'adler32': '1.2.0',
  'ahash': '0.8.2',
  'aho-corasick': '0.7.20',
  'alloc-no-stdlib': '2.0.4',
  'alloc-stdlib': '0.2.2',
  'android_system_properties': '0.1.5',
  'anyhow': '1.0.68',
  'array-init-cursor': '0.2.0',
  'arrow-format': '0.8.1',
  'arrow2': '0.15.0',
  'async-stream': '0.3.3',
  'async-stream-impl': '0.3.3',
  'async-trait': '0.1.60',
  'autocfg': '1.1.0',
  'avro-schema': '0.3.0',
  'base64': '0.13.1',
  'bincode': '1.3.3',
  'bitflags': '1.3.2',
  'brotli': '3.3.4',
  'brotli-decompressor': '2.3.2',
  'built': '0.5.2',
  'bumpalo': '3.11.1',
  'bytemuck': '1.12.3',
  'bytemuck_derive': '1.3.0',
  'byteorder': '1.4.3',
  'bytes': '1.3.0',
  'cargo-lock': '8.0.3',
  'cc': '1.0.78',
  'cfg-if': '1.0.0',
  'chrono': '0.4.23',
  'chrono-tz': '0.6.3',
  'chrono-tz-build': '0.0.3',
  'codespan-reporting': '0.11.1',
  'comfy-table': '6.1.4',
  'const-random': '0.1.15',
  'const-random-macro': '0.1.15',
  'core-foundation-sys': '0.8.3',
  'crc': '2.1.0',
  'crc-catalog': '1.1.1',
  'crc32fast': '1.3.2',
  'crossbeam-channel': '0.5.6',
  'crossbeam-deque': '0.8.2',
  'crossbeam-epoch': '0.9.13',
  'crossbeam-utils': '0.8.14',
  'crossterm': '0.25.0',
  'crossterm_winapi': '0.9.0',
  'crunchy': '0.2.2',
  'ctor': '0.1.26',
  'cxx': '1.0.85',
  'cxx-build': '1.0.85',
  'cxxbridge-flags': '1.0.85',
  'cxxbridge-macro': '1.0.85',
  'dirs': '4.0.0',
  'dirs-sys': '0.3.7',
  'dyn-clone': '1.0.10',
  'either': '1.8.0',
  'enum_dispatch': '0.3.9',
  'ethnum': '1.3.2',
  'fallible-streaming-iterator': '0.1.9',
  'flate2': '1.0.25',
  'float-cmp': '0.9.0',
  'foreign_vec': '0.1.0',
  'form_urlencoded': '1.1.0',
  'fs_extra': '1.2.0',
  'futures': '0.3.25',
  'futures-channel': '0.3.25',
  'futures-core': '0.3.25',
  'futures-executor': '0.3.25',
  'futures-io': '0.3.25',
  'futures-macro': '0.3.25',
  'futures-sink': '0.3.25',
  'futures-task': '0.3.25',
  'futures-util': '0.3.25',
  'fxhash': '0.2.1',
  'getrandom': '0.2.8',
  'ghost': '0.1.7',
  'git2': '0.15.0',
  'glob': '0.3.0',
  'halfbrown': '0.1.18',
  'hash_hasher': '2.0.3',
  'hashbrown': '0.13.1',
  'heck': '0.4.0',
  'hermit-abi': '0.2.6',
  'hex': '0.4.3',
  'iana-time-zone': '0.1.53',
  'iana-time-zone-haiku': '0.1.1',
  'idna': '0.3.0',
  'indexmap': '1.9.2',
  'indoc': '1.0.8',
  'instant': '0.1.12',
  'inventory': '0.2.3',
  'itoa': '1.0.5',
  'jemalloc-sys': '0.5.2+5.3.0-patched',
  'jemallocator': '0.5.0',
  'jobserver': '0.1.25',
  'js-sys': '0.3.60',
  'json-deserializer': '0.4.4',
  'jsonpath_lib': '0.3.0',
  'lexical': '6.1.1',
  'lexical-core': '0.8.5',
  'lexical-parse-float': '0.8.5',
  'lexical-parse-integer': '0.8.6',
  'lexical-util': '0.8.5',
  'lexical-write-float': '0.8.5',
  'lexical-write-integer': '0.8.5',
  'libc': '0.2.139',
  'libflate': '1.2.0',
  'libflate_lz77': '1.1.0',
  'libgit2-sys': '0.14.0+1.5.0',
  'libm': '0.2.6',
  'libmimalloc-sys': '0.1.28',
  'libz-sys': '1.1.8',
  'link-cplusplus': '1.0.8',
  'lock_api': '0.4.9',
  'log': '0.4.17',
  'lz4': '1.24.0',
  'lz4-sys': '1.9.4',
  'matrixmultiply': '0.3.2',
  'memchr': '2.5.0',
  'memmap2': '0.5.8',
  'memoffset': '0.7.1',
  'mimalloc': '0.1.32',
  'miniz_oxide': '0.6.2',
  'mio': '0.8.5',
  'multiversion': '0.6.1',
  'multiversion-macros': '0.6.1',
  'ndarray': '0.15.6',
  'now': '0.1.3',
  'num': '0.4.0',
  'num-bigint': '0.4.3',
  'num-complex': '0.4.2',
  'num-integer': '0.1.45',
  'num-iter': '0.1.43',
  'num-rational': '0.4.1',
  'num-traits': '0.2.15',
  'num_cpus': '1.15.0',
  'numpy': '0.16.2',
  'once_cell': '1.17.0',
  'parking_lot': '0.12.1',
  'parking_lot_core': '0.9.5',
  'parquet-format-safe': '0.2.4',
  'parquet2': '0.17.1',
  'parse-zoneinfo': '0.3.0',
  'percent-encoding': '2.2.0',
  'phf': '0.11.1',
  'phf_codegen': '0.11.1',
  'phf_generator': '0.11.1',
  'phf_shared': '0.11.1',
  'pin-project-lite': '0.2.9',
  'pin-utils': '0.1.0',
  'pkg-config': '0.3.26',
  'planus': '0.3.1',
  'polars': '0.26.1',
  'polars-arrow': '0.26.1',
  'polars-core': '0.26.1',
  'polars-io': '0.26.1',
  'polars-lazy': '0.26.1',
  'polars-ops': '0.26.1',
  'polars-pipe': '0.26.1',
  'polars-plan': '0.26.1',
  'polars-sql': '0.2.2',
  'polars-time': '0.26.1',
  'polars-utils': '0.26.1',
  'ppv-lite86': '0.2.17',
  'proc-macro-hack': '0.5.20+deprecated',
  'proc-macro2': '1.0.49',
  'py-polars': '0.15.14',
  'pyo3': '0.16.6',
  'pyo3-build-config': '0.16.6',
  'pyo3-built': '0.4.7',
  'pyo3-ffi': '0.16.6',
  'pyo3-macros': '0.16.6',
  'pyo3-macros-backend': '0.16.6',
  'quote': '1.0.23',
  'rand': '0.8.5',
  'rand_chacha': '0.3.1',
  'rand_core': '0.6.4',
  'rand_distr': '0.4.3',
  'rawpointer': '0.2.1',
  'rayon': '1.6.1',
  'rayon-core': '1.10.1',
  'redox_syscall': '0.2.16',
  'redox_users': '0.4.3',
  'regex': '1.7.0',
  'regex-syntax': '0.6.28',
  'rle-decode-fast': '1.0.3',
  'rustc_version': '0.4.0',
  'rustversion': '1.0.11',
  'ryu': '1.0.12',
  'scopeguard': '1.1.0',
  'scratch': '1.0.3',
  'semver': '1.0.16',
  'seq-macro': '0.3.2',
  'serde': '1.0.152',
  'serde_derive': '1.0.152',
  'serde_json': '1.0.91',
  'signal-hook': '0.3.14',
  'signal-hook-mio': '0.2.3',
  'signal-hook-registry': '1.4.0',
  'simd-json': '0.7.0',
  'simdutf8': '0.1.4',
  'siphasher': '0.3.10',
  'slab': '0.4.7',
  'smallvec': '1.10.0',
  'smartstring': '1.0.1',
  'snap': '1.1.0',
  'sqlparser': '0.19.0',
  'static_assertions': '1.1.0',
  'streaming-decompression': '0.1.2',
  'streaming-iterator': '0.1.8',
  'strength_reduce': '0.2.4',
  'strum': '0.24.1',
  'strum_macros': '0.24.3',
  'syn': '1.0.107',
  'target-lexicon': '0.12.5',
  'termcolor': '1.1.3',
  'thiserror': '1.0.38',
  'thiserror-impl': '1.0.38',
  'time': '0.1.45',
  'tiny-keccak': '2.0.2',
  'tinyvec': '1.6.0',
  'tinyvec_macros': '0.1.0',
  'toml': '0.5.10',
  'uncased': '0.9.7',
  'unicode-bidi': '0.3.8',
  'unicode-ident': '1.0.6',
  'unicode-normalization': '0.1.22',
  'unicode-width': '0.1.10',
  'unindent': '0.1.11',
  'url': '2.3.1',
  'value-trait': '0.5.1',
  'vcpkg': '0.2.15',
  'version_check': '0.9.4',
  'wasi': '0.11.0+wasi-snapshot-preview1',
  'wasm-bindgen': '0.2.83',
  'wasm-bindgen-backend': '0.2.83',
  'wasm-bindgen-futures': '0.4.33',
  'wasm-bindgen-macro': '0.2.83',
  'wasm-bindgen-macro-support': '0.2.83',
  'wasm-bindgen-shared': '0.2.83',
  'wasm-timer': '0.2.5',
  'web-sys': '0.3.60',
  'winapi': '0.3.9',
  'winapi-i686-pc-windows-gnu': '0.4.0',
  'winapi-util': '0.1.5',
  'winapi-x86_64-pc-windows-gnu': '0.4.0',
  'windows-sys': '0.42.0',
  'windows_aarch64_gnullvm': '0.42.0',
  'windows_aarch64_msvc': '0.42.0',
  'windows_i686_gnu': '0.42.0',
  'windows_i686_msvc': '0.42.0',
  'windows_x86_64_gnu': '0.42.0',
  'windows_x86_64_gnullvm': '0.42.0',
  'windows_x86_64_msvc': '0.42.0',
  'xxhash-rust': '0.8.6',
  'zstd': '0.11.2+zstd.1.5.2',
  'zstd-safe': '5.0.2+zstd.1.5.2',
  'zstd-sys': '2.0.4+zstd.1.5.2'},
 'features': ['ALL',
  'ASOF_JOIN',
  'AVRO',
  'BUILD_INFO',
  'CROSS_JOIN',
  'CSE',
  'CSV_FILE',
  'DECOMPRESS',
  'DEFAULT',
  'EXTRACT_JSONPATH',
  'IPC',
  'IS_IN',
  'JSON',
  'LAZY_REGEX',
  'LIST_TAKE',
  'MERGE_SORTED',
  'META',
  'NIGHTLY',
  'OBJECT',
  'PARQUET',
  'PCT_CHANGE',
  'PERFORMANT',
  'PIVOT',
  'PROPAGATE_NANS',
  'REPEAT_BY',
  'SEARCH_SORTED',
  'SERDE_JSON',
  'SIGN',
  'SQL',
  'STREAMING',
  'TIMEZONES',
  'TOP_K',
  'TRIGONOMETRY'],
 'host': {'triple': 'x86_64-pc-windows-msvc'},
 'target': {'arch': 'x86_64',
  'os': 'windows',
  'family': 'windows',
  'env': 'msvc',
  'triple': 'x86_64-pc-windows-msvc',
  'endianness': 'little',
  'pointer-width': '64',
  'profile': 'release'},
 'git': {'version': 'py-0.15.14',
  'dirty': True,
  'hash': 'b41a8ef75a61a14c726d5accdbbace5610521496',
  'head': None},
 'version': '0.15.14'}
```
<details>

**Comment by alexander-beedie** [comment]
As another datapoint - am also getting `ComputeError: Cannot aggregate as mean. The column is already aggregated.` (on macOS / M1 Max, py3.10)

**Comment by erinov1** [comment]
@alexander-beedie @thomasfrederikhoeck are either of you able to reproduce the error with the second test case as well?

```python
df_2.groupby("B").agg((expr - expr.mean()).mean())
```

Sometimes I have to run this query several times before the error arises.

**Comment by erinov1** [comment]
Thanks. I set `RUST_BACKTRACE=full` for the `df_2.groupby("B").agg((expr - expr.mean()).mean())` query, but it doesn't seem particularly informative:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `2`', /Users/runner/work/polars/polars/polars/polars-lazy/src/physical_plan/expressions/mod.rs:209:17
stack backtrace:
   0:        0x106c05d6a - _ffi_select_with_compiled_path
   1:        0x1059036fa - _BrotliDecoderVersion
   2:        0x106bdbf74 - _ffi_select_with_compiled_path
   3:        0x106c0745a - _ffi_select_with_compiled_path
   4:        0x106c07083 - _ffi_select_with_compiled_path
   5:        0x106c080c5 - _ffi_select_with_compiled_path
   6:        0x106c07bb5 - _ffi_select_with_compiled_path
   7:        0x106c07b20 - _ffi_select_with_compiled_path
   8:        0x106c07af2 - _ffi_select_with_compiled_path
   9:        0x106d30f03 - _ffi_select_with_compiled_path
  10:        0x106d310fc - _ffi_select_with_compiled_path
  11:        0x106db2d76 - _ffi_select_with_compiled_path
  12:        0x10667e109 - _ffi_select_with_compiled_path
  13:        0x106681e04 - _ffi_select_with_compiled_path
  14:        0x10675377b - _ffi_select_with_compiled_path
  15:        0x1067533e9 - _ffi_select_with_compiled_path
  16:        0x106753199 - _ffi_select_with_compiled_path
  17:        0x106de4c9d - _ffi_select_with_compiled_path
  18:        0x106b0f2fb - _ffi_select_with_compiled_path
  19:        0x106b0ee99 - _ffi_select_with_compiled_path
  20:        0x106c0920a - _ffi_select_with_compiled_path
  21:     0x7fff71408109 - __pthread_start

--------------------------------------------
```

Not sure what other info to provide, but here is the output of `pl.build_info()`:

<details>

  <summary>pl.build_info()</summary>

```  
{'build': {'rustc': 'rustc',
  'rustc-version': 'rustc 1.68.0-nightly (935dc0721 2022-12-19)',
  'opt-level': '3',
  'debug': False,
  'jobs': 3},
 'info-time': datetime.datetime(2023, 1, 8, 12, 34, 50, tzinfo=datetime.timezone.utc),
 'dependencies': {'adler': '1.0.2',
  'adler32': '1.2.0',
  'ahash': '0.8.2',
  'aho-corasick': '0.7.20',
  'alloc-no-stdlib': '2.0.4',
  'alloc-stdlib': '0.2.2',
  'android_system_properties': '0.1.5',
  'anyhow': '1.0.68',
  'array-init-cursor': '0.2.0',
  'arrow-format': '0.8.1',
  'arrow2': '0.15.0',
  'async-stream': '0.3.3',
  'async-stream-impl': '0.3.3',
  'async-trait': '0.1.60',
  'autocfg': '1.1.0',
  'avro-schema': '0.3.0',
  'base64': '0.13.1',
  'bincode': '1.3.3',
  'bitflags': '1.3.2',
  'brotli': '3.3.4',
  'brotli-decompressor': '2.3.2',
  'built': '0.5.2',
  'bumpalo': '3.11.1',
  'bytemuck': '1.12.3',
  'bytemuck_derive': '1.3.0',
  'byteorder': '1.4.3',
  'bytes': '1.3.0',
  'cargo-lock': '8.0.3',
  'cc': '1.0.78',
  'cfg-if': '1.0.0',
  'chrono': '0.4.23',
  'chrono-tz': '0.6.3',
  'chrono-tz-build': '0.0.3',
  'codespan-reporting': '0.11.1',
  'comfy-table': '6.1.4',
  'const-random': '0.1.15',
  'const-random-macro': '0.1.15',
  'core-foundation-sys': '0.8.3',
  'crc': '2.1.0',
  'crc-catalog': '1.1.1',
  'crc32fast': '1.3.2',
  'crossbeam-channel': '0.5.6',
  'crossbeam-deque': '0.8.2',
  'crossbeam-epoch': '0.9.13',
  'crossbeam-utils': '0.8.14',
  'crossterm': '0.25.0',
  'crossterm_winapi': '0.9.0',
  'crunchy': '0.2.2',
  'ctor': '0.1.26',
  'cxx': '1.0.85',
  'cxx-build': '1.0.85',
  'cxxbridge-flags': '1.0.85',
  'cxxbridge-macro': '1.0.85',
  'dirs': '4.0.0',
  'dirs-sys': '0.3.7',
  'dyn-clone': '1.0.10',
  'either': '1.8.0',
  'enum_dispatch': '0.3.9',
  'ethnum': '1.3.2',
  'fallible-streaming-iterator': '0.1.9',
  'flate2': '1.0.25',
  'float-cmp': '0.9.0',
  'foreign_vec': '0.1.0',
  'form_urlencoded': '1.1.0',
  'fs_extra': '1.2.0',
  'futures': '0.3.25',
  'futures-channel': '0.3.25',
  'futures-core': '0.3.25',
  'futures-executor': '0.3.25',
  'futures-io': '0.3.25',
  'futures-macro': '0.3.25',
  'futures-sink': '0.3.25',
  'futures-task': '0.3.25',
  'futures-util': '0.3.25',
  'fxhash': '0.2.1',
  'getrandom': '0.2.8',
  'ghost': '0.1.7',
  'git2': '0.15.0',
  'glob': '0.3.0',
  'halfbrown': '0.1.18',
  'hash_hasher': '2.0.3',
  'hashbrown': '0.13.1',
  'heck': '0.4.0',
  'hermit-abi': '0.2.6',
  'hex': '0.4.3',
  'iana-time-zone': '0.1.53',
  'iana-time-zone-haiku': '0.1.1',
  'idna': '0.3.0',
  'indexmap': '1.9.2',
  'indoc': '1.0.8',
  'instant': '0.1.12',
  'inventory': '0.2.3',
  'itoa': '1.0.5',
  'jemalloc-sys': '0.5.2+5.3.0-patched',
  'jemallocator': '0.5.0',
  'jobserver': '0.1.25',
  'js-sys': '0.3.60',
  'json-deserializer': '0.4.4',
  'jsonpath_lib': '0.3.0',
  'lexical': '6.1.1',
  'lexical-core': '0.8.5',
  'lexical-parse-float': '0.8.5',
  'lexical-parse-integer': '0.8.6',
  'lexical-util': '0.8.5',
  'lexical-write-float': '0.8.5',
  'lexical-write-integer': '0.8.5',
  'libc': '0.2.139',
  'libflate': '1.2.0',
  'libflate_lz77': '1.1.0',
  'libgit2-sys': '0.14.0+1.5.0',
  'libm': '0.2.6',
  'libmimalloc-sys': '0.1.28',
  'libz-sys': '1.1.8',
  'link-cplusplus': '1.0.8',
  'lock_api': '0.4.9',
  'log': '0.4.17',
  'lz4': '1.24.0',
  'lz4-sys': '1.9.4',
  'matrixmultiply': '0.3.2',
  'memchr': '2.5.0',
  'memmap2': '0.5.8',
  'memoffset': '0.7.1',
  'mimalloc': '0.1.32',
  'miniz_oxide': '0.6.2',
  'mio': '0.8.5',
  'multiversion': '0.6.1',
  'multiversion-macros': '0.6.1',
  'ndarray': '0.15.6',
  'now': '0.1.3',
  'num': '0.4.0',
  'num-bigint': '0.4.3',
  'num-complex': '0.4.2',
  'num-integer': '0.1.45',
  'num-iter': '0.1.43',
  'num-rational': '0.4.1',
  'num-traits': '0.2.15',
  'num_cpus': '1.15.0',
  'numpy': '0.16.2',
  'once_cell': '1.17.0',
  'parking_lot': '0.12.1',
  'parking_lot_core': '0.9.5',
  'parquet-format-safe': '0.2.4',
  'parquet2': '0.17.1',
  'parse-zoneinfo': '0.3.0',
  'percent-encoding': '2.2.0',
  'phf': '0.11.1',
  'phf_codegen': '0.11.1',
  'phf_generator': '0.11.1',
  'phf_shared': '0.11.1',
  'pin-project-lite': '0.2.9',
  'pin-utils': '0.1.0',
  'pkg-config': '0.3.26',
  'planus': '0.3.1',
  'polars': '0.26.1',
  'polars-arrow': '0.26.1',
  'polars-core': '0.26.1',
  'polars-io': '0.26.1',
  'polars-lazy': '0.26.1',
  'polars-ops': '0.26.1',
  'polars-pipe': '0.26.1',
  'polars-plan': '0.26.1',
  'polars-sql': '0.2.2',
  'polars-time': '0.26.1',
  'polars-utils': '0.26.1',
  'ppv-lite86': '0.2.17',
  'proc-macro-hack': '0.5.20+deprecated',
  'proc-macro2': '1.0.49',
  'py-polars': '0.15.14',
  'pyo3': '0.16.6',
  'pyo3-build-config': '0.16.6',
  'pyo3-built': '0.4.7',
  'pyo3-ffi': '0.16.6',
  'pyo3-macros': '0.16.6',
  'pyo3-macros-backend': '0.16.6',
  'quote': '1.0.23',
  'rand': '0.8.5',
  'rand_chacha': '0.3.1',
  'rand_core': '0.6.4',
  'rand_distr': '0.4.3',
  'rawpointer': '0.2.1',
  'rayon': '1.6.1',
  'rayon-core': '1.10.1',
  'redox_syscall': '0.2.16',
  'redox_users': '0.4.3',
  'regex': '1.7.0',
  'regex-syntax': '0.6.28',
  'rle-decode-fast': '1.0.3',
  'rustc_version': '0.4.0',
  'rustversion': '1.0.11',
  'ryu': '1.0.12',
  'scopeguard': '1.1.0',
  'scratch': '1.0.3',
  'semver': '1.0.16',
  'seq-macro': '0.3.2',
  'serde': '1.0.152',
  'serde_derive': '1.0.152',
  'serde_json': '1.0.91',
  'signal-hook': '0.3.14',
  'signal-hook-mio': '0.2.3',
  'signal-hook-registry': '1.4.0',
  'simd-json': '0.7.0',
  'simdutf8': '0.1.4',
  'siphasher': '0.3.10',
  'slab': '0.4.7',
  'smallvec': '1.10.0',
  'smartstring': '1.0.1',
  'snap': '1.1.0',
  'sqlparser': '0.19.0',
  'static_assertions': '1.1.0',
  'streaming-decompression': '0.1.2',
  'streaming-iterator': '0.1.8',
  'strength_reduce': '0.2.4',
  'strum': '0.24.1',
  'strum_macros': '0.24.3',
  'syn': '1.0.107',
  'target-lexicon': '0.12.5',
  'termcolor': '1.1.3',
  'thiserror': '1.0.38',
  'thiserror-impl': '1.0.38',
  'time': '0.1.45',
  'tiny-keccak': '2.0.2',
  'tinyvec': '1.6.0',
  'tinyvec_macros': '0.1.0',
  'toml': '0.5.10',
  'uncased': '0.9.7',
  'unicode-bidi': '0.3.8',
  'unicode-ident': '1.0.6',
  'unicode-normalization': '0.1.22',
  'unicode-width': '0.1.10',
  'unindent': '0.1.11',
  'url': '2.3.1',
  'value-trait': '0.5.1',
  'vcpkg': '0.2.15',
  'version_check': '0.9.4',
  'wasi': '0.11.0+wasi-snapshot-preview1',
  'wasm-bindgen': '0.2.83',
  'wasm-bindgen-backend': '0.2.83',
  'wasm-bindgen-futures': '0.4.33',
  'wasm-bindgen-macro': '0.2.83',
  'wasm-bindgen-macro-support': '0.2.83',
  'wasm-bindgen-shared': '0.2.83',
  'wasm-timer': '0.2.5',
  'web-sys': '0.3.60',
  'winapi': '0.3.9',
  'winapi-i686-pc-windows-gnu': '0.4.0',
  'winapi-util': '0.1.5',
  'winapi-x86_64-pc-windows-gnu': '0.4.0',
  'windows-sys': '0.42.0',
  'windows_aarch64_gnullvm': '0.42.0',
  'windows_aarch64_msvc': '0.42.0',
  'windows_i686_gnu': '0.42.0',
  'windows_i686_msvc': '0.42.0',
  'windows_x86_64_gnu': '0.42.0',
  'windows_x86_64_gnullvm': '0.42.0',
  'windows_x86_64_msvc': '0.42.0',
  'xxhash-rust': '0.8.6',
  'zstd': '0.11.2+zstd.1.5.2',
  'zstd-safe': '5.0.2+zstd.1.5.2',
  'zstd-sys': '2.0.4+zstd.1.5.2'},
 'features': ['ALL',
  'ASOF_JOIN',
  'AVRO',
  'BUILD_INFO',
  'CROSS_JOIN',
  'CSE',
  'CSV_FILE',
  'DECOMPRESS',
  'DEFAULT',
  'EXTRACT_JSONPATH',
  'IPC',
  'IS_IN',
  'JSON',
  'LAZY_REGEX',
  'LIST_TAKE',
  'MERGE_SORTED',
  'META',
  'NIGHTLY',
  'OBJECT',
  'PARQUET',
  'PCT_CHANGE',
  'PERFORMANT',
  'PIVOT',
  'PROPAGATE_NANS',
  'REPEAT_BY',
  'SEARCH_SORTED',
  'SERDE_JSON',
  'SIGN',
  'SQL',
  'STREAMING',
  'TIMEZONES',
  'TOP_K',
  'TRIGONOMETRY'],
 'host': {'triple': 'x86_64-apple-darwin'},
 'target': {'arch': 'x86_64',
  'os': 'macos',
  'family': 'unix',
  'env': '',
  'triple': 'x86_64-apple-darwin',
  'endianness': 'little',
  'pointer-width': '64',
  'profile': 'release'},
 'git': {'version': 'py-0.15.14',
  'dirty': True,
  'hash': 'b41a8ef75a61a14c726d5accdbbace5610521496',
  'head': None},
 'version': '0.15.14'}
```

</details>

**Comment by ritchie46** [comment]
Can reproduce. A cargo clean seemed to be necessary.

**Comment by ritchie46** [comment]
Note that I cannot reproduce the error reported in the tight loop.

**Comment by ritchie46** [comment]
Reproduced the 2nd one as well.

**Pull request merged**
