### PR TITLE
feat(rust): rewrite log expressions to make them serializable

### PR DESCRIPTION
**Pull request by borchero**
# Motivation

This PR refactors the implementation of the `log` and `exp` expression functions to be serializable. Follow-up from https://github.com/pola-rs/polars/pull/8102#discussion_r1161441842.

_**This PR must be merged after #8102 as it should target that PR's branch.**_

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks @borchero. Can you do a rebase? Then it's good to go.

**Comment by borchero** [comment]
🧹

**Comment by ritchie46** [comment]
Sorry, still needs a rebase. :see_no_evil:

**Comment by borchero** [comment]
Ahh too much progress in this repo :smile:

**Comment by borchero** [comment]
I'm waiting with rebasing #8132 until this is merged.

**Pull request merged**
