### PR TITLE
docs[python]: configure intersphinx and create (some) hyperlinks

### PR DESCRIPTION
**Pull request by fsimkovic**
This is mostly a cosmetic change but I thought external links to pandas, pyarrow, numpy etc are generally quite useful. It configures the intersphinx extension to point to API inventory files which were previously not configured.

### CODE REVIEW

**Comment by ritchie46** [comment]
Could you add some pictures to show what changes and why you want to make this change?

**Comment by fsimkovic** [comment]
Please see two screenshots attached. The main benefit of this change is that specific references (see PR changes) will render with hyperlinks to the external documentation of other packages. Note, this does not happen automatically and does require specifying cross-references explicitly (see [cross-referencing python objects](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html?highlight=module#cross-referencing-python-objects)).

Screenshot 2022-09-02 at 9 46 25 pm
Screenshot 2022-09-02 at 9 46 38 pm

**Comment by fsimkovic** [comment]
I guess we can close this now given https://github.com/geopolars/geopolars/pull/107

**Comment by kylebarron** [comment]
Haha sorry about that! I linked to this branch from my `geopolars` repo as a future reminder of where I got some of the intersphinx ideas 🙂

**Pull request closed without merging**
