### PR TITLE
chore(rust, python): fix typos

### PR DESCRIPTION
**Pull request by ghuls**

### CODE REVIEW

**Comment by alexander-beedie** [comment]
How on earth did you find all of these? 🤣 
You're on 🔥 this week...

**Comment by ritchie46** [comment]
> How on earth did you find all of these? rofl

Aren't you reading polars source code before bedtime. :stuck_out_tongue_winking_eye:

**Comment by ghuls** [comment]
> How on earth did you find all of these? rofl You're on fire this week...

I cheated a bit. Yesterday I found https://github.com/crate-ci/typos by accident.
We probably should add it as an additional lint. It has some false positives that I had to blacklist.

There are still some spelling mistakes left. in the rust code there is still function names and variable names with `splitted` which should be `split` to be proper English:

```
❯ rg 'fn.*splitted'
polars/polars-core/src/frame/hash_join/single_keys_dispatch.rs
145:fn splitted_to_slice<T>(splitted: &[ChunkedArray<T>]) -> Vec<&[T::Native]>
152:fn splitted_by_chunks<T>(splitted: &[ChunkedArray<T>]) -> Vec<&[T::Native]>
162:fn splitted_to_opt_vec<T>(splitted: &[ChunkedArray<T>]) -> Vec<Vec<Option<T::Native>>>
```

```
polars/polars-core/src/frame/hash_join/single_keys_dispatch.rs
polars/polars-lazy/polars-plan/src/dsl/string.rs
polars/polars-core/src/frame/asof_join/groups.rs
```

**Comment by ghuls** [comment]
> > ./polars/polars-utils/src/sort.rs
> 
> Yes

Then it is fixed correctly. I also added "typos" to pre-commit and as a github workflow in #7759.

**Pull request merged**
