### PR TITLE
feat: Allow substraction of time dtype columns

### LINKED ISSUE #19720: Can´t subtract two time columns
### Description

I am not being able to subtract between two pl.Time columns.

I just tested and I can subtract two datetime columns and the resulting column has the duration type but I can´t do the same with two time columns:

image

image

### PR DESCRIPTION
**Pull request by ptiza**
Closes #19720 

Since the documentation specifies the Time dtype as
> The underlying representation of this type is a 64-bit signed integer. The integer indicates the number of nanoseconds since midnight.

we can specify the result of a substraction as a duration with nanosecond time unit.

### CODE REVIEW

**Comment by ptiza** [comment]
closes #19720

**Comment by mcrumiller** [comment]
What about the inverse? If we have t2 - t1 = d, how about t1 + d = t2, i.e. time + duration?

**Comment by ptiza** [comment]
> What about the inverse? If we have t2 - t1 = d, how about t1 + d = t2, i.e. time + duration?

I considered implementing it within this PR but thought it's ultimately another feature.

It also needs to be discussed which behavior we want if d > 24h. Should we even allow it?
If d is the result of a substraction of two Time objects, then the resulting duration is always within 24h.

**Comment by mcrumiller** [comment]
I recall a while back during some AnyValue conversion that @stinodego came up with a set of rules regarding what temporal ops are allowed.

`t2 - t1` will always be a well-defined duration value <= 24hr, but `t + d` may be out-out-bounds and so perhaps is not as well-defined.

**Pull request merged**
