### PR TITLE
add rolling options to remaining rolling functions

### PR DESCRIPTION
**Pull request by marcvanheerden**
Still work in progress.
 
will fix: #1938

### CODE REVIEW

**Comment by ritchie46** [comment]
@marcvanheerden is it still WIP?

**Comment by marcvanheerden** [comment]
Sorry, yes, got a bit busy with Xmas things. Will resume tomorrow. Is that okay?

**Comment by ritchie46** [comment]
Of course. Happy christmas😉

**Comment by marcvanheerden** [comment]
I got a bit far behind from master and I'm worried that I might have made a mistake in the merge conflict resolution, going to close this PR and create a new one. Sorry for the delay, should be done by Friday morning.

**Pull request closed without merging**
