### PR TITLE
feat: Support `describe` on decimal

### LINKED ISSUE #13732: `df.describe` crashes with Decimal type (InvalidOperationError: `std` operation not supported for dtype `decimal[*,1]`)
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from decimal import Decimal as D
import polars as pl

pl.DataFrame({"decimal": [D("1.1"), D("2.2")]}).describe()
```

### Log output

```shell
InvalidOperationError: `std` operation not supported for dtype `decimal[*,1]`
```

### Issue description

`df.describe` crashes when df contains Decimal type 

### Expected behavior

should work

### Installed versions

<details>

```
0.20.4
```

</details>

### PR DESCRIPTION
**Pull request by flisky**
fix #13732

### CODE REVIEW

**Comment by alexander-beedie** [comment]
I'll defer to others (@orlp?) but I don't think casting to `f64` is a valid approach here. It's both an expensive conversion and loses the point of using Decimal for calculations in the first place (the fixed-precision guarantees).

**Comment by orlp** [comment]
@alexander-beedie I think it's fine for `describe`.

**Comment by alexander-beedie** [comment]
> @alexander-beedie I think it's fine for `describe`.

If it was constrained to just `describe` then I'd agree, but the implementation appears to be available everywhere, eg:
```python
    assert df.select(
        sum=pl.sum("a"),
        min=pl.min("a"),
        max=pl.max("a"),
        mean=pl.mean("a"),
        median=pl.median("a"),
    )
```

**Comment by flisky** [comment]
It turned out only `mean` need to be specialized for i128.
Please take a look, thanks!

**Comment by marcounternaehrer-cf** [comment]
Any chance to get this reviewed? :)

**Comment by flisky** [comment]
Rebased!

**Review by ritchie46 — APPROVED** [review]

**Comment by ritchie46** [comment]
Thanks @flisky

**Pull request merged**
