### PR TITLE
docs(python, rust): Add release flow info to contributing guide

### PR DESCRIPTION
**Pull request by stinodego**
Relates to #6319

Changes:
* Add licensing information to table of contents and move it to bottom of the file
* Update Python linting information
* Add release flow for Rust and Python.

Note that I added some 'wishful thinking' when it comes to describing the Rust release process - I believe we should formalize this in a GitHub action.

@ritchie46 Could you let me know what local commands you run to release a new Rust crate? And do you agree it would be nice to have this trigger on a new GitHub Rust release? Then I'll create a workflow for it. (you will probably have to set some secret in GitHub for this, just like `PYPI_PASS` utilized by the Python release workflow)

### CODE REVIEW

**Comment by ritchie46** [comment]
I have to check if cargo publish is fault tolerant currently with multiple crates. It has a new feature, so it might be. 

Currently we simply sleep in between publishes and hope it's long enough. Sometimes I republish.

Do we want to go for the release publish flow in the future?

**Comment by stinodego** [comment]
> Do we want to go for the release publish flow in the future?

If possible, I think it makes sense to have the same release flow for both Rust and Python. But for now let's focus on getting the Python flow in order.

Turns out that for Python, to achieve the release flow I described in the office the other day (and which is described in this PR) is possible without any changes to the GitHub workflow.

Do you want to give this a shot next release, tell me if it works well?

**Comment by ritchie46** [comment]
> Do you want to give this a shot next release, tell me if it works well?

Ah, makes sense as the release also creates a tag. Yes. I will do that next time.

**Comment by ritchie46** [comment]
Feel free to merge when ready.

**Comment by stinodego** [comment]
All right - I'll just merge it, and we can update as we go along if you decide the release process should be adjusted.

**Pull request merged**
