### PR TITLE
Fix some supertypes.

### PR DESCRIPTION
**Pull request by ghuls**

### CODE REVIEW

**Comment by ritchie46** [comment]
The changes are a bit a mess and there are large parts commented. Can you make a PR where its clearer to me what we changed and why?

**Comment by ghuls** [comment]
@ritchie46 This is a WIP.
Some old conversions are commented out and are put at the top now, with easier to see sections
In the old code there were quite some conversions to a supertype that are not safe (as they could overflow).

I fixed those to match what numpy does for those.
Some examples.
```diff
-        (Int16, UInt16) => Some(Int16),
+       (Int16, UInt16) => Some(Int32),

-        (Int32, UInt32) => Some(Int32),
+        (Int32, UInt32) => Some(Int64),

-        (Int64, UInt64) => Some(Int64),
+        (Int64, UInt64) => Some(Float64),

-         (UInt64, Int64) => Some(Int64),
+        (UInt64, Int32) => Some(Float64),

-        (Int32, Float32) => Some(Float32),
+        (Int32, Float32) => Some(Floa64),
...

UInt64 with signed integers are casted to Float64, by numpy. As in the comments in mentions that `(UInt64, Int64) => Some(Int64),` is needed for bigidx, this might cause a problem if it would be a Float64. 

```
               // needed for bigidx
        (UInt64, Int32) => Some(Int64),
        (UInt64, Int64) => Some(Int64),
```

**Comment by ritchie46** [comment]
I think we should be cautious here. This can easily make it impossible to keep i32 integers in lazy as when we create python literals we create i64 values. So every comparison would upcast it.

**Comment by ghuls** [comment]
numpy as a find_common_type function.
First argument is for getting the supertype for arrays, second one for scalars.

So literals will get downcasted to the array type (as far as I understand).

```python
>>> np.find_common_type([], [np.int64, np.float32, complex])
dtype('complex128')
>>> np.find_common_type([np.int64, np.float32], [])
dtype('float64')

The standard casting rules ensure that a scalar cannot up-cast an
array unless the scalar is of a fundamentally different kind of data
(i.e. under a different hierarchy in the data type hierarchy) then
the array:

>>> np.find_common_type([np.float32], [np.int64, np.float64])
dtype('float32')
```

**Comment by ritchie46** [comment]
We could btw get rid of the duplication due to order of `lhs, rhs`, by calling `_get_supertype(lhs, rhs).unwrap_or_else(|| _get_supertype(rhs, lhs)`

**Comment by ghuls** [comment]
> We could btw get rid of the duplication due to order of `lhs, rhs`, by calling `_get_supertype(lhs, rhs).unwrap_or_else(|| _get_supertype(rhs, lhs)`

Not sure it it would be easier to make sure every possibility is handled.

What do you think of the numpy approach of never casting to the type of the literal (scalar), but casting the literal to the array type instead and only using the get_supertype when you have 2 arrays?

**Comment by ritchie46** [comment]
> What do you think of the numpy approach of never casting to the type of the literal (scalar), but casting the literal to the array type instead and only using the get_supertype when you have 2 arrays?

I think we can do that. I am not entirely certain, maybe we encounter edge cases, but in lazy type coercion we could start by casting lit to array indeed.

**Comment by ghuls** [comment]
> I think we should be cautious here. This can easily make it impossible to keep i32 integers in lazy as when we create python literals we create i64 values. So every comparison would upcast it.
> 
> Maybe we need an extra optimization that uses the minimum required integer for literals.

This is implemented now, I assume?
https://github.com/pola-rs/polars/pull/3579

**Comment by ghuls** [comment]
WIP.

Updated attempt:
  - cleaned up commented code.
  - Added correct feature flags (some date related types had the wrong one and add them for u8, u16, i8, i16).

When compiling for bigidx I guess we shouldn't follow numpy (for normal polars we can).

Or could we have a separated datatype for indexes?

```diff
# I addume UInt32 ones are used for normal idx.
-        (UInt32, Int32) => Some(Int64),
-        (UInt32, Int64) => Some(Int64),
-        // needed for bigidx
-        (UInt64, Int32) => Some(Int64),
-        (UInt64, Int64) => Some(Int64),

+        (UInt32, Int32) => Some(Int64),
+        (UInt32, Int64) => Some(Int64),
+        (UInt64, Int32) => Some(Float64), // Follow numpy
+        (UInt64, Int64) => Some(Float64), // Follow numpy
```

https://github.com/pola-rs/polars/pull/3329/commits/5b26a5627348f91d82e0a7311f289e94abd3a410#diff-879773babfd3b05890145b2d1a3e803cd3226c7b9a9c0ad04b52ab0e6256183fR610-R612

**Comment by ghuls** [comment]
@ritchie46 This fixes the last failing test:

```diff
diff --git a/polars/polars-lazy/src/tests/queries.rs b/polars/polars-lazy/src/tests/queries.rs
index c8902d681..fc46b2993 100644
--- a/polars/polars-lazy/src/tests/queries.rs
+++ b/polars/polars-lazy/src/tests/queries.rs
@@ -2060,7 +2060,7 @@ fn test_partitioned_gb_binary() -> Result<()> {
 
     assert!(out.frame_equal(&df![
         "col" => [0],
-        "sum" => [200.0 as f32],
+        "sum" => [200.0 as f64],
     ]?));
 
     Ok(())
```

In Python it outputs the sum column as f32 by default, unless i force `type_coercion=False`:
```python
In [4]: (df.with_column(pl.col("col"))
   ...: .lazy()
   ...: .groupby([pl.col("col")])
   ...: .agg([(pl.col("col").cast(pl.Float32) + pl.lit(10.0)).sum().alias("sum")])
   ...: .collect(type_coercion=False)
   ...: )
Out[4]: 
shape: (1, 2)
┌─────┬───────┐
│ col ┆ sum   │
│ --- ┆ ---   │
│ i64 ┆ f64   │
╞═════╪═══════╡
│ 0   ┆ 200.0 │
└─────┴───────┘

In [5]: (df.with_column(pl.col("col"))
   ...: .lazy()
   ...: .groupby([pl.col("col")])
   ...: .agg([(pl.col("col").cast(pl.Float32) + pl.lit(10.0)).sum().alias("sum")])
   ...: .collect(type_coercion=True)
   ...: )
Out[5]: 
shape: (1, 2)
┌─────┬───────┐
│ col ┆ sum   │
│ --- ┆ ---   │
│ i64 ┆ f32   │
╞═════╪═══════╡
│ 0   ┆ 200.0 │
└─────┴───────┘

In [6]: (df.with_column(pl.col("col"))
   ...: .lazy()
   ...: .groupby([pl.col("col")])
   ...: .agg([(pl.col("col").cast(pl.Float32) + pl.lit(10.0)).sum().alias("sum")])
   ...: .collect()
   ...: )
Out[6]: 
shape: (1, 2)
┌─────┬───────┐
│ col ┆ sum   │
│ --- ┆ ---   │
│ i64 ┆ f32   │
╞═════╪═══════╡
│ 0   ┆ 200.0 │
└─────┴───────┘
```

**Pull request closed without merging**
