### PR TITLE
feat(python): allow df.rename and lf.rename to take a renaming function

### PR DESCRIPTION
**Pull request by Wainberg**
Closes https://github.com/pola-rs/polars/issues/13229.

There seemed to be a lot of popular demand for this (based on the number of likes on the original issue), so I went ahead and implemented it.

### CODE REVIEW

**Review by alexander-beedie — CHANGES_REQUESTED** [review]
I think the idea makes sense, and the use of `pl.all().name.map` looks clean; good stuff! Can you add some unit tests? Would help to see it in action and validate behaviour. Once there is code coverage and the tests pass I'll approve 👍

**Comment by Wainberg** [comment]
@alexander-beedie just added a couple of tests. Did you mean to leave comments on the code as well?

**Comment by Wainberg** [comment]
@alexander-beedie how's this looking, would you say it's ready to merge?

**Comment by alexander-beedie** [comment]
> @alexander-beedie how's this looking, would you say it's ready to merge?

I don't see that you've addressed the inline comments yet?

**Comment by Wainberg** [comment]
@alexander-beedie you'll have to forgive me if I'm being thick, but I don't see any comments. Usually they'd appear in the conversation tab, but here's what the conversation tab looks like for me:

image

and here's the files changed tab:

image

**Comment by orlp** [comment]
@Wainberg  I don't think you're being thick, I can't see them either.

@alexander-beedie Could you re-post those comments?

**Review by alexander-beedie — CHANGES_REQUESTED** [review]

**Comment by alexander-beedie** [comment]
> @alexander-beedie Could you re-post those comments?

Ouch; I blame the GitHub UI for that one; **I** could see them marked as "Pending", which I thought was _"pending action by the author of the PR"_, but apparently means _"Pending you hitting the 'submit' button so the author can see them"_ 🤣

**Comment by Wainberg** [comment]
@alexander-beedie No worries! Just made the two changes you suggested.

**Review by alexander-beedie — APPROVED** [review]

**Comment by alexander-beedie** [comment]
Looks good to me 👌

**Pull request merged**
