### PR TITLE
feat[python]: Support reading all sheets xlsx file

### LINKED ISSUE #4631: read_excel(..., sheet_name=None) should return a dict of dataframes keyed by sheet name
### Problem Description

Pandas allows the `sheet_name=None` argument, with the result returning a dictionary of dataframes, keyed by sheet:

```python
df = pd.read_excel("test_sheets.xlsx", sheet_name=None)
print(type(df))
print(df)
```
Output:
```text
<class 'dict'>
{'first':   Last_Name    First_Name    Birth_day   Age
0       Doe          Jane   1980-01-01    40
1     Smith          John   1970-01-01    50
2   Stevens   Christopher   1960-01-01    70,
'second':   Last_Name  First_Name  Birth_day   Age
0     Bluth     Jessica 1941-01-31    80
1     Bluth     Michael 1969-01-14    53
2     Funke      Tobias 1964-04-04    58}
```

Polars currently returns only the first sheet:
```python
df = pl.read_excel("test_sheets.xlsx", sheet_name=None)
print(type(df))
print(df)
```
Output:
```text
<class 'polars.internals.dataframe.frame.DataFrame'>
┌───────────┬──────────────┬─────────────┬──────┐
│ Last_Name ┆  First_Name  ┆  Birth_day  ┆  Age │
│ ---       ┆ ---          ┆ ---         ┆ ---  │
│ str       ┆ str          ┆ str         ┆ i64  │
╞═══════════╪══════════════╪═════════════╪══════╡
│ Doe       ┆  Jane        ┆  1980-01-01 ┆ 40   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ Smith     ┆  John        ┆  1970-01-01 ┆ 50   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ Stevens   ┆  Christopher ┆  1960-01-01 ┆ 70   │
└───────────┴──────────────┴─────────────┴──────┘
```

### PR DESCRIPTION
**Pull request by zundertj**
Closes #4631.

Couple of remarks:

- Note that we are currently not having any test on `read_excel`, probably because we do not want to pull in this dependency in tests? I did testing locally, can add if needed.
- The type annotation becomes more ugly now, but I guess that is fine for this type of function that wont be used throughout a code base

### CODE REVIEW

**Comment by ritchie46** [comment]
A test would be great!

**Comment by zundertj** [comment]
Added tests covering both single sheet and multi sheet usage.

**Comment by ritchie46** [comment]
Hmm.. tests seem to have failed. :/

**Comment by ghuls** [comment]
`xlsx2csv` is not installed in the test env.

**Comment by zundertj** [comment]
Sorry, have been busy, updated now.

**Comment by ritchie46** [comment]
Sorry for the delay here @zundertj. Could you do a rebase? There are some conflicts.

**Pull request merged**
