### PR TITLE
feat: Push down `is_between` expressions to Arrow

### LINKED ISSUE #15179: Support `is_between` pushdown to Arrow
### Description

When an expression is passed to Arrow, it does not support the `in_between` operator. I've added a simple rule to pass these down.

### PR DESCRIPTION
**Pull request by Fokko**
This allows PyIceberg to leverage the metadata to prune down data files, speeding up the queries significantly.

Resolves #15179

### CODE REVIEW

**Comment by Fokko** [comment]
@ritchie46 For sure! Since I'm more of a Pythonista, could you point me to the right place to add a test?

**Comment by ritchie46** [comment]
In this function we test several predicate pushdowns in pyarrow datasets: https://github.com/pola-rs/polars/blob/6a873242c84a81c7eecd394b330799a86a6d51d6/py-polars/tests/unit/io/test_pyarrow_dataset.py#L32

**Comment by Fokko** [comment]
@ritchie46 @alexander-beedie All checks are green!

**Review by ritchie46 — APPROVED** [review]
Alright. Thank you @Fokko

**Comment by alexander-beedie** [comment]
> This allows PyIceberg to leverage the metadata to prune down data files, speeding up the queries significantly.

Nice one 👌

**Pull request merged**
