### PR TITLE
Fixed most `See Also` docstring formatting, quietened the last warnings coming from `doctests`

### PR DESCRIPTION
**Pull request by alexander-beedie**
* The formatting for most of the `See Also` subsections in docstrings was a bit off, so they weren't being rendered properly on the Sphinx Polars API [website](https://pola-rs.github.io/polars/py-polars/html/reference/). This should fix them. Will be worth adding some more of these links/refs later.

* Also, found the last two or three `doctests` warnings and took care of them - everything there passes cleanly.

* As they now run clean, I added `doctests` to the recently introduced `make test-all` option in the py-polars Makefile; this is not currently run automatically anywhere, it's manual/opt-in (as it runs both `tests` _and_ `parametric_tests`), but as I have been bitten a couple of times by doctests not passing on commit, it will help prevent a few of those before they hit GitHub... ;)

* Reduced the default scale of parametric tests to speed them up a touch.

### CODE REVIEW

**Comment by ghuls** [comment]
Can we have an empty newline after `- - - - - - ` lines (like example) ? Without is fine when rendering html, but I use quite often `?pl.Expr.head` to show help in an interactive interpreter.

**Comment by alexander-beedie** [comment]
> Can we have an empty newline after `- - - - - - ` lines (like example) ? Without is fine when rendering html, but I use quite often `?pl.Expr.head` to show help in an interactive interpreter.

Odd. Which interpreter/env is that?
I see no difference here with/without a newline (in PyCharm, with/without ipython, using `help(xyz)` or `xyz?`).

**Comment by ritchie46** [comment]
I agree it is a good custom to end with a new line. I have requested people to do this with the examples as well.

If I could I would check this in CI so that we can enforce that.

**Comment by alexander-beedie** [comment]
> I agree it is a good custom to end with a new line. I have requested people to do this with the examples as well.

They end with a newline - this is about adding a newline after (all?) the section underscores:

Usual:
```
Parameters
----------
x
y
z

Examples
--------
>>> do_something()

```
With extra newlines:
```
Parameters
----------
                     ## extra newline
x
y
z

Examples
--------
                     ## extra newline
>>> do_something()

```
Is there a particular advantage to the latter? (I've not seen this style of docstring spaced-out like that before, so wondering if it's an editor-specific thing). I have no opinion either way, and am generally in favour of standardising.

**Comment by ritchie46** [comment]
> Is there a particular advantage to the latter? (I've not seen this style of docstring spaced-out like that before, so wondering if it's an editor-specific thing). I have no strong opinion either way, and am generally in favour of standardising.

Right, sorry, I misunderstood. Let's take numpydoc as guideline then: https://numpydoc.readthedocs.io/en/latest/example.html

They don't have it, so let us not do that as well.

**Comment by ghuls** [comment]
`ipython` in a normal terminal (no notebook):
```
In [4]:  ?pl.Expr.pow
Signature: pl.Expr.pow(self, exponent: 'int | float | pli.Series | Expr') -> 'Expr'
Docstring:
Raise expression to the power of exponent.
Examples
--------

>>> df = pl.DataFrame({"foo": [1, 2, 3, 4]})
>>> df.select(pl.col("foo").pow(3))
shape: (4, 1)
┌──────┐
│ foo  │
│ ---  │
│ f64  │
╞══════╡
│ 1.0  │
├╌╌╌╌╌╌┤
│ 8.0  │
├╌╌╌╌╌╌┤
│ 27.0 │
├╌╌╌╌╌╌┤
│ 64.0 │
└──────┘
File:      ~/software/polars/py-polars/polars/internals/expr.py
Type:      function
```

**Comment by ghuls** [comment]
At least if the docstring formatting is consistent in all samples.

**Comment by ritchie46** [comment]
Is it good to go @alexander-beedie ?

**Comment by alexander-beedie** [comment]
> Is it good to go @alexander-beedie ?

Yup; there weren't actually that many newlines to normalise in the end - think I got most (all?) of them.

**Pull request merged**
