### PR TITLE
fix(rust!, python): Reject literal input in `sort_by_exprs()`

### LINKED ISSUE #17539: Strange behavior when Series is given to `DataFrame.sort()`
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars as pl
>>> df = pl.DataFrame({"foo": [1, 2, 3]})
>>> df.sort(pl.Series(values=[1, 2]))
shape: (2, 1)
┌─────┐
│ foo │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 2   │
└─────┘
>>> df.sort(pl.Series(values=[1, 2, 3, 4]))
shape: (4, 1)
┌─────┐
│ foo │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 2   │
│ 3   │
│ 0   │
└─────┘
>>> df.sort(pl.Series(values=[1, 2, 3, 4, 5]))
shape: (5, 1)
┌─────┐
│ foo │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 2   │
│ 3   │
│ 0   │
│ 5   │
└─────┘
>>> df.sort(pl.Series(values=[1, 2, 3, 4, 5, 6]))
shape: (6, 1)
┌─────────────────┐
│ foo             │
│ ---             │
│ i64             │
╞═════════════════╡
│ 1               │
│ 2               │
│ 3               │
│ 0               │
│ 1               │
│ 140298187804288 │
└─────────────────┘
>>> df.sort(pl.Series(values=[1, 2, 3, 4, 5, 6, 7]))
shape: (7, 1)
┌─────────────────┐
│ foo             │
│ ---             │
│ i64             │
╞═════════════════╡
│ 1               │
│ 2               │
│ 3               │
│ 0               │
│ 17              │
│ 140298187804288 │
│ 17              │
└─────────────────┘
>>> df.sort(pl.Series(values=[1, 2, 3, 4, 5, 6, 7, 8]))
shape: (8, 1)
┌─────────────────────┐
│ foo                 │
│ ---                 │
│ i64                 │
╞═════════════════════╡
│ 1                   │
│ 2                   │
│ 3                   │
│ 0                   │
│ 2314885531037412640 │
│ 2314885530818453536 │
│ 32                  │
│ 0                   │
└─────────────────────┘
>>> df.sort(pl.Series(values=[1, 2, 3, 4, 5, 6, 7, 8, 9]))
shape: (9, 1)
┌─────────────────────┐
│ foo                 │
│ ---                 │
│ i64                 │
╞═════════════════════╡
│ 1                   │
│ 2                   │
│ 3                   │
│ 0                   │
│ 3834876879520870944 │
│ 3545519499638813493 │
│ 138247681586        │
│ 0                   │
│ 21                  │
└─────────────────────┘
>>> df.sort(pl.Series(values=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
shape: (10, 1)
┌─────────────────────┐
│ foo                 │
│ ---                 │
│ i64                 │
╞═════════════════════╡
│ 1                   │
│ 2                   │
│ 3                   │
│ 0                   │
│ 21                  │
│ 140298187804256     │
│ 21                  │
│ 0                   │
│ 2314885530818457888 │
│ 2314885530818453536 │
└─────────────────────┘
```

### Log output

_No response_

### Issue description

Given a Series, we get strange output. In some cases, it may even crash.

### Expected behavior

In such a case, I think it should be an error.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.1.0
Index type:           UInt32
Platform:             Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by eitsupi**
Fix #17539

### CODE REVIEW

**Comment by eitsupi** [comment]
@stinodego How should the PR title be written if the change is breaking to Rust but not to Python? (Perhaps the checker checked incorrectly?)

**Comment by ritchie46** [comment]
> @stinodego How should the PR title be written if the change is breaking to Rust but not to Python? (Perhaps the checker checked incorrectly?)

No clue. Seem scorrect to me. @stinodego ?

**Review by ritchie46 — APPROVED** [review]

**Comment by ritchie46** [comment]
Thanks!

**Comment by stinodego** [comment]
> @stinodego How should the PR title be written if the change is breaking to Rust but not to Python? (Perhaps the checker checked incorrectly?)

Apparently my current regex doesn't allow spaces between the scopes.

**Pull request merged**
