### PR TITLE
depr(python): Rename `Series/Expr.apply` to `map_elements`

### PR DESCRIPTION
**Pull request by ritchie46**
Pandas `apply` will have opposite behavior of polars. We chose apply because people were so familiar with it in pandas.

Now that influence stops and we try to keep true to our own naming strategy. I favour `map` as functional name for mapping a function and if I ask what we `map`, the best name I could come with was `elements`.

We map scalar elements during projections and group elements during a groupby agg.

Ideally I also want to clarify what we map in `map`. That function get the whole column / state / batch, but we cannot guarantee that a column is complete, so I am still thinking about that one.

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
nice - regardless of what ends up being decided in pandas, I do think `map_elements` / `map_groups` / etc are much better names

**Comment by ritchie46** [comment]
> I don't mind finishing this PR to include the changes above, if you prefer.

That would be great. :) And yes, we should come up with `map_<>` for other cases as well. I think we should do that in different PR's.

**Comment by stinodego** [comment]
> I think we should do that in different PR's.

I'm not sure - the whole `InefficientApplyWarning` thing doesn't make sense anymore when some things are called `apply` and others are called `map`.

To split things up, I usually find it easier to do Rust side first fully and make it make sense there, then do the Python side.

**Comment by ritchie46** [comment]
> To split things up, I usually find it easier to do Rust side first fully and make it make sense there, then do the Python side.

In rust we don't have a map_elements. I still have to think a bit on that.

**Comment by stinodego** [comment]
@ritchie46 I realized the apply-specific warning was only implemented for `Series/Expr.apply`, so it only applies to `map_elements`. That makes everything a bit simpler. So this PR only does the rename to `map_elements`. Let's try to get the other renames in with `0.19.0` as well so that the API makes sense as a whole.

I don't mind doing the legwork if we can agree on the names :)

**Comment by stinodego** [comment]
I made #10744 to discuss naming of other apply functions/methods.

This PR should be good to go!

**Comment by ritchie46** [comment]
Alright. Thanks a lot for taking this one to the finish line.

**Comment by alexander-beedie** [comment]
> I'm not sure - the whole InefficientApplyWarning thing doesn't make sense anymore

@stinodego: `InefficientUsageWarning`? :)
Nice and generic but also not vague...

**Comment by stinodego** [comment]
It's now an `InefficientMapWarning` which I think is fine! It will make sense again when the rest of the `apply` stuff is renamed.

**Pull request merged**
