### PR TITLE
fix(rust, python): arg_min & arg_max return null for empty series

### LINKED ISSUE #10703: list.arg_min() now returns 0 instead of null on an empty sub-list
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

in py-polars 0.18.5 

```py
pl.select( pl.lit(pl.Series([["a"],[]]))).with_columns(pl.all(),pl.all().list.arg_min().alias("arg_min"
),pl.all().list.arg_max().alias("arg_max"))
shape: (2, 3)
┌───────────┬─────────┬────────────┐
│           ┆ arg_min ┆ arg_max    │
│ ---       ┆ ---     ┆ ---        │
│ list[str] ┆ u32     ┆ u32        │
╞═══════════╪═════════╪════════════╡
│ ["a"]     ┆ 0       ┆ 0          │
│ []        ┆ 0       ┆ 4294967295 │
└───────────┴─────────┴────────────┘
```

### Issue description

Noticed when bumping r-polars dependency to rust-polars 0.30.0 -> 0.32.0.

arg_min() now returns 0 instead of null on empty sub-list. However an empty list has zero length and there would be no first element to point to.

### Expected behavior

as from rust-polars 0.30.0

```py
pl.select( pl.lit(pl.Series([["a"],[]]))).with_columns(pl.all(),pl.all().list.arg_min().alias("arg_min"
),pl.all().list.arg_max().alias("arg_max"))
shape: (2, 3)
┌───────────┬─────────┬────────────┐
│           ┆ arg_min ┆ arg_max    │
│ ---       ┆ ---     ┆ ---        │
│ list[str] ┆ u32     ┆ u32        │
╞═══════════╪═════════╪════════════╡
│ ["a"]     ┆ 0       ┆ 0          │
│ []        ┆ Null       ┆ Null │
└───────────┴─────────┴────────────┘
```
in upcomming r-polars
```

### Installed versions

<details>

as of py-polars 0.18.5

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This fixes #10703.

### CODE REVIEW

**Comment by reswqa** [comment]
For other types, already return `None` if empty.

**Comment by orlp** [comment]
I think this is still wrong. It should also return `null` if all elements are `null`, shouldn't it?

**Comment by reswqa** [comment]
Actually, I have noticed this already. I found that there are many problems with Null value, not just the one you mentioned. So I opened an issue to deal with it. I need to ask everyone for advice on the handling of that situation. This pr is only to solve the problem that the length is 0. WDYH？

**Comment by reswqa** [comment]
See #10701

**Comment by reswqa** [comment]
@orlp Do you think this changes is enough to close #10703? Then I will create a new PR based on this to specifically handle the null values mentioned in #10707.

**Comment by orlp** [comment]
@reswqa Yes, they're very similar.

**Comment by ritchie46** [comment]
> 

Agree on this one. @reswqa can you make a branch for this?

**Pull request closed without merging**
