### PR TITLE
feat(python, rust): preserve whitespace in notebook output

### LINKED ISSUE #10643: Preserve whitespace in notebook html output
## Problem

- for text column with whitespace (multiple spaces, tabs, newlines) you do **not get a correct data representation** (due to html whitespace collapse)
- if you want to copy&paste a value you see in your rendered output and use that to filter your Dataframe **you will not find it**

## Example

```python
DATA = {'text': ['nospace', '     before', 'after     ', '     both     ', 'bet     ween', 'tab-after\t', '\ttab-before', 'new\nline',]}
df = pl.DataFrame(data=DATA)
df.filter(pl.col('text') == '<PASTED FROM RENDERED OUTPUT>')  # will NOT work because whitespace collapsed
```

image

## Solution

there seems to be an easy css solution using `white-space: pre;` . Fix coming right up

### PR DESCRIPTION
**Pull request by JulianCologne**
fixes #10643

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Very clean solution; nice one.

**Review by alexander-beedie — APPROVED** [review]

**Comment by stevenlis** [comment]
@alexander-beedie It causes some problems and introduces a breaking change. https://github.com/pola-rs/polars/issues/10643#issuecomment-1688380037

**Comment by JulianCologne** [comment]
With this PR you will get a correct presentation of your actual data.
You will see
- multiple spaces (otherwise collapsed into 1)
- tabs (otherwise collapsed into space)
- newlines (otherwise collapsed into space)

If the original data does not contain line breaks you will not get them here either.
This could be changed by using `pre-wrap` instead on `pre` to still get text wrap if desired. (not sure, maybe a make it a config option?)

```python
pl.Config.set_fmt_str_lengths(n=50)
DATA = {
    "text": [
        "nospace",
        "     before",
        "after     ",
        "     both     ",
        "bet     ween",
        "tab-after\t",
        "\ttab-before",
        "new\nline",
    ],
    "c1": "long " * 10,
    "c2": "very long" * 100,
}
pl.DataFrame(data=DATA)
```

**`white-space: pre`**
image


**`white-space: pre-wrap`**
image


I do NOT see any breaking change here! We are talking about a html representation in a notebook cell! How can this break workflows? :O 
Nevertheless I think also adding `\n` and `\t` representation would be nice for a future PR! :)

**Comment by alexander-beedie** [comment]
Yup, this is definitely not a breaking change ;)

I could easily be persuaded to go for `pre-wrap` though, as that appears to balance both issues well?

**Comment by stevenlis** [comment]
I think so, but it would be better to also implement https://github.com/pola-rs/polars/issues/10700#issuecomment-1693973728 along with `pre-wrap` so that you will see more-than-one-line of text only when you get a very long string cell.

**Pull request merged**
