### PR TITLE
fix(python): Remove `BatchedCsvReader` from public API

### PR DESCRIPTION
**Pull request by stinodego**
This object should be accessed through `pl.read_csv_batched` - not directly.

Also removed a duplicate entry of `get_idx_type`.

### CODE REVIEW

**Comment by ritchie46** [comment]
Though users might want it for type checking..

**Comment by ghuls** [comment]
I am using `get_idx_type` in my code.

**Comment by stinodego** [comment]
> Though users might want it for type checking..

We also don't export `GroupBy`, `LazyGroupBy`, `WhenThen`, etc.; what makes this helper class special?

> I am using `get_idx_type` in my code.

That was just a duplicate, it's still in there (near the bottom).

**Comment by ritchie46** [comment]
>  I'd argue that the user can import these from their module 

Yep, I agree. I thought we removed it entirely to private.

**Comment by stinodego** [comment]
There is not really such a thing as privacy in Python - if someone really wants to import private utils, e.g. `from polars.internals.anonymous_scan import _deser_and_exec`, they can.

I'll go ahead and merge this then :)

**Comment by ritchie46** [comment]
I know, but if it starts with and underscore we can say I told you so! 😊

**Pull request merged**
