### PR TITLE
improve conversion to ndarray/numpy `~3/4x`

### PR DESCRIPTION
**Pull request by ritchie46**
Improves conversion to numpy. Series to numpy conversion can be zero copy. For `DataFrames` this is not the case as for numpy all data needs to be contiguous and row-oriented.

We `memcpy` parallel to the correct offsets and then we transpose the array. The transposed array is only a strides adjustment.

image

### CODE REVIEW

**Comment by ghuls** [comment]
> For `DataFrames` this is not the case as for numpy all data needs to be contiguous and row-oriented.

numpy arrays don't need to be row oriented. If you set fortran order on the numpy array the numpy array is layed out contiguously by column.

It would be nice if polars can support both.

**Comment by ritchie46** [comment]
> > For `DataFrames` this is not the case as for numpy all data needs to be contiguous and row-oriented.
> 
> numpy arrays don't need to be row oriented. If you set fortran order on the numpy array the numpy array is layed out contiguously by column.
> 
> It would be nice if polars can support both `order="C"` (row oriented memory layout) and `order="F"` (column oriented memory layout).

I have been wrestling with this, but I did not succeed to make this work.

**Comment by ghuls** [comment]
for example creating a polars df from a numpy array in fortran order is way faster:
```python
import numpy as np
import polars as pl

In [14]: np_F_order = np.array(np.random.rand(10000, 10000), order="F")

In [15]: %timeit pl.DataFrame(np_F_order)
116 ms ± 1.88 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [16]: np_C_order = np.array(np_F_order, order="C")

In [17]: %timeit pl.DataFrame(np_C_order)
324 ms ± 1.51 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by ghuls** [comment]
> I have been wrestling with this, but I did not succeed to make this work. I will merge it for now. We can improve upon this.

Gor Fortran order:
  - memcpy each whole polars column after each other
  - at the numpy size: `array.transpose()` or probably better set the Fortran flag on the numpy array.

```
In [23]: np_C_order.flags
Out[23]:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [24]: np_F_order.flags
Out[24]:
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [21]: np_C_order_transposed = np_C_order.transpose()

In [22]: np_C_order.flags
Out[22]:
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

**Comment by ritchie46** [comment]
```

    memcpy each whole polars column after each other
    at the numpy size: array.transpose() or probably better set the Fortran flag on the numpy array.

```

This is exactly what I have done.

**Comment by ghuls** [comment]
> This is exactly what I have done.

I see now. FIist I thought the offsets you were creating was `[x gap gap gap gap x gap gap gap gap x ...]`, `[ gap y gap gap gap gap y gap gap gap gap y ...]` which would result in a lot of cache misses (especially when executed in parallel).

**Comment by ritchie46** [comment]
> eating was `[x gap gap gap gap x gap gap gap gap x ...]`, `[ gap y gap gap gap gap y gap gap gap gap y ...]` which would result in a lot of cache misses (especially when executed in parallel).

Jup, that was the initial naive implementation (this was not exposed to python, there we used numpy `vstack`). Anyhow.. The benchmarks for that algorithm were counting 2.7s or something. So very slow.

**Pull request merged**
