### PR TITLE
Remove xlsx2csv error handling hack

### PR DESCRIPTION
**Pull request by cnpryer**
See https://github.com/dilshod/xlsx2csv/pull/235

### CODE REVIEW

**Comment by ritchie46** [comment]
I think we should ensure the right version of xlsx2csv is installed before we can remove this.

**Comment by cnpryer** [comment]
Good point

**Comment by cnpryer** [comment]
https://github.com/dilshod/xlsx2csv/issues/236

**Comment by ghuls** [comment]
There is more stuff to cleanup in this function, if a new version of xlsx2csv get released.

**Comment by cnpryer** [comment]
> There is more stuff to cleanup in this function, if a new version of xlsx2csv get released.

Are you referring to this part?
```python
    if sheet_name:
        sheet_id = xlsx2csv_instance.getSheetIdByName(sheet_name)
        if not sheet_id:
            raise xlsx2csv.XlsxException(f"Sheet '{sheet_name}' not found.")
```

**Comment by ghuls** [comment]
> > There is more stuff to cleanup in this function, if a new version of xlsx2csv get released.
> 
> Are you referring to this part?
> 
> ```python
>     if sheet_name:
>         sheet_id = xlsx2csv_instance.getSheetIdByName(sheet_name)
>         if not sheet_id:
>             raise xlsx2csv.XlsxException(f"Sheet '{sheet_name}' not found.")
> ```

Yes, I think the following can be replaced:
```python
    xlsx2csv_instance = xlsx2csv.Xlsx2csv(file, **xlsx2csv_options)

    if sheet_name:
        sheet_id = xlsx2csv_instance.getSheetIdByName(sheet_name)
        if not sheet_id:
            raise xlsx2csv.XlsxException(f"Sheet '{sheet_name}' not found.")
    csv_buffer = StringIO()
    # Convert sheet from XSLX document to CSV.
    xlsx2csv_instance.convert(outfile=csv_buffer, sheetid=sheet_id)
```
with:
```python
    csv_buffer = StringIO()
    xlsx2csv.Xlsx2csv(file, **xlsx2csv_options).convert(outfile=csv_buffer, sheetid=sheet_id, sheetname=sheet_name)
```
As the git version of xlsx1csv handled the sheetname option automatically (while the pip version does not).

**Comment by cnpryer** [comment]
> As the git version of xlsx1csv

We're blocked by its pypi release tho right? Idk if you're implying we should just target master. 😈

**Comment by cnpryer** [comment]
What would be the ideal resolution here? Drop it or do we consider other excel packages?

**Comment by cnpryer** [comment]
No response. Closing since stale.

**Comment by cnpryer** [comment]
0.8.0 is up. I’ll wrap this up.

**Comment by cnpryer** [comment]
I'm just going to move to a new PR. Struggling to squash the rebase.

**Pull request closed without merging**
