### PR TITLE
docs: Update `by` param description for rolling_*_by functions

### LINKED ISSUE #19491: `rolling_*_by()` functions work when `by` is integer while docs say it shouldn't
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3, 4, 5, 6], "id": [11, 12, 13, 14, 15, 16]})

df.select(pl.col("a").rolling_mean_by("id", window_size = "2i"))
```

### Log output

```shell
shape: (6, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
│ 1.5 │
│ 2.5 │
│ 3.5 │
│ 4.5 │
│ 5.5 │
└─────┘
```

### Issue description

Mismatch between the [docs](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.rolling_min_by.html) of the `by` parameter, that say:

> **by**:  This column must be of dtype Datetime or Date.

and the code that works when `by` is integer.

### Expected behavior

Not sure if this is just a documentation issue or if it should error when `by` is integer.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.12.0
Index type:          UInt32
Platform:            Linux-6.8.0-47-generic-x86_64-with-glibc2.39
Python:              3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.2
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #19491

### CODE REVIEW

**Review by rodrigogiraoserrao — COMMENTED** [review]
I'm assuming the types `(U)Int32` / `(U)Int64` are allowed because they can be interpreted as a timestamp (number of some-fraction-of-a-second since epoch), right?
Would it make sense to add a note regarding that?
Someone might be left thinking that (U)Ints of smaller precisions could still work and we just forgot to add them to the docstring..?

Dunno, just asking. Feel free to ignore 😬

**Comment by MarcoGorelli** [comment]
thanks for your review - they're allowed because you pass `'i'` to mean "index count" to `window_size`, e.g. `pl.col('price').rolling_mean_by('index', '3i')`

**Comment by rodrigogiraoserrao** [comment]
Ah I see. Then the docstrings should probably say something about the `i` / index count, but that's maybe for another PR; i.e., not necessarily your responsibility here

**Comment by MarcoGorelli** [comment]
it's ok i can add it, thanks!

**Review by rodrigogiraoserrao — APPROVED** [review]
Thanks for making the docs clearer! 🚀

**Comment by MarcoGorelli** [comment]
thanks for your review!

**Pull request merged**
