### PR TITLE
improve schema correctness

### PR DESCRIPTION
**Pull request by ritchie46**
#2804

### CODE REVIEW

**Comment by SimonSchneider** [comment]
Thank you @ritchie46, not sure where you want this comment (on PR or on Issue)but I tested this branch and with a release build all tests seem to work and I'm unable to reproduce the flaky test failing after about 2minutes of rerunning it. Seems this solved it 🎉  (at least for release builds)

**Comment by ritchie46** [comment]
> Thank you @ritchie46, not sure where you want this comment (on PR or on Issue)but I tested this branch and with a release build all tests seem to work and after about 2minutes of rerunning the flaky test I can't get it to fail. Seems this solved it tada (at least for release builds)

Yeap. :) In release builds we fallback to old behavior. :)

In debug build we still panic so that these errors don't get unnoticed.

**Comment by ritchie46** [comment]
@SimonSchneider I will add another feature flag so that this does not panic on your debug/test builds as the logic is correct.

**Comment by SimonSchneider** [comment]
Thank you @ritchie46 🙇

**Pull request merged**
