### PR TITLE
feat(python, rust): Adds `NULLIF` and `COALESCE` SQL functions

### PR DESCRIPTION
**Pull request by SeanTroyUWO**
Adds a pair of functions from the Postgres SQL documentation:
https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL

I'm getting SQL issues from here: https://github.com/pola-rs/polars/issues/7227

Apparently these were community requested, I cannot find who requested them.

### CODE REVIEW

**Review by universalmind303 — APPROVED** [review]

**Comment by SeanTroyUWO** [comment]
I have no idea why that lint is mad at me.

**Comment by SeanTroyUWO** [comment]
> I have no idea why that lint is mad at me.

The last time those lines were changed was a year ago. I don't know why they would create an issue now.

**Comment by SeanTroyUWO** [comment]
> > I have no idea why that lint is mad at me.
> 
> The last time those lines were changed was a year ago. I don't know why they would create an issue now.

Fixed by forwarding past https://github.com/pola-rs/polars/pull/11126

**Comment by universalmind303** [comment]
@SeanTroyUWO seems to be broken across the board

This PR should fix it: 
https://github.com/pola-rs/polars/pull/11144

**Pull request merged**
