### PR TITLE
Add tests for several io utilities

### PR DESCRIPTION
**Pull request by zundertj**
* the `scan_*` functions were not covered. They need a physical file for testing (I tried a named temporary file but that did not work), hence the `small.csv` & `small.parquet` files. They are small in size, so no bloat.
* add from/to combinations to the buffer test

### CODE REVIEW

**Comment by zundertj** [comment]
The test failures are unrelated to the changes in the PR; PR #1698 will solve the test failures.

**Comment by ritchie46** [comment]
> The test failures are unrelated to the changes in the PR; PR #1698 will solve the test failures.

Ok, I will first merge that one, and rerun these tests.

**Comment by ritchie46** [comment]
@zundertj, could you rebase, so that the tests are updated?

**Comment by ritchie46** [comment]
Thanks!

**Pull request merged**
