### PR TITLE
fix float fmting

### LINKED ISSUE #2033: Minor: inconsistent table repr for float values
#### Versions

Python 3.9 / Polars 0.10.27 / Windows 10

#### Describe your bug / reproduce behaviour

```python
>>> # create trivial float series and observe the resulting repr
>>> import polars as pl
>>> pl.from_records( data=[1.0, 0.0, -1.0], columns=['test'] )

shape: (3, 1)
┌──────┐
│ test │
│ ---  │
│ f64  │
╞══════╡
│ 1    │   # <- integer repr
├╌╌╌╌╌╌┤
│ 0.0  │   # <- float repr (as expected)
├╌╌╌╌╌╌┤
│ -1e0 │   # <- scientific notation with 'e0'...
└──────┘
```

Obviously not an especially pressing issue, but seems peculiar to see three different formatting styles for three values of the same type in the same series, so thought I'd report it in case it's simple to address. 

Feel free to throw this one very, _very_ low down the list of priorities... ;)

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #2033

### CODE REVIEW

**Comment by zundertj** [comment]
The doc examples failing makes sense. It does highlight some issues, as it tends to print a lot of digits now:

```
Failed example:
    s.tan()
Expected:
    shape: (3,)
    Series: 'a' [f64]
    [
        0.0
        1.633123935319537e16
        -1.2246467991473532e-16
    ]
Got:
    shape: (3,)
    Series: 'a' [f64]
    [
    	0.0
    	1.633123935319537e16
    	-0.00000000000000012246467991473532
    ]
```
I would personally be happy with scientific notation in this case, if this happens in a dataframe, it would ruin the layout.

**Comment by ritchie46** [comment]
> I would personally be happy with scientific notation in this case, if this happens in a dataframe, it would ruin the layout.

I agree.

**Comment by ghuls** [comment]
Pandas has an option to set the print precision. (6 by default).

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.set_option.html#pandas.set_option
```
display.precisionint

    Floating point output precision in terms of number of places after the decimal, for regular formatting as well as scientific notation. Similar to precision in numpy.set_printoptions(). [default: 6] [currently: 6]

```

**Comment by ritchie46** [comment]
Some examples:

## old
```
    shape: (1, 3)
    ┌─────┬─────┬──────┐
    │ foo ┆ bar ┆ ham  │
    │ --- ┆ --- ┆ ---  │
    │ f64 ┆ f64 ┆ str  │
    ╞═════╪═════╪══════╡
    │ 1   ┆ 1   ┆ null │
    └─────┴─────┴──────┘
```
## new
```
    shape: (1, 3)
    ┌─────┬─────┬──────┐
    │ foo ┆ bar ┆ ham  │
    │ --- ┆ --- ┆ ---  │
    │ f64 ┆ f64 ┆ str  │
    ╞═════╪═════╪══════╡
    │ 1.0 ┆ 1.0 ┆ null │
    └─────┴─────┴──────┘

```

## old

```

    shape: (5, 4)
    ┌──────────┬────────────────────┬─────┬──────┐
    │ describe ┆ a                  ┆ b   ┆ c    │
    │ ---      ┆ ---                ┆ --- ┆ ---  │
    │ str      ┆ f64                ┆ f64 ┆ f64  │
    ╞══════════╪════════════════════╪═════╪══════╡
    │ mean     ┆ 2.2666666666666666 ┆ 5   ┆ null │
    ├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
    │ std      ┆ 1.1015141094572205 ┆ 1   ┆ null │
    ├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
    │ min      ┆ 1                  ┆ 4   ┆ 0.0  │
    ├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
    │ max      ┆ 3                  ┆ 6   ┆ 1    │
    ├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
    │ median   ┆ 2.8                ┆ 5   ┆ null │
    └──────────┴────────────────────┴─────┴──────┘


```

## new

```
    shape: (5, 4)
    ┌──────────┬──────────┬─────┬──────┐
    │ describe ┆ a        ┆ b   ┆ c    │
    │ ---      ┆ ---      ┆ --- ┆ ---  │
    │ str      ┆ f64      ┆ f64 ┆ f64  │
    ╞══════════╪══════════╪═════╪══════╡
    │ mean     ┆ 2.266667 ┆ 5.0 ┆ null │
    ├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
    │ std      ┆ 1.101514 ┆ 1.0 ┆ null │
    ├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
    │ min      ┆ 1.0      ┆ 4.0 ┆ 0.0  │
    ├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
    │ max      ┆ 3.0      ┆ 6.0 ┆ 1.0  │
    ├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┤
    │ median   ┆ 2.8      ┆ 5.0 ┆ null │
    └──────────┴──────────┴─────┴──────┘

```

## old

```
    shape: (3,)
    Series: 'a' [f64]
    [
        0.0
        1
        1.2246467991473532e-16
    ]

```

## new

```
    shape: (3,)
    Series: 'a' [f64]
    [
    	0.0
    	1.0
    	1.2246e-16
    ]


```

**Pull request merged**
