### PR TITLE
fix: Struct filter by index

### PR DESCRIPTION
**Pull request by barak1412**
Fixes https://github.com/pola-rs/polars/issues/18732.

### CODE REVIEW

**Comment by cmdlineluser** [comment]
Thanks @barak1412 

I think negative indexing is normally allowed:

```python
>>> df.with_columns(a = pl.col.foo.struct[-1])
# shape: (2, 2)
# ┌───────────┬─────┐
# │ foo       ┆ a   │
# │ ---       ┆ --- │
# │ struct[1] ┆ i64 │
# ╞═══════════╪═════╡
# │ {1}       ┆ 1   │
# │ {2}       ┆ 2   │
# └───────────┴─────┘
```

The logic for that seems to be here:

https://github.com/pola-rs/polars/blob/6561ebab214695e76695ff77435169b91b29079b/crates/polars-plan/src/dsl/function_expr/struct_.rs#L26-L27

**Comment by barak1412** [comment]
@cmdlineluser Sure I will look into it.
It looks like some test related to date is failing, something with the CD is broken?

**Comment by barak1412** [comment]
@cmdlineluser Fixed

**Comment by ritchie46** [comment]
I appreciate the fix, but this isn't how it should be fixed. The expression should be replaced by a field by name, hence the panic. We should never access data by index as that doesn't allow us to remove fields we don't need.

**Comment by barak1412** [comment]
@ritchie46 Sure, I am glad to learn 

So the right way is given index, fetch the right field and then use its name to fetch the data?

**Comment by ritchie46** [comment]
> So the right way is given index, fetch the right field and then use its name to fetch the data in the expression level?

Yes, but we already have that logic, it seems that we don't hit that in the `filter`

Note that `select` works as expected:

```python
df = pl.DataFrame({"foo": [{"a":1},{"a":2}]})
df.select(pl.col.foo.struct[0] == 1)
```

**Comment by barak1412** [comment]
@ritchie46 

Thanks for the guidance, should be the right fix now.

**Review by ritchie46 — APPROVED** [review]
Thanks @barak1412. That's the proper fix.

**Pull request merged**
