### PR TITLE
Use maturin v1.0.0-beta.5 with PEP 704 (.venv) support

### PR DESCRIPTION
**Pull request by konstin**
I recently add support to maturin to automatically use `.venv` from [PEP 704](https://peps.python.org/pep-0704/) and i'm now trying to integrate this into real world projects.

Depending on your preference you might want to wait for the stable v1.0 maturin release before merging this.

### CODE REVIEW

**Comment by stinodego** [comment]
`venv` is a Make command that relies on the `venv` folder being present. We would have to rename that to `.venv`, which I think is fine but I'm not sure is allowed?

**Review by stinodego — CHANGES_REQUESTED** [review]
I'd be in favor of this change - I think `.venv` is more standardized as a folder than the current `venv` folder we use. But please do a search for `venv` through the code base, because there are some other spots where we rely on the `venv` folder, i.e. `.gitignore` and the Make command `venv` which should then be renamed to `.venv`.

Also, I think this change might also come in helpful in the CI?

And personally, I'd like to wait for the stable release, otherwise we'd have to update again when that comes out.

**Comment by konstin** [comment]
rebase to avoid merge conflicts once #7790 is merged

**Comment by stinodego** [comment]
I'll close this for now, and open a new PR whenever maturin `1.0.0` comes out.

**Pull request closed without merging**
