### PR TITLE
improve sample_perf

### PR DESCRIPTION
**Pull request by ritchie46**
improve sample without replacement performance by 2/2.5 x

### CODE REVIEW

**Comment by dannyfriar** [comment]
@ritchie46 Does this PR mean that `df.sample(frac=1.0)` will now do nothing? https://github.com/pola-rs/polars/pull/3264/files#diff-c73eeb581ed9bc71c79c89ffe5174249b33d7040917213e862d60842d72c3277R32

**Comment by ritchie46** [comment]
It will sample but not guarantee shuffling.

**Comment by dannyfriar** [comment]
Would it be possible to expose the `shuffle` argument in the Python API? Or to add a `shuffle` method on the dataframe? If you think this is reasonable I can create an issue with the feature request.

**Comment by ritchie46** [comment]
Yes. Can you make the request?

**Comment by dannyfriar** [comment]
https://github.com/pola-rs/polars/issues/3306

**Pull request merged**
