### PR TITLE
Anonymous scan lazyframe

### PR DESCRIPTION
**Pull request by universalmind303**
add functionality to allow lazyframe scans from anonymous sources. 

Currently only supports projection pushdowns, but I would like to add more options such as predicate, n_rows, & more.

a simple example allowing a `scan_json` type

```rust
pub fn scan_json(path: String, schema: Wrap<Schema>) -> Result<LazyFrame> {
    let f = move |options: AnonymousScanOptions| {
        let path = path.clone();

        if let Some(s) = options.output_schema {
            JsonLineReader::from_path(path)
                .expect("unable to read file")
                .with_schema(&s)
                .finish()
        } else {
            JsonLineReader::from_path(path)
            .expect("unable to read file")
            .finish()
        }
    };
    LazyFrame::anonymous_scan(f, schema.0)
}

```

the `anonymous_scan` has a requirement that the schema **MUST** be provided by the user. This should give users a lot of flexibility to easily add custom data sources such as databases, custom file formats, or other rust structs.

### CODE REVIEW

**Comment by ritchie46** [comment]
Cool idea. Maybe could add a trait object that generates the schema as well. Then we can implement the trait objects (similar to what we do with `Expr::apply`).

This would eventually allow us to refactor the all the scans to implmentations this generic scan node. 

One thing that we have to do before merging, is checking all optimizations and ensure that we update these with the anonymous scan as well. If a pushed down filter for instance does not do the filter at the scan level, it will not do it at all and your result would be incorrect.

**Comment by universalmind303** [comment]
> Cool idea. Maybe could add a trait object that generates the schema as well. Then we can implement the trait objects (similar to what we do with Expr::apply).
>
> This would eventually allow us to refactor the all the scans to implmentations this generic scan node.

thats a great idea. Ill take a look into it.

**Comment by universalmind303** [comment]
@ritchie46 maybe im missing something. when you mention the trait, are you referring to the `SeriesUdf` trait? 
I implemented an `AnonymousScan` trait that was based around the `SeriesUdf` one.  


```rust
pub trait AnonymousScan: Send + Sync {
    fn scan(&self, scan_opts: AnonymousScanOptions) -> Result<DataFrame>;
}

impl<F> AnonymousScan for F
where
    F: Fn(AnonymousScanOptions) -> Result<DataFrame> + Send + Sync,
{
    fn scan(&self, scan_opts: AnonymousScanOptions) -> Result<DataFrame> {
        self(scan_opts.clone())
    }
}

```

so i think you could already do something like `impl AnonymousScan for <struct>` 


also referring to the optimizations, I think i have all of those working. 

If i understand the optimizer correctly, it will pushdown when it can, otherwise it will execute at the current node.

I tried a few different expressions such as filter, rename, select & they all worked. Is there a better way to test that **ALL**  operations are working properly though?

**Comment by universalmind303** [comment]
Added more to the `AnonymousScan` trait. it now has `scan` and `schema` methods.
```rust
pub trait AnonymousScan: Send + Sync {
    fn scan(&self, scan_opts: AnonymousScanOptions) -> Result<DataFrame>;
    fn schema(&self, _infer_schema_length: Option<usize>) -> Result<Schema> {
        Err(PolarsError::ComputeError(
            "Must supply either a schema or a schema function".into(),
        ))
    }
}
```

it will first try to use a provided schema via the `AnonymousScanOptions`, otherwise it will call the `.schema()` method. 

the JSON implementation using the trait


```rust
struct JsonScan {
    path: String,
}

impl AnonymousScan for JsonScan {
    fn scan(&self, scan_opts: AnonymousScanOptions) -> polars::prelude::Result<DataFrame> {
        if let Some(s) = scan_opts.output_schema {
            JsonLineReader::from_path(&self.path)
                .expect("unable to read file")
                .with_schema(&s)
                .finish()
        } else {
            JsonLineReader::from_path(&self.path)
                .expect("unable to read file")
                .finish()
        }
    }

    fn schema(&self, infer_schema_length: Option<usize>) -> polars::prelude::Result<Schema> {
        let f = File::open(&self.path)?;
        let mut reader = BufReader::new(f);

        let data_type = ndjson::read::infer(&mut reader, infer_schema_length).unwrap();
        let schema: polars_core::prelude::Schema = StructArray::get_fields(&data_type).into();

        Ok(schema)
    }
}
#[napi]
pub fn scan_json(path: String) -> napi::Result<JsLazyFrame> {
    let f = JsonScan { path };

    let options = ScanArgsAnonymous {
        name: "JSON SCAN",
        infer_schema_length: Some(100),
        ..ScanArgsAnonymous::default()
    };
    let lf = LazyFrame::anonymous_scan(std::sync::Arc::new(f), options)
        .map_err(JsPolarsErr::from)?;
    Ok(lf.into())
}
```

**Comment by universalmind303** [comment]
here is a full example of using the anonymousScan trait to lazily load from mongo. 

https://github.com/universalmind303/polars-mongo/tree/main/src

**Comment by chitralverma** [comment]
Do you think its a good idea to split the anonymous scan code bits from the scan_json into 2 different PRs?

the scan_json PR can then act as a template for others to contribute their own implementations. I'm thinking of trying scan_sql based on connector-x but I'm toooo new to Rust

**Comment by universalmind303** [comment]
@ritchie46 is there anything else you would like to see done in this PR before merging it?

**Comment by ritchie46** [comment]
Thanks for the work on this @universalmind303. It looks good. I think there are still a few things we can iron out, such as predicate pushdown, and slice pushdown, but that is not a blocker. Let's merge it in and continue with this.

**Pull request merged**
