### PR TITLE
cumulative_eval

### PR DESCRIPTION
**Pull request by ritchie46**
New expression evaluation.

```python
df = pl.DataFrame({
    "values": [1, 2, 3, 4, 5]
})

df.select([
    pl.col("values").cumulative_eval(pl.element().first() - pl.element().last() ** 2)
])
```

```
shape: (5, 1)
┌────────┐
│ values │
│ ---    │
│ f64    │
╞════════╡
│ null   │
├╌╌╌╌╌╌╌╌┤
│ -3.0   │
├╌╌╌╌╌╌╌╌┤
│ -8.0   │
├╌╌╌╌╌╌╌╌┤
│ -15.0  │
├╌╌╌╌╌╌╌╌┤
│ -24.0  │
└────────┘

```

### CODE REVIEW

**Comment by cbilot** [comment]
Question: could this be handled by a `rolling_apply`, with `window_size` set to df.height?  (Presumably this is related to the SO question about replicating the `expanding` functionality in Pandas.)

One note: `rolling_apply` returns a column of `null` values when `window_size` >= df.height

**Comment by ritchie46** [comment]
> Question: could this be handled by a rolling_apply, with window_size set to df.height? (Presumably this is related to the SO question about replicating the expanding functionality in Pandas.)

Good observation. :thinking: 

I was thinking about a `rolling_eval` as well. Are you saying that `rolling_eval` is a superset of this function?

**Comment by cbilot** [comment]
What I was going to recommend (after filing the two bug reports for `rolling_apply`) was a `cum_apply`, which would be syntactic sugar for calling `rolling_apply`, but with `cum_apply` supplying the `window_size` set to the height of the DataFrame, which may not known to the caller, especially in Lazy mode.

I realize that `pipe` can be used to get the current state of a DataFrame when methods are chained, but that might not be readily apparent to most users.

**Comment by ritchie46** [comment]
> What I was going to recommend (after filing the two bug reports for `rolling_apply`) was a `cum_apply`, which would be syntactic sugar for calling `rolling_apply`, but with `cum_apply` supplying the `window_size` set to the height of the DataFrame, which may not known to the caller, especially in Lazy mode.
> 
> I realize that `pipe` can be used to get the current state of a DataFrame when methods are chained, but that might not be readily apparent to most users.

We should be able to use `pl.count()` for that. I think I will still merge this in as `experimental` API and will follow-up with a `rolling_eval` as well. I think that we should be able to replace this later with `rolling_eval(expr, window_size=pl.count())`.

**Pull request merged**
