### PR TITLE
fix(python): Replace _kwargs in collect method

### PR DESCRIPTION
**Pull request by jackxxu**
when I was incorporating @ritchie46's suggestion in disabling CSE in the `collect` method in https://github.com/pola-rs/polars/issues/19480, I initially used 

```python
ldf.collect(common_subplan_elim=False)
```

it didn't complain but produces no performance improvements that I was expecting, until I looked it up and found the keyword to be `comm_subplan_elim` instead. 

this PR solves this potential pitfull for developers by replacing the _kwargs with spelled out keyword arguments, to let python do the checking for us and raise TypeError if not correct. 

typically, unless a method either forwards/delegates the kwargs to another method or it takes whatever, it is reasonable to assume that the method spells out its interface.

### CODE REVIEW

**Comment by cmdlineluser** [comment]
This will close https://github.com/pola-rs/polars/issues/16525

**Comment by ritchie46** [comment]
post_opt_callback is not intended for public use. It is private. We should instead check the content of `_kwargs` for items that aren't allowed (if any).

**Comment by jackxxu** [comment]
@ritchie46, commits added

**Comment by ritchie46** [comment]
Thank you @jackxxu

**Pull request merged**
