### PR TITLE
docs(python): Overview of available SQL functions

### PR DESCRIPTION
**Pull request by r-brink**
Related to #15575.

### CODE REVIEW

**Comment by stinodego** [comment]
@r-brink Did you mean to keep this on draft or is this ready to be reviewed?

**Comment by alexander-beedie** [comment]
(Mouse/keyboard went nuts for a second and somehow closed the issue - reopened 🤣)

**Comment by jqnatividad** [comment]
Awesome! Would be ideal if the examples also show the expected results...

**Comment by r-brink** [comment]
@jqnatividad great idea. When the foundation is in place I will look into extending the examples.

**Review by alexander-beedie — APPROVED** [review]
Structure is looking good, and a decent percentage of the functions are now covered! Can follow-up with the ones that are still missing (eg: operators, supported function aliases, etc) 😎👍

**Comment by ritchie46** [comment]
@alexander-beedie there is a lint error. Can you take a look? Would be nice if we can ship this with the release. :)

**Pull request merged**
