### PR TITLE
Override series logical operators and deal with expr

### PR DESCRIPTION
**Pull request by alonme**
closes https://github.com/pola-rs/polars/issues/8534

### CODE REVIEW

**Comment by alonme** [comment]
Would `py-polars/tests/unit/operations/test_comparison.py` be a better place for the tests?
not sure why meta is needed in both sides of the comparison here, but not in`test_series_expr_arithm`

**Comment by mcrumiller** [comment]
Ahh I already have a PR for this at #8549. I put the unit tests in `test_comparison.py`.

**Comment by alexander-beedie** [comment]
I'll review this and #8549 tomorrow (heading out any second for the weekend!) 😅👍

**Comment by alexander-beedie** [comment]
@alonme: thanks very much for the patch! it looks absolutely fine, but it is also essentially the same as @mcrumiller's slightly earlier patch, which has wider test coverage - I'm going to merge the earlier PR "as-is", but I _also_ think there is value in including your `meta` tests too. If you don't mind rebasing and leaving just those `meta` tests, I'll also happily merge those 👍

**Review by alexander-beedie — CHANGES_REQUESTED** [review]
@alonme: first, thanks very much for the patch! it looks absolutely fine, but it is also essentially the same as @mcrumiller's slightly [earlier](https://github.com/pola-rs/polars/pull/8549) patch, which has wider test coverage - I'm going to merge the earlier PR "as-is", but I _also_ think there is value in including the `meta` tests from your PR here. If you don't mind rebasing and leaving just those tests in this PR, I'll also happily merge those 👍

**Comment by ritchie46** [comment]
superseded by #8549

**Pull request closed without merging**
