### PR TITLE
fix(rust,python): improve printing controls of DataFrame and Series

### LINKED ISSUE #5046: printing any Series is limited to 25 elements maximum
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Currently, `polars` limits the printed output of any Series to 25 elements maximum. If a series is larger than 25 elements the first 12 and the last 12 elements are printed for a total of 24. The limit of 25 is hard-coded (see `const LIMIT` in `polars/polars-core/src/fmt.rs`). On the other hand for a `DataFrame` the maximum number of rows printed can be controlled with `polars.Config.set_tbl_rows` function. Following the Principle of Least Surprise I would expect prining `Series` to behave similar to printing a `DataFrame` with the same degree of user controls.

### Reproducible Example

```python
import polars as pl
import numpy as np
ser = pl.Series('ser', np.arange(1, 1+32))
print(ser)
```

### Expected Behavior

I would expect `polars.Config.set_tbl_rows` to control maximum number of rows when printing a `Series` the same way it does it in the case of a `DataFrame`.

### Installed Versions

<details>
```

---Version info---
Polars: 0.14.14
Index type: UInt32
Platform: macOS-12.6-arm64-arm-64bit
Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:22) [Clang 13.0.1 ]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.0
numpy: 1.23.3
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8

```
</details>

### PR DESCRIPTION
**Pull request by slonik-az**
fixes #5046

(1) Let polars.Config.set_tbl_rows to control maximum number of
    elements when printing Series (in general any Series => str conversion).
    Works the same way as when printing DataFrame.

(2) Calling polars.Config.set_tbl_rows or polars.Config.set_tbl_cols with
    any negative integer (-1 is recommended) will cause all the rows
    (DataFrame and Series) or all the columns (DataFrame) be printed.

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Nice! Do you think you could tweak the "all rows" value to `-1`, rather than `0`? If I went into a shop and asked for zero apples, I'd be quite surprised if they then gave me all of the apples they had 😄

(On a more realistic note, I can imagine that there may be some --admittedly odd!-- edge-cases where you might actually _want_ to return tables with no rows; overriding zero to mean "all" leaves no way to do so).

**Comment by slonik-az** [comment]
> Nice! Do you think you could tweak the "all rows" value to -1, rather than 0? 

Fair enough. For the sake of consistency I will make setting rows (cols) to any negative number (-1,-2,etc) to print all the rows (cols) in a DataFrame or Series.

**Comment by slonik-az** [comment]
> (On a more realistic note, I can imagine that there may be some --admittedly odd!-- edge-cases where you might actually want to return tables with no rows; overriding zero to mean "all" leaves no way to do so).

Actually, in the current polars (as of `py-0.14.15`) when you `set_tbl_rows(0)` the actual value used for max rows will be 2, making it impossible to force print zero number of rows. In my PR I keep this behavior unchanged.
https://github.com/pola-rs/polars/blob/1968f3f6fe9f82215eb8dbebbde2fb04e1df0cca/polars/polars-core/src/fmt.rs#L344-L348

**Comment by slonik-az** [comment]
Just updated the PR with the requested changes. Also rebased it onto the latest `master`.

**Comment by ritchie46** [comment]
Al right. Thanks!

**Comment by slonik-az** [comment]
@ritchie46: Thanks for promptly merging it in!

**Comment by alexander-beedie** [comment]
> Actually, in the current polars (as of `py-0.14.15`) when you `set_tbl_rows(0)` the actual value used for max rows will be 2, making it impossible to force print zero number of rows. In my PR I keep this existing behavior unchanged.
> 
> https://github.com/pola-rs/polars/blob/1968f3f6fe9f82215eb8dbebbde2fb04e1df0cca/polars/polars-core/src/fmt.rs#L344-L348

Very peculiar :) 
Think I might take a look at this separately later to see why; thanks!

**Pull request merged**
