### PR TITLE
feat(rust, python): expression functions should be nullable

### PR DESCRIPTION
**Pull request by ritchie46**
Polars function should be able to return `None`. So I had to suck it up and change all signatures.

This also make them fallible in the groupby context.

### CODE REVIEW

**Comment by alexander-beedie** [comment]
頑張れ! 🤣👍

**Comment by rben01** [comment]
What is the rationale for being able to return `None`, and what happens if a function does return `None`?

**Comment by ritchie46** [comment]
We have a missing data type null. If you return `None` an element in that column will be null.

**Comment by rben01** [comment]
Sorry, I should have been more specific. I'm wondering specifically about the `Series -> Result<Option<Series>>` function in map(). What would it mean to return `Ok(None)`?

**Comment by rben01** [comment]
Never mind, looks like it returns all nulls. I'm not sure this is preferable to the pre-v0.27 way, where you just returned a `Result<Series>`. If a user wants to return all nulls, they can just return `Ok(Series::full_null(...))`. I'm not sure you should have to wrap your Series in `Some()` just to enable a shorthand for `Series::full_null(...)`. Was there a use case in mind when this was changed?

**Comment by ritchie46** [comment]
In a groupby it returns a null for that groupby. We have to deal with multiple contexts, not only select.

**Pull request merged**
