### PR TITLE
python: expose hash expr and row hash

### PR DESCRIPTION
**Pull request by ritchie46**
Following discussion #983. This PR exposes fast ways to hash the rows of a DataFrame using expressions or `DataFrame.hash_rows` on eager. The latter is multi-threaded.

```python
  df = pl.DataFrame({"a": [1, 2, 3, 4], "b": [2, 2, 2, 2]})
  assert df.hash_rows().dtype == pl.UInt64
  assert df["a"].hash().dtype == pl.UInt64
  assert df[[col("a").hash().alias("foo")]]["foo"].dtype == pl.UInt64
```

@potter420 Then you only need a way to map `Uint64` to `Int64`.

### CODE REVIEW

**Comment by alippai** [comment]
This is really useful, I often miss column and row hashes from databases and OLAP engines.

**Comment by potter420** [comment]
Thank you, many of  ETL process use hashing for fast comparison. About mapping UInt64 -> Int64, I would implement some special cast function that perform some thing similar to C interpreted cast to keep hash collision chance the same.

**Comment by ritchie46** [comment]
> This is really useful, I often miss column and row hashes from databases and OLAP engines.

Yes, its the second time I got a question about this, so why not expose that logic. :)

**Comment by potter420** [comment]
Hi @ritchie46, I found some strange behaviors with dataframe `hash_rows`:
```python
import polars as pl

df = pl.DataFrame(
    {
        "nrs": [1, 2, 3, 4, None],
        'test': [1,2,3,None, None],
        "names": ["ham", "spam","foo", None, None],
        "names2": ["ham", "spam", None, "foo", None],
    }
)
# First Time
df.hash_rows()
shape: (5,)
Series: '' [u64]
[
	1488686405957914050
	6737329070860408218
	8536850415921746323
	6434648716224363646
	17425255898174199390
]
# Second Time
shape: (5,)
Series: '' [u64]
[
	1404979440027547477
	16668494198585157804
	17949374023307804071
	8002145416063809924
	10914413357562785698
]
```

Series `hash` seem to worked fine since you set the seed already, but the seed is not set for DataFrame `hash_rows`. So it produced random result as seen in the above.

Was this its intended behaviours?

**Comment by ritchie46** [comment]
> Was this its intended behaviours?

Yes, this is as expected. The hash logic is from the [ahash crate](https://github.com/tkaitchuck/aHash), which randomly initializes between runs, this can prevent accidental quadratic behavior.

I understand that this may be confusing, or unwanted. I will add the seeds, similar to that in `Series.hash`

**Comment by potter420** [comment]
I actually went and modify the code to have a static seed like Series `hash`, should I create a pull requests?

**Pull request merged**
