### PR TITLE
feat(rust, python): quote style option for csv writer

### LINKED ISSUE #9433: Add quoting parameter in pl.write_csv()
### Problem description

It will be good to have a `quoting` parameter in `df.write_csv()` method.

Something like
```
df.write_csv(path, separator=",", quoting=QuoteStyle.Necessary)
```

For reference here is a doc page in Rust
https://docs.rs/csv/latest/csv/enum.QuoteStyle.html

As example Pandas have similar parameter which is defaults to `csv.QUOTE_MINIMAL`

### PR DESCRIPTION
**Pull request by ritchie46**
closes #9433

### CODE REVIEW

**Comment by orlp** [comment]
Do we really want `QuoteStyle::Never`?

**Comment by ritchie46** [comment]
> Do we really want `QuoteStyle::Never`?

I thought this was iffy as well. I will remove it, as we cannot roundtrip.

**Comment by cjackal** [comment]
> Do we really want `QuoteStyle::Never`?

My understanding is that it has a value to [rather escape than quote the delimiters appearing in a field](https://docs.python.org/3/library/csv.html?highlight=csv#csv.QUOTE_NONE) (e.g. for a text field with `\t` to be written in tab-delimited format), but polars does not support disabling double quote so `quote.never` is kind of vestigal for now.

**Comment by ritchie46** [comment]
We will also never enable it.

We only follow RFC 4180 as closest thing to formal csv format: https://datatracker.ietf.org/doc/html/rfc4180

**Pull request merged**
