### PR TITLE
feat(rust, python)!: adjusting date method return values

### PR DESCRIPTION
**Pull request by andrewpollack**
Fixes: #6079

Tracking progress to adjust date method return values to more efficient int sizings

### CODE REVIEW

**Comment by andrewpollack** [comment]
Chasing down errors from trait impl from differences between `ChunkedArray<Int8Type>` and `ChunkedArray<Int32Type>`

```
error[E0599]: the method `into_series` exists for struct `ChunkedArray<Int8Type>`, but its trait bounds were not satisfied
   --> polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs:101:28
    |
101 |     s.second().map(|ca| ca.into_series())
    |                            ^^^^^^^^^^^ method cannot be called on `ChunkedArray<Int8Type>` due to unsatisfied trait bounds
    |
   ::: /home/andrew/devel/polars/polars/polars/polars-core/src/chunked_array/mod.rs:150:1
    |
150 | pub struct ChunkedArray<T: PolarsDataType> {
    | ------------------------------------------ doesn't satisfy `_: IntoSeries`
    |
   ::: /home/andrew/devel/polars/polars/polars/polars-core/src/series/implementations/mod.rs:48:1
    |
48  | pub(crate) struct SeriesWrap<T>(pub T);
    | ------------------------------- doesn't satisfy `_: SeriesTrait`
    |
    = note: the following trait bounds were not satisfied:
            `implementations::SeriesWrap<polars_core::chunked_array::ChunkedArray<Int8Type>>: polars_core::prelude::SeriesTrait`
            which is required by `polars_core::chunked_array::ChunkedArray<Int8Type>: polars_core::prelude::IntoSeries`

For more information about this error, try `rustc --explain E0599`.
```

**Comment by stinodego** [comment]
Great that you're getting this done! I added a `breaking` tag, since this will break existing code.

**Review by ritchie46 — COMMENTED** [review]
Thanks for the PR @andrewpollack. I only think the current implementation is not the right way forward. All the code is essentially doing

```
out= []
for val in container:
   out.push(some_computation(val))
  
out2 = []
for val in out:
  out2.push( cast(val))
```

Which is double the amount of work we should do. 

We should adapt the kernels in https://github.com/jorgecarleitao/arrow2/blob/main/src/compute/temporal.rs

so that they give the output we'd like for this crate.

**Comment by andrewpollack** [comment]
Got it! I've opened an issue to see if we could build that upstream https://github.com/jorgecarleitao/arrow2/issues/1372

As well, life circumstances have changed a bit and I do not have as much time to work on this as before. I apologize @ritchie46 and will try to get to this when I'm able to. Also happy to let others work on it should there be interest

**Comment by stinodego** [comment]
I am closing this PR as it has not been updated in a while.

Also, I believe the linked issue in the Arrow2 repo must be addressed first.

**Pull request closed without merging**
