### PR TITLE
chore(python): Add lint for boolean trap

### PR DESCRIPTION
**Pull request by stinodego**
A while back I opened https://github.com/pola-rs/polars/issues/6993 to standardize keyword-only arguments across our API. Part of this was to make all boolean arguments keyword-only.

Apparently, I am not the only one that thinks this is a good idea, as it there is an actual term associated with this - the boolean trap.

Since then, a lot of new boolean parameters have been introduced to our API, and a lot of them as positional arguments. To stop this from happening in the future, I enabled the ruff lint `flake8-boolean-trap`.

Had to fix a bunch of internal calls and add some deprecation warnings. Hopefully we can now keep a consistent API going forward.

#### Changes

* Add [`flake8-boolean-trap`](https://beta.ruff.rs/docs/rules/#flake8-boolean-trap-fbt) lint
* Fix all errors
* Deprecate some non-keyword arguments in our public API

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Nice find! 🏆

**Comment by alexander-beedie** [comment]
I notice one more thing here - are we making a policy of standardising on American spellings?
(Saw that you changed "normalise" 🇬🇧  to "normalize" 🇺🇸).

**Comment by stinodego** [comment]
> I notice one more thing here - are we making a policy of standardising on American spellings?
> (Saw that you changed "normalise" 🇬🇧 to "normalize" 🇺🇸).

Indeed, I think we should try to adhere to American spelling. We already do so in our public API (`serialize`, `finalize`), so let's do the same in our docstrings and private API.

For better or worse, American spelling is what most people are familiar with, outside of Great Britain and academia.

**Comment by alexander-beedie** [comment]
> For better or worse, American spelling is what most people are familiar with, outside of Great Britain and academia.

Well, that's definitely not true, heh - India alone counts for over a billion people who use British English as a second language. Still, British English technically allows both `-ise` and `-ize` suffixes, so no grammar wars need be waged 🤣

**Comment by stinodego** [comment]
I guess that is my non-informed European take then 😄

**Comment by alexander-beedie** [comment]
> I guess that is my non-informed European take then 😄

The European Union _"English Style Guide, A handbook for authors and translators in the European Commission"_ also declares `-ise` as their standard 😇 (now I'm just actively causing trouble, haha...)

Section 3.2, p.18: https://commission.europa.eu/system/files/2023-07/styleguide_english_dgt_en.pdf

**Pull request merged**
