### PR TITLE
Add align_on parameter to pl.concat(how="horizontal")

### LINKED ISSUE #8807: Add align_on parameter to pl.concat when horizontal is used
### Problem description

Possibly an addition to #8753. A relatively common operation is to align multiple dataframes and combine them. We already have an [`align_frames`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.align_frames.html) function, but has this note:

> Note that this does not result in a joined frame - you receive the same number of frames back that you passed in, but each is now aligned by key and has the same number of rows.

After aligning, you have to go through frames 2-N and drop the key columns. A nice feature would be either to have `pl.concat(dfs, how="horizontal", align_on=keys)`, or a separate `pl.align_and_join`. Something like this:

```python
import polars as pl

df1 = pl.DataFrame({
    "key": [1, 2, 3],
    'a': [4, 5, 6],
})

df2 = pl.DataFrame({
    "key": [1, 3, 4],
    'b': [7, 8, 9],
})

df3 = pl.concat([df1, df2], how="horizontal", align_on="key")

     df1                   df2                       df3
┌─────┬──────┐        ┌─────┬──────┐        ┌─────┬──────┬──────┐
│ key ┆ a    │        │ key ┆ b    │        │ key ┆ a    ┆ b    │
╞═════╪══════╡        ╞═════╪══════╡        ╞═════╪══════╪══════╡
│ 1   ┆ 4    │        │ 1   ┆ 7    │        │ 1   ┆ 4    ┆ 7    │
│ 2   ┆ 5    │        │ 3   ┆ 8    │  --->  │ 2   ┆ 5    ┆ null │
│ 3   ┆ 6    │        │ 4   ┆ 9    │        │ 3   ┆ 6    ┆ 8    │
└─────┴──────┘        └─────┴──────┘        │ 4   ┆ null ┆ 9    │
                                            └─────┴──────┴──────┘
```

### PR DESCRIPTION
**Pull request by mcrumiller**
resolves #8807. Willing to discuss better syntax.

```python
import polars as pl

df1 = pl.DataFrame({
    "key": [1, 2, 3],
    'a': [4, 5, 6],
})

df2 = pl.DataFrame({
    "key": [1, 3, 4],
    'b': [7, 8, 9],
})

df3 = pl.concat([df1, df2], how="horizontal", align_on="key")

     df1                   df2                       df3
┌─────┬──────┐        ┌─────┬──────┐        ┌─────┬──────┬──────┐
│ key ┆ a    │        │ key ┆ b    │        │ key ┆ a    ┆ b    │
╞═════╪══════╡        ╞═════╪══════╡        ╞═════╪══════╪══════╡
│ 1   ┆ 4    │        │ 1   ┆ 7    │        │ 1   ┆ 4    ┆ 7    │
│ 2   ┆ 5    │        │ 3   ┆ 8    │  --->  │ 2   ┆ 5    ┆ null │
│ 3   ┆ 6    │        │ 4   ┆ 9    │        │ 3   ┆ 6    ┆ 8    │
└─────┴──────┘        └─────┴──────┘        │ 4   ┆ null ┆ 9    │
                                            └─────┴──────┴──────┘
```

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Ahhh... I have a version of this about to land that additionally auto-determines the common-cols alignment key 😅

**Comment by mcrumiller** [comment]
Ahh dang, ok. That makes sense since we'd err out with additional common columns anyway. Out of curiosity, what did you land on for syntax? `align=True`?

**Comment by mcrumiller** [comment]
Come to think of it, `how="join"` makes the most sense. Not sure if the join type should be provided.

**Comment by alexander-beedie** [comment]
> what did you land on for syntax? `align=True`?

Yup; the alignment with the existing `align_frames` makes things consistent, and avoids an extra param that only works with 1 of the 4 options. I've also found a small gremlin in `align_frames` while adding more tests, so I'm going to deal with that at the same time.

**Comment by mcrumiller** [comment]
> So what is the difference with join(..., on='key', how='outer')

This performs the join simultaneously on multiple dataframes. This was most likely the original purpose of `align_frames` in the first place (to set up multiple frames for an outer join), so it makes sense to have a function that finishes the job.

**Comment by gab23r** [comment]
My humble opinion on this one: I am -0.5 on adding this extra argument to the `concat` method. For me, one method should do one thing and one thing right. You already have one method to join, one method to concat and you even have one method to align frames ( which is a synthetic sugar for a join AFAIK) 
I am scared to bloat the api with to many arguments to functions...
If it is for performance purpose ( parallel join...) maybe we could work on this optimizer side ? 
Or maybe we need `pl.join(df1, df2, ...)`. But for me, this sounds definitely like a join operation.

**Comment by alexander-beedie** [comment]
I'm going to close this out; now I've addressed an issue in `align_frames` I'm going to rework/finish-up a slightly different approach to this one that doesn't require the extra parameter (but thanks as always for the PR @mcrumiller! 👍)

**Pull request closed without merging**
