### PR TITLE
build(python): Don't compile the `x86_64` Mac binaries with AVX/FMA instructions (unsupported under Rosetta)

### LINKED ISSUE #11650: illegal hardware instruction in Mac OS with M1 chip (under Rosetta)
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pip install polars
import polars
```

### Log output

```shell
zsh: illegal hardware instruction.
BTW., if I use conda install -c conda-forge polars, I will obtain the segmentation faults when I try to use it.
```

### Issue description

The problem should be related to the M1 chip. I install polars-lts-cpu, i can import it and work well. But I really hope the polars can support Mac OS with M1 chip.
BTW., the system is MacOS 11.2.3.

### Expected behavior

It should work, just like in windows and ubuntu.

### Installed versions

<details>

```
0.19.7
```

</details>

### PR DESCRIPTION
**Pull request by alexander-beedie**
I suspect this closes #11650, as AVX instructions are not available[^1] under Rosetta.

(Note: this change has no impact on the native `aarch64` Apple Silicon builds).

FYI: for the curious, you can see exactly what _is_ supported by opening a Rosetta Terminal and running:
```bash
❯ sysctl -a | grep machdep.cpu.features

FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR 
PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE 
SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTSE64 MON DSCPL 
VMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 AES SEGLIM64
```

[^1]: https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment#What-Cant-Be-Translated

### CODE REVIEW

**Comment by orlp** [comment]
Isn't this fighting the symptoms rather than the cause? Why did `pip install polars` on an Apple M1 result in a Rosetta x86-64 wheel being shipped? Is it because they have x86-64 Python installed?

Either way x86-64 Mac is on its dying breath so I wouldn't mind this, at least until we have proper error messages for CPU feature detection. I'd also get rid of the FMA then, though.

**Comment by alexander-beedie** [comment]
> Isn't this fighting the symptoms rather than the cause? Why did `pip install polars` on an Apple M1 result in a Rosetta x86-64 wheel being shipped? Is it because they have x86-64 Python installed?

Yup, exactly; their _entire_ python/polars environment would have to be running under Rosetta to trigger this. Quite a few possibilities, such as pre 3.9 versions of Python (which -I think- is when that got native support).

**Comment by stinodego** [comment]
At this point the flags are exactly the same as LTS-CPU, so why do we even build this wheel then?

**Comment by alexander-beedie** [comment]
> At this point the flags are exactly the same as LTS-CPU, so why do we even build this wheel then?

Doesn't configure mimalloc? 
That looks like the only difference now.

**Comment by orlp** [comment]
@stinodego It's still a good idea to make the `polars-lts-cpu` wheel available everywhere so it's a stable workflow anywhere.

**Comment by alexander-beedie** [comment]
> Why did `pip install polars` on an Apple M1 result in a Rosetta x86-64 wheel being shipped? Is it because they have x86-64 Python installed?

User just provided their `pl.show_versions()` and it confirms the initial suspicion; they're running an old Anaconda environment against Python 3.8 under Rosetta... So, this update would definitely fix their issue - as would them transitioning to a native Apple Silicon build of Anaconda (I'm curious what keeps them on this build, but perhaps there are a few long-tail binaries they need that still haven't made the jump 🤷).

**Comment by stinodego** [comment]
I would lean towards closing this and just tell the user to use `polars-lts-cpu`. We've been compiling with the same flags for ages and this is the first we hear about someone having problems (and it's not because of the recent update as it didn't affect MacOS).

**Pull request closed without merging**
