### PR TITLE
[Arrow2] IO parquet + ipc

### PR DESCRIPTION
**Pull request by jorgecarleitao**
Built on top of #864, migrated io and lazy, `cargo build` exits 0 :)

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Actually, migrated the rest:

```
azureuser@arrow:~/projects/polars$ cargo build
   Compiling polars-lazy v0.14.2 (/home/azureuser/projects/polars/polars/polars-lazy)
   Compiling polars v0.14.2 (/home/azureuser/projects/polars/polars)
    Finished dev [unoptimized + debuginfo] target(s) in 14.41s
```

**Comment by jorgecarleitao** [comment]
There are some test failures, which is the next goal

```
failures:
    chunked_array::test::test_shrink_to_fit
    frame::hash_join::test::test_join_multiple_columns
    frame::test::test_h_agg
    series::arithmetic::test::test_arithmetic_series_date
    series::implementations::dates::test::test_agg_list_type
    series::implementations::dates::test::test_datelike_join
    series::implementations::dates::test::test_datelike_methods
```

**Comment by ritchie46** [comment]
> There are some test failures, which is the next goal

Yes, I will also merge changes from latest two weeks in. And see what we have the do in the python bindings. I think mostly some changes regarding FFI there.

**Comment by ritchie46** [comment]
I think this one needs a rebase.

**Comment by jorgecarleitao** [comment]
@ritchie46 rebased. The CI is refusing the flag `--test-threads 2`. Maybe it is missing an extra `--`?

py-polars is picking the wrong version of arrow2; I can reproduce it in my pc and I am debugging.

**Pull request merged**
