### PR TITLE
fix(python): parse time unit properly in pl.lit

### PR DESCRIPTION
**Pull request by orlp**
Fixes https://github.com/pola-rs/polars/issues/11571.

### CODE REVIEW

**Comment by orlp** [comment]
@MarcoGorelli Do you have any idea why this fails the tests? I don't see how my changes could've cause that.

**Comment by MarcoGorelli** [comment]
I think it's because `removeprefix` and `removesuffix` aren't available in Python 3.8

**Review by MarcoGorelli — APPROVED** [review]
nice one

**Comment by ritchie46** [comment]
Can you add a test, so we don't regress?

**Comment by orlp** [comment]
@ritchie46 Done.

**Review by ritchie46 — APPROVED** [review]

**Pull request merged**
