### PR TITLE
docs(rust): Align dates in DataFrame example with Python

### PR DESCRIPTION
**Pull request by xhiroga**
Aligns dates in Rust DataFrame example with Python version and standard output.

This improves consistency across documentation, preventing confusion for users.

### CODE REVIEW

**Comment by xhiroga** [comment]
FYI: As shown, there is a discrepancy between the Rust code and the standard output example (as well as the Python code) in [docs](https://docs.pola.rs/user-guide/concepts/data-structures/#dataframe).

image

**Review by alexander-beedie — APPROVED** [review]
Well spotted ;)

**Comment by alexander-beedie** [comment]
@xhiroga: Ahhh... I see there is now a conflict; could would you mind resolving? 🙏

**Comment by xhiroga** [comment]
@alexander-beedie Sure! I've just resolved the conflict and updated the PR.
Thanks for the heads-up :)

**Comment by alexander-beedie** [comment]
@ritchie46: FYI, this one's good to merge now :)

**Review by stinodego — APPROVED** [review]

**Pull request merged**
