### PR TITLE
Check byte after "\n" for "\r" instead of 2 bytes after.

### PR DESCRIPTION
**Pull request by ghuls**
Fixes https://github.com/pola-rs/polars/issues/2433

### CODE REVIEW

**Comment by ghuls** [comment]
@ritchie46 I am not sure if we should check the byte after "\n" for a "\n" as Windows line-ending are "\r\n" and not "\r\n".

**Comment by pensono** [comment]
Thanks! 

As a note, I personally have never seen `\n\r`

**Comment by ritchie46** [comment]
No, I think I just made a mistake here.

**Comment by ghuls** [comment]
@ritchie46 then removing this few lines of code might speedup CSV parsing 0.01%.

**Comment by ritchie46** [comment]
> @ritchie46 then removing this few lines of code might speedup CSV parsing 0.01%.

Yes, could you do an additional PR?

Likely does more if it is in a hot path.

**Comment by ghuls** [comment]
https://github.com/pola-rs/polars/pull/2437

**Pull request merged**
