### PR TITLE
feat(python,rust): add many more auto inferable datetime formats

### LINKED ISSUE #16115: str.to_datetime - should support date format "%Y.%m.%d" # 2023.12.31
### Description

I'd like to see
%Y.%m.%d" # 2023.12.31
date format added to polars.Expr.str.to_datetime.

This would then support the date notation in Hungary (see also [Wikipedia article](https://en.wikipedia.org/wiki/Date_and_time_notation_in_Hungary)).

(The time format is similar to other countries, eg %H:%M:%S, %H:%M.)

### PR DESCRIPTION
**Pull request by JulianCologne**
fix #16115

also as @alexander-beedie mentioned (https://github.com/pola-rs/polars/issues/16115#issuecomment-2101990383) I added support for many missing patterns so that all separators (`-`, `.`, `/`) have the same patterns.

## ❗ Needs Decision

There are currently 3 failing tests because they have datetime texts with fractional seconds that do not have 3/6/9 digits but something else like
- `2018-09-05T04:24:01.9` -> 1 digit
- `2018-09-05T04:24:02.11` -> 2 digits

usually fractional seconds should only be in milli, micro or nano seconds. Not sure if there are actually any formats out there apart from the tests?!?
Still, it would be possible to support that using the `%.f` specifier (little slower probably) instead of `%.3f`, `%.6f`, `%.9f`

Need Feedback if we want to support those (strange?) seconds fractions (-> will adjust patterns accordingly) or not (-> will adjust tests)

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
thanks @JulianCologne 

for the failing tests, is that because you've removed `"%FT%H:%M:%S%.f"`? tbh I'd be ok with just keeping that one in at the end of the list, no big deal

**Comment by JulianCologne** [comment]
> thanks @JulianCologne
> 
> for the failing tests, is that because you've removed `"%FT%H:%M:%S%.f"`? tbh I'd be ok with just keeping that one in at the end of the list, no big deal

yes, I removed that on purpose because it makes the patterns unbalanced.
With all the different separators and formats we have like ~30 patterns but then only 1(!) should support different number of fractional digits? Feels very wrong and arbitrary to me

Format `%FT%H:%M:%S%.f` is just an abbreviation where `%F=%Y-%m-%d` 

My suggestion would be either to not support this (have never seen this irl) or support any fractional digits for all patterns wich can be achieved by either
- adding `%.f` (any number of digits) after all the `%.3f`, `%.6f`, `%.9f` patterns, or
- use `%.f` (any number of digits) **instead of** all the `%.3f`, `%.6f`, `%.9f` patterns

**Comment by MarcoGorelli** [comment]
> Feels very wrong 

It's just an extra pattern :) For context, it comes from https://github.com/pola-rs/polars/issues/3195 . %Y-%m-%dT%H:%M:%S%.f is the common ISO8601 format, IMO it's ok for that one to be a bit laxxer as a last-resort, so long as it's in the "other" section at the end of the formats (as it currently is)

**Comment by JulianCologne** [comment]
@MarcoGorelli 
my last commit added the missing pattern again and all checks are passing.
Ready from my side 😃

**Review by MarcoGorelli — APPROVED** [review]
cool, open to expanding these, thanks @JulianCologne !

**Pull request merged**
