### PR TITLE
depr(python): Deprecate `DataType.is_nested`

### PR DESCRIPTION
**Pull request by stinodego**
I _really_ like the idea of extending our `DataType` class with methods like `is_nested()` and `is_integer()` (and other groups). But these should not be properties - they should be (class)methods just like we have `Series.is_integer()` and `DataFrame.is_empty()` etc.

Unfortunately, `is_nested` is some sort of custom property, which means we have to break it before we can implement `DataType.is_nested()` as a classmethod.

#### Changes
* Add the `NESTED_DTYPES` group
* Deprecate `DataType.is_nested`, suggest using `dtype in pl.NESTED_DTYPES` instead (until we implement `DataType.is_nested()` as a breaking change).

@alexander-beedie Any thoughts?

### CODE REVIEW

**Comment by alexander-beedie** [comment]
The changes make sense to me, though I'm not quite as convinced about having a method per-dtype; could also have a series of more generic methods so we don't have to update the class every time we add anew dtype (which isn't going to be often, but still... Thinking out loud, something along these lines might also work?

General match, eg: "Datetime == Datetime("us")
Exact match, eg: "Datetime("us") == Datetime("us"):
* `dtype.is_( ..., exact=True/False )`
* `dtype.is_not( ..., exact=True/False )`

Matches one of the given types:
* `dtype.in_( ..., exact=True/False )`
* `dtype.not_in( ..., exact=True/False )`

---

This also reminds me that I still need to get around to adding support for wildcard selection of nested/compound types in `col` (for selectors) 😅

**Review by alexander-beedie — APPROVED** [review]

**Comment by stinodego** [comment]
I was planning on opening an issue explaining my intentions here, will do so shortly! Then we can take some time to discuss before I dive in 😄 

Whichever way we go, though, I think we need to get rid of the custom `is_struct` property ASAP as I believe it should have been a classmethod in the first place and it cannot neatly be replaced without being a breaking change.

**Comment by alexander-beedie** [comment]
> Whichever way we go, though, I think we need to get rid of the custom `is_struct` property ASAP as I believe it should have been a classmethod in the first place and it cannot neatly be replaced without being a breaking change.

Agreed! :)

**Review by Jaxs88 — COMMENTED** [review]
> #11914

**Pull request merged**
