### PR TITLE
refactor(python): rename `read_sql` to `read_database`

### PR DESCRIPTION
**Pull request by ritchie46**
I really don't like the name `read_sql`. All our `read_` specify the format or source they read from, not with which query. It also is a bit confusing as we have a `SQLContext` as well and we will expand upon this functionality in the future.

I want to rename this to `read_db` before we add a `write_db`. As I think `write_sql` makes even less sense, as we don't even provide a `SQL` query upon writing.

This also keeps naming available for a cool feature we might have int he future. I can image we have a `LazyFrame.to_sql` which can produce a `SQL` query from a query plan.

### CODE REVIEW

**Comment by alexander-beedie** [comment]
`read_database`?

**Comment by ritchie46** [comment]
> How about read_database? 

Yeap, also good. Even more readable, and <tab> will do the rest. I shall update.

**Comment by stinodego** [comment]
I like this rename! Can we rename the file from `sql` to `database` too?

I'm also not a fan of `scan_ds` for pyarrow datasets.. `scan_dataset`, or even `scan_pyarrow_dataset` would be better.

**Comment by alexander-beedie** [comment]
Is `dataset` pyarrow-specific? If so, and nobody else has it we could still call it `arrow_dataset` as it would be unique, and if any other arrow implementations show up we could slide them in. Just thinking that `pyarrow` may be overly-prescriptive.

**Comment by ritchie46** [comment]
It is pyarrow specific and has nothing to do with `arrow` as a memory format. So the name `arrow dataset` would be a real misnomer IMO.

**Pull request merged**
