### PR TITLE
fix(rust, python): projection_node always do projection locally if no…

### LINKED ISSUE #5086: `projection_pushdown` regression/error from >= 0.14.15 (changes types, causes SchemaMismatch Error)
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Projection pushdown can unexpectedly change types/values.
The below example succeeds in `0.14.14`, but raises an exception in all versions since.

### Reproducible example

**Setup:**
```python
import polars as pl
a, b, c = map( pl.col, 'abc' )

x = pl.DataFrame(
    data = [
        ('a', 1, 0),
        ('a', 0, 1),
        ('a', 1, 2),
        ('b', 0, 0),
    ],
    columns = ['a','b','c'],
).lazy()

y = x.select( [a, b.take(c).cumsum().over(a) > 0] )
z = y.select( [a, (b ^ b.shift(1).over(a)).fill_null(True).alias('keep')] )
```
**Error:** _(with/without `projection_pushdown`)_
```python
print( z.collect(projection_pushdown=False) )
# ┌─────┬───────┐
# │ a   ┆ keep  │
# │ --- ┆ ---   │
# │ str ┆ bool  │
# ╞═════╪═══════╡
# │ a   ┆ true  │
# │ a   ┆ false │
# │ a   ┆ false │
# │ b   ┆ true  │
# └─────┴───────┘

print( z.collect(projection_pushdown=True) )
# ┌─────┬──────┐
# │ a   ┆ keep │
# │ --- ┆ ---  │
# │ str ┆ i64  │
# ╞═════╪══════╡
# │ a   ┆ 1    │
# │ a   ┆ 1    │
# │ a   ┆ 1    │
# │ b   ┆ 1    │
# └─────┴──────┘

z.filter( pl.col('keep') ).collect()
# ComputeError: Filter predicate must be of type Boolean,
#  got: SchemaMisMatch(Owned("Series of dtype: Int64 != Boolean"))
```

### Expected behavior

Projection pushdown shouldn't result in incorrect types/values.
Expected result:
```python
# ┌─────┬──────┐
# │ a   ┆ keep │
# │ --- ┆ ---  │
# │ str ┆ bool │
# ╞═════╪══════╡
# │ a   ┆ true │
# │ b   ┆ true │
# └─────┴──────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.17
Index type: UInt32
Platform: macOS-12.6-arm64-arm-64bit
Python: 3.9.7 (default, Aug 12 2022, 09:02:06) 
[Clang 13.1.6 (clang-1316.0.21.2.5)]

---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.3
fsspec: 2022.7.1
connectorx: 0.3.0
xlsx2csv: <not installed>
matplotlib: 3.5.3

```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
…t pruned

fixes #5086

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Barely had time to get home and eat dinner and there's already a patch! 🚀 
Fantastic... :)

**Comment by ritchie46** [comment]
> Barely had time to get home and eat dinner and there's already a patch! 🚀 Fantastic... :)

Yes.. I made the projection optimization better, but there are few edge cases coming in here and there.

**Comment by alexander-beedie** [comment]
Heh. It's always the optimisations that get you - even basic column pruning has surprising edge-cases (especially in conjunction with joins). And I have to contend with multiple backends, with different rules for each... :)

I'm going to have a block of time coming up later in the month (significant other will be away for 2-3 weeks); should be able to make some progress on that parametric testing concept with chains of optimised/non-optimised operations 👍

**Comment by ritchie46** [comment]
Ah.. 2 weeks if man-cave can lead to great things. That will be the guard rails of future optimizations! :)

**Pull request merged**
