### PR TITLE
feat: support cast decimal to utf8

### PR DESCRIPTION
**Pull request by flisky**
I pushed down `format_decimal` from polars-core into polars-arrow.

### CODE REVIEW

**Comment by ritchie46** [comment]
Your timing is a bit unlucky. We just swapped the internal string type in polars.

**Comment by ritchie46** [comment]
@flisky can you rewrite to the new `Utf8View`?

**Comment by flisky** [comment]
Okay, I'll try tomorrow.

**Review by ritchie46 — APPROVED** [review]
Thanks!

**Pull request merged**
