### PR TITLE
perf(python): add a "no_duplicate_keys" option to `align_frames`

### PR DESCRIPTION
**Pull request by alexander-beedie**
Ref: #8896.

This PR adds a "no_duplicate_keys" parameter to `align_frames` that can restore (or even exceed) the previous performance in the case where the caller _knows_ that there are no duplicate keys (otherwise a slightly more expensive join strategy is used).

The new parameter defaults to `False` as the results will be wrong if it is set incorrectly. In conjunction with the just-added "how" parameter, the previous function performance can now be exceeded if/when joining against suitable frames.

## Example
```python
pl.align_frames(
    *frames,
    on = ["key"],
    how = "left",
    no_duplicate_keys = True,
)
```

### CODE REVIEW

**Comment by alexander-beedie** [comment]
FYI: @erinov1, @kpberry - if your data is suitable for this flag (and `how="left"`) you should see speedups above & beyond the original implementation now...

**Comment by ritchie46** [comment]
Couldn't we check that quite cheaply up front?

**Comment by ritchie46** [comment]
I am not that sure about this one. As in, this information is valuable for many operations, and I don't think align frames is special and deserves an extra parameter for this.

**Comment by alexander-beedie** [comment]
I can see that; was also a bit on the fence, hence leaving it for consideration 🤔 I can probably make the case that `align_frames` is a bit different from the usual methods, as it may apply to tens/hundreds of _individual_ frames, rather than being a single-frame op, but that's not a strongly-held conviction, heh...

**Comment by ritchie46** [comment]
Hmm... let's flag it experimental (similar to the unstable features in rust that will never stabilize). I don't think I am certain enough about this path to promise it as a stable API.

**Comment by alexander-beedie** [comment]
After a bit more thought I'm leaning away from including this flag, experimental or otherwise; keeping the version that will _always_ be correct (even if slower) seems like a better idea in the long run - otherwise it's a bit of an _"opt-in and it'll work until it doesn't"_ scenario, where it may be hard even to know that your aligned frames are subtly wrong... 

The `how="left"` option will likely have _some_ overlap with the `no_duplicate_keys` case, and that is even faster at alignment than the original method... I'll sit on it for a bit, see if I can speed-up the "correct" case any further, and probably close this out 🤔

**Comment by ritchie46** [comment]
That sounds better to me as well.

**Pull request closed without merging**
