### PR TITLE
feat(rust!,python): Add `Series.cat.uses_lexical_ordering`

### LINKED ISSUE #5671: Implement `Series.cat.categories` and `Series.cat.ordered`
### Problem description

Required for #5662 

We should be able to get the categories of a Categorical Series, and get whether the ordering is lexical or physical.

If I understand correctly, a Series of type `Categorical` is really a Series of type `UInt32` with a mapping of a `UInt32` value to a string. We should be able to access this mapping.

I propose we access this through a `@property` in the `Series.cat` namespace, with the result being a `Series` of type `Utf8` (could also be a `list[str]`, but that's probably not as efficient), where the index is the `UInt32` (physical) value.

```python
s = pl.Series(['a', 'c', 'b', 'b'], dtype=pl.Categorical)
s.cat.categories  # new property
# shape: (3,)
# Series: '' [str]
# [
#        "a"
#        "c"
#        "b"
# ]
```

By default, the ordering is physical:

```python
s.sort()
# shape: (4,)
# Series: '' [cat]
# [
#         "a"
#         "c"
#         "b"
#         "b"
# ]
```

We can set the ordering to lexical, but there is no way to find if the Series is currently ordered lexically or physically. I propose we add a `@property` to the `Series.cat` namespace that indicates whether or not the Series is ordered lexically.

```python
s.cat.ordered  # new property, returns False
s = s.cat.set_ordering('lexical')
s.cat.ordered  # returns True

s.sort()
# shape: (4,)
# Series: '' [cat]
# [
#         "a"
#         "b"
#         "b"
#         "c"
# ]

I am not sure what happens here under the hood, but I imagine calling `set_ordering` affects the mapping of the `UInt32` value to string. In that case, it should affect the `Series.cat.categories` property:

```python
s.cat.categories
# shape: (3,)
# Series: '' [str]
# [
#        "a"
#        "b"
#        "c"
# ]
```

So, in short, the `CatNameSpace` class should get two new properties with the following signatures:

```python
class CatNameSpace

    @property
    def ordered(self) -> bool:
        """Returns whether the Categorical is ordered lexically."""
        ...

    @property
    def categories(self) -> pl.Series:
        """Returns the categories of the Categorical as a Series."""
        ...
```

### PR DESCRIPTION
**Pull request by stinodego**
Closes #5671, supersedes #5705, blocker for #10267

I didn't want to rebase the existing PR, so here's a fresh PR.

**WARNING: This functionality is considered experimental for now.**

Changes:
* On the Rust side:
  * Rename `set_lexical_sorted` to `set_lexical_ordering`.
  * Rename bit setting `LEXICAL_SORT` to `LEXICAL_ORDERING`.
  * Rename `use_lexical_sort` to `uses_lexical_ordering` and make it public outside the crate
* On the Python side:
  * Expose the `uses_lexical_ordering` method for categorical Series.

~I am really looking for a better name for this method, but I'm struggling to come up with something good. Help is appreciated!~
~I initially thought `is_ordered` would be appropriate. That would be the reverse of this - an ordered categorical sorts by physical type rather than lexical.~ -> Chose a sensible name for now and marked as experimental.

### CODE REVIEW

**Review by ritchie46 — APPROVED** [review]

**Comment by orlp** [comment]
Why not just `get_ordering` returning `"lexical"` or `"physical"` just like the input of `set_ordering`?

**Comment by stinodego** [comment]
> Why not just `get_ordering` returning `"lexical"` or `"physical"` just like the input of `set_ordering`?

That makes sense with the current API, though I don't like having to check the result versus a string, when I know there are only two options. It's both inefficient and easy to mess up.

**Comment by stinodego** [comment]
@ritchie46 I chose a slightly different name / renamed related functionality on the Rust side. Are you OK with this?

**Comment by ritchie46** [comment]
> @ritchie46 I chose a slightly different name / renamed related functionality on the Rust side. Are you OK with this?

Yeap.

**Pull request merged**
