### PR TITLE
feat(rust, python): add dt.month_start and dt.month_end

### PR DESCRIPTION
**Pull request by MarcoGorelli**
possible solution to https://github.com/pola-rs/polars/issues/8217 ?

todo: use this to simplify the date_range docstring [edit: done!]

---

I'll do a little refactor now, this probably warrants `polars/polars-time/src/month_start_and_end.rs` [edit: done!]

---

taking https://github.com/pola-rs/polars/pull/8261 forward, have taken care to keep @mcrumiller included as commit autour

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
tests and all pass, but then the `features` check fails with
```
 123 |         let ca = PolarsTruncate::truncate(self, Duration::parse("1mo"), no_offset, NO_TIMEZONE)?;
    |                  ------------------------ ^^^^ the trait `PolarsTruncate` is not implemented for `Logical<DateType, Int32Type>`
    |                  |
    |                  required by a bound introduced by this call

error[E0277]: the trait bound `Logical<DateType, Int32Type>: PolarsTruncate` is not satisfied
   --> polars/polars-time/src/month_start.rs:113:34
    |
113 |         PolarsTruncate::truncate(self, Duration::parse("1mo"), no_offset, NO_TIMEZONE)
    |         ------------------------ ^^^^ the trait `PolarsTruncate` is not implemented for `Logical<DateType, Int32Type>`
```
and I can't figure out what to do about that

**Comment by mcrumiller** [comment]
Hi @MarcoGorelli, thank you so much for taking over with this. I've had a hectic few days and I don't think I could have gotten this done at all.

**Comment by ritchie46** [comment]
Thanks @MarcoGorelli. Could we add this to our string duration language as well?

```python
from datetime import date

(
    pl.DataFrame({"date": pl.date_range(date(2022, 1, 1), date(2023, 1, 1), "1d")})
    .sort("date")
    .groupby_rolling("date", period="1mo")
    .agg(pl.count())
)
```

This will now panic, and there is no clear way to get what the user intended.

**Comment by MarcoGorelli** [comment]
> For this PR, could you add docs entries in python?

knew I was forgetting something :) done

---

Yup, I'll make a separate PR for the snippet you mentioned, it seems that there really needs to be an option for this

**Pull request merged**
