### PR TITLE
perf(rust, python): Rolling min/max for partially sorted data

### PR DESCRIPTION
**Pull request by magarick**
Improves performance for data with long runs of sorted values. The effect on random data is small. In some cases it performs better in others slightly worse. But it's a net win, performance will be more consistent, and we no longer need the special sorted case checker. I'll post some benchmarks soon to triple-check.

### CODE REVIEW

**Comment by ritchie46** [comment]
> I'll post some benchmarks soon to triple-check.

Looking forward on these. :)

**Comment by magarick** [comment]
So, it's a _usually_ a little slower on "regular" data. Up to 20% and twice as long if the data is completely sorted. However, these are very fast cases to begin with and can be more than 10x as fast when there are long sorted runs in an unsorted slice. That latter case could be an order of magnitude or two slower without the optimization, so I think this is worth it. Even with the "performance regression" it shouldn't be any slower than before I made the last set of changes.

That being said, I've tried to narrow the gap as much as possible but I haven't been able to find a consistent way to claw back all of the performance. If this is OK, I'll just clean up the code, post the numbers I'm getting and call it a day.

**Comment by magarick** [comment]
I also clearly don't understand what the compiler was doing, because I went from an almost universal performance improvement in debug builds to losing some performance on most random sequences in optimized builds. So I have the feeling we can't avoid paying a cost on some of the faster cases if we want to mitigate the slow cases.

**Comment by magarick** [comment]
Lesson learned. I'll maybe take one or two more cracks at it, but what do you think? Small performance hit on fast cases for a bit speedup on rarer but much slower cases?

**Comment by ritchie46** [comment]
It depends a bit on how rare it is and what the numbers are, how the code looks etc. But it might be worthwile. Normally I want the default case to be fast, but we don't want to drop of a cliff in edge cases (that do occur regularly).

**Comment by magarick** [comment]
Alright, I think this is good to go.
The performance is more or less on par for typical cases. At the worst it's around the performance prior to the last round of optimizations. But it's a dramatic improvement when you have long sorted subsequences. It also seems to help in some cases for dynamic rolling windows.

Results include a comparison to the current version and 0.18.1, which is right before the previous changes were merged.

Here's the data I generated for comparisons
```python
N = 50
nrep = 50
np.random.seed(100)
ds = pl.date_range(datetime(2013, 1, 1), datetime(2022, 12, 31), '1h', eager = True)
v = pl.Series(np.random.standard_normal(N * len(ds)))
x = pl.Series(np.random.randint(0, 50, len(ds)).repeat(N))
s = pl.Series(range(len(ds) * N))
r = s.reverse()
p = pl.Series((list(range(125)) + list(range(125, 0, -1))) * (701 * N//2))
p2 = pl.Series((list(range(17525)) + list(range(17525, 0, -1))) * (5 * N//2))

dat = pl.DataFrame(dict(d = ds.to_numpy().repeat(N), v = v, x = x, s = s, r = r, p = p, p2 = p2))
dat = dat.set_sorted('d')
```

For fixed windows, I used lengths 5, 250, and 7500
For dynamic windows I used (every, period) pairs of (1h, 2h), (1d, 5d) and (1h, 5d)

Results are long so they're in the attached CSV.

[rolling_minmax_perf.csv](https://github.com/pola-rs/polars/files/12060627/rolling_minmax_perf.csv)

**Comment by ritchie46** [comment]
Care to render the results in a markdown table? We really want to have them rendered for future reference as well. Think of this as part of our documentation. :)

**Comment by magarick** [comment]
Sure. I was concerned about clogging up the comments with loads of text.
All times are in seconds for the run.
Fixed windows

|Window/size/op |v0.18.1|v0.18.7|New   |
|---------------|-------|-------|------|
|(x, 5, min)    |1.773  |1.588  |1.734 |
|(x, 5, max)    |1.782  |1.539  |1.669 |
|(x, 250, min)  |2.053  |1.712  |2.114 |
|(x, 250, max)  |2.087  |1.723  |2.343 |
|(x, 7500, min) |2.073  |1.658  |1.622 |
|(x, 7500, max) |2.113  |1.582  |1.557 |
|(v, 5, min)    |3.332  |2.667  |3.157 |
|(v, 5, max)    |3.264  |2.855  |3.515 |
|(v, 250, min)  |2.889  |2.166  |2.016 |
|(v, 250, max)  |2.736  |2.236  |2.59  |
|(v, 7500, min) |2.794  |2.116  |1.982 |
|(v, 7500, max) |2.667  |2.175  |2.54  |
|(s, 5, min)    |1.181  |1.164  |1.927 |
|(s, 5, max)    |1.722  |1.516  |1.784 |
|(s, 250, min)  |1.206  |1.169  |1.93  |
|(s, 250, max)  |1.711  |1.503  |1.78  |
|(s, 7500, min) |1.172  |1.158  |1.934 |
|(s, 7500, max) |1.715  |1.509  |1.776 |
|(r, 5, min)    |1.714  |1.557  |1.763 |
|(r, 5, max)    |1.201  |1.201  |2.005 |
|(r, 250, min)  |1.761  |1.595  |1.76  |
|(r, 250, max)  |1.205  |1.2    |1.999 |
|(r, 7500, min) |1.739  |1.599  |1.767 |
|(r, 7500, max) |1.208  |1.192  |2     |
|(p, 5, min)    |1.977  |1.996  |1.829 |
|(p, 5, max)    |2.071  |2.06   |1.899 |
|(p, 250, min)  |1.847  |1.655  |1.686 |
|(p, 250, max)  |1.727  |1.582  |1.585 |
|(p, 7500, min) |1.845  |1.651  |1.684 |
|(p, 7500, max) |1.71   |1.57   |1.589 |
|(p2, 5, min)   |1.975  |2.013  |1.835 |
|(p2, 5, max)   |2.091  |2.056  |1.883 |
|(p2, 250, min) |17.807 |15.784 |1.864 |
|(p2, 250, max) |26.473 |26.522 |1.93  |
|(p2, 7500, min)|362.89 |305.307|21.895|
|(p2, 7500, max)|592.526|587.585|40.97 |

Dynamic Windows

|Window/size/op |v0.18.1|v0.18.7|New   |
|---------------|-------|-------|------|
|(x, min, every = 1h, period = 2h)|1.149  |1.186  |1.049 |
|(x, max, every = 1h, period = 2h)|1.147  |1.142  |1.038 |
|(v, min, every = 1h, period = 2h)|1.961  |2.179  |1.791 |
|(v, max, every = 1h, period = 2h)|2.034  |2.446  |1.853 |
|(s, min, every = 1h, period = 2h)|0.933  |0.995  |0.885 |
|(s, max, every = 1h, period = 2h)|0.955  |0.998  |0.894 |
|(r, min, every = 1h, period = 2h)|0.947  |1.01   |0.891 |
|(r, max, every = 1h, period = 2h)|0.925  |0.941  |0.883 |
|(p, min, every = 1h, period = 2h)|1.164  |1.206  |1.15  |
|(p, max, every = 1h, period = 2h)|1.17   |1.102  |1.125 |
|(p2, min, every = 1h, period = 2h)|1.153  |1.187  |1.038 |
|(p2, max, every = 1h, period = 2h)|1.151  |1.115  |1.012 |
|(x, min, every = 1d, period = 5d)|1.496  |1.539  |1.318 |
|(x, max, every = 1d, period = 5d)|1.5    |1.372  |1.185 |
|(v, min, every = 1d, period = 5d)|2.274  |1.888  |1.899 |
|(v, max, every = 1d, period = 5d)|2.317  |2.024  |1.901 |
|(s, min, every = 1d, period = 5d)|1.165  |1.17   |0.971 |
|(s, max, every = 1d, period = 5d)|1.163  |1.168  |0.969 |
|(r, min, every = 1d, period = 5d)|1.159  |1.17   |0.969 |
|(r, max, every = 1d, period = 5d)|1.163  |1.166  |0.972 |
|(p, min, every = 1d, period = 5d)|1.417  |1.494  |1.3   |
|(p, max, every = 1d, period = 5d)|1.416  |1.351  |1.206 |
|(p2, min, every = 1d, period = 5d)|1.738  |1.837  |1.234 |
|(p2, max, every = 1d, period = 5d)|1.728  |1.56   |1.167 |
|(x, min, every = 1h, period = 5d)|18.635 |18.559 |12.647|
|(x, max, every = 1h, period = 5d)|18.619 |18.428 |12.586|
|(v, min, every = 1h, period = 5d)|19.724 |19.29  |13.507|
|(v, max, every = 1h, period = 5d)|19.68  |19.339 |13.644|
|(s, min, every = 1h, period = 5d)|18.254 |18.259 |12.453|
|(s, max, every = 1h, period = 5d)|18.258 |18.264 |12.446|
|(r, min, every = 1h, period = 5d)|18.255 |18.268 |12.448|
|(r, max, every = 1h, period = 5d)|18.243 |18.266 |12.454|
|(p, min, every = 1h, period = 5d)|19.917 |18.445 |12.669|
|(p, max, every = 1h, period = 5d)|18.455 |18.375 |12.673|
|(p2, min, every = 1h, period = 5d)|28.171 |28.134 |12.858|
|(p2, max, every = 1h, period = 5d)|28.334 |23.827 |12.851|

**Comment by ritchie46** [comment]
Thanks, if now someone drops it into their favorite plotting library, we can make comparisons!

**Comment by magarick** [comment]
If you give a mouse a cookie, eh?
image

image

Note also the very large numbers at the bottom of both tables.

**Comment by ritchie46** [comment]
> Note also the very large numbers at the bottom of both tables.

What do you mean?

I need some help understanding what I am looking at. I understand time and version window size and the operations :sweat_smile: 

What are the letters?

**Comment by magarick** [comment]
Oh, the letters refer to the column names as posted above in code. For reference this is how the data was generated
```python
ds = pl.date_range(datetime(2013, 1, 1), datetime(2022, 12, 31), '1h', eager = True)
v = pl.Series(np.random.standard_normal(N * len(ds)))
x = pl.Series(np.random.randint(0, 50, len(ds)).repeat(N))
s = pl.Series(range(len(ds) * N))
r = s.reverse()
p = pl.Series((list(range(125)) + list(range(125, 0, -1))) * (701 * N//2))
p2 = pl.Series((list(range(17525)) + list(range(17525, 0, -1))) * (5 * N//2))

dat = pl.DataFrame(dict(d = ds.to_numpy().repeat(N), v = v, x = x, s = s, r = r, p = p, p2 = p2))
dat = dat.set_sorted('d')```

What I mean is at the bottom of both the fixed and dynamic tables are some operations that took much longer than the others and the new version delivers a large improvement (and yes, I made sure the results are identical).

**Comment by ritchie46** [comment]
Right, I understand. And that are some solid performance in the bottom graphs indeed. :rocket: Overall it seems like a downwards diagonal trend, so well done!

**Pull request merged**
