### PR TITLE
python polars 0.15.17

### PR DESCRIPTION
**Pull request by ritchie46**
The last planned `0.15.x` release. @stinodego @alexander-beedie FYI. I will start merging the breaking PR's shortly.

### CODE REVIEW

**Comment by stinodego** [comment]
Time to do some rebasing then 😅

**Comment by ritchie46** [comment]
> Time to do some rebasing then 😅
> 
> EDIT: DONE!

On fire! Will start merging tomorrow. First to bed. I am gradually training to join the 5AM club 🥲

**Comment by alexander-beedie** [comment]
> EDIT: DONE!

🏆 :)

**Comment by stinodego** [comment]
Darn, this release broke my tests 😕 working out a minimal example.

**Comment by alexander-beedie** [comment]
@ritchie46: quick q - for `iterrows` -> `iter_rows`, shall we briefly have two methods, with one pointing to the other alongside a DeprecationWarning/FutureWarning, or just do a hard cutoff? (Or - cleaner but faintly more exotic- transparently intercept the old call in `__getattr__` and redirect to the new, alongside the aforementioned warning). The latter is probably the nicest, and we could leave it in place for a bit before retiring, without cluttering the visible API 🤔

**Comment by ritchie46** [comment]
Maybe deprecate it for a while and remove it in 0.17?

**Comment by alexander-beedie** [comment]
> Maybe deprecate it for a while and remove it in 0.17?

I'll write a `@deprecate_method` class decorator in the same vein as `@deprecate_alias` so we can do this smoothly in the general case - I'm sure it won't be the last time we want to deprecate a method ;)

**Comment by stinodego** [comment]
> I'll write a `@deprecate_method` class decorator 

That would be great!

**Comment by alexander-beedie** [comment]
> That would be great!

Done (#6461); created `@redirect`, which we can now use for any methods/attributes that change name.

**Pull request merged**
