### PR TITLE
Add support for building dataframe from rows when they contain None f…

### PR DESCRIPTION
**Pull request by ghuls**
…or Float32/Float64 values.

### CODE REVIEW

**Comment by ghuls** [comment]
@ritchie46 time related dtypes might need fixing too:
```
             #[cfg(feature = "dtype-date")]
             (Date(builder), AnyValue::Null) => builder.append_null(),
             #[cfg(feature = "dtype-datetime")]
             (Datetime(builder, _, _), AnyValue::Datetime(v, _, _)) => builder.append_value(v),
             #[cfg(feature = "dtype-time")]
             (Time(builder), AnyValue::Time(v)) => builder.append_value(v),
```

**Comment by ritchie46** [comment]
Nice.. thank you.

**Comment by ghuls** [comment]
@ritchie46 do the time related dtypes require a `AnyValue::Null` too, or is that not supported?

**Comment by ritchie46** [comment]
> @ritchie46 do the time related dtypes require a `AnyValue::Null` too, or is that not supported?

I have to look.

**Pull request merged**
