### PR TITLE
perf(rust, python): improve batched csv readers perf and memory perf

### PR DESCRIPTION
**Pull request by ritchie46**
Don't trash virtual memory by first determining offsets. Do this while we read the file in batches.

related to #7324

### CODE REVIEW

**Comment by alexander-beedie** [comment]
`0.16.10` is shaping up to be quite a release ;)

**Comment by ritchie46** [comment]
> `0.16.10` is shaping up to be quite a release ;)

It is right! And that for only 5 days. :see_no_evil:

**Comment by alexander-beedie** [comment]
> It is right! And that for only 5 days. 🙈

_"To infinity... and beyond!"_ 🤣 

(I've just got sparklines working in the Excel export too - finishing some test coverage and an example now :)

**Comment by ritchie46** [comment]
> (I've just got sparklines cleanly integrated into the Excel export too - finishing some test coverage and an example now).

I had to google that. :innocent:

**Pull request merged**
