### PR TITLE
feat(rust, python): enable min-max skipping for binary in parquet, enable min-max skipping for `is_in` exprs

### PR DESCRIPTION
**Pull request by ozgrakkurt**
This PR enables row group skipping using min-max statistics in parquet files for binary data type.

DISCLAIMER: I didn't test this yet

### CODE REVIEW

**Comment by ritchie46** [comment]
We already do this?

**Comment by ozgrakkurt** [comment]
it looked like it was only done on string and numeric data from the code

**Comment by ozgrakkurt** [comment]
@ritchie46 this seems ok to merge but doesn't make any perf diff for me because of https://github.com/pola-rs/polars/issues/7206

**Comment by ozgrakkurt** [comment]
now it gives a very nice over 50% performance boost

**Comment by ozgrakkurt** [comment]
closes https://github.com/pola-rs/polars/issues/7206

**Comment by ozgrakkurt** [comment]
@ritchie46 all done

**Comment by ozgrakkurt** [comment]
> Great! Thanks @ozgrakkurt. This is a nice feature. 👍

thank you as well!

**Pull request merged**
