### PR TITLE
Fix db-benchmark failure as queries sometimes take slightly more than…

### PR DESCRIPTION
**Pull request by ghuls**
… 10 seconds.

### CODE REVIEW

**Comment by ritchie46** [comment]
Maybe we should be ambitious and lower it😜

**Comment by ghuls** [comment]
Are the benchmarks run on release mode?

Like this kind of "failures" I have seen a few times:
https://github.com/pola-rs/polars/runs/4163608167?check_suite_focus=true

**Comment by ritchie46** [comment]
> Are the benchmarks run on release mode?
> 
> Like this kind of "failures" I have seen a few times: https://github.com/pola-rs/polars/runs/4163608167?check_suite_focus=true

Yes, the differences are due to shared vms I think.

**Comment by ritchie46** [comment]
I use this mostly as a safeguard against accidental regression. Some false positives are ok.

**Pull request merged**
