### PR TITLE
feat(python): automatically convert series CMP expr -> pl.lit(series) CMP expr where CMP is comparison operator

### LINKED ISSUE #8534: Logical comparison of pl.Series() to pl.Expr fails
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

This is essentially the same issue as #6971. While arithemetic operations now work, logical comparisons fail.

### Reproducible example

```python
import polars as pl

pl.Series([1]) < pl.col('a')
```
```
ValueError: Cannot convert Python type <class 'polars.expr.expr.Expr'> to Int64
```

### Expected behavior

Should return an expression identical to:

```python
pl.lit(pl.Series([1])) < pl.col('a')
```

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Fixes #8534

### CODE REVIEW

**Comment by mcrumiller** [comment]
Hey @ritchie46 I'm not sure how to properly resolve the error I'm getting:

```
polars/series/series.py:500: error: Signature of "__eq__" incompatible with supertype "object"  [override]
polars/series/series.py:500: note:      Superclass:
polars/series/series.py:500: note:          def __eq__(self, object, /) -> bool
polars/series/series.py:500: note:      Subclass:
polars/series/series.py:500: note:          @overload
polars/series/series.py:500: note:          def __eq__(self, Expr, /) -> Expr
polars/series/series.py:500: note:          @overload
polars/series/series.py:500: note:          def __eq__(self, Any, /) -> Series
```

All of the other logical comparison operators use the same signatures, what makes `eq`/`ne` special? This must be something about typing that I don't know, as the unit tests pass fine.

---

Also, `make pre-commit` is giving me indentation errors `tests/unit/test_fmt.py:169:1: W191 Indentation contains tabs`, despite having never touched that file, and I don't want to mess with files unrealted to this commit; any way to ignore those?
```

**Comment by stinodego** [comment]
> Also, make pre-commit is giving me indentation errors tests/unit/test_fmt.py:169:1: W191 Indentation contains tabs, despite having never touched that file, and I don't want to mess with files unrelated to this commit; any way to ignore those?

Run `make requirements` to update your `ruff` version, that will take care of that.

**Comment by mcrumiller** [comment]
@ritchie46 I think this one is good to go if you'd like to review. @alonme made a similar request for the same issue over at #8569.

**Comment by alexander-beedie** [comment]
Ok, this looks good to me - would be nice to resolve the need to `# type: ignore[misc]`, but that's a distinctly secondary issue.

**Comment by mcrumiller** [comment]
Thanks  @alexander-beedie for reviewing my first PR!

**Pull request merged**
