### PR TITLE
Python: parallel concat df

### PR DESCRIPTION
**Pull request by gunjunlee**
Paralle concat df

### CODE REVIEW

**Comment by ritchie46** [comment]
I don't think we should do this. The `vstack`s only push to a vector. There is not much work to do so parallellization is not much help here and bloats compile time.

**Comment by gunjunlee** [comment]
In my benchmark this parallelization improves speed a lot

```
------------------------------------------------------------------------------------ benchmark: 2 tests ------------------------------------------------------------------------------------
Name (time in ms)             Min                 Max                Mean            StdDev              Median               IQR            Outliers      OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_concat_parallel      36.1961 (1.0)       49.6611 (1.0)       41.3415 (1.0)      3.9324 (1.0)       41.0653 (1.0)      4.8364 (1.0)           6;0  24.1887 (1.0)          17           1
test_concat_series       225.2016 (6.22)     236.1800 (4.76)     230.0854 (5.57)     5.2751 (1.34)     228.0421 (5.55)     9.9220 (2.05)          1;0   4.3462 (0.18)          5           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

test code:
```
import polars as pl
import time

def test_concat_parallel(benchmark):
    num = 100
    dfs = [pl.DataFrame({str(i): [i] * num for i in range(100)}) for _ in range(1000)]
    df = benchmark(pl.polars.concat_df_parallel, dfs)
    assert df.height() == 1000 * num

def test_concat_series(benchmark):
    num = 100
    dfs = [pl.DataFrame({str(i): [i] * num for i in range(100)}) for _ in range(1000)]
    df = benchmark(pl.polars.concat_df_series, dfs)
    assert df.height() == 1000 * num
```

**Comment by mutecamel** [comment]
I usually need to concat thousands of frames. I would appreciate the performance boost.

**Comment by ritchie46** [comment]
Al right! Thanks @gunjunlee

**Pull request merged**
