### PR TITLE
Fix: fixes list repr to return inner type

### LINKED ISSUE #6084: string_repr returns always `list[bool]`.
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

string_repr returns always `list[bool]` for any kind of pl.List.

### Reproducible example

```python
import polars as pl


In [30]: pl.List(pl.Utf8).string_repr()
Out[30]: 'list[bool]'

In [31]: pl.List(pl.Int32).string_repr()
Out[31]: 'list[bool]'
```

### Expected behavior

Return dtype string representation as shown when printing a dataframe:

```python
In [30]: pl.List(pl.Utf8).string_repr()
Out[30]: 'list[str]'

In [31]: pl.List(pl.Int32).string_repr()
Out[31]: 'list[i32]'
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.13
Index type: UInt32
Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.10
Python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.0
numpy: 1.23.5
fsspec: 2022.10.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by Mehrbod2002**
Fixes #6084.

List on `string_repr` doesn't contain `inner_dtype` , it's added and because of it's only List will contain Datatype value ( reference to `Datatype` enum ) , it will `format!` to evaluate inner Datatype.

### CODE REVIEW

**Comment by Mehrbod2002** [comment]
is there anything with other files and tests files ? 
Because it's all failed by others changes .
Appreciate Collaborators to solve it or aware me about it .

**Comment by alexander-beedie** [comment]
It looks like you didnn't run `make pre-commit` before pushing? Most of those errors are lint which will be autofixed for you.

**Comment by ghuls** [comment]
Also tests live in the test subdir.

e.g.:
```diff
diff --git a/py-polars/tests/unit/test_df.py b/py-polars/tests/unit/test_df.py
index bf0424ce90..a583488c03 100644
--- a/py-polars/tests/unit/test_df.py
+++ b/py-polars/tests/unit/test_df.py
@@ -2593,6 +2593,8 @@ def test_glimpse() -> None:
             "d": [None, "b", "c"],
             "e": ["usd", "eur", None],
             "f": [date(2020, 1, 1), date(2021, 1, 2), date(2022, 1, 1)],
+            "g": [[5, 6], [3, 4], [9, 8]],
+            "h": [[5.0, 6.0], [3.0, 4.0], [9.0, 8.0]],
         }
     )
     result = df.glimpse()
@@ -2600,13 +2602,15 @@ def test_glimpse() -> None:
     expected = textwrap.dedent(
         """\
         Rows: 3
-        Columns: 6
-        $ a <Float64> 1.0, 2.8, 3.0
-        $ b   <Int64> 4, 5, None
-        $ c <Boolean> True, False, True
-        $ d    <Utf8> None, b, c
-        $ e    <Utf8> usd, eur, None
-        $ f    <Date> 2020-01-01, 2021-01-02, 2022-01-01
+        Columns: 8
+        $ a        <f64> 1.0, 2.8, 3.0
+        $ b        <i64> 4, 5, None
+        $ c       <bool> True, False, True
+        $ d        <str> None, b, c
+        $ e        <str> usd, eur, None
+        $ f       <date> 2020-01-01, 2021-01-02, 2022-01-01
+        $ g  <list[i64]> [5, 6], [3, 4], [9, 8]
+        $ h  <list[f64]> [5.0, 6.0], [3.0, 4.0], [9.0, 8.0]
         """
     )
     assert result == expected
```

**Comment by Mehrbod2002** [comment]
> Also tests live in the test subdir.
> 
> e.g.:
> ```diff
> diff --git a/py-polars/tests/unit/test_df.py b/py-polars/tests/unit/test_df.py
> index bf0424ce90..a583488c03 100644
> --- a/py-polars/tests/unit/test_df.py
> +++ b/py-polars/tests/unit/test_df.py
> @@ -2593,6 +2593,8 @@ def test_glimpse() -> None:
>              "d": [None, "b", "c"],
>              "e": ["usd", "eur", None],
>              "f": [date(2020, 1, 1), date(2021, 1, 2), date(2022, 1, 1)],
> +            "g": [[5, 6], [3, 4], [9, 8]],
> +            "h": [[5.0, 6.0], [3.0, 4.0], [9.0, 8.0]],
>          }
>      )
>      result = df.glimpse()
> @@ -2600,13 +2602,15 @@ def test_glimpse() -> None:
>      expected = textwrap.dedent(
>          """\
>          Rows: 3
> -        Columns: 6
> -        $ a <Float64> 1.0, 2.8, 3.0
> -        $ b   <Int64> 4, 5, None
> -        $ c <Boolean> True, False, True
> -        $ d    <Utf8> None, b, c
> -        $ e    <Utf8> usd, eur, None
> -        $ f    <Date> 2020-01-01, 2021-01-02, 2022-01-01
> +        Columns: 8
> +        $ a        <f64> 1.0, 2.8, 3.0
> +        $ b        <i64> 4, 5, None
> +        $ c       <bool> True, False, True
> +        $ d        <str> None, b, c
> +        $ e        <str> usd, eur, None
> +        $ f       <date> 2020-01-01, 2021-01-02, 2022-01-01
> +        $ g  <list[i64]> [5, 6], [3, 4], [9, 8]
> +        $ h  <list[f64]> [5.0, 6.0], [3.0, 4.0], [9.0, 8.0]
>          """
>      )
>      assert result == expected
> ```

Do you mean I run PyTest on it , will it resolve?

**Comment by alexander-beedie** [comment]
> Do you mean I run PyTest on it , will it resolve?

No; you seem to have accidentally included a file called `py-polars/test.py`; new DataFrame tests should go in `py-polars/tests/unit/test_df.py`, as @ghuls is suggesting). Once you have some new tests in the usual place, and update the PR after running `make pre-commit`, I would expect CI to pass and we can assess the change (thanks for making a PR 👍;)

**Comment by Mehrbod2002** [comment]
@alexander-beedie 
Thanks a lot for guides .
I added some tests on that function you mentioned .
I do as documents and you said , all tests and Lint problem solve in local , can you consider to look what was happened on Tests on Ubuntu ?

**Review by ghuls — COMMENTED** [review]
Keep the test_string_repr() function (remove this commit).

**Comment by Mehrbod2002** [comment]
@ghuls 
It says conflicts with Master branch

**Comment by alexander-beedie** [comment]
I don't see conflicts, but you do still have some `mypy` errors to fix; for example:
```
tests/unit/test_lists.py:78: error: Unused "type: ignore" comment
tests/unit/test_lists.py:269: error: Unused "type: ignore" comment
```

**Comment by Mehrbod2002** [comment]
> I don't see conflicts, but you do still have some `mypy` errors to fix; for example:
> ```
> tests/unit/test_lists.py:78: error: Unused "type: ignore" comment
> tests/unit/test_lists.py:269: error: Unused "type: ignore" comment
> ```

I know , but I didn't do anything with these errors .
And what's is the issue when on Windows passed but on Ubuntu didn't ? 
As I said,  I did what exactly docs said but what is this error for?

**Comment by Mehrbod2002** [comment]
> Keep the test_string_repr() function (remove commit [34ec4b4](https://github.com/pola-rs/polars/pull/6206/commits/34ec4b4552b1baf5992920dc34dbf4bc109203dd)).

Appreciate if you describe and guide me , how my code make this error on `mypy` .
Thanks

**Comment by ghuls** [comment]
@Mehrbod2002 I have a local branch that fixes the merge issue and typing issues. Then I noticed that the patch does not fix the problem properly. It is supposed to return `list[str]` and `list[f64]`, like the dtype output you see when you print a dataframe. The rust Display trait for list always seems to get a Boolean, so I have a feeling that maybe in the constructor of the pyseries, the inner dtype is not set in the rust code.

**Comment by alexander-beedie** [comment]
It seems you do now have some conflicts; can you `rebase` this PR against the `master` branch? As for `mypy` you may simply be able to remove those "ignore" directives now.

**Comment by Mehrbod2002** [comment]
@ghuls 
If we are not going to use Display on Rust it will always return `str` . trait of Rust will do that  .
So I think it's better to use it as format and Display to not conflict with Datatype trait .

**Comment by Mehrbod2002** [comment]
> It seems you do now have some conflicts; can you `rebase` this PR against the `master` branch? As for `mypy` you may simply be able to remove those "ignore" directives.

It will help my a lot if you please edit commit , sorry I am not really familiar with this project documentation and help on further PR on this project 🙇🏻

**Comment by Mehrbod2002** [comment]
new commit pushed .

**Pull request closed without merging**
