### PR TITLE
feat(python): rework `ColumnFactory` to additionally support tab-complete for `col` in IPython

### LINKED ISSUE #11433: tab-complete doesn't work for `pl.col(...)` in IPython
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

If I do `pl.DataFrame(data).` and hit 'tab', I get a lot of valid hints:

image

But not if I do the same with `pl.col`:

image

It does however work if I assign `pl.col('a')` to a variable

image

### Log output

_No response_

### Issue description

This came up in training yesterday as being quite annoying

Arguably it may be an IPython bug, but still, is there anything that could be done within Polars to help?
I'll experiment with this a little

### Expected behavior

tab-complete to help as much as possible

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.5
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  0.7.0
cloudpickle:         2.2.1
connectorx:          0.3.2
deltalake:           0.10.1
fsspec:              2023.9.2
gevent:              23.9.1
matplotlib:          3.8.0
numpy:               1.26.0
openpyxl:            3.1.2
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            2.3.0
pyiceberg:           0.5.0
pyxlsb:              1.0.10
sqlalchemy:          2.0.21
xlsx2csv:            0.8.1
xlsxwriter:          3.1.5
```

</details>

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #11433.

Reworks the `ColumnFactory` to improve tab-complete in IPython (without regression in other IDEs).

ipython_col_complete

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Thanks a tonne for doing this! I sometimes reluctantly have to use notebooks and this will make that experience much better

I also started looking at a meta class solution but didn't manage to take it far enough, glad you figured out how to

**Comment by alexander-beedie** [comment]
Hmmm; looks like some kind of docs-build gremlin - I can also see that namespaces aren't 100% (they work with `col.xyz.str.<tab>`, but not `col("xyz").str.<tab>` yet). Still, a big improvement already! Will try and work out the rest shortly ;)

**Comment by MarcoGorelli** [comment]
> (they work with col.xyz.str.<tab>, but not col("xyz").str.<tab>). Still, an improvement! 

I just checked, and that didn't autocomplete in 0.19.1 either. So, this completely fixes the regression in the linked issue - well done!

If `col('a').str.<tab>` could auto-complete as well, that'd be fantastic, but definitely not a blocker here - I say, "ship it"!

**Comment by ritchie46** [comment]
Thanks a lot for this fix! I leave this one to you two. If it is ready to go, let's merge. :)

**Comment by alexander-beedie** [comment]
> Thanks a lot for this fix! I leave this one to you two. If it is ready to go, let's merge. :)

Yup - rock & roll :)  🎸

**Review by MarcoGorelli — APPROVED** [review]

**Comment by MarcoGorelli** [comment]
>  let's merge. :)

I don't think I can (at least, I see "Merging can be performed automatically with 1 approving review." - presumably because I'm not "code owner" of these paths?)

**Review by ritchie46 — APPROVED** [review]

**Pull request merged**
