### PR TITLE
refactor: eliminate repetition in utf8 datetime functions

### PR DESCRIPTION
**Pull request by orlp**
This should not have changed any semantics.

If we find it to be useful somewhere else we can move `CachedFunc` to `utils` or something.

### CODE REVIEW

**Comment by ritchie46** [comment]
> If we find it to be useful somewhere else we can move CachedFunc to utils or something.

I think it is. We can probably grow it into something akin to an LRU cache.

**Comment by orlp** [comment]
@ritchie46 So do you want me to move it in this PR or later in a different one?

**Comment by ritchie46** [comment]
Can you move it in this PR?

**Comment by orlp** [comment]
@ritchie46 Done.

**Pull request merged**
