### PR TITLE
fix(rust, python): evaluate whole branch expression to determine if r…

### LINKED ISSUE #5855: Wrong results pushing down formula with parquet files when statistics are used
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Bad behavior when pushing down an formula using parquet files when the file is created with statistics.

In the example bellow I use pyarrow to write the files, however, the behavior is the same if not using it.

If the predicate isn't pushed down, everything works has expected, regardless of how the file was created.

Strangely, if I change one value in the dataframe that i first use in the example bellow, it suddenly works. So it's not an "consistent" error.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    data = [
        ('a', 2),
        ('b', 2),
        ('c', 3.1),
        ('d', 4),
        ('3', 5),
    ],
    columns = ['a','b'],)

df.write_parquet('no_stats.parquet', use_pyarrow=True, statistics=False)
df.write_parquet('with_stats.parquet', use_pyarrow=True, statistics=True)

e = ((pl.col('b')/2.0)<=1.9)

x1 = pl.scan_parquet('no_stats.parquet')
y = x1.filter(e)
z = y.collect(predicate_pushdown=True)
print(z)

x2 = pl.scan_parquet('with_stats.parquet')
y = x2.filter(e)
z = y.collect(predicate_pushdown=True)
print(z)

#this does work - if we change the first dataframe row to 1.9 instead of 2:
df = pl.DataFrame(
    data = [
        ('a', 1.9), #<-------
        ('b', 2),
        ('c', 3.1),
        ('d', 4),
        ('3', 5),
    ],
    columns = ['a','b'],)

df.write_parquet('no_stats_19.parquet', use_pyarrow=True, statistics=False)
df.write_parquet('with_stats_19.parquet', use_pyarrow=True, statistics=True)

e = ((pl.col('b')/2.0)<=1.9)

x1 = pl.scan_parquet('no_stats_19.parquet')
y = x1.filter(e)
z = y.collect(predicate_pushdown=True)
print(z)

x2 = pl.scan_parquet('with_stats_19.parquet')
y = x2.filter(e)
z = y.collect(predicate_pushdown=True)
print(z)
```

### Expected behavior

.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.7
Index type: UInt32
Platform: Linux-6.0.6-76060006-generic-x86_64-with-glibc2.35
Python: 3.11.1 (main, Dec  7 2022, 01:11:34) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
None
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
…ow group can be skipped

fixes #5855

### CODE REVIEW

**Comment by gfmartins** [comment]
I tried to read the rust code, however I'm a zero at it sorry. And I hope that my following message can contribute something. 

I'm not sure that it can only be achieved by comparing the whole branch expression. After some though I think that's not possible.

let's consider a row group for col('foo') where **min is -20 and max is 20** and an expression like this `pow(col('foo'), 2) <= 300`

if the expression is evaluated by the min then` (-20)^2 == 400` and if not mistaken the group is skipped. because 400 is not less than 300. however **that row group can contain values like -10 that evaluate to 100**, and because of that those are valid values.

so the expressions should probably not be pushed down to "parquet stats level" filtering, unless it's possible to simplify them.

expressions like x*5 = 10 simplify to x = 10/5, and those can be pushed down for min max filtering
however x^2 = 10, has two solutions x = -sqrt(10) and x = sqrt(10)

are this cases accounted for?

**Comment by ritchie46** [comment]
Good thinking. 

We don't skip based on equality, only on `greater than` or `less than`. We take the minimum and the maximum value in a single column and apply the filter. If a single value remains after the filter we must read the file. I think this still works even with square roots. What you?

**Comment by gfmartins** [comment]
I think that I'm not following you, sorry.

		       Column 'foo'

		        | min = -10
row group 1	|
		        | max = 10

		        | min = -20
row group 2	|
		        | max = 15

		        | min = -2
row group 3	|
		        | max = 2

expression to consider:` foo^2<=50`

` We take the minimum and the maximum value in a single column`
column 'foo' max is 15, min is -20

	15^2 =  225    -> 225 <= 50 is False
	-20^2 = 400    -> 400 <= 50 is False

**the file would be excluded? because both min and max when applied to the formula are greater** 

row group 1:  min: (-10)^2 = 100  -> 100 <= 50 is False
	              max: ( 10)^2 = 100  -> 100 <= 50 is False

	     row group 1 is excluded 

	     Inside row group 1 there we can be values ranging from -7 to 7 that evaluate to 49 and are therefore valid, but the objective of min max filtering is not to read them.
	     (1)^2 = 1            -> 1 <= 50 is True
	     (7)^2 = 49          -> 49 <= 50 is True

row group 3 is not excluded because -2^2 = 4 and therefore 4 <= 50 is True

However I don't understand what you say by:
`"If a single value remains after the filter we must read the file"`

**Comment by ritchie46** [comment]
Good point. I will adapt the logic to only take simple comparisons into account.

**Pull request merged**
