### PR TITLE
feat: Display streaming status of FunctionNodes

### PR DESCRIPTION
**Pull request by itamarst**
It's useful to understand what is or isn't streaming when explaining a lazy plan. While this is just a small subset of the places where this info would need to be added (see #10936), this should at least give slightly more information to users.

This is something of a sketch; it would be helpful to understand how much would be possible to add (and where) to other parts of the displayed lazy plan.

### CODE REVIEW

**Comment by ritchie46** [comment]
The thing is, that this information is confusing. Only a pipeline runs in a streaming fashion. Now it looks like a non-streaming group-by runs in streaming.

**Comment by itamarst** [comment]
> Now it looks like a non-streaming group-by runs in streaming.

Because the internal operations are marked as streaming?

Is there a way to tell if a group-by will be streaming from the logical plan?

**Comment by ritchie46** [comment]
Yes, if you it is in a `pipeline` block, it will run streaming.  Maybe a better solution would be renaming the display from pipeline to streaming.

**Comment by itamarst** [comment]
So what I'm understanding is that if anything is in PIPELINE, that means it's streaming?

If I understood correctly, renaming it to STREAMING would make that clearer, yes. I did notice though that sometimes PIPELINE is shown in a plan whether or not `collect()` was called with `streaming=True`. So does the PIPELINE indicate streaming will be used even if `streaming=False`?

**Comment by ritchie46** [comment]
> So does the PIPELINE indicate streaming will be used even if streaming=False?

Yes, we hybridly use both engines.

**Comment by itamarst** [comment]
OK, so just replacing PIPELINE with STREAMING seems like it would be informative for users, I'll update the PR.

**Pull request closed without merging**
