### PR TITLE
Use "doc_auto_cfg" again (#6164)

### PR DESCRIPTION
**Pull request by n8henrie**
Reverts the revert.

(This reverts commit 557f986de83f800edc52ba10a1e00db3a6713be8.)

Seems to be building and displaying correctly at my fork:
<https://n8henrie.com/polars/polars/prelude/enum.Expr.html#method.diff>

Fixes https://github.com/pola-rs/polars/issues/6123

Let's not merge to master *quite* yet to see if I can figure out why it's
working for me but didn't last time you merged.

### CODE REVIEW

**Comment by n8henrie** [comment]
🤞

**Comment by n8henrie** [comment]
Seems to be working. All actions have completed, and clearing cache and reloading https://pola-rs.github.io/polars/polars/prelude/enum.Expr.html#method.diff I see

**Comment by ritchie46** [comment]
Yeap, I see it too! Thanks a lot @n8henrie :raised_hands:

**Comment by n8henrie** [comment]
Good deal. I'll keep my eye out for the next release to crates.io to make sure docs.rs is also working -- the original cause for the issue!

**Pull request merged**
