### PR TITLE
Let rust decompress and normalise path

### PR DESCRIPTION
**Pull request by olivier-lacroix**
Hi @ritchie46 ,

This PR is to limit fsspec use to remote files only, due to more features now being implemented on the rust side.

Unfortunately, the following fail:

- read_csv of a local compressed file yields `RuntimeError: Any(Other("Other(\"invalid utf8 data\") on thread line 0;`. it seems the content is not decompressed on the rust side automatically.
- read_csv of something like '~/file.csv' yields a file not found error:

```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<timed exec> in <module>

/opt/conda/lib/python3.9/site-packages/polars/io.py in read_csv(file, infer_schema_length, batch_size, has_headers, ignore_errors, stop_after_n_rows, skip_rows, projection, sep, columns, rechunk, encoding, n_threads, dtype, new_columns, use_pyarrow, low_memory, comment_char, storage_options, null_values)
    268 
    269     with _prepare_file_arg(file, **storage_options) as data:
--> 270         df = pl.DataFrame.read_csv(
    271             file=data,
    272             infer_schema_length=infer_schema_length,

/opt/conda/lib/python3.9/site-packages/polars/eager/frame.py in read_csv(file, infer_schema_length, batch_size, has_headers, ignore_errors, stop_after_n_rows, skip_rows, projection, sep, columns, rechunk, encoding, n_threads, dtype, low_memory, comment_char, null_values)
    443         processed_null_values = _process_null_values(null_values)
    444 
--> 445         self._df = PyDataFrame.read_csv(
    446             file,
    447             infer_schema_length,

FileNotFoundError: No such file or directory (os error 2)
```

### CODE REVIEW

**Comment by ritchie46** [comment]
I will take a look.

**Comment by ritchie46** [comment]
#1020 Will fix that. I will merge this after that PR.

**Comment by ritchie46** [comment]
Can this be merged?

**Comment by olivier-lacroix** [comment]
@ritchie46 , let me pull, compile and make sure everything is fine before that.

**Comment by olivier-lacroix** [comment]
@ritchie46 , testing pl.read_csv :

- Resolution of ~ works well
- Decompression works well as well, but not when specifying a subset of columns (maybe other arguments will make it fail as well)

`RuntimeError: Any(NotFound("Unable to get field named \"XXX\". Valid fields: [\"\\u{1f}�\\u{8}\\u{8}\\u{1d}��\\u ... `

almost there :-)

**Comment by olivier-lacroix** [comment]
I guess this does not prevent from merging this PR though.

**Comment by ritchie46** [comment]
> 
    Resolution of ~ works well
    Decompression works well as well, but not when specifying a subset of columns (maybe other arguments will make it fail as well)

> RuntimeError: Any(NotFound("Unable to get field named \"XXX\". Valid fields: [\"\\u{1f}�\\u{8}\\u{8}\\u{1d}��\\u ... 

Could you open an issue with a minimal example? Then we can fix that in another PR.

**Comment by ritchie46** [comment]
> I guess this does not prevent from merging this PR though.

If you remove the draft, I can merge. :)

**Comment by olivier-lacroix** [comment]
Oops. I did not realise this was preventing merge!

**Comment by olivier-lacroix** [comment]
@ghuls , yes, I wondered that as well. I wasn't too sure about the value vs the added complexity tbh.

**Pull request merged**
