### PR TITLE
feat[rust]: impl ArrowGetItem for BinaryArray

### PR DESCRIPTION
**Pull request by ozgrakkurt**

### CODE REVIEW

**Comment by ritchie46** [comment]
Polars does not support the Binary arrow type, so I don't really understand this PR?

**Comment by ozgrakkurt** [comment]
I though it is supported because of the discussion here: https://github.com/pola-rs/polars/issues/4877

**Comment by ritchie46** [comment]
I meant that you could use a `ListType` filled with `u8` as a proxy type for binary.

**Comment by ozgrakkurt** [comment]
would it make sense to add support for binary arrow type all around? It is more efficient to store in parquet files than just encoding binary data and putting into text

**Pull request closed without merging**
