### PR TITLE
Home directory support

### PR DESCRIPTION
**Pull request by cjermain**
This PR adds support for passing in file paths that use the home directory (e.g. `"~/test.parquet"`). At present this returns a file not found error, as the `~` is not interpreted correctly. Paths with the home directory are also not currently supported in `pyarrow` (and by extension `read_parquet("~/test.parquet", use_pyarrow=True)`, but I put up a fix in apache/arrow#12675. This is helpful for working with local files and is consistent with `pandas` behavior.

```
import polars as pl
df = pl.read_parquet("~/test.parquet")
```
I'm not sure the best place to add tests for this. I was thinking to use mock and avoid actually testing in the home directory. :smile: Any suggestions?

I added the functionality to `_prepare_file_arg` to add support broadly. Are there other places that need to be included?

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks, seems like a good solution. 

> I'm not sure the best place to add tests for this. I was thinking to use mock and avoid actually testing in the home directory. smile Any suggestions?

`py-polars/tests/db-benchmark/various.py` only runs in CI. We could write something to home there and test if we can read it.

**Comment by universalmind303** [comment]
Is this a python specific issue, or would rust have the same behavior for `~/` paths? If it's the latter, would it make more sense to look at implementing a rust based solution?

**Comment by ritchie46** [comment]
> Is this a python specific issue, or would rust have the same behavior for `~/` paths? If it's the latter, would it make more sense to look at implementing a rust based solution?

I know we already handle it for csv files in Rust. I am not certain about other formats.

The reason I think this python solution is ok, is because we also handle the case we dispatch to pyarrow.

**Comment by cjermain** [comment]
That sounds good. I'll add the tests soon.

**Comment by cjermain** [comment]
I looked at options for solving this in Rust directly, but the std library seems to have [deprecated support for home directory](https://doc.rust-lang.org/std/env/fn.home_dir.html). I updated all the read/write methods for DataFrame to support home directory expansion in Python. I think there is potential for some consolidation around re-used types for the hints, but I tried to avoid refactoring. :smile: 

The test in `various.py` feels brittle. I'm open to adding more effective tests using [pytest-mock](https://pypi.org/project/pytest-mock/) that could be parametrized to cover the various cases.

**Comment by ritchie46** [comment]
@cjermain Thank you. I will merge this in as I think it is good enough to be merged. I agree that the various.py is not ideal. We can improve upon it an a future PR. Thanks again!

**Pull request merged**
