### PR TITLE
fix: Correct wildcard expansion for functions

### LINKED ISSUE #18968: `pl.all().list.count_matches` results in a `SchemaError`
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [[1, 2]], "b": [[3, 4]]})

df.select(pl.all().list.count_matches(539))
# SchemaError: could not evaluate comparison between series 'a' of dtype: i64 and series '' of dtype: list[i64]
```

### Log output

_No response_

### Issue description

The plan:

```python
df.lazy().select(pl.all().list.count_matches(539)).explain()
# ' SELECT [col("a").list.count_matches([col("b"), dyn int: 539])] FROM\n  DF ["a", "b"]; PROJECT 2/2 COLUMNS; SELECTION: None'
```

Is producing:

```python
col(a).list.count_matches(col(b), lit(539))
```

Instead of:

```python
col(a).list.count_matches(lit(539))
col(b).list.count_matches(lit(539))
```

**Other examples**

`.list.concat` (and the `.list.set_*` methods (https://github.com/pola-rs/polars/issues/18795)) also seem affected causing incorrect results/dropped columns.

```python
df.select(pl.all().list.concat(539))
# shape: (1, 1)
# ┌───────────────────┐
# │ a                 │ # expected: a [1, 2, 539], b [3, 4, 539]
# │ ---               │
# │ list[i64]         │
# ╞═══════════════════╡
# │ [1, 2, 3, 4, 539] │
# └───────────────────┘
```

**Debugging**

It seems all these cases end up here:

https://github.com/pola-rs/polars/blob/cafc163f1c72d5926a3500d072115a137f7f6468/crates/polars-plan/src/plans/conversion/expr_expansion.rs#L551-L553

i.e. it only happens if the `INPUT_WILDCARD_EXPANSION` flag is set.

### Expected behavior

The initial example should produce a count for each column.

```python
# shape: (1, 2)
# ┌─────┬─────┐
# │ a   ┆ b   │
# │ --- ┆ --- │
# │ u32 ┆ u32 │
# ╞═════╪═════╡
# │ 0   ┆ 0   │
# └─────┴─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.8.2
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### LINKED ISSUE #19007: `pl.duration(days=pl.all())` also passes values to `hours=`
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1], "b": [2]})

df.select(pl.duration(days=pl.all()))
# shape: (1, 1)
# ┌──────────────┐
# │ literal      │
# │ ---          │
# │ duration[μs] │
# ╞══════════════╡
# │ 1d 2h        │
# └──────────────┘
```

### Log output

_No response_

### Issue description

I think this may actually be another form of: 

- https://github.com/pola-rs/polars/issues/18968

It seems to be doing

```
pl.duration(col(a), col(b))
```

Instead of

```
pl.duration(col(a))
pl.duration(col(b))
```

### Expected behavior

I was expecting a `literal` duplicate error, but thought adding `.name.keep()` would be the same as:

```python
df.select(
    pl.duration(days="a").name.keep(),
    pl.duration(days="b").name.keep()
)

# shape: (1, 2)
# ┌──────────────┬──────────────┐
# │ a            ┆ b            │
# │ ---          ┆ ---          │
# │ duration[μs] ┆ duration[μs] │
# ╞══════════════╪══════════════╡
# │ 1d           ┆ 2d           │
# └──────────────┴──────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.8.2
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by siddharth-vi**
Fixes #19007 
Fixes #18968 

Remove INPUT_WILDCARD_EXPANSION  for the following functions -

- list.contains
- list.count_matches
- pl.duration

INPUT_WILDCARD_EXPANSION is meant for functions which can have variadic arguments. The above functions have fixed number of arguments, hence this flag should not be set.

Behaviour - 
Before 
```
import polars as pl

df = pl.DataFrame({"a": [1], "b": [2]})
df.select(pl.duration(hours=pl.all()).name.keep() )

shape: (1, 1)
┌──────────────┐
│ a            │
│ ---          │
│ duration[μs] │
╞══════════════╡
│ 1h 2m        │
└──────────────┘


df = pl.DataFrame({"a": [[1, 2]], "b": [[3, 4]]})
df.select(pl.all().list.contains(3))

#InvalidOperationError: `is_in` operation not supported for dtype `list[i64]`


df = pl.DataFrame({"a": [[1, 2]], "b": [[3, 4]]})
print(df.select(pl.all().list.count_matches(3)))

#SchemaError: could not evaluate comparison between series 'a' of dtype: i64 and series '' of dtype: list[i64]


```
After
```
df = pl.DataFrame({"a": [1], "b": [2]})
print(df.select(pl.duration(hours=pl.all()).name.keep() ))

shape: (1, 2)
┌──────────────┬──────────────┐
│ a            ┆ b            │
│ ---          ┆ ---          │
│ duration[μs] ┆ duration[μs] │
╞══════════════╪══════════════╡
│ 1h           ┆ 2h           │
└──────────────┴──────────────┘

df = pl.DataFrame({"a": [[1, 2]], "b": [[3, 4]]})
df.select(pl.all().list.contains(3))

shape: (1, 2)
┌───────┬──────┐
│ a     ┆ b    │
│ ---   ┆ ---  │
│ bool  ┆ bool │
╞═══════╪══════╡
│ false ┆ true │
└───────┴──────┘

df = pl.DataFrame({"a": [[1, 2]], "b": [[3, 4]]})
print(df.select(pl.all().list.count_matches(3)))

shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ u32 ┆ u32 │
╞═════╪═════╡
│ 0   ┆ 1   │
└─────┴─────┘
```

More discussion about this can be found in the issue #19007

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks, can you add some tests on the python side?

**Comment by siddharth-vi** [comment]
@ritchie46 Please check now.

**Comment by ritchie46** [comment]
Thanks!

**Comment by cmdlineluser** [comment]
Thank you @siddharth-vi 

I'm not sure if it's something you want to look into, but I think there were also some other cases where this seems to happen.

- `.list.set_*` https://github.com/pola-rs/polars/issues/18795
- `.list.concat`

The corresponding `.arr.*` methods also seemed to demonstrate the same behaviour e.g. `.arr.count_matches()` etc.

**Comment by siddharth-vi** [comment]
Will check them out @cmdlineluser

**Pull request merged**
