### PR TITLE
docs(python): Update reference to `apply`

### PR DESCRIPTION
**Pull request by avimallu**
Closes https://github.com/pola-rs/polars/issues/15945.

Removed the reference to `apply` as indicated and replaced with `map_rows` or `map_elements` as appropriate.

### CODE REVIEW

**Comment by avimallu** [comment]
Test failures unrelated to this PR: Ruff job failed to setup and Code Coverage failed with the error:

>  Codecov: Failed to properly create commit: The process '/Users/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1

**Review by alexander-beedie — APPROVED** [review]

**Comment by alexander-beedie** [comment]
> Removed the reference to `apply` as indicated and replaced with `map_rows` or `map_elements` as appropriate.

Nice one; you receive today's "eye of the tiger" award 😁🏆

**Review by alexander-beedie — CHANGES_REQUESTED** [review]
Ahh; just to be sure I re-ran the failing `ruff` lint job and one small fix is required ;)
```
py-polars/polars/dataframe/frame.py:6202:89: 
  W505 Doc line too long (89 > 88)
```

**Comment by avimallu** [comment]
> you receive today's "Eye of the Tiger" award 😁🏆
Haha, full credit goes to @david-waterworth though :)

> one small fix is required ;)
Nice catch, have made the update.

Code coverage seems to require a token now, so I guess that will fail until then.

**Review by alexander-beedie — APPROVED** [review]

**Comment by alexander-beedie** [comment]
Thank you both! ✌️

**Pull request merged**
