### PR TITLE
docs: Change dprint config

### PR DESCRIPTION
**Pull request by rodrigogiraoserrao**
By changing [the `dprint` config](https://dprint.dev/plugins/markdown/config/) we get markdown files with a consistent maximum line width which makes it easier to review and diff markdown documents, especially in the docs.

### CODE REVIEW

**Comment by ritchie46** [comment]
Ouch.. That's a painful one. Let's get it over with. :D

Can you rebase?

**Comment by rodrigogiraoserrao** [comment]
> Ouch.. That's a painful one. Let's get it over with. :D
> 
> Can you rebase?

Done 🫡

**Comment by ritchie46** [comment]
The CI seems to fail (twice).

**Comment by rodrigogiraoserrao** [comment]
> The CI seems to fail (twice).

Well, yes, but actually, no. The `markdown-link-check` fails very often on links that are working. I'm rerunning the CI job but it's passing.

**Pull request merged**
