### PR TITLE
feat(python): expose `take` to Lazy/DataFrame

### LINKED ISSUE #11911: `DataFrame.take`
### Description

`polars.Series`, `pandas.Series`, `pandas.DataFrame`, `pyarrow.Array` and `pyarrow.Table` all support the `.take(indices)` method, which given a collection of integer indices selects the sub-series/table of the corresponding rows. Maybe worth considering as an addition to `polars.DataFrame`?

### PR DESCRIPTION
**Pull request by mcrumiller**
Resolves #11911

### CODE REVIEW

**Review by stinodego — CHANGES_REQUESTED** [review]
We should first decide on https://github.com/pola-rs/polars/issues/10972

`take` is probably not the right name.

**Comment by ritchie46** [comment]
I am also not convinced on adding this. I want to stay away from index aware queries with temporary series that hold indexes which represents some earlier predicate.

**Comment by mcrumiller** [comment]
@ritchie46 should I close this one, i.e. are you firmly against having `take` on a frame? It's implemented on the rust side for some reason, but I suppose never used.

**Comment by ritchie46** [comment]
Yes, I think we should close. In python we already have indexing.

**Pull request closed without merging**
