### PR TITLE
test(python): Fix `read/write_database` tests

### PR DESCRIPTION
**Pull request by stinodego**
Changes:
* Rename `sql` argument to `query` for `read_database`. This is more intuitive - and it's in line with how `connectorx` does the naming. Make some args keyword-only. This is not breaking as this function has not been released yet.
* Tests for `read_database` weren't being run! Due to the packages not being available and a sneaky `suppress(ImportError)`. Tests shouldn't silently pass just because the environment isn't set up correctly...
  * `connectorx` only supports Python `>=3.8`
  * `adbc_driver_sqlite` only supports Python `>=3.9`, and doesn't support Windows on Python 3.11.
  * Packages have been added to the `dev` requirements and are conditionally skipped for Python 3.7 / Windows tests.

After fixing the tests, I encountered a strange bug where apparently `write_database` rounds floats? Check out the `# TODO` comment in the test... out of scope for this PR, but should definitely be fixed.

### CODE REVIEW

**Comment by ritchie46** [comment]
> Check out the # TODO comment in the test... out of scope for this PR, but should definitely be fixed.

Can you make an issue of that one? Todo's tend to live long.

**Comment by stinodego** [comment]
See #7328

**Comment by stinodego** [comment]
> > Rename sql argument to query for read_database. This is more intuitive - and it's in line with how connectorx does the naming. Make some args keyword-only. This is not breaking as this function has not been released yet.
> 
> Like that one.

We could also swap the first two arguments to be fully in line with `connectorx` (first the `connection_uri` and then the `query`). That makes sense to me too. I think it's OK either way - but now would be the time to adjust if we want to!

**Comment by ritchie46** [comment]
In this case I think the pandas default has more muscle memory for people. No strong opinion here.

**Pull request merged**
