### PR TITLE
feat(rust): expr.is_between added to rust

### PR DESCRIPTION
**Pull request by rancomp**
fixes: https://github.com/pola-rs/polars/issues/11285

I implemented `Expr.is_between`. Perhaps we should add `Series.is_between` as well?

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Note that when an `Expr` is implemented in Rust then that same implementation should be what we use in Python; do you think you can update/extend the PR accordingly? 😎

**Comment by stinodego** [comment]
@rancomp You can check this diff for a reference of how to add an expression in both Rust/Python:
https://github.com/pola-rs/polars/pull/10958/files

**Comment by rancomp** [comment]
Thanks @stinodego . IIUC I'm missing two things:
1. the implementation of is_between `crates/polars-ops/src/series`. Is `/ops/is_between.rs` the proper location?
2. the wrapper in `crates/polars-plan/src/dsl/function_expr/`.

**Comment by rancomp** [comment]
> @rancomp You can check this diff for a reference of how to add an expression in both Rust/Python: https://github.com/pola-rs/polars/pull/10958/files

Thanks @stinodego . IIUC I'm missing two things:
1. the implementation of is_between `crates/polars-ops/src/series`. Is `/ops/is_between.rs` the proper location?
2. the wrapper in `crates/polars-plan/src/dsl/function_expr/`.

**Pull request closed without merging**
