### PR TITLE
feat(python): Order percentiles in `describe`

### LINKED ISSUE #10187: Order rows by percentiles in DataFrame.describe()
### Problem description

```python
import polars as pl

pl.DataFrame(
    {
        "a": [1.0, 2.8, 3.0],
        "b": [4, 5, None],
        "c": [True, False, True]
    }
).describe()
```
```
shape: (9, 4)
┌────────────┬──────────┬──────────┬──────────┐
│ describe   ┆ a        ┆ b        ┆ c        │
│ ---        ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪══════════╪══════════╪══════════╡
│ count      ┆ 3.0      ┆ 3.0      ┆ 3.0      │
│ null_count ┆ 0.0      ┆ 1.0      ┆ 0.0      │
│ mean       ┆ 2.266667 ┆ 4.5      ┆ 0.666667 │
│ std        ┆ 1.101514 ┆ 0.707107 ┆ 0.57735  │
│ min        ┆ 1.0      ┆ 4.0      ┆ 0.0      │
│ max        ┆ 3.0      ┆ 5.0      ┆ 1.0      │
│ median     ┆ 2.8      ┆ 4.5      ┆ 1.0      │
│ 25%        ┆ 1.0      ┆ 4.0      ┆ null     │
│ 75%        ┆ 3.0      ┆ 5.0      ┆ null     │
└────────────┴──────────┴──────────┴──────────┘
```

It would be better if the rows could be ordered as `min`, `25%`, `median`, `75%`, `max`
```
┌────────────┬──────────┬──────────┬──────────┐
│ describe   ┆ a        ┆ b        ┆ c        │
│ ---        ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪══════════╪══════════╪══════════╡
│ count      ┆ 3.0      ┆ 3.0      ┆ 3.0      │
│ null_count ┆ 0.0      ┆ 1.0      ┆ 0.0      │
│ mean       ┆ 2.266667 ┆ 4.5      ┆ 0.666667 │
│ std        ┆ 1.101514 ┆ 0.707107 ┆ 0.57735  │
│ min        ┆ 1.0      ┆ 4.0      ┆ 0.0      │
│ 25%        ┆ 1.0      ┆ 4.0      ┆ null     │
│ median     ┆ 2.8      ┆ 4.5      ┆ 1.0      │
│ 75%        ┆ 3.0      ┆ 5.0      ┆ null     │
│ max        ┆ 3.0      ┆ 5.0      ┆ 1.0      │
└────────────┴──────────┴──────────┴──────────┘
```
Or maybe even better: just name median as 50% 
```
┌────────────┬──────────┬──────────┬──────────┐
│ describe   ┆ a        ┆ b        ┆ c        │
│ ---        ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪══════════╪══════════╪══════════╡
│ count      ┆ 3.0      ┆ 3.0      ┆ 3.0      │
│ null_count ┆ 0.0      ┆ 1.0      ┆ 0.0      │
│ mean       ┆ 2.266667 ┆ 4.5      ┆ 0.666667 │
│ std        ┆ 1.101514 ┆ 0.707107 ┆ 0.57735  │
│ min        ┆ 1.0      ┆ 4.0      ┆ 0.0      │
│ 25%        ┆ 1.0      ┆ 4.0      ┆ null     │
│ 50%        ┆ 2.8      ┆ 4.5      ┆ 1.0      │
│ 75%        ┆ 3.0      ┆ 5.0      ┆ null     │
│ max        ┆ 3.0      ┆ 5.0      ┆ 1.0      │
└────────────┴──────────┴──────────┴──────────┘
```

I believe this will also make sorting easier if users pass percentiles, such as
```
┌────────────┬──────────┬──────────┬──────────┐
│ describe   ┆ a        ┆ b        ┆ c        │
│ ---        ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪══════════╪══════════╪══════════╡
│ count      ┆ 3.0      ┆ 3.0      ┆ 3.0      │
│ null_count ┆ 0.0      ┆ 1.0      ┆ 0.0      │
│ mean       ┆ 2.266667 ┆ 4.5      ┆ 0.666667 │
│ std        ┆ 1.101514 ┆ 0.707107 ┆ 0.57735  │
│ min        ┆ 1.0      ┆ 4.0      ┆ 0.0      │
│ 40%        ┆ 2.8      ┆ 4.0      ┆ null     │
│ 50%        ┆ 2.8      ┆ 4.5      ┆ 1.0      │
│ 90%        ┆ 3.0      ┆ 5.0      ┆ null     │
│ max        ┆ 3.0      ┆ 5.0      ┆ 1.0      │
└────────────┴──────────┴──────────┴──────────┘
```

### PR DESCRIPTION
**Pull request by lfn3**
Resolves #10187

Replaces median with 50th percentile, and orders it within the provided percentiles when describing series and dataframes.

### CODE REVIEW

**Review by stinodego — APPROVED** [review]
This is very well done 👌 

I changed one `if` to an `elif`, otherwise this is good to go!

@ritchie46 I don't think this counts as a breaking change, right? A minor change in `describe` should not be breaking anyone's production pipelines 🤔 

One meta comment: for your next issue, try picking up an issue that is not already assigned. @cjackal may have already been working on this issue.

**Comment by lfn3** [comment]
Thanks!

I read the contrib guidelines and found the bit about assignment after I'd already written it - do feel bad about that. 
@cjackal apologies if this has burnt some the time you've already spent on this.

**Comment by ritchie46** [comment]
> @ritchie46 I don't think this counts as a breaking change, right? A minor change in describe should not be breaking anyone's production pipelines thinking

I don't know? I leave this one to you. ;)

**Comment by stinodego** [comment]
Then it's going in!

**Pull request merged**
