### PR TITLE
ci(python): Merge release workflows

### PR DESCRIPTION
**Pull request by stinodego**
Having four different release workflows makes things unnecessarily complicated. They all trigger on the same thing (a `py-*` tag), so they can be part of the same workflow.

This makes it easy to temporarily disable the release process entirely, or restart failed release jobs.

### CODE REVIEW

**Comment by ritchie46** [comment]
I understand the rationale of this one, but I am a bit hesitant of the practical implications of this one.

The outside world is erratic and it happens more often than I like that a release flow fails because of a network connection that is down, a downstream crate doesn't compile, or the linker having an error etc. Currently, such an error, does not influence the other releases and we can focus on finishing the failing pipeline whilst the others can be ignored.

**Comment by stinodego** [comment]
> Currently, such an error, does not influence the other releases and we can focus on finishing the failing pipeline whilst the others can be ignored.

That would still be the case. You'll get a workflow summary like [this one](https://github.com/pola-rs/polars/actions/runs/3502685477), but with a bunch more jobs in it. Some of these may fail, that does not influence the other jobs (they are all independent jobs). And then you can re-run individual jobs, all jobs, or all failed jobs.

**Comment by ritchie46** [comment]
Alright! Thanks!

**Comment by stinodego** [comment]
Easily reverted if you're not happy about it! 😸

**Pull request merged**
