### PR TITLE
Improve error message in FileNotFoundError

### LINKED ISSUE #3432: Improve error message in `FileNotFoundError`
#### Describe your feature request

Now, py-polars error message when reading a non-existing file does not have the information of filename like

```python
>>> import polars as pl
>>> pl.read_csv("./not_exists.csv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/python/3.9.7/lib/python3.9/site-packages/polars/io.py", line 422, in read_csv
    df = DataFrame._read_csv(
  File "/path/to/python/3.9.7/lib/python3.9/site-packages/polars/internals/frame.py", line 586, in _read_csv
    self._df = PyDataFrame.read_csv(
FileNotFoundError: No such file or directory (os error 2)
```

I think it is helpful to add filename information like pandas, especially in the case of reading many files.

```python
>>> import pandas as pd
>>> pd.read_csv("./not_exists.csv")
Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] No such file or directory: './not_exists.csv
```

### PR DESCRIPTION
**Pull request by ishmandoo**
This PR resolves #3432 by catching the original `FileNotFoundError` and reraising it with the file name for context.

### CODE REVIEW

**Comment by illumination-k** [comment]
I think we should resolve this on the rust side to improve all io not only csv but also ipc, parquet etc.,.

Maybe here?
https://github.com/pola-rs/polars/blob/3484245d58df88b5d2fa233b4dae08bca9ffbe1d/py-polars/src/file.rs#L209-L213

**Comment by ishmandoo** [comment]
@illumination-k something like this?

**Comment by ritchie46** [comment]
The changes are still only on the python bindings. We should improve the error where it originates. It then bubbles up correctly for all polars front-ends.

**Comment by ishmandoo** [comment]
Happy to keep working on this but doesn't the error originate in the `File::open()`` call I'm wrapping?
https://github.com/ishmandoo/polars/blob/read_csv_error_message/py-polars/src/file.rs#L213

**Comment by ritchie46** [comment]
Oh sorry. You are right. My bad. :)

**Comment by ritchie46** [comment]
Thanks for the PR!

**Pull request merged**
