### PR TITLE
Allow negative column-indexing for additional functions, and expose frame-level `take_every`

### PR DESCRIPTION
**Pull request by alexander-beedie**
A couple of small additions/tweaks, and associated new test coverage:

* Allow negative indexing for -
  * `select_at_idx`
  * `insert_at_idx`
  * `replace_at_idx`
  * `to_series`

* Expose frame-level `take_every` method to DataFrame and LazyFrame (consistent with Series).

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks @alexander-beedie. 

I am only not yet convinced of exposing `take_every`. Maybe we could argue in favor of this one, because it is indexing/slicing, but in general I don't want to expose many expressions to a `DataFrame` level as it would be yet another way to do things.

But as I said, maybe let's allow this once because it is data access and no computation.

**Comment by alexander-beedie** [comment]
> Thanks @alexander-beedie.
> 
> I am only not yet convinced of exposing `take_every`. Maybe we could argue in favor of this one, because it is indexing/slicing, but in general I don't want to expose many expressions to a `DataFrame` level as it would be yet another way to do things.
> 
> But as I said, maybe let's allow this once because it is data access and no computation.

I started out being a little on-the-fence about it, but (at least to me) it does feel like something that works naturally as a frame-level selection op; and, indeed, there is no computation so it's cheap. (It's a bit like the `reverse()` op in this sense - you _can_ express it as a `select(pl.col("*").reverse())`, but it 'feels' like it should probably be available at frame level.

Maybe it's the difference between thinking row-wise ("I want every other row of this frame") vs column-wise ("I want every other row of each individual column but then I want to bundle them all back together as a frame"). My suspicion is really just that the first is a bit more discoverable :)

Can omit if you prefer though 👍

**Comment by ritchie46** [comment]
I think it is consistent to expose this to the frame level, as we do this for more access/ slicing methods. :+1: 

Thanks for the PR @alexander-beedie. Can you do a rebase for the conflicting files? Then I merge it in.

**Comment by alexander-beedie** [comment]
> Thanks for the PR @alexander-beedie. Can you do a rebase for the conflicting files? Then I merge it in.

I swear I have the worst luck with rebases... there must be a "don't mess it up" flag somewhere that I'm just not setting, hah. will try and tidy it up or just submit a fresh/clean PR.

**Pull request closed without merging**
