### PR TITLE
Add polars-lazy support to IPC Arrow Stream

### PR DESCRIPTION
**Pull request by joshuataylor**
Hi!

This copies the IPC Lazy Streaming. I've also added the same file tests the IPC files uses for lazy testing.

I've been testing this across my files and it works well.

What this does:

1. Adds `ipc_streaming` feature flag to polars_lazy
2. When enabled, adds lazy streaming to IPC Arrow Streaming files.

### CODE REVIEW

**Comment by ritchie46** [comment]
What do you mean by streaming? The polars computation graph does not support streaming processes? So a stream should be consumed in one go, and if we do, what does it differ from files then?

**Comment by joshuataylor** [comment]
Good question.

Apache Arrow defines two formats for serializing data for IPC:
1. File format
2. Stream format

read_ipc is against the file format, whereas read_ipc_stream is against the stream format.

https://arrow.apache.org/docs/format/Columnar.html#ipc-streaming-format

The main difference is summed up pretty well here: https://arrow.apache.org/docs/format/Columnar.html#ipc-file-format

IMHO, if this could be somehow used for both IPC/IPC Streams, that would be great?

This PR is handy because you might get files back in the stream format, for example Snowflake sends this back when you use their internal API.

What I want to be able to do is do lazy calculations against their datasets I get back from them, without first having to transform to something else. Polars allows me to easily do this with lazy.

**Comment by ritchie46** [comment]
There are a few things to consider regarding my aim for polars lazy. Currently we have some reader nodes, but they all do sort of the same, I don't like this as it bloats our compile times and code complexity. The plan is to refactor everything to `AnynomousNode` readers, but this is still a WIP.

If we would do this, we should use the `Anonymous` node, and probably could be something that is in the `examples` directory. As a show case of how a consumer/user of polars could bring there own readers into `polars-lazy`.

To be able to use the `AnonymousNode` you need to provide two things. A function that creates the `Schema` before we do any computation. And a function that materializes the `DataFrame`.

# Regarding streams
Streams can be a bit problematic as polars lazy is not streaming. That means you need to consume the stream completely for output to make sense.

If you have already consumed your stream, there is no need for a separate node in the query plan. You can simply consume the stream into a `DataFrame` and then call `lazy()` to use polars lazy.

**Comment by joshuataylor** [comment]
Let's close this for now, we can revisit it later when that other work is in :+1:

**Comment by ritchie46** [comment]
> Let's close this for now, we can revisit it later when that other work is in +1

Ok,  I am still curious about how you process the stream, so maybe we can explore an example crate in the examples directory and see if there are any roadbloack/nice to haves?

**Pull request closed without merging**
