### PR TITLE
Create internal Python api

### PR DESCRIPTION
**Pull request by zundertj**
All interdependent modules live in `internals`.  Within those modules, I use the convention `import polars.internals as pli` and refer to `pli`. Outside these modules, but inside the lib, we can do `from polars.internals import DataFrame` for instance. The top level `__init__` is now purely the public facing api.

### CODE REVIEW

**Comment by zundertj** [comment]
I need to fix flake8 & mypy errors still, almost all are a rename from `pl` to `pli`.

Could someone help with the test failures? I do not understand:
* why is `wrap_s` on toplevel needed?
* where is `pl.list` defined?
* and other errors

**Comment by ritchie46** [comment]
> I need to fix flake8 & mypy errors still, almost all are a rename from `pl` to `pli`.
> 
> Could someone help with the test failures? I do not understand:
> 
>     * why is `wrap_s` on toplevel needed?
> 
>     * where is `pl.list` defined?
> 
>     * and other errors

wrap_s is not needen at top level.

`pl.list` is `pl.to_list` exported as `list`. Its internally defined as `to_list` to not colide with the python builtin

**Comment by zundertj** [comment]
The `wrap_s` on the top-level does fix some of the below, but it should indeed not be done. I have fixed the PR, and Im only stuck with this error a number of tests. Any idea? 

```python
test_lazy.py:90 (test_binary_function)
def test_binary_function() -> None:
        df = pl.DataFrame({"a": [1, 2, 3], "b": [1.0, 2.0, 3.0]})
        out = (
>           df.lazy()
            .with_column(map_binary(col("a"), col("b"), lambda a, b: a + b))
            .collect()
        )

test_lazy.py:94: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <polars.internals.lazy_frame.LazyFrame object at 0x0000023772E59FD0>
type_coercion = True, predicate_pushdown = True, projection_pushdown = True
simplify_expression = True, string_cache = False, no_optimization = False

    def collect(
        self,
        type_coercion: bool = True,
        predicate_pushdown: bool = True,
        projection_pushdown: bool = True,
        simplify_expression: bool = True,
        string_cache: bool = False,
        no_optimization: bool = False,
    ) -> pli.DataFrame:
        """
        Collect into a DataFrame.
    
        Parameters
        ----------
        type_coercion
            Do type coercion optimization.
        predicate_pushdown
            Do predicate pushdown optimization.
        projection_pushdown
            Do projection pushdown optimization.
        simplify_expression
            Run simplify expressions optimization.
        string_cache
            Use a global string cache in this query.
            This is needed if you want to join on categorical columns.
    
            Caution!
                If you already have set a global string cache, set this to `False` as this will reset the
                global cache when the query is finished.
        no_optimization
            Turn off optimizations.
    
        Returns
        -------
        DataFrame
        """
        if no_optimization:
            predicate_pushdown = False
            projection_pushdown = False
    
        ldf = self._ldf.optimization_toggle(
            type_coercion,
            predicate_pushdown,
            projection_pushdown,
            simplify_expression,
            string_cache,
        )
>       return pli.wrap_df(ldf.collect())
E       pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'AttributeError'>, value: AttributeError("module 'polars' has no attribute 'wrap_s'"), traceback: None }

..\polars\internals\lazy_frame.py:297: PanicException
```

**Comment by ritchie46** [comment]
> The `wrap_s` on the top-level does fix some of the below, but it should indeed not be done. I have fixed the PR, and Im only stuck with this error a number of tests. Any idea?
> 
> ```python
> test_lazy.py:90 (test_binary_function)
> def test_binary_function() -> None:
>         df = pl.DataFrame({"a": [1, 2, 3], "b": [1.0, 2.0, 3.0]})
>         out = (
> >           df.lazy()
>             .with_column(map_binary(col("a"), col("b"), lambda a, b: a + b))
>             .collect()
>         )
> 
> test_lazy.py:94: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> self = <polars.internals.lazy_frame.LazyFrame object at 0x0000023772E59FD0>
> type_coercion = True, predicate_pushdown = True, projection_pushdown = True
> simplify_expression = True, string_cache = False, no_optimization = False
> 
>     def collect(
>         self,
>         type_coercion: bool = True,
>         predicate_pushdown: bool = True,
>         projection_pushdown: bool = True,
>         simplify_expression: bool = True,
>         string_cache: bool = False,
>         no_optimization: bool = False,
>     ) -> pli.DataFrame:
>         """
>         Collect into a DataFrame.
>     
>         Parameters
>         ----------
>         type_coercion
>             Do type coercion optimization.
>         predicate_pushdown
>             Do predicate pushdown optimization.
>         projection_pushdown
>             Do projection pushdown optimization.
>         simplify_expression
>             Run simplify expressions optimization.
>         string_cache
>             Use a global string cache in this query.
>             This is needed if you want to join on categorical columns.
>     
>             Caution!
>                 If you already have set a global string cache, set this to `False` as this will reset the
>                 global cache when the query is finished.
>         no_optimization
>             Turn off optimizations.
>     
>         Returns
>         -------
>         DataFrame
>         """
>         if no_optimization:
>             predicate_pushdown = False
>             projection_pushdown = False
>     
>         ldf = self._ldf.optimization_toggle(
>             type_coercion,
>             predicate_pushdown,
>             projection_pushdown,
>             simplify_expression,
>             string_cache,
>         )
> >       return pli.wrap_df(ldf.collect())
> E       pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'AttributeError'>, value: AttributeError("module 'polars' has no attribute 'wrap_s'"), traceback: None }
> 
> ..\polars\internals\lazy_frame.py:297: PanicException
> ```

Oh yes, I use `wrap_s` inside the Rust bindings itself. Let's keep it top level for now. I can fix that once this is merged.

**Comment by zundertj** [comment]
Thank you, that fixed it indeed. Had to add `wrap_df` as well, added the TODO's. Should now pass tests. 

I see I have still some wildcard imports from the non-internals modules, I will clean up in a separate PR.

**Comment by zundertj** [comment]
CI fails on py3.6, and therefore cancels the other Python tests. I cant reproduce on my local machine, I do the development on py3.9. Is there a way to check on 3.9? Or it is my machine, so if someone can reproduce this, that would be helpful.

**Comment by ritchie46** [comment]
If you create a virtualenv with python 3.6. Then you do the same as in CI. I can also take a look later.

**Comment by zundertj** [comment]
Ok, I can reproduce this on Python 3.6 locally. Python 3.7 and Python 3.9 are fine. It is unclear what is driving this. Given that Python 3.6 receives security fixes only since January 2019 and will be end-of-life in 5 weeks (https://www.python.org/dev/peps/pep-0494/), would dropping Python 3.6 support be acceptable? This PR in itself is not important enough for breaking Python 3.6 support, but as it comes up very soon, and with 4 newer versions of Python available (3.7, 3.8, 3.9 & 3.10), I would think this is acceptable?

**Comment by zundertj** [comment]
Fixed, `import polars.internals as pli`does not work in Py36, but `from polars import internals as pli`. does...

**Comment by ritchie46** [comment]
Thanks a lot @zundertj. Good to have separation of internal and external API. :100:

**Pull request merged**
