### PR TITLE
feat(python): Add string representation for data types

### LINKED ISSUE #5674: Prettier datatype string representation
### Problem description

Printing out dtypes results in a string that is not nicely formatted for readability:

```python
df = pl.DataFrame({'a': [1,2,3], 'b': ['a', 'b', 'c']})
df.dtypes
# [<class 'polars.datatypes.Int64'>, <class 'polars.datatypes.Utf8'>]
```

Surely we can do better, maybe something like: `[Int64, Utf8]`

### PR DESCRIPTION
**Pull request by stinodego**
Resolves #5674 

Changes:
* Add a `type` metaclass to the `DataType` class with a `__repr__`. This class is now named `DataTypeClass` (suggestions for a better name are welcome). This makes sure the uninstantiated classes get a nice string representation.
* Update the `__repr__` for the special classes (Datetime, Duration, List, Struct, Field).
* Fixed a bunch of type hints along the way

See the test case for this implementation in action.

### CODE REVIEW

**Comment by ritchie46** [comment]
Good one! I tried this but got stuck in some very hacky rabbit hole so called it a day for now.

**Comment by ritchie46** [comment]
My problems were that by setting a `MetaClass` we overwrite `type` which needs us to adapt a low of type checks. I think it is doable and in the process it can be cleaner, but it probably needs some thought/work.

**Comment by stinodego** [comment]
There's definitely some weirdness going on with the types (this is on the master branch):

```python
reveal_type(pl.Utf8)
# Revealed type is "def (*args: Any, **kwargs: Any) -> polars.datatypes.Utf8"
```

Must have something to do with the `__new__` definition on the `DataType` class. Time to go down the rabbithole 🐰

**Comment by stinodego** [comment]
Got it to work 👍 we can probably still improve some type hints, but it's already better than before.

**Comment by ritchie46** [comment]
Wow.. Deep bow to your python meta programming! :bow:

**Comment by alexander-beedie** [comment]
Devious - and very nice  :)

**Pull request merged**
