### PR TITLE
fix: Raise exception for illegal `explode` usage

### PR DESCRIPTION
**Pull request by barak1412**
Fixes https://github.com/pola-rs/polars/issues/19049.

I am not sure if it's the right fix, since I think it is better to be caught earlier.

### CODE REVIEW

**Comment by ritchie46** [comment]
`explode` on non nested types is allowed and is considered a no-op.

**Comment by barak1412** [comment]
@ritchie46 So the the opened issue is not a bug?
Or it should error only when used in the context of list/array namespace.

**Comment by ritchie46** [comment]
The `arr.explode` now goes into the `DSL` as explode, but should go into a unique `Arrray::Explode` node in the `DSL`. 

When converting to `IR`, we can then check if the `.arr` was actually called on an array type.

**Comment by barak1412** [comment]
Thanks, I will try to learn this part of the code, and do the fix.
I guess also `List::Explode` should be added and verified as well.

**Pull request closed without merging**
