### PR TITLE
feat(rust, python): The 1 billion row sort

### PR DESCRIPTION
**Pull request by ritchie46**
Processed 1B rows 64 GBS of data in 1.52 mins.

image

### CODE REVIEW

**Comment by ritchie46** [comment]
Still have to drop synccounters.

**Comment by akhildevelops** [comment]
Please share the dataset on which this test run was done.

**Comment by ritchie46** [comment]
> Please share the dataset on which this test run was done.

Did you see the image? I create the dataset in the first cell.

**Comment by sjackman** [comment]
How do I configure the maximum amount of memory to use in an out-of-core sort? Similar to GNU sort's option `--buffer-size=SIZE`
```
       -S, --buffer-size=SIZE
              use SIZE for main memory buffer
```
https://man7.org/linux/man-pages/man1/sort.1.html

**Pull request merged**
