### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by elbaro**

### CODE REVIEW

**Comment by ghuls** [comment]
**Series** is used both for a singular and a plural form:

> Usage Note: Series is both a singular and a plural form. When it has the singular sense of "one set," it takes a singular verb, even when series is followed by of and a plural noun: A series of lectures is scheduled. When it has the plural sense of "two or more sets," it takes a plural verb: Two series of lectures are scheduled: one for experts and one for laypeople.
https://www.thefreedictionary.com/Series

**Comment by elbaro** [comment]
@ghuls The original code uses `series.push(serie)` because we cannot write `series.push(series)`.

**Comment by ritchie46** [comment]
> @ghuls The original code uses `series.push(serie)` because we cannot write `series.push(series)`.

Thanks for the fix @elbaro. 
I think @ghuls was referring to the docs being renamed to `serie`. He is right,  we must use the plural form `series`. If there are code snippets that use the variable `serie`, they can better be remaned to `s`, `series_`, `series`, `series_1`... You get the idea 😉

**Comment by elbaro** [comment]
This PR doesn't rename `series` to `serie` at all. Maybe the last commit confused you. I thought `serie` was a typo but reverted because it makes sense as an alternative variable name to `series`. If you have a preference about `s` vs `series_` vs `serie` then feel free to add in the PR.

**Comment by ritchie46** [comment]
> This PR doesn't rename `series` to `serie` at all. Maybe the last commit confused you. I thought `serie` was a typo but reverted because it makes sense as an alternative variable name to `series`. If you have a preference about `s` vs `series_` vs `serie` then feel free to add in the PR.

My bad. I read this diff exactly the other way around. 

```
    - // Compute the mean serie and rename to the `mean_column_name` provided
    + // Compute the mean series and rename to the `mean_column_name` provided
```

Forget what I said!

**Comment by ritchie46** [comment]
Thanks for the typo fixes @elbaro. LGTM. :)

**Pull request merged**
