### PR TITLE
fix(rust): don't use mimalloc on windows

### PR DESCRIPTION
**Pull request by csko**
Closes https://github.com/pola-rs/polars/issues/6409

Mimalloc seems to be causing issues on windows.

- [ ] Test on windows without mimalloc
- [ ] Benchmark

### CODE REVIEW

**Comment by ritchie46** [comment]
That's a bit rushed IMO. For one we haven't excluded that this is expected behavior of the memory allocator. Memory allocators keep a hold of memory to be used later. I first want to see some benchmarks showing the culprit and improvements if we step of from mimalloc.

**Comment by csko** [comment]
> That's a bit rushed IMO. For one we haven't excluded that this is expected behavior of the memory allocator. Memory allocators keep a hold of memory to be used later. I first want to see some benchmarks showing the culprit and improvements if we step of from mimalloc.

I agree on doing a benchmark and further digging into this. I ran the repro with the versions reported in the issue on Windows and Linux. On Linux, the memory stays constant between the for-loops with `pl.scan_csv`. On Windows, the memory keeps growing and the program eventually crashes after a few calls to the for-loop.

**Comment by ritchie46** [comment]
And on windows default allocator? Maybe we should change some mimalloc settings?

**Comment by ghuls** [comment]
@csko
Could you try with some mimalloc environment variables, before running Polars?

```
MIMALLOC_PAGE_RESET=1
MIMALLOC_RESET_DECOMMITS=1
MIMALLOC_RESET_DELAY=1

# Or:
MIMALLOC_PAGE_RESET=1
MIMALLOC_RESET_DECOMMITS=1
MIMALLOC_RESET_DELAY=0
```

> Thank you for the report; (if you can create a binary that I could run to repro locally that would be great, but I can see that usually not so easy).
>
>    Is this on Windows ? (this is important for commit/reset statistics vs. Linux). Is this the latest mimalloc master branch?
>
> Generally, mimalloc is not eager to share memory between threads as that generally is not good for performance so the behavior is not entirely unexpected (moreover, mimalloc will reset memory so the physical memory can be reused by other threads anyways). Nevertheless, it seems as if the memory stays in rss without ever being "reset"; here are some things to try:
>
 >   On some OS's, even when the memory is "reset" it will still show in the rss as it is reset lazily by the OS (but it is actually available to other processes). You could set both MIMALLOC_PAGE_RESET=1 as well as MIMALLOC_RESET_DECOMMITS=1 to force more aggressive reset that is reflected in the rss for sure. (Also set MIMALLOC_ABANDONED_PAGE_RESET=1 -- I don't think it helps but just to make sure.).
>
 >   At the end of the parsing etc. call mi_collect(false); mi_collect(true) (twice) -- this should really purge everything. You seem to imply it does not do this though, which makes me suspect that some memory is not freed ... (.. but you checked with valgrind ... hmm, I wonder if perhaps the library uses a free call that is not intercepted by mimalloc? )
>
>    If the previous things do not change things, it would be great if you could try the dev-slice branch -- this is currently the candidate for mimalloc 1.8 and does decommit on a finer grained basis. Try it first with stock settings, and then with MIMALLOC_RESET_DELAY=1 or even MIMALLOC_RESET_DELAY=0 (these settings are too aggressive for general use but it would let me understand what is happening with your workload).
>
> Hope there is something we can do here.

https://github.com/microsoft/mimalloc/issues/351

**Comment by ghuls** [comment]
Some other mimalloc environment variables:

```
You can set further options either programmatically (using [mi_option_set](https://microsoft.github.io/mimalloc/group__options.html)), or via environment variables.

    MIMALLOC_SHOW_STATS=1: show statistics when the program terminates.
    MIMALLOC_VERBOSE=1: show verbose messages.
    MIMALLOC_SHOW_ERRORS=1: show error and warning messages.
    MIMALLOC_PAGE_RESET=0: by default, mimalloc will reset (or purge) OS pages when not in use to signal to the OS that the underlying physical memory can be reused. This can reduce memory fragmentation in long running (server) programs. By setting it to 0 no such page resets will be done which can improve performance for programs that are not long running. As an alternative, the MIMALLOC_RESET_DELAY=<msecs> can be set higher (100ms by default) to make the page reset occur less frequently instead of turning it off completely.
    MIMALLOC_LARGE_OS_PAGES=1: use large OS pages (2MiB) when available; for some workloads this can significantly improve performance. Use MIMALLOC_VERBOSE to check if the large OS pages are enabled – usually one needs to explicitly allow large OS pages (as on [Windows](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-the-lock-pages-in-memory-option-windows?view=sql-server-2017) and [Linux](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/tuning_and_optimizing_red_hat_enterprise_linux_for_oracle_9i_and_10g_databases/sect-oracle_9i_and_10g_tuning_guide-large_memory_optimization_big_pages_and_huge_pages-configuring_huge_pages_in_red_hat_enterprise_linux_4_or_5)). However, sometimes the OS is very slow to reserve contiguous physical memory for large OS pages so use with care on systems that can have fragmented memory (for that reason, we generally recommend to use MIMALLOC_RESERVE_HUGE_OS_PAGES instead when possible).
    MIMALLOC_RESERVE_HUGE_OS_PAGES=N: where N is the number of 1GiB huge OS pages. This reserves the huge pages at startup and sometimes this can give a large (latency) performance improvement on big workloads. Usually it is better to not use MIMALLOC_LARGE_OS_PAGES in combination with this setting. Just like large OS pages, use with care as reserving contiguous physical memory can take a long time when memory is fragmented (but reserving the huge pages is done at startup only once). Note that we usually need to explicitly enable huge OS pages (as on [Windows](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-the-lock-pages-in-memory-option-windows?view=sql-server-2017) and [Linux](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/tuning_and_optimizing_red_hat_enterprise_linux_for_oracle_9i_and_10g_databases/sect-oracle_9i_and_10g_tuning_guide-large_memory_optimization_big_pages_and_huge_pages-configuring_huge_pages_in_red_hat_enterprise_linux_4_or_5))). With huge OS pages, it may be beneficial to set the setting MIMALLOC_EAGER_COMMIT_DELAY=N (N is 1 by default) to delay the initial N segments (of 4MiB) of a thread to not allocate in the huge OS pages; this prevents threads that are short lived and allocate just a little to take up space in the huge OS page area (which cannot be reset).
    MIMALLOC_RESERVE_HUGE_OS_PAGES_AT=N: where N is the numa node. This reserves the huge pages at a specific numa node. (N is -1 by default to reserve huge pages evenly among the given number of numa nodes (or use the available ones as detected))

Use caution when using fork in combination with either large or huge OS pages: on a fork, the OS uses copy-on-write for all pages in the original process including the huge OS pages. When any memory is now written in that area, the OS will copy the entire 1GiB huge page (or 2MiB large page) which can cause the memory usage to grow in big increments.
```

https://microsoft.github.io/mimalloc/environment.html

@ritchie46 The mimalloc large page setting from:
https://github.com/pola-rs/polars/commit/01364823488c2fcb2f810db29336a0a490173dcc
was removed no?

**Comment by ritchie46** [comment]
> @ritchie46 The mimalloc large page setting from:

Yes, this was really fast in some cases, but also really slow in others.

Let's await the results of a windows users on this. @zundertj care to give your windows machine a run?

**Comment by ghuls** [comment]
@zundertj What is the output on Windows of the following?

```
❯ export MIMALLOC_VERBOSE=1

❯ ipython
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.10.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import polars as pl
mimalloc: option 'show_errors': 0
mimalloc: option 'show_stats': 0
mimalloc: option 'verbose': 1
mimalloc: option 'eager_commit': 1
mimalloc: option 'deprecated_eager_region_commit': 0
mimalloc: option 'deprecated_reset_decommits': 0
mimalloc: option 'large_os_pages': 0
mimalloc: option 'reserve_huge_os_pages': 0
mimalloc: option 'reserve_huge_os_pages_at': -1
mimalloc: option 'reserve_os_memory': 0
mimalloc: option 'deprecated_segment_cache': 0
mimalloc: option 'page_reset': 0
mimalloc: option 'abandoned_page_decommit': 0
mimalloc: option 'deprecated_segment_reset': 0
mimalloc: option 'eager_commit_delay': 1
mimalloc: option 'decommit_delay': 25
mimalloc: option 'use_numa_nodes': 0
mimalloc: option 'limit_os_alloc': 0
mimalloc: option 'os_tag': 100
mimalloc: option 'max_errors': 16
mimalloc: option 'max_warnings': 16
mimalloc: option 'max_segment_reclaim': 8
mimalloc: option 'allow_decommit': 1
mimalloc: option 'segment_decommit_delay': 500
mimalloc: option 'decommit_extend_delay': 1
mimalloc: option 'destroy_on_exit': 0
mimalloc: process init: 0x7eff243df740
mimalloc: secure level: 0
mimalloc: mem tracking: none
mimalloc: using 1 numa regions
mimalloc: option 'show_errors': 0
mimalloc: option 'show_stats': 0
mimalloc: option 'eager_commit': 1
mimalloc: option 'deprecated_eager_region_commit': 0
mimalloc: option 'deprecated_reset_decommits': 0
mimalloc: option 'large_os_pages': 0
mimalloc: option 'reserve_huge_os_pages': 0
mimalloc: option 'reserve_huge_os_pages_at': -1
mimalloc: option 'reserve_os_memory': 0
mimalloc: option 'deprecated_segment_cache': 0
mimalloc: option 'page_reset': 0
mimalloc: option 'abandoned_page_decommit': 0
mimalloc: option 'deprecated_segment_reset': 0
mimalloc: option 'eager_commit_delay': 1
mimalloc: option 'decommit_delay': 25
mimalloc: option 'use_numa_nodes': 0
mimalloc: option 'limit_os_alloc': 0
mimalloc: option 'os_tag': 100
mimalloc: option 'max_errors': 16
mimalloc: option 'max_warnings': 16
mimalloc: option 'max_segment_reclaim': 8
mimalloc: option 'allow_decommit': 1
mimalloc: option 'segment_decommit_delay': 500
mimalloc: option 'decommit_extend_delay': 2
mimalloc: process init: 0x7eff243df740
mimalloc: secure level: 0
```

For the rest of the questions, does running certain polars workflows repeatedly increase overall memory usage on Windows? or does it plateau?

For example, the following, keeps stable at 212M ram no matter the amount of loops with Polars on Linu with mimalloc:
```python
In [15]: for i in range(500):
    ...:     df = pl.scan_csv('data/data_*.csv').collect()
    ...:     del df
    ...: 
``

**Comment by csko** [comment]
> @csko Could you try with some mimalloc environment variables, before running Polars?
> 
> ```
> MIMALLOC_PAGE_RESET=1
> MIMALLOC_RESET_DECOMMITS=1
> MIMALLOC_RESET_DELAY=1
> 
> # Or:
> MIMALLOC_PAGE_RESET=1
> MIMALLOC_RESET_DECOMMITS=1
> MIMALLOC_RESET_DELAY=0
> ```

Both of these had no impact on polars==0.15.16 on Windows. Memory usage keeps growing with each run of the for-loop code snippet.

f.py:
```
import polars as pl

def f():
    for i in range(5):
        df = pl.scan_csv('data/data_*.csv').collect()
        del df
```

Default mimalloc on my computer:
```
ipython
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.10.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from f import f as fn
mimalloc: option 'show_errors': 0
mimalloc: option 'show_stats': 0
mimalloc: option 'verbose': 1
mimalloc: option 'eager_commit': 1
mimalloc: option 'deprecated_eager_region_commit': 0
mimalloc: option 'deprecated_reset_decommits': 0
mimalloc: option 'large_os_pages': 0
mimalloc: option 'reserve_huge_os_pages': 0
mimalloc: option 'reserve_huge_os_pages_at': -1
mimalloc: option 'reserve_os_memory': 0
mimalloc: option 'deprecated_segment_cache': 0
mimalloc: option 'page_reset': 0
mimalloc: option 'abandoned_page_decommit': 0
mimalloc: option 'deprecated_segment_reset': 0
mimalloc: option 'eager_commit_delay': 4
mimalloc: option 'decommit_delay': 25
mimalloc: option 'use_numa_nodes': 0
mimalloc: option 'limit_os_alloc': 0
mimalloc: option 'os_tag': 100
mimalloc: option 'max_errors': 16
mimalloc: option 'max_warnings': 16
mimalloc: option 'max_segment_reclaim': 8
mimalloc: option 'allow_decommit': 1
mimalloc: option 'segment_decommit_delay': 500
mimalloc: option 'decommit_extend_delay': 1
mimalloc: option 'destroy_on_exit': 0
mimalloc: process init: 0x888ccc0000
mimalloc: secure level: 0
mimalloc: mem tracking: none
mimalloc: using 1 numa regions

In [2]: fn()

In [3]: fn()

In [4]: fn()

In [5]:                                                                                                                                                                                                                                                                                                   
Do you really want to exit ([y]/n)? y
heap stats:    peak      total      freed    current       unit      count   
  reserved:  234.8 GiB  234.8 GiB      0      234.8 GiB
 committed:   14.7 GiB   22.4 GiB    7.6 GiB   14.7 GiB
     reset:      0          0          0          0                            ok
   touched:  468.8 MiB  468.8 MiB  696.1 MiB -227.3 MiB                        ok
  segments:    7.3 Ki     7.3 Ki     7.3 Ki       1                            not all freed!
-abandoned:    7.3 Ki     7.3 Ki       0        7.3 Ki                         not all freed!
   -cached:      0          0          0          0                            ok
     pages:      0          0       66.8 Ki   -66.8 Ki                         ok
-abandoned:   66.1 Ki    66.1 Ki       0       66.1 Ki                         not all freed!
 -extended:      0
 -noretire:      0
     mmaps:      0
   commits:   22.1 Ki
   threads:    7.3 Ki    14.7 Ki     7.3 Ki     7.3 Ki                         not all freed!
  searches:     0.0 avg
numa nodes:       1
   elapsed:       8.647 s
   process: user: 2.109 s, system: 2.296 s, faults: 638113, rss: 1.9 GiB, commit: 14.8 GiB
mimalloc: process done: 0x888ccc0000
```

Looks like the `eager_commit_delay` option is different (4 vs. 1).

**Comment by zundertj** [comment]
All done on master:

```
venv_py310) C:\Users\jeroen\projects\polars>set MIMALLOC_VERBOSE=1

(venv_py310) C:\Users\jeroen\projects\polars>set MIMALLOC_VERBOSE
MIMALLOC_VERBOSE=1

(venv_py310) C:\Users\jeroen\projects\polars>python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl
mimalloc: option 'show_errors': 0
mimalloc: option 'show_stats': 0
mimalloc: option 'eager_commit': 1
mimalloc: option 'deprecated_eager_region_commit': 0
mimalloc: option 'deprecated_reset_decommits': 0
mimalloc: option 'large_os_pages': 0
mimalloc: option 'reserve_huge_os_pages': 0
mimalloc: option 'reserve_huge_os_pages_at': -1
mimalloc: option 'reserve_os_memory': 0
mimalloc: option 'deprecated_segment_cache': 0
mimalloc: option 'page_reset': 0
mimalloc: option 'abandoned_page_decommit': 0
mimalloc: option 'deprecated_segment_reset': 0
mimalloc: option 'eager_commit_delay': 4
mimalloc: option 'decommit_delay': 25
mimalloc: option 'use_numa_nodes': 0
mimalloc: option 'limit_os_alloc': 0
mimalloc: option 'os_tag': 100
mimalloc: option 'max_errors': 16
mimalloc: option 'max_warnings': 16
mimalloc: option 'max_segment_reclaim': 8
mimalloc: option 'allow_decommit': 1
mimalloc: option 'segment_decommit_delay': 500
mimalloc: option 'decommit_extend_delay': 2
mimalloc: process init: 0x6fe75ae000
mimalloc: secure level: 0
mimalloc: using 1 numa regions
```

The code runs for approximately 30 seconds, but does not inflate memory in any way, wasn't noticeable this snippet.

**Comment by ghuls** [comment]
@csko Could you at least try the lastest version of Polars instead of  polars 0.15.16 and repeat the test?

**Comment by csko** [comment]
The latest polars version reproduces the problem too. Polars compiled with mimalloc does not have the issue on my end.

That said, I don't think the build conditions are set up properly, jemalloc did not work for me. The PR needs more work, including more experimentation with settings. I'm closing it for now as I won't be addressing it for a while so anyone should feel free to pick it up from here.

**Pull request closed without merging**
