### PR TITLE
Fixes indexing error if a single row is selected, e.g. df[1]

### PR DESCRIPTION
**Pull request by FlorianWilhelm**
This fixes the problem described in #686.

@ritchie46: This PR just fixes the bug. If you agree I would like to refactor `__getitem__` a bit to avoid errors like that in the future.

I also added `setup.py` to allow easier development of the Python part using editable installs and a pre-commit configuration making it easier to have a common programming style.

### CODE REVIEW

**Comment by ritchie46** [comment]
There are a lot of files changed not really related to this fix.

Could you redo your commit with the changes to the needed logic? 

The `setup.py` doesn't really make sense in this context as we use maturin to compile. I believe that a `pip install -e .` does not compile the rust binary. 

The maturin command for `pip install -e .` is `maturin develop`

And if you want to quickly test. `./tasks.sh test`

The pipeline is also failing due to formatting issues. [Those can be resolved with black](https://github.com/pola-rs/polars/blob/master/CONTRIBUTING.md)

**Comment by FlorianWilhelm** [comment]
@ritchie46, okay, I will separate the PRs. Didn't know about `maturin develop`, good to now. Should this be added to the docs?

If you want I could provide the following PRs:

* proper `pre-commit` config to make the coding style a bit more consistent. It seems that currently there is also a mix of different line break characters.
* refactor `__getitem__` as I believe that the code is currently a bit hard to read.

**Comment by ritchie46** [comment]
I don't use pre-commit and dont want config that are out of sync with the CI workflows. For code formatting we use black.

Also isort is not used. We could try adding that in another PR, but then it should also be added in CI.

Can we add the indexing logic in this PR. And pherhaps make a refactor proposal in another one?

**Comment by FlorianWilhelm** [comment]
I am not completely happy with this PR as I had to introduce a method `_pos_idx` that converts negative indices to the corresponding positive indices. I guess that should better be done in Rust as `PySeries.take` and `PyDataFrame.slice`.

Also, I realized that `select_at_idx` is quite verbose and why can't it handle lists of integers directly, i.e. `select_at_idx([1,2])`? Couldn't it be integrated with `select(self, exprs: "Union[str, Expr, List[str], List[Expr]]")` the same way we do it now with `__getitem__`?

**Comment by ritchie46** [comment]
> I am not completely happy with this PR as I had to introduce a method _pos_idx that converts negative indices to the corresponding positive indices. I guess that should better be done in Rust within PySeries.take and PyDataFrame.slice.

Negative indexing is not allowed in the `take` kernels. This would have quite a significant overhead. In the `slice` implementation this is allowed, but there it isn't expensive.

For now I think it is fine that this is done in python as it mostly will be used in row selection I imagine? 

Thanks for the PR. It looks good! :+1: 


> Also, I realized that select_at_idx is quite verbose and why can't it handle lists of integers directly, i.e. select_at_idx([1,2])? Couldn't it be integrated with select(self, exprs: "Union[str, Expr, List[str], List[Expr]]") anyway the same way we do 

Yes, maybe it is better to mark `select_at_idx` private.

**Comment by FlorianWilhelm** [comment]
Thanks @ritchie46, would you also be open for a PR that extends `select(self, exprs: "Union[str, Expr, List[str], List[Expr]]"` to support `int` and `List[int]`, making `_select_at_idx` privat? Don't know when I would find the time but I would love to support as I see the unique selling point of Polars in having a consistent interface.

BTW, I gave a little talk about Polars at @inovex and already got feedback from Spark developers that they would be eager to try in order to replace some Pandas transformations.

**Comment by ritchie46** [comment]
> BTW, I gave a little talk about Polars at @inovex and already got feedback from Spark developers that they would be eager to try in order to replace some Pandas transformations.

Really, That sounds great! So it was well received?

**Comment by FlorianWilhelm** [comment]
Yeah, even pretty well received I would say :-)

**Pull request merged**
