### PR TITLE
chore(rust): Minor makeover for Rust Makefile

### PR DESCRIPTION
**Pull request by stinodego**
The Makefile contains mostly `cargo` commands, and it makes most sense to run these from the workspace root. In this case, that's the repo root. That way we can include the crates in examples and `polars-cli` in `clippy` runs, for example (this already happens in the CI). Commands that should target the `polars` crate only can specifiy `-p polars`.

Changes:
* ~Move Makefile to repo root~
* Re-order commands a bit
* Add help text
* ~Slight modifications so that commands will work from repo root~

### CODE REVIEW

**Comment by ritchie46** [comment]
> and it makes most sense to run these from the workspace root. 

Does it? I saw them as the test commands for the polars-rust crate. Similar to `py-polars` having the makefile in its own folder.

**Comment by stinodego** [comment]
The way I see it, the Cargo workspace is a collection of crates that depend on each other. If you make changes in the polars crate, you may break the examples or the polars-cli. So these should be tested together.

This is already done in the CI, to a certain extent. So running `make pre-commit` in the polars directory gives you no guarantees that the CI will pass.

But if you prefer to have the Makefile in the polars directly, we can leave it there! Then I will revert some of these changes and only keep the minor improvements like the help text.

**Comment by ritchie46** [comment]
Yes, but I think we should have different makefiles then. `polars-cli`, or `polars-sql`, or `py-polars` are a whole different entity, that use the `polars` crate. They all have their own makefiles with logic unique to them.

There can be an overarching Makefile (we had before).

**Comment by stinodego** [comment]
All right, sure thing. I'll redo this one.

**Comment by stinodego** [comment]
I'll just merge this as there's nothing interesting going on here - just reorder & add help text.

**Pull request merged**
