### PR TITLE
fix: re-allow for creation of long date range. This reverts the "fix: Fix behavior of month intervals in `date_range`" - if you want a date range with the last date of each month, just use `.dt.month_end()`

### PR DESCRIPTION
**Pull request by MarcoGorelli**
Reverts pola-rs/polars#12317

closes https://github.com/pola-rs/polars/issues/12461

### CODE REVIEW

**Comment by stinodego** [comment]
I'm not sure about this. The new implementation caused some issues, but it also solved some. Shouldn't we revisit the implementation rather than simply reverting?

**Comment by MarcoGorelli** [comment]
I'm not really sure how much it resolves though - consider:
```python
In [15]: pl.date_range(date(2020, 1, 31), date(2020, 5, 31), '1mo', eager=True)
Out[15]:
shape: (5,)
Series: 'date' [date]
[
        2020-01-31
        2020-02-29
        2020-03-31
        2020-04-30
        2020-05-31
]
```
A user might try this and think "oh great, it preserves the last-day-of-the-monthness! Let's try":
```python
In [16]: pl.date_range(date(2020, 2, 29), date(2020, 5, 31), '1mo', eager=True)
Out[16]:
shape: (4,)
Series: 'date' [date]
[
        2020-02-29
        2020-03-29
        2020-04-29
        2020-05-29
]
```
"oh, wait"

Teaching `.dt.month_end()` right away might cause less issues in the long-run

Will think about this a bit longer anyway

**Comment by stinodego** [comment]
I would say that is expected behavior and not all that confusing. But of course, feel free to give it some thought.

I wonder though what is really causing the new implementation to fail on the linked issue 🤔

**Comment by MarcoGorelli** [comment]
instead of doing
```python
t = starting_point; points.append(t)
t = t + offset;  points.append(t)
...
t = t + offset;  points.append(t)
```
it's doing
```python
t = starting_point; points.append(t)
t = starting_point + offset;  points.append(t)
t = starting_point + 2*offset;  points.append(t)
...
t = starting_point + n*offset;  points.append(t)
```
and `n*offset` may overflow

should be fixable, just wondering what's really the best UX - will try some things out, let's see

**Comment by MarcoGorelli** [comment]
https://github.com/pola-rs/polars/pull/12479 is simple enough actually - if you prefer this behaviour, let's keep it then, thanks for having pushed me towards a better soln here :pray:

**Pull request closed without merging**
