### PR TITLE
docs[python]: Fix some docstring formatting

### PR DESCRIPTION
**Pull request by stinodego**
I want to enable the `pydocstyle` D400 and D205 lints. Together, these make sure every docstring starts with a single line summary (as [prescribed](https://numpydoc.readthedocs.io/en/latest/format.html#short-summary) by the NumPy docstring conventions). This is great for users to get a quick idea of what a method does, before diving into the details.

There's a whole bunch of docstrings to be fixed, so I'll do it in stages. Here's part 1 😄

### CODE REVIEW

**Comment by ritchie46** [comment]
I also got a lint that my `declarative` description should be `imperative`. E.g.:

`Returns a sum` should be `Return a sum`. I think we should invert that. Our API is more declarative and I think that style fits better. E.g. it returns a sum, once it runs. When it will run is often not determined yet. What do you think?

**Comment by ritchie46** [comment]
> > I also got a lint that my `declarative` description should be `imperative`. E.g.:
> > `Returns a sum` should be `Return a sum`. I think we should invert that. Our API is more declarative and I think that style fits better. E.g. it returns a sum, once it runs. When it will run is often not determined yet. What do you think?
> 
> The 'imperative' thing comes from [PEP257](https://peps.python.org/pep-0257/#one-line-docstrings): _"The docstring is a phrase ending in a period. It prescribes the function or method’s effect as a command (“Do this”, “Return that”), not as a description; e.g. don’t write “Returns the pathname …”."_
> 
> You can find a bunch of discussions online on the why / why not. Personally, I think the imperative mood makes sense. The function name is also imperative ("sum", "replace", "describe"), the one-line summary is an extension of that.
> 
> I don't care too much either way, I just conform to the standard. If the lint bothers you, we can turn it off (D401). There is no 'inverse' lint to enforce declarative mood, so then we'll get a mix.
> 
> For what it's worth, `pyspark` docs seem to be mostly declarative, while `pandas` docs seem to be mostly imperative.

Yes, the both have their docs style extended to thwir API. I think we should be declarative then. Thanks for the explanation.

**Comment by stinodego** [comment]
> The 'imperative' thing comes from [PEP257](https://peps.python.org/pep-0257/#one-line-docstrings): _"The docstring is a phrase ending in a period. It prescribes the function or method’s effect as a command (“Do this”, “Return that”), not as a description; e.g. don’t write “Returns the pathname …”."_

All right, I'll disable the lint and we can transition to declarative over time!

**Comment by ritchie46** [comment]
> > The 'imperative' thing comes from [PEP257](https://peps.python.org/pep-0257/#one-line-docstrings): _"The docstring is a phrase ending in a period. It prescribes the function or method’s effect as a command (“Do this”, “Return that”), not as a description; e.g. don’t write “Returns the pathname …”."_
> 
> All right, I'll disable the lint and we can transition to declarative over time!

<3

**Pull request merged**
