### PR TITLE
feat(rust, python)!: make date_range/time_range output shape consistent, add date_ranges/time_ranges

### PR DESCRIPTION
**Pull request by MarcoGorelli**
#9019 (addresses half of it)

This is a pretty noticeable breaking change, so it should probably wait til 1.0?

### CODE REVIEW

**Comment by stinodego** [comment]
I'm almost done with the other half 😄

**Comment by stinodego** [comment]
> This is a pretty noticeable breaking change, so it should probably wait til 1.0?

We should first merge a non-breaking PR that does the following:
* Add `date_ranges` / `time_ranges`, with the intended functionality.
* Add a deprecation warning when using `date_range`/`time_range` with `eager=False` -> use `date_ranges` instead.

**Comment by stinodego** [comment]
> We should first merge a non-breaking PR that does the following:

@MarcoGorelli do you want to pick this up, or should I make a PR?

**Comment by MarcoGorelli** [comment]
hey @stinodego thanks for asking - gonna be a bit busy today and in the upcoming week, so feel free to take over, thanks 🙏

**Comment by MarcoGorelli** [comment]
superseded by https://github.com/pola-rs/polars/pull/10005

**Pull request closed without merging**
