### PR TITLE
perf(rust): Improve performance of `cot` (cotangent)

### PR DESCRIPTION
**Pull request by svaningelgem**
During the adjustments of the docs, I noticed that `cot` was implemented as `cos/sin`.
But actually cotangent is just the inverse of tangent. So I was wondering what the effect would be of taking the tangent and inverse it.

Here are the results against the "build-opt" binary on wsl:
_original:_ Time taken to execute 1000000x the collect: 11.39s
_new:_ Time taken to execute 1000000x the collect: 11.10s

I was wondering why I couldn't do `1.0 / tan(v)`... As that might even be faster than what I made here.
And I know it's not much gain, but any gain is good right? 😁

**test script**
```python
import timeit

import polars as pl

df = pl.DataFrame(
    {
        "a": [-4, -3, -2, -1.00001, 0, 1.00001, 2, 3, 4],
    }
)

ctx = pl.SQLContext(df=df, eager_execution=False)
res = ctx.execute(
    """
    SELECT
    cot(a) AS "cot",
    FROM df
    """,
    eager=False,
)

print(ctx.execute('SELECT cot(a) as "cot", cos(a) / sin(a) as "cot_original" from df').collect())

print(f'Time taken to execute {timeit.default_number}x the collect: {timeit.timeit("res.collect()", globals=globals()):.2f}s')
```

### CODE REVIEW

**Comment by stinodego** [comment]
You may be able to see a bigger performance difference if you throw in some real data, e.g. randomly generate 1.000.000 floats or so and run it on that.

**Comment by svaningelgem** [comment]
> randomly generate 1.000.000 floats
Thanks for the tip!

New test script:
```python
import timeit

import numpy as np
import polars as pl

df = pl.DataFrame({"a": np.deg2rad(np.random.randn(1_000_000))})

ctx = pl.SQLContext(df=df, eager_execution=False)
res = ctx.execute("SELECT cot(a) FROM df", eager=False)

print(ctx.execute('SELECT cot(a) as "cot", cos(a) / sin(a) as "cot_original" from df').collect())

nr = 5_000
print(f'Time taken to execute {nr}x the collect: {timeit.timeit("res.collect()", number=nr, globals=globals()):.2f}s')
```

`Ok(ca.apply_values(|v| v.cos() / v.sin()).into_series())` **\[old way]**
> Time taken to execute 5000x the collect: 48.53s

`Ok(ca.apply_values(|v| v.tan().powi(-1)).into_series())` **\[pr way]**
> Time taken to execute 5000x the collect: 21.47s

It seems because of the small test sample I used initially, that I was mostly timing the setup of the test, and not the actual change in the code. Thanks for pointing that out!
Is there

**Comment by stinodego** [comment]
My benchmark (ran using a release build) shows a small difference, but still noticable (12.4ms per loop now vs. 13.9ms old implementation).

I'll take it!

**Review by stinodego — APPROVED** [review]

**Comment by stinodego** [comment]
We should also make this available on the Python side.

**Comment by svaningelgem** [comment]
A very quick and dirty check on `hasattr(df["a"], ...)` showed me that these methods are not available on the series on the python side:
- acos
- acosd
- array_contains
- array_get
- array_length
- array_lower
- array_mean
- array_reverse
- array_sum
- array_unique
- array_upper
- asin
- asind
- atan
- atan2
- atan2d
- atand
- avg
- ceiling
- coalesce
- cosd
- cot
- cotd
- count
- degrees
- first
- last
- length
- ln
- log2
- lower
- ltrim
- nullif
- octet_length
- pi
- power
- radians
- rtrim
- sind
- stddev
- tand
- tand
- unnest
- upper
- variance

A few of them have other names I guess like lower/upper is `.str.to_lowercase()`. But I see a lot of additional trigonometry methods there. You want me to add them to the python side? (other PR)
[Additionally: I see 2x tan & tand in here](https://github.com/pola-rs/polars/blob/5894b7d2b8f950dcad4bd5319b80480c2490c716/crates/polars-sql/src/functions.rs#L507)

**Comment by svaningelgem** [comment]
> We should also make this available on the Python side.

There you go :-)

**Review by ritchie46 — APPROVED** [review]

**Pull request merged**
