### PR TITLE
fix(python): Add missing join strategy.

### PR DESCRIPTION
**Pull request by haim0n**

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks! Do we need to add that at the `LazyFrame` docstring as well?

**Comment by haim0n** [comment]
> Thanks! Do we need to add that at the `LazyFrame` docstring as well?

Yeah, sorry for missing it. I'll add + I think that `'outer'` is just an alias for `full` . WDYT ?

**Comment by alexander-beedie** [comment]
We have actively deprecated "outer" - I dont' think we should be putting it back in, as "full" is the correct strategy name.

**Comment by ritchie46** [comment]
Yes, you're right. I missed it. :D 

I think we can close htis.

**Pull request closed without merging**
