### PR TITLE
Arrow2 now supports non-ordered projections in IPC. Fixes #1761.

### LINKED ISSUE #1761: `pl.read_ipc(..., columns=specific_column_order, use_pyarrow=False)` does not preserve the column order .
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

git commit: e8f6b0f98fc850cd74659bd64babb935383e5888

#### What operating system are you using polars on?

CentOS 7

#### Describe your bug.

`pl.read_ipc(..., columns=specific_column_order, use_pyarrow=False)` does not preserve the column order specified by the user (as it is sorted by column indices when passing to arrow2 read IPC function).

#### What are the steps to reproduce the behavior?

```python
In [28: import polars as pl
]
In [29]: df = pl.DataFrame([
    ...:     pl.Series("a", [2, 5]),
    ...:     pl.Series("b", [4, 3]),
    ...:     pl.Series("c", [1, 6]),
    ...:     pl.Series("d", [7, 9]),
    ...: ])

In [30]: df.to_ipc('test.feather')

In [31]: df_read = pl.read_ipc('test.feather', columns=["a", "b", "c", "d"], use_pyarrow=False)

In [32]: df_read_out_of_order = pl.read_ipc('test.feather', columns=["c", "b", "d", "a"], use_pyarrow=False)

In [33]: df
Out[33]: 
shape: (2, 4)
┌─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ d   │
│ --- ┆ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╡
│ 2   ┆ 4   ┆ 1   ┆ 7   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 5   ┆ 3   ┆ 6   ┆ 9   │
└─────┴─────┴─────┴─────┘

In [34]: df_read
Out[34]: 
shape: (2, 4)
┌─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ d   │
│ --- ┆ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╡
│ 2   ┆ 4   ┆ 1   ┆ 7   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 5   ┆ 3   ┆ 6   ┆ 9   │
└─────┴─────┴─────┴─────┘

In [35]: df_read_out_of_order
Out[35]: 
shape: (2, 4)
┌─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ d   │
│ --- ┆ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╡
│ 2   ┆ 4   ┆ 1   ┆ 7   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 5   ┆ 3   ┆ 6   ┆ 9   │
└─────┴─────┴─────┴─────┘

In [36]: df_read_out_of_order_pyarrow = pl.read_ipc('test.feather', columns=["c", "b", "d", "a"], use_pyarrow=True)

In [37]: df_read_out_of_order_pyarrow
Out[37]: 
shape: (2, 4)
┌─────┬─────┬─────┬─────┐
│ c   ┆ b   ┆ d   ┆ a   │
│ --- ┆ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╡
│ 1   ┆ 4   ┆ 7   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┤
│ 6   ┆ 3   ┆ 9   ┆ 5   │
└─────┴─────┴─────┴─────┘

```

### PR DESCRIPTION
**Pull request by ghuls**

### CODE REVIEW

**Comment by ghuls** [comment]
Any Idea why it fails for some parquet related tests? I get the same problem with polars 0.13.31 from PyPi.
```python
In [1]: import polars as pl

In [2]: df_parquet1_lazy = pl.scan_parquet(
   ...:     "/software/polars//examples/datasets/foods1.parquet"
   ...: )

In [3]: df_parquet1_lazy.filter(pl.col("calories") > 0).collect()
Out[3]: 
shape: (0, 4)
┌──────────┬──────────┬────────┬──────────┐
│ category ┆ calories ┆ fats_g ┆ sugars_g │
│ ---      ┆ ---      ┆ ---    ┆ ---      │
│ str      ┆ i64      ┆ f64    ┆ i64      │
╞══════════╪══════════╪════════╪══════════╡
└──────────┴──────────┴────────┴──────────┘

In [4]: df_parquet1_lazy.collect().lazy().filter(pl.col("calories") > 0).collect()
Out[4]: 
shape: (27, 4)
┌────────────┬──────────┬────────┬──────────┐
│ category   ┆ calories ┆ fats_g ┆ sugars_g │
│ ---        ┆ ---      ┆ ---    ┆ ---      │
│ str        ┆ i64      ┆ f64    ┆ i64      │
╞════════════╪══════════╪════════╪══════════╡
│ vegetables ┆ 45       ┆ 0.5    ┆ 2        │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ seafood    ┆ 150      ┆ 5.0    ┆ 0        │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ meat       ┆ 100      ┆ 5.0    ┆ 0        │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ fruit      ┆ 60       ┆ 0.0    ┆ 11       │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...      ┆ ...    ┆ ...      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ fruit      ┆ 130      ┆ 0.0    ┆ 25       │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ meat       ┆ 100      ┆ 7.0    ┆ 0        │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ vegetables ┆ 30       ┆ 0.0    ┆ 5        │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ fruit      ┆ 50       ┆ 0.0    ┆ 11       │
└────────────┴──────────┴────────┴──────────┘

In [5]: pl.__version__
Out[5]: '0.13.31'

```

**Comment by ritchie46** [comment]
That's a bug in statistics reading. I will fix it.

**Comment by ghuls** [comment]
Removing the old `foods1.parquet` file and letting it regenerate, solves the problem. I guess the old file does not have the statistics part.
```
# New file.
-rw-r--r-- 1 ghuls ghuls 1862 Mai 12 11:47 foods1.parquet

# Old file.
-rw-r--r-- 1 ghuls ghuls 1351 Mär  9 15:12 foods1.parquet
```

**Comment by ghuls** [comment]
Here is the file, in case you want to check: [foods1.parquet.zip](https://github.com/pola-rs/polars/files/8677084/foods1.parquet.zip)

**Comment by ghuls** [comment]
Why does it crash on: `SINGLE_LOCK.lock().unwrap();`
```
failures:

---- tests::optimization_checks::test_simple_slice stdout ----
thread 'tests::optimization_checks::test_simple_slice' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', polars/polars-lazy/src/tests/optimization_checks.rs:147:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/core/src/result.rs:1078:23
   4: polars_lazy::tests::optimization_checks::test_simple_slice
             at ./src/tests/optimization_checks.rs:147:18
   5: polars_lazy::tests::optimization_checks::test_simple_slice::{{closure}}
             at ./src/tests/optimization_checks.rs:146:1
   6: core::ops::function::FnOnce::call_once
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Is is also intended that for actual code the lock is never checked `SINGLE_LOCK.lock()`, while in tests it is unwrapped?
```
❯ rg SINGLE_LOCK
polars-core/src/frame/hash_join/mod.rs
1170:        let _lock = crate::SINGLE_LOCK.lock();

polars-core/src/lib.rs
115:pub static SINGLE_LOCK: Lazy<Mutex<()>> = Lazy::new(|| Mutex::new(()));

polars-core/src/chunked_array/logical/categorical/mod.rs
200:    use crate::{reset_string_cache, toggle_string_cache, SINGLE_LOCK};
205:        let _lock = SINGLE_LOCK.lock();
230:        let _lock = SINGLE_LOCK.lock();
249:        let _lock = SINGLE_LOCK.lock();
264:        let _lock = SINGLE_LOCK.lock();

polars-core/src/chunked_array/logical/categorical/merge.rs
82:        let _lock = SINGLE_LOCK.lock();

polars-core/src/chunked_array/logical/categorical/builder.rs
213:    use crate::{reset_string_cache, toggle_string_cache, SINGLE_LOCK};
217:        let _lock = SINGLE_LOCK.lock();
258:        let _lock = crate::SINGLE_LOCK.lock();

polars-core/src/chunked_array/ops/sort/categorical.rs
116:    use crate::{toggle_string_cache, SINGLE_LOCK};
128:        let _lock = SINGLE_LOCK.lock();
156:        let _lock = SINGLE_LOCK.lock();

polars-core/src/chunked_array/mod.rs
794:        use crate::SINGLE_LOCK;
795:        let _lock = SINGLE_LOCK.lock();

polars-lazy/src/tests/optimization_checks.rs
147:    let _guard = SINGLE_LOCK.lock().unwrap();
166:    let _guard = SINGLE_LOCK.lock().unwrap();
194:    let _guard = SINGLE_LOCK.lock().unwrap();
223:    let _guard = SINGLE_LOCK.lock().unwrap();

polars-lazy/src/tests/io.rs
6:    let _guard = SINGLE_LOCK.lock().unwrap();
37:    let _guard = SINGLE_LOCK.lock().unwrap();
78:    let _guard = SINGLE_LOCK.lock().unwrap();
149:    let _guard = SINGLE_LOCK.lock().unwrap();
244:    let _guard = SINGLE_LOCK.lock().unwrap();
253:    let _guard = SINGLE_LOCK.lock().unwrap();
278:    let _guard = SINGLE_LOCK.lock().unwrap();
337:    let _guard = SINGLE_LOCK.lock().unwrap();
```

**Comment by ritchie46** [comment]
Yes, I'll have to look into that.

**Comment by ritchie46** [comment]
superseded by #3591

**Pull request closed without merging**
