### PR TITLE
feat(rust): Support `duration + date`

### PR DESCRIPTION
**Pull request by billylanchantin**
## Description

Closes: https://github.com/pola-rs/polars/issues/11034

This PR adds support for `duration + date`. Supporting that operation will bring the Rust API more in line with the Python API, which already supports it.

## Changes

* Support `duration + date`
* Tests

### CODE REVIEW

**Comment by ritchie46** [comment]
>  Python API, which already supports it.

I don't understand. How can the python API already support it in this case? Shouldn't we go to both code branches for both apis?

**Comment by billylanchantin** [comment]
@alexander-beedie posted an example in the issue:

https://github.com/pola-rs/polars/issues/11034#issuecomment-1712957936

TBH I was surprised that the Python side already supported it. I think what's happening is that `PySeries` ends up calling `try_add` instead of just `add`. And `try_add` seems to coerce the arguments.

I _think_ the relevant code is here (but I had a little trouble confirming it):

https://github.com/pola-rs/polars/blob/main/crates/polars-core/src/series/arithmetic/borrowed.rs#L340-L347

**Comment by alexander-beedie** [comment]
Yup; the underlying PySeries `add` is called from the Python side (via `_arithmetic`), and that then kicks out to `try_add`.

On the Rust side we have precedence from `chrono` not liking "duration + date", but on the Python side the standard library is completely fine with "timedelta + date", _and_ we seem to have (probably inadvertently!) allowed it via the Python Series for some time so it might be a bit harsh to take it away ;)

I'm not going to declare which one is "best", but it would be good to align both sides of the API, and the weight of things appears to support allowing it ;)

**Comment by billylanchantin** [comment]
Also, there was already support for `duration + datetime` on the Rust side despite chrono not being a fan.

**Comment by ritchie46** [comment]
Alright, thanks for the clarification. :+1:

**Pull request merged**
