### PR TITLE
build(python): only require `typing_extensions` before Python 3.8

### PR DESCRIPTION
**Pull request by MarcoGorelli**
Another attempt at https://github.com/pola-rs/polars/pull/8610, hope it's OK to reopen

I've added `typing-extensions` to requirements-lint.txt, so anyone doing development will get the install and be able to run `mypy` and type-check their code

Why make this change:
- fewer dependencies => easier installation && less chance of "dependency hell"

Example of installation issues already happening: https://github.com/pola-rs/polars/issues/2260

Python3.7 will be dropped in a month, so this would mean that polars would literally have no required dependencies

### CODE REVIEW

**Comment by stinodego** [comment]
This is really not a good idea.

Imagine you're starting a new project. You're using Python 3.10. Install Polars. Write some code. Run mypy to check -> ERROR. Not everyone will know to install the `typing_extensions` module.

And there really is no chance of 'dependency hell'. It's an 'official' Python extension, even mentioned in the [official docs](https://docs.python.org/3/library/typing.html):

> New features are frequently added to the typing module. The [typing_extensions](https://pypi.org/project/typing-extensions/) package provides backports of these new features to older versions of Python.

**Comment by MarcoGorelli** [comment]
> Run mypy to check -> ERROR. Not everyone will know to install the typing_extensions module.

For users rather than developers? Not sure this would be an issue - pandas nor pandas-stubs have `typing-extensions` as dependencies, but type checking for users works fine

I'll check this now with a toy project

**Comment by stinodego** [comment]
I also checked. It looks like `mypy` also depends on `typing_extensions` so that kind of solves it.

**Review by stinodego — APPROVED** [review]
I was a bit too quick to dismiss this idea, thanks @MarcoGorelli !

**Comment by MarcoGorelli** [comment]
> So that means this is actually a good idea 😄

😄 thanks for reconsidering

it's true that it's an official python package, but for some reason people do run into installation issues with it
- https://github.com/pola-rs/polars/issues/5250
- https://github.com/pola-rs/polars/issues/2260
- https://github.com/pola-rs/polars/issues/2185
(plus lots of similar ones in other projects)

No strong feelings on this one anyway, happy to let this one drop, thanks for your feedback!

**Comment by stinodego** [comment]
Those issues don't really have anything to do with installing `typing_extensions` during runtime, though. Now that most of the stuff is in `TYPE_CHECKING` blocks, there really isn't much that can go wrong.

Anyway, I think this is a good change. I don't expect any issues. Maybe there's that odd person running an older version of `mypy` with `typing_extensions<4.0.0` that now runs into some trouble during development. We'll see!

**Pull request merged**
