### PR TITLE
feat!: change outer join schema

### PR DESCRIPTION
**Pull request by ritchie46**

### CODE REVIEW

**Comment by yusufshalaby** [comment]
Thanks. FYI this breaking change was not listed in the release info and took me an hour to track.

**Comment by MarcoGorelli** [comment]
@yusufshalaby it's listed here:

image


and also is the first item appearing in the upgrade guide: https://pola-rs.github.io/polars/releases/upgrade/0.20/

Perhaps you're looking at the wrong release notes?

**Comment by yusufshalaby** [comment]
Sorry! I didn't see the upgrade guide and I missed that point in the release notes. Thanks for clarifying

**Comment by eJamie98** [comment]
echoing the comments from #9335 , should this also be implemented for other join types? I've been tripped up a few times by left joins deleting my rh join column

**Comment by ritchie46** [comment]
Will add add an option for left joins later

**Pull request merged**
