### PR TITLE
chore(rust): make hive mod public

### PR DESCRIPTION
**Pull request by ion-elgreco**
I want to construct the hive partitions myself using the polars delta stats but the mod is not public at the moment.

### CODE REVIEW

**Comment by ritchie46** [comment]
The hive partitioning is still heavy under construction. I am not really excited about making this public. What do you need to access?

**Comment by ion-elgreco** [comment]
@ritchie46 I need access to the hive_partitions struct because I have the file and column stats available through the delta log, instead of reading each parquet metadata individually

**Comment by ritchie46** [comment]
Ah, totally forgot about this one. Did you find a solution, or should we make it public and mark as unstable?

**Comment by ion-elgreco** [comment]
@ritchie46 nope, but I also stopped working on a native delta lake reader until the polars parquet reader becomes more usable for those usecases

**Pull request closed without merging**
