### PR TITLE
More expr docstrings

### PR DESCRIPTION
**Pull request by braaannigan**

### CODE REVIEW

**Comment by braaannigan** [comment]
@ritchie46 I'm getting errors about building with arrow2 after I do
```bash
make clean
make venv
<Many lines of output>
error: could not compile `arrow2` due to 89 previous errors
```
Has anything changed in terms of how I build the library locally?

**Comment by ritchie46** [comment]
> @ritchie46 I'm getting errors about building with arrow2 after I do
> 
> ```shell
> make clean
> make venv
> <Many lines of output>
> error: could not compile `arrow2` due to 89 previous errors
> ```
> 
> Has anything changed in terms of how I build the library locally? PS I'm on Mac OS if that affects things The error messages are generally SIMD related like:
> 
> ```
>  no method named `simd_max` found for struct `std::simd::Simd` in the current scope
> ```

You must use a nightly compiler.

**Comment by stinodego** [comment]
> > You must use a nightly compiler.
> 
> I've looked through the various makefiles etc, but I don't see how do I do that - any guidance welcome!

Try following these steps that are hidden all the way down at the bottom of the Contributing guide:
https://github.com/pola-rs/polars/blob/master/CONTRIBUTING.md#python-setup

**Comment by braaannigan** [comment]
So I already had the nightly build. The issue seemed to be just updating Rust from 1.63 to 1.65 with `rustup`

**Comment by braaannigan** [comment]
Almost there after rebasing, but doctest is failing on files I haven't changed. I've only modified the expression files so not sure why I'm getting this:
```

======================================================================
FAIL: write_csv (polars.internals.dataframe.frame.DataFrame)
Doctest: polars.internals.dataframe.frame.DataFrame.write_csv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<path>/lib/python3.8/doctest.py", line 2204, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for polars.internals.dataframe.frame.DataFrame.write_csv
  File "<path>/py-polars/polars/internals/dataframe/frame.py", line 1068, in write_csv

----------------------------------------------------------------------
File "<path>/polars/py-polars/polars/internals/dataframe/frame.py", line 1109, in polars.internals.dataframe.frame.DataFrame.write_csv
Failed example:
    df.write_csv(path, sep=",")
Exception raised:
    Traceback (most recent call last):
      File "<path>/envs/base38/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest polars.internals.dataframe.frame.DataFrame.write_csv[3]>", line 1, in <module>
        df.write_csv(path, sep=",")
      File "<path>/playModels/polars/py-polars/polars/internals/dataframe/frame.py", line 1133, in write_csv
        self._df.write_csv(
    TypeError: PyDataFrame.write_csv() takes 5 positional arguments but 8 were given
```

**Comment by braaannigan** [comment]
> Almost there after rebasing, but doctest is failing on files I haven't changed. I've only modified the expression files so not sure why I'm getting this:

I'd like to run this through CI to check that it isn't just a problem with my local install

**Comment by ritchie46** [comment]
Thanks a lot! That are many more examples! :100:

**Pull request merged**
