### PR TITLE
Removing make build cmd from readme

### LINKED ISSUE #15655: build python wheel faild: No rule to make target `build'
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
1. download src code from pypi: https://files.pythonhosted.org/packages/46/be/0450264d087e43ccbd72732054e8a79da6a247b3e5ad034fc4ae5ecf979e/polars-0.20.20.tar.gz
2. unpack and follow https://github.com/pola-rs/polars?tab=readme-ov-file#python-compile-polars-from-source
```

### Log output

```shell
Downloads/polars-0.20.20/py-polars [📦 v0.20.20][🦀 v1.79.0-nightly]
❯ cargo version
cargo 1.79.0-nightly (499a61ce7 2024-03-26)

Downloads/polars-0.20.20/py-polars [📦 v0.20.20][🦀 v1.79.0-nightly]
❯ make build
make[1]: *** No rule to make target `build'.  Stop.
make: *** [build] Error 2
```

### Issue description

I has run "make buid" on Macos14, and within docker container, all has failed.   

Maybe something I lost?

### Expected behavior

make build should work fine.

### Installed versions

<details>

```
polars-0.20.20 from pypi and 0.39.0 release from github
```

</details>

### PR DESCRIPTION
**Pull request by andristarr**
Removed make build cmd from readme

Fixes #15655

### CODE REVIEW

**Comment by stinodego** [comment]
Why?

**Comment by andristarr** [comment]
Sorry, this is addressing the following issue #15655

**Comment by stinodego** [comment]
Ah I see, thanks for linking the issue. I think this section indeed needs to be updated, but different changes are needed.

**Comment by stinodego** [comment]
Thanks for the PR, but I'll close this as this is not the way to go. See the linked issue for how to approach this. Unfortunately it's not a great first issue.

**Pull request closed without merging**
