### PR TITLE
Extended docs for .replace() and .replace_all()

### PR DESCRIPTION
**Pull request by DrMaphuse**
- Added respective `See Also` cross-references to .replace() and .replace_all()
- Added examples to .replace_all()

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks @DrMaphuse 

Can you run a `make pre-commit`? That should solve the CI issues.

**Comment by DrMaphuse** [comment]
Thanks for the tip @ritchie46 
I am restricted to making commits on the web, where I can't run cli commands.
However, I saw in the details that the failed check is related to formatting. I blackened the modifications, which should allow them to pass.

**Comment by DrMaphuse** [comment]
@ritchie46 
I see that the checks failed again. 
Sorry for the hassle - I will need some time to set up a local repo to make proper PRs.

**Comment by cnpryer** [comment]
Curious what the motivation is for the split behavior. Anyway seems like a needed contribution. Let me know if you want a successor PR.

**Comment by ritchie46** [comment]
superseded by #3582

**Pull request closed without merging**
