### PR TITLE
build(python)!: drop Python 3.7 support

### PR DESCRIPTION
**Pull request by stinodego**
Re-opened from #7949

Changes:
* Set required Python version to `>=3.8`
* Set PyO3 abi3 feature to Python 3.8
* Update CI to run on Python 3.8 instead of 3.7 (for release, test, and mypy jobs).
* Update some typing imports
* Remove some typing workarounds
* Update `pandas-stubs` version and update some pandas type hints

Notes:
* We still must allow untyped calls for `mypy` on Python 3.8 due to the `backports.zoneinfo` package having some [issues](https://github.com/pganssle/zoneinfo/issues/125).

### CODE REVIEW

**Comment by ritchie46** [comment]
I think we can just merge this right? Doesn't need a major/breaking version? Numpy dropped support on version 1.22.

**Review by ritchie46 — APPROVED** [review]

**Comment by ritchie46** [comment]
Shall we wait another release? 3.7 downloads proportion is still on 40%. :/

**Comment by stinodego** [comment]
> Shall we wait another release? 3.7 downloads proportion is still on 40%. :/

I really wonder where those downloads are coming from 🤔 

I'd say let this sit and merge it whenever we're going for the next breaking release. Deal?

**Comment by ritchie46** [comment]
Yeap, sounds good. Hopefully these downloads are pinned to an older version and would never be updated.

**Comment by stinodego** [comment]
> Yeap, sounds good. Hopefully these downloads are pinned to an older version and would never be updated.

`pandas` is also still on 40% Python 3.7 downloads, and they have dropped it 6 months ago.

In the end, Polars 0.18.x is still available on Python 3.7. If you want the latest features and fixes, you have to run a supported Python version. I don't see any issue with that.

**Comment by mcrumiller** [comment]
> Shall we wait another release? 3.7 downloads proportion is still on 40%. :/

They're most likely companies like mine that offer employees software via an in-house software repository that is always way way out of date for "support" reasons. Using no-longer-supported software is the status quo.

**Comment by ritchie46** [comment]
Ok, let's merge it then!

**Pull request merged**
