### PR TITLE
Print each argument on new line in Python docs

### PR DESCRIPTION
**Pull request by zundertj**
When there are multiple arguments, they were just added onto the same line. Given type annotations and such, this lead to a very cluttered view. I have added a bit of custom css (see commit for source, modified slightly) to list each new param on a new line.

### CODE REVIEW

**Comment by zundertj** [comment]
Example (not the best actually, as one config has a lot of string values):
before

With this PR:
after

**Comment by ritchie46** [comment]
Nice one! <3

**Comment by zundertj** [comment]
CI errors are unrelated, fixed in #2211 .

**Comment by ritchie46** [comment]
> CI errors are unrelated, fixed in #2211 .

Ok, I will run CI again.

**Comment by ritchie46** [comment]
I think this needs a rebase.

**Comment by zundertj** [comment]
Indeed, done.

**Pull request merged**
