### PR TITLE
feat(python, rust): allow polars Config options to be serialised/shared, and more easily unset

### LINKED ISSUE #5202: Printing the shape below the DataFrame is more usable than printing on top
### Problem description

Quite a silly suggestion but I think printing the shape below the DataFrame could be a slight improvement when using pl.DataFrame. Obviously, we could also simply use df.shape but my point is this: if the shape is being printed at all, why not at the bottom? Quite annoying to keep scrolling up to check the shape from time to time. 

By the way, polars is awesome. Keep it up!

Instead of this:

```
df

shape: (4420, 2)
┌─────────────────┬───────┐
│ id              ┆ open  │
│ ---             ┆ ---   │
│ str             ┆ f64   │
╞═════════════════╪═══════╡
│ 2007-04-27_STAR ┆ 48.75 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-01_FOXA ┆ 44.8  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-14_CTIC ┆ 5.44  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-15_FONR ┆ 4.5   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
```

Do this:

```
df
┌─────────────────┬───────┐
│ id              ┆ open  │
│ ---             ┆ ---   │
│ str             ┆ f64   │
╞═════════════════╪═══════╡
│ 2007-04-27_STAR ┆ 48.75 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-01_FOXA ┆ 44.8  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-14_CTIC ┆ 5.44  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2007-05-15_FONR ┆ 4.5   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤

shape: (4420, 2)
```

### PR DESCRIPTION
**Pull request by alexander-beedie**
**Config enhancements:** 
_(backwards-compatible, no changes to existing behaviour)_

* Added new `save` and `load` classmethods to allow for easy serialisation of `Config` options to a simple JSON dict/string that can then be shared, stored, or reloaded later.
* Added `restore_defaults` method that can unset all registered `Config` vars from the environment.
* Added `state` method to easily see the state of environment vars set from `Config` (as dict).
* Previously only `set_tbl_change_column_data_type_position_format` had an `active` param that supported setting/unsetting its boolean value; now _all_ boolean config options support the same.

  ```python
  # save current config settings to json string
  cfg = pl.Config.save()

  # clear current environment and load a previously-saved config
  pl.Config.restore_defaults().load( cfg )
  ```

**Also:**
_(new config options)_

* Added `set_verbose` option to allow for easy set/unset of `POLARS_VERBOSE`.
* Added `POLARS_FMT_TABLE_DATAFRAME_SHAPE_BELOW` env var to allow for `shape` output to be printed _below_ the table data (closes #5202).  Defaults to False; no change to the standard layout/formatting.

  ```python
  pl.Config.set_verbose( True )  
  pl.Config.set_tbl_dataframe_shape_below( True )  
  ```

### CODE REVIEW

**Comment by ritchie46** [comment]
Awesome! Can you add the new methods to the docs?

**Comment by alexander-beedie** [comment]
> Awesome! Can you add the new methods to the docs?

Done :)

**Comment by alexander-beedie** [comment]
Side-note; doesn't seem like `set_global_string_cache` and `unset_global_string_cache` really belong on the `Config` object; they're available from the polars root via `pl.toggle_string_cache` - shall we remove in `0.15.x`?

**Comment by ritchie46** [comment]
> Side-note; doesn't seem like set_global_string_cache and unset_global_string_cache really belong on the Config object; they're available from the polars root via pl.toggle_string_cache, and (even more idiomatically?) via the pl.StringCache context manager - should we remove?

Yep, good observation.

**Pull request merged**
