### PR TITLE
Add splitn function to split string fixed number of times and keep remainder intact

### PR DESCRIPTION
**Pull request by physinet**
Addresses #4359 by adding `splitn`. The name was chosen to match the underlying [Rust function](https://doc.rust-lang.org/std/primitive.str.html#method.splitn).

I kept the return type as list to match the output of `splitn`, but this could be changed to a struct similar to `split_exact` because we know the exact number of fields. I personally have no preference. Any thoughts @ritchie46 ?

Unfortunately there is no `splitn_inclusive` in Rust, so I'm not sure if the `inclusive` option for `split` and `split_exact` can be replicated easily here.

### CODE REVIEW

**Comment by physinet** [comment]
cc @ghuls This is simlar to #2746, thought you might be interested

**Comment by ritchie46** [comment]
Thanks @physinet the PR looks great. I only think we should return a `Struct` type as this is it is far performant to get the `nth` element from that type and we know the number of fields we get. 

This is also inconsistent with out other functions return.

**Comment by physinet** [comment]
> Thanks @physinet the PR looks great. I only think we should return a `Struct` type as this is it is far performant to get the `nth` element from that type and we know the number of fields we get.
> 
> This is also inconsistent with out other functions return.

Thanks for your support! Happy to change the return to a Struct. A couple of potential concerns I see:
- `split` and `splitn` would have inconsistent return types, whereas the underlying rust functions have the same List return type.
- Cases like [this](https://github.com/pola-rs/polars/blob/master/py-polars/polars/internals/series/string.py) would need the extra Struct fields padded with nulls. The underlying rust function does not pad the List with nulls, so there might be some inconsistency here.

@ritchie46 if you’re not too worried about the points above, I’ll update the PR soon.

**Comment by ritchie46** [comment]
> split and splitn would have inconsistent return types, whereas the underlying rust functions have the same List return type.

Rust returns iterators, the caller can decide what to collect those in. The reason we use `List` for `split` is that we do not know how many elements we get per row. That's why we choose a dynamic length type `List`. This dynamic length type slower than the fixed length type `Struct` with regard to getting its elements. In fact, in a `Struct` it is free to access it's elements, so that's why it should be preferred.

**Comment by physinet** [comment]
Thanks for the explanation about iterators. This makes sense now. I've moved to a Struct return type in 7493eba.

**Comment by ritchie46** [comment]
Hi @physinet sorry for the delay here. I forgot this one. Could you do a rebase? There are some conflicts.

**Comment by ritchie46** [comment]
Thanks @physinet. Looks great!

**Pull request merged**
