### PR TITLE
update schema in udfs

### LINKED ISSUE #4157: Projection pushdown `NotFound` error after rename->drop
The projection pushdown optimization in polars seems to be causing a spurious `NotFound` error in certain circumstances after `rename` and `drop` are called on a `LazyFrame`.  With projection pushdown disabled, the error does not occur.

This error occurs on the most recent commit on `master`, 3b7b60553788a1c2d36d834b6ad0d84f6ef13114 (equivalent to `py-polars-v0.13.58`).

Minimized reproductions:

```rust
#[test]
fn test_projection_pushdown_with_rename_drop() {
  use polars::prelude::*;
  let lf = df![
    "c0" => [0],
    "c1" => [0],
    "c2" => [0],
  ]
  .unwrap()
  .lazy()
  .rename(["c2"], ["c2_"])
  .drop_columns(["c2_"])
  .select([col("c0")]);
  assert!(matches!(
    lf.clone().collect(),
    Err(PolarsError::NotFound(x)) if x == "c1"
  ));
  assert!(matches!(
    lf.with_projection_pushdown(false).collect(),
    Ok(_)
  ));
}
```

```python
import polars as pl

def test_bug():
  return pl.DataFrame({
    "c0": [],
    "c1": [],
    "c2": [],
  }).lazy().rename({
    "c2": "c2_",
  }).drop("c2_").select(pl.col("c0"))

#test_bug().collect(projection_pushdown=True).shape
# NotFoundError: c1
#test_bug().collect(projection_pushdown=False).shape
# (0, 1)
```

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #4157

### CODE REVIEW

**Comment by ritchie46** [comment]
@stinodego I get a flake8 linting error after a black run? Should we ignore that flake8 lint? 

Black should decide the spacing.

**Comment by stinodego** [comment]
> @stinodego I get a flake8 linting error after a black run? Should we ignore that flake8 lint?
> 
> Black should decide the spacing.

I'll check in a sec.

**Comment by ritchie46** [comment]
Alright. I'll see if we can update black. Maybe this bug is already resolved in a later version. Thanks for the explanation.

**Comment by stinodego** [comment]
> Alright. I'll see if we can update black. Maybe this bug is already resolved in a later version. Thanks for the explanation.

I tried the latest black version, but that doesn't help, unfortunately.

**Pull request merged**
