### PR TITLE
Do not check for cariage return after newline character.

### PR DESCRIPTION
**Pull request by ghuls**

### CODE REVIEW

**Comment by ghuls** [comment]
Maybe a bit worrying, when I changed: `return Some(total_pos + pos);` in `next_line_position` to e.g. `return Some(total_pos + pos +100);` all test still passed (rust and python). So it seems like tests probably should check more stuff.

**Comment by ritchie46** [comment]
> Maybe a bit worrying, when I changed: `return Some(total_pos + pos);` in `next_line_position`

**Comment by ritchie46** [comment]
I have take a look. It seems that those were not part of any critical code of the parser. Used for collecting statistics and splitting the file in chunks to process.

**Comment by ritchie46** [comment]
Thanks for the PR @ghuls

**Pull request merged**
