### PR TITLE
python polars 0.14.15

### PR DESCRIPTION
**Pull request by ritchie46**

### CODE REVIEW

**Comment by stinodego** [comment]
@ritchie46 Can you do a 'regular' merge here? That preserves the tagged commit (I verified this).

**Comment by ritchie46** [comment]
> @ritchie46 Can you do a 'regular' merge here? That preserves the tagged commit (I verified this).
> 
> EDIT: Actually, tag `0.14.14` points to this commit?? That must be a mistake somehow.

Right.. So I should repush the tag?

**Comment by stinodego** [comment]
> > @ritchie46 Can you do a 'regular' merge here? That preserves the tagged commit (I verified this).
> > EDIT: Actually, tag `0.14.14` points to this commit?? That must be a mistake somehow.
> 
> Right.. So I should repush the tag?

I think re-push the `0.14.15` tag to point to this commit (`bf8d3922648f01d2d64940237eee9a81972ca22d`), and then re-push the `0.14.14` tag to point to the correct commit as well (`6ab6e26d95803741827c349692d19c1471cf913d`).

Then after that, regular merge this PR.

**Comment by stinodego** [comment]
@ritchie46 I went ahead and updated the tags!

**Comment by ritchie46** [comment]
Alright 👍

**Comment by ritchie46** [comment]
That was an ordinary merge. Did it go ok?

**Comment by stinodego** [comment]
> That was an ordinary merge. Did it go ok?

Yes, you can see that this commit is now in the master branch. So the tag points to an existing commit 🎉

**Pull request merged**
