### PR TITLE
refactor(python): Return correct temporal type from Rust in `to_numpy`

### PR DESCRIPTION
**Pull request by stinodego**
Ref #14334

... as opposed to returning an integer array and then creating a view afterwards.

### CODE REVIEW

**Comment by ritchie46** [comment]
Couldn't we reuse the `integer` code branches? It feels a bit wasteful (code bloat wise).

**Comment by stinodego** [comment]
> Couldn't we reuse the `integer` code branches? It feels a bit wasteful (code bloat wise).

We cannot reuse those because they return floats.

This could be a little bit less wasteful if we had a way to create a Datetime view of an existing integer array, similar to what we have in Python right now. But I don't think the difference will be significant.

**Comment by ritchie46** [comment]
Alright. @stinodego can you refactor this one with the new array views? We could probably remove the old view completely.

**Comment by stinodego** [comment]
> Alright. @stinodego can you refactor this one with the new array views? We could probably remove the old view completely.

The old view has been removed in a different PR. It would still be nice to support creating views with different dtypes in Rust, e.g. a `datetime64[ns]` view. But that can be done in a different PR. This PR is about the path with nulls, which requires copying the data.

**Pull request merged**
